src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>D_B_Country__c</fullName>
        <label>D&amp;B Country</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_NAICS_Code__c</fullName>
        <label>D&amp;B NAICS Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_NAICS_code_Description__c</fullName>
        <label>D&amp;B NAICS code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Number__c</fullName>
        <label>D&amp;B Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_SIC_Code_Description__c</fullName>
        <label>D&amp;B SIC Code Description</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_SIC_Code__c</fullName>
        <label>D&amp;B SIC Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_State_Province__c</fullName>
        <label>D&amp;B State/Province</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAICS_Code__c</fullName>
        <inlineHelpText>NAICS code from DUNS (The North America Industry Classification System (NAICS) is used by business and governments to classify and measure economic activity in the United States, Canada, and Mexico).</inlineHelpText>
        <label>NAICS Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>00 - No found</fullName>
                </value>
                <value>
                    <fullName>11 - Agriculture, Forestry, Fishing and Hunting</fullName>
                </value>
                <value>
                    <fullName>21 - Mining, Quarrying, and Oil and Gas Extraction</fullName>
                </value>
                <value>
                    <fullName>22 - Utilities</fullName>
                </value>
                <value>
                    <fullName>23 - Construction</fullName>
                </value>
                <value>
                    <fullName>31 - Manufacturing</fullName>
                </value>
                <value>
                    <fullName>32 - Manufacturing</fullName>
                </value>
                <value>
                    <fullName>33 - Manufacturing</fullName>
                </value>
                <value>
                    <fullName>42 - Wholesale Trade</fullName>
                </value>
                <value>
                    <fullName>44 - Retail Trade</fullName>
                </value>
                <value>
                    <fullName>45 - Retail Trade</fullName>
                </value>
                <value>
                    <fullName>48 - Transportation and Warehousing</fullName>
                </value>
                <value>
                    <fullName>49 - Transportation and Warehousing</fullName>
                </value>
                <value>
                    <fullName>51 - Information</fullName>
                </value>
                <value>
                    <fullName>52 - Finance and Insurance</fullName>
                </value>
                <value>
                    <fullName>53 - Real Estate and Rental and Leasing</fullName>
                </value>
                <value>
                    <fullName>54 - Professional, Scientific, and Technical Services</fullName>
                </value>
                <value>
                    <fullName>55 - Management of Companies and Enterprises</fullName>
                </value>
                <value>
                    <fullName>56 - Administrative, Support , Waste Management , Remediation Services</fullName>
                </value>
                <value>
                    <fullName>61 - Educational Services</fullName>
                </value>
                <value>
                    <fullName>62 - Health Care and Social Assistance</fullName>
                </value>
                <value>
                    <fullName>71 - Arts, Entertainment, and Recreation</fullName>
                </value>
                <value>
                    <fullName>72 - Accommodation and Food Services</fullName>
                </value>
                <value>
                    <fullName>81 - Other Services (except Public Administration)</fullName>
                </value>
                <value>
                    <fullName>92 - Public Administration</fullName>
                </value>
                <value>
                    <fullName>99 - Unclassified Establishments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIC_Code__c</fullName>
        <inlineHelpText>SIC code from DUNS (Standard Industrial Classification (SIC) codes are four-digit numerical codes assigned by the U.S. government to business establishment to identify the primary business of the establishment).</inlineHelpText>
        <label>SIC Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0000 - No found</fullName>
                </value>
                <value>
                    <fullName>0100 - Agricultural Production-Crops</fullName>
                </value>
                <value>
                    <fullName>0200 - Agricultural Prod-Livestock &amp; Animal Specialties</fullName>
                </value>
                <value>
                    <fullName>0700 - Agricultural Services</fullName>
                </value>
                <value>
                    <fullName>0800 - Forestry</fullName>
                </value>
                <value>
                    <fullName>0900 - Fishing, Hunting and Trapping</fullName>
                </value>
                <value>
                    <fullName>1000 - Metal Mining</fullName>
                </value>
                <value>
                    <fullName>1040 - Gold and Silver Ores</fullName>
                </value>
                <value>
                    <fullName>1090 - Miscellaneous Metal Ores</fullName>
                </value>
                <value>
                    <fullName>1220 - Bituminous Coal &amp; Lignite Mining</fullName>
                </value>
                <value>
                    <fullName>1221 - Bituminous Coal &amp; Lignite Surface Mining</fullName>
                </value>
                <value>
                    <fullName>1241 - Coal mining services</fullName>
                </value>
                <value>
                    <fullName>1311 - Crude Petroleum &amp; Natural Gas</fullName>
                </value>
                <value>
                    <fullName>1381 - Drilling Oil &amp; Gas Wells</fullName>
                </value>
                <value>
                    <fullName>1382 - Oil &amp; Gas Field Exploration Services</fullName>
                </value>
                <value>
                    <fullName>1389 - Oil &amp; Gas Field Services, NEC</fullName>
                </value>
                <value>
                    <fullName>1400 - Mining &amp; Quarrying of Nonmetallic Minerals (No Fuels)</fullName>
                </value>
                <value>
                    <fullName>1520 - General Bldg Contractors - Residential Bldgs</fullName>
                </value>
                <value>
                    <fullName>1531 - Operative Builders</fullName>
                </value>
                <value>
                    <fullName>1540 - General Bldg Contractors - Nonresidential Bldgs</fullName>
                </value>
                <value>
                    <fullName>1600 - Heavy Construction Other Than Bldg Const - Contractors</fullName>
                </value>
                <value>
                    <fullName>1611 - Highway and street construction</fullName>
                </value>
                <value>
                    <fullName>1622 - Bridge, tunnel, and elevated highway construction</fullName>
                </value>
                <value>
                    <fullName>1623 - Water, Sewer, Pipeline, Comm &amp; Power Line Construction</fullName>
                </value>
                <value>
                    <fullName>1629 - Heavy construction, nec</fullName>
                </value>
                <value>
                    <fullName>1700 - Construction - Special Trade Contractors</fullName>
                </value>
                <value>
                    <fullName>1711 - Plumbing, heating, air-conditioning</fullName>
                </value>
                <value>
                    <fullName>1721 - Painting and paper hanging</fullName>
                </value>
                <value>
                    <fullName>1731 - Electrical Work</fullName>
                </value>
                <value>
                    <fullName>1742 - Plastering, drywall, and insulation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_of_D_B_Cleansing__c</fullName>
        <label>DNB Verified</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DNB Accepted</fullName>
                </value>
                <value>
                    <fullName>DNB Rejected: Poor Match</fullName>
                    <color>#FFCC33</color>
                    <label>DNB Rejected: Poor Match</label>
                </value>
                <value>
                    <fullName>DNB Rejected: Not Found</fullName>
                    <color>#FF0000</color>
                    <label>DNB Rejected: Not Found</label>
                </value>
                <value>
                    <fullName>DNB Rejected: Address Retained</fullName>
                </value>
                <value>
                    <fullName>D&amp;B Excluded: Technical Services</fullName>
                    <color>#641CCF</color>
                    <label>D&amp;B Excluded: Technical Services</label>
                </value>
                <value>
                    <fullName>D&amp;B Excluded: AOP</fullName>
                    <color>#33CCFF</color>
                    <label>D&amp;B Excluded: AOP</label>
                </value>
                <value>
                    <fullName>D&amp;B Excluded: Other Exceptions</fullName>
                    <color>#0B6FCE</color>
                    <label>D&amp;B Excluded: Other Exceptions</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountControllerExtensionDnBTest.cls
@isTest
public class AccountControllerExtensionDnBTest
{
    static testMethod void accountControllerExtensionDnBTest() 
    {
        Account testA = new Account( 
            Name = 'Test' ,
            Status_of_D_B_Cleansing__c = null ,
            D_B_Number__c = 'Test DUNS' ,
            D_B_SIC_Code__c = 'Test SIC' ,
            D_B_SIC_Code_Description__c = 'Test SIC Desc' ,
            D_B_NAICS_Code__c = 'Test NAICS' ,
            D_B_NAICS_Code_Description__c = 'Test NAICS Desc' ,
            D_B_Country__c = 'Test Country' ,
            D_B_State_Province__c = 'Test Province' ,
            D_B_City__c = 'Test City' ,
            D_B_Street__c = 'Test Street' ,
            D_B_ZIP_Postal_Code__c = 'Test ZIP'
        );
        insert testA;

        PageReference pageRef = Page.Account_DnB;
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardController sc = new ApexPages.standardController( testA );   
        ApexPages.currentPage().getParameters().put('id', testA.Id );     
        AccountControllerExtensionDnB testCE = new AccountControllerExtensionDnB( sc );

        testCE.Reject();
        System.assertEquals( testA.Status_of_D_B_Cleansing__c , 'D&B Rejected: Address Retained' );

        testCE.Accept();
        System.assertEquals( testA.Status_of_D_B_Cleansing__c , 'D&B Accepted' );
        System.assertEquals( testA.DUNS_Number__c , testA.D_B_Number__c );
        System.assertEquals( testA.Sic , testA.D_B_SIC_Code__c );
        System.assertEquals( testA.SicDesc , testA.D_B_SIC_Code_Description__c );
        System.assertEquals( testA.SIC_Code__c , testA.D_B_SIC_Code__c + ' - ' + testA.D_B_SIC_Code_Description__c );
        System.assertEquals( testA.NAICS__c , testA.D_B_NAICS_Code__c );
        System.assertEquals( testA.NAICS_Description__c , testA.D_B_NAICS_Code_Description__c );
        System.assertEquals( testA.NAICS_Code__c , testA.D_B_NAICS_Code__c + ' - ' + testA.D_B_NAICS_Code_Description__c );
        System.assertEquals( testA.Country__c , testA.D_B_Country__c );
        System.assertEquals( testA.State_Province__c , testA.D_B_State_Province__c );
        System.assertEquals( testA.City__c , testA.D_B_City__c );
        System.assertEquals( testA.Street__c , testA.D_B_Street__c );
        System.assertEquals( testA.ZIP_Postal_Code__c , testA.D_B_ZIP_Postal_Code__c );
    }
}