src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMD_Industry_Segment__c</fullName>
        <description>Customer Buying Group</description>
        <inlineHelpText>Customer Buying Group</inlineHelpText>
        <label>CBG</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria_1__c</fullName>
        <label>Criteria 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_2__c</fullName>
        <description>This field is to capture the region when approver type is sales director</description>
        <label>Criteria 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_1__c</fullName>
        <label>Threshold 1</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <recordTypes>
        <fullName>Direct_Oppty</fullName>
        <active>true</active>
        <label>Direct Oppty</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LT_Value_USD__c</fullName>
        <description>Opportunity lifetime value in USD.</description>
        <formula>IF (Locked_Exchange_Rate__c &lt;&gt; 0, LT_Value__c / ROUND(Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summary of all products&apos; [Prod LT Value] converted to USD.</inlineHelpText>
        <label>Oppty LT Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Locked_Exchange_Rate__c</fullName>
        <inlineHelpText>The Exchange Rate against USD which is locked when opportunity is Approved</inlineHelpText>
        <label>Locked Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Regional_VP_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFJpr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Director_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Sales Director approver for opportunity</description>
        <label>Sales Director Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesF8rX</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Claim_Value_MAG_Setting__mdt.object
<CustomObject>
    <description>Store claim value year at the MAG level</description>
    <fields>
        <fullName>Claim_Value_Quarters__c</fullName>
        <label>Claim Value Quarters</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lifetime</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                    <default>true</default>
                    <label>12</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q69</fullName>
                </value>
                <value>
                    <fullName>R01</fullName>
                    <default>true</default>
                    <label>R01</label>
                </value>
                <value>
                    <fullName>R05</fullName>
                </value>
                <value>
                    <fullName>R06</fullName>
                </value>
                <value>
                    <fullName>R07</fullName>
                </value>
                <value>
                    <fullName>R08</fullName>
                </value>
                <value>
                    <fullName>R09</fullName>
                </value>
                <value>
                    <fullName>R10</fullName>
                </value>
                <value>
                    <fullName>R12</fullName>
                </value>
                <value>
                    <fullName>R13</fullName>
                </value>
                <value>
                    <fullName>R14</fullName>
                </value>
                <value>
                    <fullName>R16</fullName>
                </value>
                <value>
                    <fullName>R21</fullName>
                </value>
                <value>
                    <fullName>R22</fullName>
                </value>
                <value>
                    <fullName>R23</fullName>
                </value>
                <value>
                    <fullName>R24</fullName>
                </value>
                <value>
                    <fullName>R25</fullName>
                </value>
                <value>
                    <fullName>R26</fullName>
                </value>
                <value>
                    <fullName>R27</fullName>
                </value>
                <value>
                    <fullName>R28</fullName>
                </value>
                <value>
                    <fullName>R29</fullName>
                </value>
                <value>
                    <fullName>R30</fullName>
                </value>
                <value>
                    <fullName>R31</fullName>
                </value>
                <value>
                    <fullName>R32</fullName>
                </value>
                <value>
                    <fullName>R33</fullName>
                </value>
                <value>
                    <fullName>R34</fullName>
                </value>
                <value>
                    <fullName>R35</fullName>
                </value>
                <value>
                    <fullName>R36</fullName>
                </value>
                <value>
                    <fullName>R37</fullName>
                </value>
                <value>
                    <fullName>R38</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Claim Value MAG Setting</label>
    <pluralLabel>Opportunity Claim Value MAG Settings</pluralLabel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <formula>PricebookEntry.Product2.BL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LT_Value_USD__c</fullName>
        <description>Opportunity product lifetime value in USD.</description>
        <formula>IF (Opportunity.Locked_Exchange_Rate__c &lt;&gt; 0, LT_Value__c / ROUND(Opportunity.Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity product lifetime value in USD.</inlineHelpText>
        <label>Prod LT Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunitySchedule__c.object
<CustomObject>
    <description>Opportunity Schedule</description>
    <fields>
        <fullName>Frozen_Oppty_Sched_Qty__c</fullName>
        <label>Frozen Oppty Sched Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Schedules</relationshipLabel>
        <relationshipName>Opportunity_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Oppty_Sched_Qty__c</fullName>
        <label>Oppty Sched Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sched_Date__c</fullName>
        <label>Sched Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Opportunity Schedule</label>
    <nameField>
        <displayFormat>OS-{0000}</displayFormat>
        <label>Opportunity Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OpportunityProductSetProbToWinPluginTest.cls
@isTest
public class OpportunityProductSetProbToWinPluginTest {
	private static final String TEST_USER_PROFILE = 'Standard User';
	private static final String TEST_USER = 't_user_1';
	private static final String TEST_USER_MAG_STAR = 'uMagSTAR';
	private static final String TEST_USER_BL_STAR = 'uBlSTAR';
	private static final String TEST_USER_GAM_STAR = 'uGamSTAR';
	private static final String TEST_USER_GAM_SAMSUNG = 'uGamSAMS';
	private static final String TEST_USER_EVP_STAR = 'uEvpSTAR';
	private static final String TEST_USER_EVP_SAMSUNG = 'uEvpSAMS';
	private static final String TEST_USER_AUTO = 'userAUTO';
	private static final String TEST_USER_MT1 = 'userMT1';
	private static final String TEST_USER_MT2 = 'userMT2';
	private static final String TEST_USER_MAG = 'userMAG';
	private static final String TEST_USER_BL = 'userBL';
	private static final String MAG_SHORT_LIVED;
    private static final String MAG_LIFETIME;
    private static final String BL1 = 'BL01';
    private static final String BL2 = 'BLM1';
    private static final String CCY_CODE_USD = 'USD';
    private static final String CCY_CODE_EUR = 'EUR';
    private static final String CCY_CODE_DEFAULT = CCY_CODE_USD; // @default
    private static final Double EXCH_RATE_USD = 2.0;
    private static final Double EXCH_RATE_EUR = 0.9;
    private static final String PARENT_ACCOUNT_STAR = 'STAR';
	private static final String PARENT_ACCOUNT_SAMSUNG = 'Samsung';
    private static final String CBG_AUTOMOTIVE = 'Automotive';
    private static final String CBG_NON_AUTOMOTIVE = 'Non-Automotive';
    private static final String REGION_GC = 'Greater China';
    private static final String REGION_SAP = 'South Asia Pacific';
    private static final Date PRODUCTION_DATE = Date.newInstance(2016, 04, 30);
    private static final Decimal UNIT_PRICE = 2;
    private static final Double COMP_MULT = 5;
    private static final Integer PROD_COUNT = 4;
    private static final Double THRESHOLD_MAG = 100 * 1000;
    private static final Double THRESHOLD_BL = 15 * 1000 * 1000;
    private static final Double THRESHOLD_VP = 10 * 1000 * 1000;
    
    private static ID userIdMagSTAR;
    private static ID userIdBlSTAR;
    private static ID userIdGamSTAR;
    private static ID userIdGamSamsung;
    private static ID userIdEvpSTAR;
    private static ID userIdEvpSamsung;
    private static ID userIdAuto;
    private static ID userIdMT1;
    private static ID userIdMT2;
    private static ID userIdMAG;
    private static ID userIdBL;
    private static ID parentAccountIdSTAR;
    private static ID parentAccountIdSamsung;
    private static List<OpportunityLineItem> opptyProds = new List<OpportunityLineItem>();
    private static OpportunityLineItem opptyProd;
	
	static {
		Opportunity_Claim_Value_MAG_Setting__mdt claimValueMagSetting = 
            [select MAG__c 
               from Opportunity_Claim_Value_MAG_Setting__mdt 
              where Claim_Value_Quarters__c != 'Lifetime'
                and IsActive__c = true
              limit 1];
        
        MAG_SHORT_LIVED = claimValueMagSetting.MAG__c;
               
        claimValueMagSetting = 
            [select MAG__c 
               from Opportunity_Claim_Value_MAG_Setting__mdt 
              where Claim_Value_Quarters__c = 'Lifetime'
                and IsActive__c = true
              limit 1];
        
        MAG_LIFETIME = claimValueMagSetting.MAG__c;
        
        List<User> users = [select Alias, MT_1__c, MT_2__c from User where Alias in (:TEST_USER, :TEST_USER_MAG, :TEST_USER_BL, :TEST_USER_MAG_STAR, :TEST_USER_BL_STAR, :TEST_USER_GAM_STAR, :TEST_USER_GAM_SAMSUNG, :TEST_USER_EVP_STAR, :TEST_USER_EVP_SAMSUNG, :TEST_USER_AUTO)];
        
        for (User u : users) {
        	if (u.Alias == TEST_USER) {
        		userIdMT1 = u.MT_1__c;
        		userIdMT2 = u.MT_2__c;	
        	} else if (u.Alias == TEST_USER_MAG) {
        		userIdMAG = u.Id;
        	} else if (u.Alias == TEST_USER_BL) {
        		userIdBL = u.Id;
        	} else if (u.Alias == TEST_USER_MAG_STAR) {
        		userIdMagSTAR = u.Id;
        	} else if (u.Alias == TEST_USER_BL_STAR) {
        		userIdBlSTAR = u.Id;
        	} else if (u.Alias == TEST_USER_GAM_STAR) {
        		userIdGamSTAR = u.Id;
        	} else if (u.Alias == TEST_USER_GAM_SAMSUNG) {
        		userIdGamSamsung = u.Id;
        	} else if (u.Alias == TEST_USER_EVP_STAR) {
        		userIdEvpSTAR = u.Id;
        	} else if (u.Alias == TEST_USER_EVP_SAMSUNG) {
        		userIdEvpSamsung = u.Id;
        	} else if (u.Alias == TEST_USER_AUTO) {
        		userIdAuto = u.Id;
        	}
        }
        
        List<Account> accounts = [select Name from Account];
        
        for (Account a : accounts) {
        	if (a.Name == PARENT_ACCOUNT_STAR) {
        		parentAccountIdSTAR = a.Id;	
        	} else if (a.Name == PARENT_ACCOUNT_SAMSUNG) {
        		parentAccountIdSamsung = a.Id;	
        	}
        }
        
        List<OpportunityLineItem> opptyLineItems = [select Id, OpportunityId, PricebookEntry.Product2.MAG__c from OpportunityLineItem]; 
        
        for (OpportunityLineItem oli : opptyLineItems) {
        	opptyProds.add(oli);    
        }
        
        if (opptyProds.size() > 0) {
        	opptyProd = opptyProds.get(0);
        }
    }

    @testSetup
    static void setup()
    {
    	Profile p = [select Id from Profile where Name = :TEST_USER_PROFILE];
    	
    	// insert test users
    	List<User> users = new List<User>();
    	users.add(newUser(TEST_USER_MAG_STAR, TEST_USER_MAG_STAR, p.Id));
    	users.add(newUser(TEST_USER_BL_STAR, TEST_USER_BL_STAR, p.Id));
    	users.add(newUser(TEST_USER_GAM_STAR, TEST_USER_GAM_STAR, p.Id));
    	users.add(newUser(TEST_USER_GAM_SAMSUNG, TEST_USER_GAM_SAMSUNG, p.Id));
    	users.add(newUser(TEST_USER_EVP_STAR, TEST_USER_EVP_STAR, p.Id));
    	users.add(newUser(TEST_USER_EVP_SAMSUNG, TEST_USER_EVP_SAMSUNG, p.Id));
    	users.add(newUser(TEST_USER_AUTO, TEST_USER_AUTO, p.Id));
    	users.add(newUser(TEST_USER_MT1, TEST_USER_MT1, p.Id));
    	users.add(newUser(TEST_USER_MT2, TEST_USER_MT2, p.Id));
    	users.add(newUser(TEST_USER_MAG, TEST_USER_MAG, p.Id));
    	users.add(newUser(TEST_USER_BL, TEST_USER_BL, p.Id));
    	insert users;
    	
    	User userMagSTAR = users.get(0);
    	User userBlSTAR = users.get(1);
    	User userGamSTAR = users.get(2);
    	User userGamSamsung = users.get(3);
    	User userEvpSTAR = users.get(4);
    	User userEvpSamsung = users.get(5);
    	User userAuto = users.get(6);
    	User userMT1 = users.get(7);
    	User userMT2 = users.get(8);
    	User userMAG = users.get(9);
    	User userBL = users.get(10);
    	
    	User u = createUser(TEST_USER, TEST_USER, p.Id);
        u.MT_1__c = userMT1.Id;
        u.MT_2__c = userMT2.Id;
        update u;
        
        // insert approvers
        List<Approvers_Matrix__c> ams = new List<Approvers_Matrix__c>();
        ams.add(newApproverMatrix('MAG Approver', MAG_SHORT_LIVED, null, THRESHOLD_MAG, userMAG.Id));
        ams.add(newApproverMatrix('MAG Approver', MAG_LIFETIME, null, THRESHOLD_MAG, userMAG.Id));
        ams.add(newApproverMatrix('BL Approver', BL1, null, THRESHOLD_BL, userBL.Id));
        ams.add(newApproverMatrix('BL Approver', BL2, null, THRESHOLD_BL, userBL.Id));
        ams.add(newApproverMatrix('MAG Approver', MAG_SHORT_LIVED, 'STAR', THRESHOLD_MAG, userMagSTAR.Id));
        ams.add(newApproverMatrix('MAG Approver', MAG_LIFETIME, 'STAR', THRESHOLD_MAG, userMagSTAR.Id));
        ams.add(newApproverMatrix('BL Approver', BL1, 'STAR', THRESHOLD_BL, userBlSTAR.Id));
        ams.add(newApproverMatrix('BL Approver', BL2, 'STAR', THRESHOLD_BL, userBlSTAR.Id));
        ams.add(newApproverMatrix('GAM', 'STAR', null, 0, userGamSTAR.Id));
        ams.add(newApproverMatrix('GAM', 'Samsung', null, 0, userGamSamsung.Id));
        ams.add(newApproverMatrix('EVP', 'STAR', null, THRESHOLD_VP, userEvpSTAR.Id));
        ams.add(newApproverMatrix('EVP', 'Samsung', null, THRESHOLD_VP, userEvpSamsung.Id));
        ams.add(newApproverMatrix('Segment VP', 'Automotive', null, THRESHOLD_VP, userAuto.Id));
        ams.add(newApproverMatrix('GSM Sales Director', null, null, 0, u.Id));
        ams.add(newApproverMatrix('GSM VP 1', null, null, THRESHOLD_VP, u.Id));
        ams.add(newApproverMatrix('GSM VP 2', 'Automotive', 'Greater China', THRESHOLD_VP, u.Id));
        ams.add(newApproverMatrix('GSM VP 2', 'Automotive', 'South Asia Pacific', THRESHOLD_VP, u.Id));
        insert ams;
        
        // insert FX Rates
        // There is a workflow which sets Opportunity.Locked_Exchange_Rate__c to 
        // Opportunity.Currency__r.Exchange_Rate__c, which refers to FX_Rates__c.Exchange_Rate__c
        List<FX_Rates__c> fxrs = new List<FX_Rates__c>();
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_USD, Currency_Code__c = CCY_CODE_USD, CurrencyIsoCode = CCY_CODE_USD, Exchange_Rate__c = EXCH_RATE_USD));
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_EUR, Currency_Code__c = CCY_CODE_EUR, CurrencyIsoCode = CCY_CODE_EUR, Exchange_Rate__c = EXCH_RATE_EUR));
        insert fxrs;
        
        Map<String, FX_Rates__c> fxRates = new Map<String, FX_Rates__c>();
        fxRates.put(CCY_CODE_USD, fxrs.get(0));
        fxRates.put(CCY_CODE_EUR, fxrs.get(1));
        
        // Insert accounts
        createAccount(PARENT_ACCOUNT_STAR, AccountsSelector.getParentRecordTypeID(), null, null);
        createAccount(PARENT_ACCOUNT_SAMSUNG, AccountsSelector.getParentRecordTypeID(), null, null);
        Account parentGeneral = createAccount('Parent Account - General', AccountsSelector.getParentRecordTypeID(), null, null);
        Account a = createAccount('Test Account', AccountsSelector.getChildRecordTypeID(), parentGeneral.Id, CBG_AUTOMOTIVE);
         
        // Insert products
        List<Product2> prods = new List<Product2>();
        
        for (Integer i = 0; i < PROD_COUNT; i++) {
            Integer rem = Math.mod(i, 2);
            
            if (rem == 0) {
                prods.add(new Product2(Name = 'Test Product' + i, MAG__c = MAG_SHORT_LIVED, BL__c = BL1, IsActive = true));
            } else {
                prods.add(new Product2(Name = 'Test Product' + i, MAG__c = MAG_LIFETIME, BL__c = BL2, IsActive = true));
            }            
        }
        
        insert prods;
        
        // Insert an opportunity
        Opportunity o = new Opportunity(Name = 'Test Oppty', OwnerId = u.Id, AccountId = a.Id, StageName = 'Initial Engagement');
        o.Production_Date__c = PRODUCTION_DATE;
        o.CloseDate = PRODUCTION_DATE - 60;
        o.Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id; // Locked_Exchange_Rate__c will be set to this by workflow.
        o.CurrencyIsoCode = CCY_CODE_DEFAULT; // CurrencyIsoCode and Currency__c are correlated.
        o.Bypass_Validation_Sched_Start_Date__c = true;
        insert o;
        
        System.debug('//J ========== after insert oppty');  
        
        createOpportunitySchedules(o.Id, 1000); 
        
        List<PricebookEntry> pbes = [select Id from PricebookEntry where Product2Id in :prods and CurrencyIsoCode = :CCY_CODE_DEFAULT];
        
        // Insert opportunity products
        List<OpportunityLineItem> olis = new List<OpportunityLineItem>();
        
        for (PricebookEntry pbe : pbes) {
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = o.Id, PricebookEntryId = pbe.Id);
            oli.UnitPrice = UNIT_PRICE;
            oli.Component_Multiplier__c = COMP_MULT;
            olis.add(oli);
        }
        
        insert olis;
        
        System.debug('//J ========== after insert oppty prods');
    }
    
    static void createOpportunitySchedules(ID opptyID, Double totalQty) {
    	List<OpportunitySchedule__c> opptyScheds = new List<OpportunitySchedule__c>();
    	Double qty = totalQty / 4;
    	
    	OpportunitySchedule__c opptySched;
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 01, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 04, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 07, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 10, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);	
    	
    	insert opptyScheds;
    } 
    
    static User createUser(String alias, String lastName, ID profileID) {
    	User user = newUser(alias, lastName, profileID); 
    	insert user;
        
        return user;	
    }
    
    static User newUser(String alias, String lastName, ID profileID) {
    	String email = CommonUtils.generateGUID() + '@nxp.com.test123';
    	
    	User user = new User(EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles');
		user.Alias = alias;
		user.LastName = lastName;
		user.ProfileId = profileID;
		user.Email = email;
		user.UserName = email;
        user.Signed_ARIA__c = true;
        
        return user;	
    }
    
    static Account createAccount(String name, ID recordTypeID, ID parentID, String cbg) {
    	Account account = new Account(Region__c = 'EMEA');
    	account.Name = name;
    	account.RecordTypeId = recordTypeID;
    	account.ParentId = parentID;
    	account.CMD_Industry_Segment__c = cbg;
    	insert account;
    	
    	return account;
    }
    
    static Approvers_Matrix__c newApproverMatrix(String type, String criteria1, String criteria2, Double threshold1, ID approverID) {
    	Approvers_Matrix__c approverMatrix = new Approvers_Matrix__c();
    	approverMatrix.RecordTypeId = new ApproverMatrixesSelector().getRecordTypeId(ApproverMatrixesSelector.RecordType.DIRECT_OPPTY);
    	approverMatrix.Type__c = type;
    	approverMatrix.Criteria_1__c = criteria1;
    	approverMatrix.Criteria_2__c = criteria2;
    	approverMatrix.Threshold_1__c = threshold1;
    	approverMatrix.Approver__c = approverID;
    	    	
    	return approverMatrix;
    }
    
    static Opportunity getOpportunity(ID opptyID) {
        return [select LT_Value_USD__c, Sales_Director_Approver__c, Regional_VP_Approver__c, VP_Approver_2__c, 
        			   MAG_Approver_1__c, MAG_Approver_2__c, BL_Approver_1__c, BL_Approver_2__c,  
        			   Account.ParentId, Owner.MT_2__c 
        		  from Opportunity 
        		 where Id = :opptyID];    
    } 
    
    @isTest
    static void testPluginInvoke()
    {
        OpportunityProductSetProbToWinPlugin plugin = new OpportunityProductSetProbToWinPlugin();
        Map<String,String> parms = new Map<String,String>();
        Opportunity oppty = getOpportunity(opptyProd.OpportunityId);
        Test.startTest();
        parms.put('Id', oppty.Id);
        Process.PluginRequest request = new Process.PluginRequest(parms);
        Process.PluginResult result = plugin.invoke(request);
        Test.stopTest();
    }
    
    @isTest
    static void testPluginDescribe()
    {
        Test.startTest();
        OpportunityProductSetProbToWinPlugin plugin = new OpportunityProductSetProbToWinPlugin();
        Process.PluginDescribeResult result = plugin.describe();
        Test.stopTest();
    }
    
    @isTest
    static void testPluginInvokeException()
    {
        OpportunityProductSetProbToWinPlugin plugin = new OpportunityProductSetProbToWinPlugin();
        Map<String,String> parms = new Map<String,String>();
        delete [Select Id from Approvers_Matrix__c Where Type__c = 'GSM Sales Director'];
        Opportunity oppty = getOpportunity(opptyProd.OpportunityId);
        Test.startTest();
        parms.put('Id', oppty.Id);
        Process.PluginRequest request = new Process.PluginRequest(parms);
        Process.PluginResult result = plugin.invoke(request);
        Test.stopTest();
    }
}