src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Child_Account</fullName>
        <active>true</active>
        <label>Child Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked_Exchange_Rate__c</fullName>
        <inlineHelpText>The Exchange Rate against USD which is locked when opportunity is Approved</inlineHelpText>
        <label>Locked Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2010_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2010 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2011_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2011 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2012_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2012 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2013_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2013 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2014_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2014 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2015_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2015 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2016_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2016 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2017_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2017 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2018_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2018 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2019_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2019 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2020_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2020 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2021_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2021 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2022_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2022 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2023_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2023 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2024_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2024 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2025_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2025 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2026_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2026 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2027_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2027 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2028_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2028 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2029_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2029 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2030_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2030 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>SFDC_Oppty</fullName>
        <active>true</active>
        <businessProcess>NXP Sales Process</businessProcess>
        <description>NXP Sales Opportunity</description>
        <label>SFDC Oppty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Name of Account of Opportunity</description>
        <formula>Opportunity.Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BL__c</fullName>
        <formula>PricebookEntry.Product2.BL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>PricebookEntry.Product2.BU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunitySchedule__c.object
<CustomObject>
    <description>Opportunity Schedule</description>
    <fields>
        <fullName>Frozen_Oppty_Sched_Qty__c</fullName>
        <label>Frozen Oppty Sched Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Schedules</relationshipLabel>
        <relationshipName>Opportunity_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Oppty_Sched_Qty__c</fullName>
        <label>Oppty Sched Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sched_Date__c</fullName>
        <label>Sched Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Opportunity Schedule</label>
    <nameField>
        <displayFormat>OS-{0000}</displayFormat>
        <label>Opportunity Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Top_Accounts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of accounts used in drop down of &apos;Account Tracker&apos; tab. #SIR960</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Top 30 Accounts</label>
</CustomObject>

src/classes/FunnelTrackerSnapshotPopulateBatchTest.cls
/***************************************************************************************************
@Created By :      Balaji G
@Created Date:     11 July 2016
@Description:      Test class for FunnelTrackerSnapshotPopulateBatch
****************************************************************************************************/

/* Last ModifiedBy : Baji
   Last ModifiedDate : 02 Jun 2017
   Description : Updated to remove the test data related to Opportunity Approval Setting.
*/ 

@isTest
public class FunnelTrackerSnapshotPopulateBatchTest
   {
        private static final String CCY_CODE_USD = 'USD';
        private static final String CCY_CODE_EUR = 'EUR';
        private static final String CCY_CODE_DEFAULT = CCY_CODE_USD; // @default
        private static final Double EXCH_RATE_USD = 1.0;
        private static final Double EXCH_RATE_EUR = 0.9;
        private static final Double EXCH_RATE_DEFAULT = EXCH_RATE_USD; // @default
        private static final String ACCOUNT_CHILDACCOUNT = 'Child_Account';
        private static final String ACCOUNT_ParentACCOUNT = 'Parent_Account';
        private static final String Optty_sfdcOptty = 'SFDC_Oppty';
        public static RecordType sfdcOptty = [Select Id, DeveloperName
                                  From RecordType
                                  Where IsActive=true and
                                   (SobjectType = 'Opportunity' and (DeveloperName =: Optty_sfdcOptty ))
                                  Limit 1];
        public static RecordType childAccount = [Select Id, DeveloperName
                                  From RecordType
                                  Where IsActive=true and
                                   (SobjectType = 'Account' and (DeveloperName =: ACCOUNT_CHILDACCOUNT))
                                  Limit 1];                                  
        public static RecordType parentAccount= [Select Id, DeveloperName
                                  From RecordType
                                  Where IsActive=true and
                                   (SobjectType = 'Account' and (DeveloperName =: ACCOUNT_ParentACCOUNT))
                                  Limit 1];    
                          
        public static testMethod void FunnelTrackerSnapshotPopulateBatchTest() 
          {
                List<FX_Rates__c> fxrs = new List<FX_Rates__c>();
                fxrs.add(new FX_Rates__c(Name = CCY_CODE_USD, Currency_Code__c = CCY_CODE_USD, CurrencyIsoCode = CCY_CODE_USD, Exchange_Rate__c = EXCH_RATE_USD));
                fxrs.add(new FX_Rates__c(Name = CCY_CODE_EUR, Currency_Code__c = CCY_CODE_EUR, CurrencyIsoCode = CCY_CODE_EUR, Exchange_Rate__c = EXCH_RATE_EUR));
                insert fxrs;
                Map<String, FX_Rates__c> fxRates = new Map<String, FX_Rates__c>();
                fxRates.put(CCY_CODE_USD, fxrs.get(0));
                fxRates.put(CCY_CODE_EUR, fxrs.get(1));  
               
                Pricebookentry priceBookEntryRecord =new Pricebookentry();
                Product2 testProduct;
                Id testPriceBookId = Test.getStandardPricebookId();
                product2 listProduct=new product2();
                integer BlVal=11;
                integer MAGValue=33;
                String BUvalue='510';
                listProduct = new Product2(Name = 'testName',IsActive=true, MAG__c='R'+MAGvalue++, Bl__c='BL'+BlVal++,BU__c=BUvalue,CurrencyISOCode = 'USD');                
                insert listProduct;  
                priceBookEntryRecord = [select id from PriceBookentry where Product2Id=:listProduct.id and CurrencyISOCode='USD'];
                Account ParentStarTest = new Account(Name='Test Account',RecordTypeId=parentAccount.Id);
                Account ChildStarTest = new Account(Name='Test Account',RecordTypeId=childAccount.Id,ParentId=ParentStarTest.Id);
                insert ParentStarTest;
                insert ChildStarTest;
                List<Opportunity> listDWs = new List<Opportunity>();
                Integer numOpptys=6;
                date d2=Date.newInstance(2010, 1, 1);
                date d4=Date.newInstance(2010, 1, 1);
                        Opportunity o = new Opportunity(Name='TestOppty',AccountId=ChildStarTest.Id,CloseDate=d2,StageName='Initial Engagement',Production_Date__c=d4,RecordTypeID=sfdcOptty.Id,X2010_Pieces__c=10,X2011_Pieces__c=11,X2012_Pieces__c=12,X2013_Pieces__c=13,X2014_Pieces__c=14,X2015_Pieces__c=15,X2016_Pieces__c=16,X2017_Pieces__c=17,X2018_Pieces__c=18,X2019_Pieces__c=19,X2020_Pieces__c=20,X2021_Pieces__c=21,X2022_Pieces__c=22,X2023_Pieces__c=23,X2024_Pieces__c=24,X2025_Pieces__c=25,X2026_Pieces__c=26,X2027_Pieces__c=27,X2028_Pieces__c=28,X2029_Pieces__c=29,X2030_Pieces__c=30,Locked_Exchange_Rate__c = 1.00,Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT);
                        listDWs.add(o);
                Test.StartTest();
                insert listDWs;
                
                //must create opportunity schedules before creating opportunity products
                List<OpportunitySchedule__c> opptyScheds = new List<OpportunitySchedule__c>();
                
                List<OpportunityLineItem> listDWsLineItems = new List<OpportunityLineItem>();
                for( Opportunity theOpportunity : listDWs) 
                    {
                        OpportunitySchedule__c opptySched = new OpportunitySchedule__c(Opportunity__c = theOpportunity.ID, Sched_Date__c = Date.newInstance(2017, 01, 01), Oppty_Sched_Qty__c = 250, Frozen_Oppty_Sched_Qty__c = 250);
                        opptyScheds.add(opptySched);
                        OpportunityLineItem oli = new OpportunityLineItem(Opportunityid=theOpportunity.id,PriceBookEntryID=priceBookEntryRecord.id,Quantity=1,UnitPrice=1,Component_Multiplier__c=1);
                        listDWsLineItems.add(oli);
                    }
                insert opptyScheds;
                insert listDWsLineItems ;
                // Insert Custom Setting for top Account  
                Top_Accounts__c top = new Top_Accounts__c();
                top.Name = 'Test Account';
                top.Account_Name__c = 'Test Account';
                insert top;
                FunnelTrackerSnapshotPopulateBatch batchController = new FunnelTrackerSnapshotPopulateBatch();
                Database.BatchableContext bc;
                batchController.start(bc);
                batchController.execute(bc, listDWsLineItems);
                batchController.finish(bc);
    }    
  }