src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria_2__c</fullName>
        <description>This field is to capture the region when approver type is sales director</description>
        <label>Criteria 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_1__c</fullName>
        <label>Threshold 1</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Project__c.object
<CustomObject>
    <description>CAS: Customer Project</description>
    <fields>
        <fullName>Actions_Closed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of tasks with status as &apos;Completed&apos; and status flag as green.</description>
        <inlineHelpText>The number of tasks with status as &apos;Completed&apos; and status flag as green.</inlineHelpText>
        <label>Actions Closed On Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If there are tasks in Task which are not completed (no Completed Date), then Activity is true; otherwise false.</description>
        <inlineHelpText>If there are tasks in Task which are not completed (no Completed Date), then Activity is true; otherwise false.</inlineHelpText>
        <label>Activity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is created to lookup to Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Projects</relationshipLabel>
        <relationshipName>CAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>This field is created to populate with the Opportunity&apos;s Account Region</description>
        <formula>TEXT(Opportunity__r.Account.Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Actions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of tasks in the Task.</description>
        <label>Total Actions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked_Exchange_Rate__c</fullName>
        <inlineHelpText>The Exchange Rate against USD which is locked when opportunity is Approved</inlineHelpText>
        <label>Locked Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TaskTriggerTest.cls
@isTest
private class TaskTriggerTest {
    private static final ID SFDC_RECORD_TYPE_ID;
    private static final String TEST_USER_PROFILE = 'System Administrator';
    private static final String TEST_USER_EMAIL = 'testuser@testorg.com.test';
    private static final Date PRODUCTION_DATE = Date.newInstance(2016, 04, 30);
    private static final String CCY_CODE_USD = 'USD';
    private static final String CCY_CODE_EUR = 'EUR';
    private static final Double EXCH_RATE_USD = 1.0;
    private static final Double EXCH_RATE_EUR = 0.9;
    private static final Integer TASK_COUNT_DEFAULT = 5;
        
    static {
        SFDC_RECORD_TYPE_ID = OpportunitiesSelector.getSfdcRecordTypeId();
    }
    
    @testSetup
    static void setup() {
    	Profile p = [SELECT Id FROM Profile WHERE Name = :TEST_USER_PROFILE];
        
        // insert a test user
        User u = new User(Alias = 'test', Email = TEST_USER_EMAIL, 
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id, UserName = TEST_USER_EMAIL);
        insert u;
        
        // insert approvers
        List<Approvers_Matrix__c> amcs = new List<Approvers_Matrix__c>();
        amcs.add(new Approvers_Matrix__c(Type__c='Regional VP', criteria_2__c='EMEA', Approver__c = u.Id, Threshold_1__c = 0));
        amcs.add(new Approvers_Matrix__c(Type__c='Regional VP', criteria_2__c='Americas', Approver__c = u.Id, Threshold_1__c = 0));
        amcs.add(new Approvers_Matrix__c(Type__c='Regional Controller', criteria_2__c='EMEA', Approver__c = u.Id, Threshold_1__c = 0));
        amcs.add(new Approvers_Matrix__c(Type__c='Regional Controller', criteria_2__c='Americas', Approver__c = u.Id, Threshold_1__c = 0));
        insert amcs;
        
        // insert FX Rates
        // There is a workflow which sets Opportunity.Locked_Exchange_Rate__c to 
        // Opportunity.Currency__r.Exchange_Rate__c, which refers to FX_Rates__c.Exchange_Rate__c
        List<FX_Rates__c> fxrs = new List<FX_Rates__c>();
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_USD, Currency_Code__c = CCY_CODE_USD, CurrencyIsoCode = CCY_CODE_USD, Exchange_Rate__c = EXCH_RATE_USD));
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_EUR, Currency_Code__c = CCY_CODE_EUR, CurrencyIsoCode = CCY_CODE_EUR, Exchange_Rate__c = EXCH_RATE_EUR));
        insert fxrs;
        
        Map<String, FX_Rates__c> fxRates = new Map<String, FX_Rates__c>();
        fxRates.put(CCY_CODE_USD, fxrs.get(0));
        fxRates.put(CCY_CODE_EUR, fxrs.get(1));
        
        // Insert an account
        Account a = new Account(Name = 'Test Account', Region__c = 'EMEA');
        insert a;
        
        // Insert an opportunity
        Opportunity o = new Opportunity(Name = 'Test Oppty', AccountId = a.Id, StageName = 'Initial Engagement');
        o.RecordTypeId = SFDC_RECORD_TYPE_ID;
        o.Production_Date__c = PRODUCTION_DATE;
        o.CloseDate = PRODUCTION_DATE - 60;
        o.Currency__c = fxRates.get(CCY_CODE_USD).Id; // Locked_Exchange_Rate__c will be set to this by workflow.
        o.CurrencyIsoCode = CCY_CODE_USD; // CurrencyIsoCode and Currency__c are correlated.
        insert o;
        
        // Insert a customer project
        Customer_Project__c cp = new Customer_Project__c();
        cp.Opportunity__c = o.Id;
        insert cp;
        
        // Insert tasks
        List<Task> tasks = new List<Task>();
        
        for (Integer i = 1; i <= TASK_COUNT_DEFAULT; i++) {
            Task t = new Task();
            t.OwnerId = u.Id;
            t.Subject = 'task ' + i;
            t.Status = 'Not Started';
            t.Priority = 'Normal';
            t.WhatId = cp.Id; 
            tasks.add(t);
        }
        
        insert tasks;
    }
    
    @isTest
    static void testTaskDueDateSetAsToday() {
        Test.startTest();
        Task t = [select ActivityDate from Task where Subject = 'task 1'];
        t.ActivityDate = null;
        update t;
        Test.stopTest();
        
        t = [select ActivityDate from Task where Subject = 'task 1'];
        
        System.assertEquals(Date.today(), t.ActivityDate);
    }
    
    @isTest
    static void testTaskDueDateNotSetAsToday() {
        Date aDate = Date.newInstance(2100, 10, 30);
        
        Test.startTest();
        Task t = [select ActivityDate from Task where Subject = 'task 1'];
        t.ActivityDate = aDate;
        update t;
        Test.stopTest();
        
        t = [select ActivityDate from Task where Subject = 'task 1'];
        
        System.assertEquals(aDate, t.ActivityDate);
    }
    
    @isTest
    static void testTaskStatusCompletedAndDateNull() {
        Test.startTest();
        Task t = [select Status, Completed_Date__c from Task where Subject = 'task 1'];
        t.Status = 'Completed';
        t.Completed_Date__c = null;
        update t;
        Test.stopTest();
        
        t = [select Completed_Date__c from Task where Subject = 'task 1'];
        
        System.assertEquals(Date.today(), t.Completed_Date__c);        
    }
    
    @isTest
    static void testTaskStatusCompletedAndDateNotNull() {
        Date aDate = Date.newInstance(2100, 10, 30);
        
        Test.startTest();
        Task t = [select Status, Completed_Date__c from Task where Subject = 'task 1'];
        t.Status = 'Completed';
        t.Completed_Date__c = aDate;
        update t;
        Test.stopTest();
        
        t = [select Status, Completed_Date__c from Task where Subject = 'task 1'];
        
        System.assertEquals('Completed', t.Status);
        System.assertEquals(aDate, t.Completed_Date__c);      
    }
    
    @isTest
    static void testTaskStatusNotCompletedAndDateNotNull() {
        Date aDate = Date.newInstance(2100, 10, 30);
        
        Test.startTest();
        Task t = [select Status, Completed_Date__c from Task where Subject = 'task 1'];
        t.Status = 'Not Started';
        t.Completed_Date__c = aDate;
        update t;
        Test.stopTest();
        
        t = [select Status from Task where Subject = 'task 1'];
        
        System.assertEquals('Completed', t.Status);        
    }
    
    @isTest
    static void testTaskStatusNotCompletedAndDateNull() {
        Date aDate = Date.newInstance(2100, 10, 30);
        
        Test.startTest();
        Task t = [select Status, Completed_Date__c from Task where Subject = 'task 1'];
        t.Status = 'Not Started';
        t.Completed_Date__c = null;
        update t;
        Test.stopTest();
        
        t = [select Status, Completed_Date__c from Task where Subject = 'task 1'];
        
        System.assertEquals('Not Started', t.Status);  
        System.assertEquals(null, t.Completed_Date__c);
    }
    
    @isTest
    static void testTaskUndelete() {
        Test.startTest();
        List<Task> tasks = [select Id from Task];
        delete tasks;
        undelete tasks;
        Test.stopTest();
        
        Integer count = [select count() from Task];
        
        System.assertEquals(TASK_COUNT_DEFAULT, count);
    }
    
    @isTest
    static void testCustProjTotalActions() {
        Test.startTest();
        User u = [select Id from User where Email = :TEST_USER_EMAIL];
        Customer_Project__c cp = [select Id from Customer_Project__c];
        
        Task t = new Task();
        t.OwnerId = u.Id;
        t.Subject = 'task test';
        t.Status = 'Not Started';
        t.Priority = 'Normal';
        t.WhatId = cp.Id;
        insert t;
        Test.stopTest();
        
        cp = [select Total_Actions__c from Customer_Project__c];
        
        System.assertEquals((TASK_COUNT_DEFAULT + 1), cp.Total_Actions__c);
    }
    
    @isTest
    static void testCustProjActionsClosedOnTime() {
        Test.startTest();
        List<Task> tasks = [select ActivityDate, Completed_Date__c from Task];
        Integer count = 0;
        
        for (Task t : tasks) {
            if (Math.mod(count, 2) == 0) {
                t.ActivityDate = Date.today();
                t.Completed_Date__c = Date.today() - 1;
            } else {
                t.ActivityDate = Date.today();
                t.Completed_Date__c = Date.today() + 1;
            }
            
            count++;
        }
        
        update tasks; 
        Test.stopTest();
        
        Customer_Project__c cp = [select Actions_Closed__c from Customer_Project__c];
        
        System.assertEquals(3, cp.Actions_Closed__c);
    }
    
    @isTest
    static void testCustProjActivityTrue() {
        Test.startTest();
        List<Task> tasks = [select Id from Task where Subject != 'task 1'];
        delete tasks;
        
        Task t = [select Completed_Date__c from Task where Subject = 'task 1'];
        t.Completed_Date__c = null;
        update t;
        Test.stopTest();
        
        Customer_Project__c cp = [select Activity__c from Customer_Project__c];
        
        System.assertEquals(true, cp.Activity__c);
    }
    
    @isTest
    static void testCustProjActivityFalse() {
        Test.startTest();
        List<Task> tasks = [select Completed_Date__c from Task];
        
        for (Task t : tasks) {
            t.Completed_Date__c = Date.today();    
        }
        
        update tasks;
        Test.stopTest();
        
        Customer_Project__c cp = [select Activity__c from Customer_Project__c];
        
        System.assertEquals(false, cp.Activity__c);
    }
}