src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Top_Accounts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of accounts used in drop down of &apos;Account Tracker&apos; tab. #SIR960</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Top 30 Accounts</label>
</CustomObject>

src/classes/AccountTrackerControllerTest.cls
@isTest
private class AccountTrackerControllerTest 
    {
        private static final String PARENT_ACCOUNT_RECORD_TYPE='Parent_Account';
        private static final ID PARENT_ACCOUNT_RECORD_TYPE_ID;
        private static Recordtype rt;
        static
        {
            rt=[Select Id, DeveloperName From RecordType Where IsActive=true AND (SobjectType = 'Account' and (DeveloperName =:PARENT_ACCOUNT_RECORD_TYPE))];
            PARENT_ACCOUNT_RECORD_TYPE_ID=rt.id;
        }
        @isTest
        static void testAccountTrackerController()
        {
            Test.startTest();
            PageReference pageRef = Page.AccountTracker;
            // Insert an account
            Account testAccount = new Account(Name = 'Test Account', Region__c = 'EMEA', RecordTypeId=PARENT_ACCOUNT_RECORD_TYPE_ID);
            insert testAccount;
            // Insert Custom Setting for top Account  
            Top_Accounts__c top = new Top_Accounts__c();
            top.Name = 'Test Account';
            top.Account_Name__c = 'Test Account';
            insert top;
            List<SelectOption> test_options = new List<SelectOption>();
            test_options.add(new SelectOption(top.Name,top.Account_Name__c));
            Test.setCurrentPageReference(new PageReference('AccountTracker'));
            AccountTrackerController controller = new AccountTrackerController();
            controller.selectedAccountName='Test Account';
            controller.getlstAccountName();
            controller.launchTracker();
            System.assertNotEquals(null,controller.launchTracker());
            test.stopTest();
        }
    }