src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMD_Industry_Segment__c</fullName>
        <description>Customer Buying Group</description>
        <inlineHelpText>Customer Buying Group</inlineHelpText>
        <label>CBG</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Claim_Value__c</fullName>
        <description>Opportunity claim value in opportunity currency.</description>
        <inlineHelpText>Summary of all products&apos; [Prod Claim Value] in opportunity currency. 
Lost/Cancelled products are excluded from this calculation.</inlineHelpText>
        <label>Oppty Claim Value</label>
        <summarizedField>OpportunityLineItem.Claim_Value__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LT_Value__c</fullName>
        <description>Opportunity lifetime value in opportunity currency.</description>
        <inlineHelpText>Summary of all products&apos; [Prod LT Value] in opportunity currency. 
Lost/Cancelled products are excluded from this calculation.</inlineHelpText>
        <label>Oppty LT Value</label>
        <summarizedField>OpportunityLineItem.LT_Value__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Lost_Cancelled_Claim_Value__c</fullName>
        <description>Opportunity lost/cancelled claim value in opportunity currency.</description>
        <inlineHelpText>Summary of all products&apos; [Prod Lost/Cancelled Claim Value] in opportunity currency.</inlineHelpText>
        <label>Oppty Lost/Cancelled Claim Value</label>
        <summarizedField>OpportunityLineItem.Lost_Cancelled_Claim_Value__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Lost_Cancelled_LT_Value__c</fullName>
        <description>Opportunity lost/cancelled lifetime value in opportunity currency.</description>
        <inlineHelpText>Summary of all products&apos; [Prod Lost/Cancelled LT Value] in opportunity currency.</inlineHelpText>
        <label>Oppty Lost/Cancelled LT Value</label>
        <summarizedField>OpportunityLineItem.Lost_Cancelled_LT_Value__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TMMA_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The field is checked if some fields are overridden by TSE for Model N Opportunities.</description>
        <label>TMMA Override</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Claim_Value_MAG_Setting__mdt.object
<CustomObject>
    <description>Store claim value year at the MAG level</description>
    <fields>
        <fullName>Claim_Value_Quarters__c</fullName>
        <label>Claim Value Quarters</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lifetime</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                    <default>true</default>
                    <label>12</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q69</fullName>
                </value>
                <value>
                    <fullName>R01</fullName>
                    <default>true</default>
                    <label>R01</label>
                </value>
                <value>
                    <fullName>R05</fullName>
                </value>
                <value>
                    <fullName>R06</fullName>
                </value>
                <value>
                    <fullName>R07</fullName>
                </value>
                <value>
                    <fullName>R08</fullName>
                </value>
                <value>
                    <fullName>R09</fullName>
                </value>
                <value>
                    <fullName>R10</fullName>
                </value>
                <value>
                    <fullName>R12</fullName>
                </value>
                <value>
                    <fullName>R13</fullName>
                </value>
                <value>
                    <fullName>R14</fullName>
                </value>
                <value>
                    <fullName>R16</fullName>
                </value>
                <value>
                    <fullName>R21</fullName>
                </value>
                <value>
                    <fullName>R22</fullName>
                </value>
                <value>
                    <fullName>R23</fullName>
                </value>
                <value>
                    <fullName>R24</fullName>
                </value>
                <value>
                    <fullName>R25</fullName>
                </value>
                <value>
                    <fullName>R26</fullName>
                </value>
                <value>
                    <fullName>R27</fullName>
                </value>
                <value>
                    <fullName>R28</fullName>
                </value>
                <value>
                    <fullName>R29</fullName>
                </value>
                <value>
                    <fullName>R30</fullName>
                </value>
                <value>
                    <fullName>R31</fullName>
                </value>
                <value>
                    <fullName>R32</fullName>
                </value>
                <value>
                    <fullName>R33</fullName>
                </value>
                <value>
                    <fullName>R34</fullName>
                </value>
                <value>
                    <fullName>R35</fullName>
                </value>
                <value>
                    <fullName>R36</fullName>
                </value>
                <value>
                    <fullName>R37</fullName>
                </value>
                <value>
                    <fullName>R38</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Claim Value MAG Setting</label>
    <pluralLabel>Opportunity Claim Value MAG Settings</pluralLabel>
</CustomObject>

src/objects/Opportunity_Claim_Value_Setting__mdt.object
<CustomObject>
    <description>General setting for Opportunity Claim Value calculation</description>
    <fields>
        <fullName>Account_CBG__c</fullName>
        <description>If opportunity account CBG equals the value, claim value is lifetime.</description>
        <label>Account CBG</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cross_Update_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, allow products claim values to be updated if triggered from objects other than Opportunity or Opportunity Product.</description>
        <label>Cross Update Allowed</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Claim Value Setting</label>
    <pluralLabel>Opportunity Claim Value Settings</pluralLabel>
</CustomObject>

src/objects/Opportunity_TMMA_Override_Setting__mdt.object
<CustomObject>
    <description>Control Opportunity fields which can be overridden by TSE for TMMA</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opportunity TMMA Override Setting</label>
    <pluralLabel>Opportunity TMMA Override Settings</pluralLabel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Claim_Value__c</fullName>
        <description>Opportunity product claim value in opportunity currency.</description>
        <inlineHelpText>Opportunity product claim value in opportunity currency.</inlineHelpText>
        <label>Prod Claim Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LT_Value__c</fullName>
        <description>Opportunity product lifetime value in opportunity currency.</description>
        <inlineHelpText>Opportunity product lifetime value in opportunity currency.</inlineHelpText>
        <label>Prod LT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lost_Cancelled_Claim_Value__c</fullName>
        <description>Opportunity product lost/cancelled claim value in opportunity currency.</description>
        <inlineHelpText>Opportunity product lost/cancelled claim value in opportunity currency.</inlineHelpText>
        <label>Prod Lost/Cancelled Claim Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lost_Cancelled_LT_Value__c</fullName>
        <description>Opportunity product lost/cancelled lifetime value in opportunity currency.</description>
        <inlineHelpText>Opportunity product lost/cancelled lifetime value in opportunity currency.</inlineHelpText>
        <label>Prod Lost/Cancelled LT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Erosion_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price Erosion Rate (%)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prod_Lost_Cancelled__c</fullName>
        <label>Prod Lost/Cancelled</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Share__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Share (%)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/objects/OpportunitySchedule__c.object
<CustomObject>
    <description>Opportunity Schedule</description>
    <fields>
        <fullName>Frozen_Oppty_Sched_Qty__c</fullName>
        <label>Frozen Oppty Sched Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Schedules</relationshipLabel>
        <relationshipName>Opportunity_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sched_Date__c</fullName>
        <label>Sched Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Opportunity Schedule</label>
    <nameField>
        <displayFormat>OS-{0000}</displayFormat>
        <label>Opportunity Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OpportunityProductClaimValue.cls
/**
 * Fields updated:
 *   OpportunityLineItem
 *	   LT_Value__c
 *     Claim_Value__c
 *	   Lost_Cancelled_LT_Value__c
 *     Lost_Cancelled_Claim_Value__c 
 */
public class OpportunityProductClaimValue {
	@TestVisible 
    private static final Map<String, String> MAG_CLAIM_VALUE_QUARTERS = new Map<String, String>();
    
    private static final Boolean CROSS_UPDATE_ALLOWED;
    private static final String ACCOUNT_CBG;
    
    // TMMA
    private static final List<String> TMMA_OVERRIDE_FIELDS_OPPTY = new List<String>();
    private static final List<String> TMMA_OVERRIDE_FIELDS_OPPTY_PROD = new List<String>();
        
    // Used to prevent claim value calculation if triggered from other object changes, such as Product2 and Account.
    public static Boolean isUpdatable = true;
    
    static {
        Opportunity_Claim_Value_Setting__mdt claimValueSetting = new OpportunityClaimValueSettingsSelector().selectWhere('MasterLabel = \'Setting\'').get(0);
        CROSS_UPDATE_ALLOWED = claimValueSetting.Cross_Update_Allowed__c;
        ACCOUNT_CBG = claimValueSetting.Account_CBG__c;
        
        List<Opportunity_Claim_Value_MAG_Setting__mdt> claimValueMagSettings = new OpportunityClaimValueMagSettingsSelector().selectAll();
        
        for (Opportunity_Claim_Value_MAG_Setting__mdt ocvms : claimValueMagSettings) {
        	MAG_CLAIM_VALUE_QUARTERS.put(ocvms.MAG__c, ocvms.Claim_Value_Quarters__c);
        }
        
        // TMMA
        List<Opportunity_TMMA_Override_Setting__mdt> tmmaOverrideSettings = new OpportunityTmmaOverrideSettingsSelector().selectAll();
        
        for (Opportunity_TMMA_Override_Setting__mdt otos : tmmaOverrideSettings) {
        	if (otos.Object_Name__c == 'Opportunity') {
        		TMMA_OVERRIDE_FIELDS_OPPTY.add(otos.Field_Name__c);	
        	} else if (otos.Object_Name__c == 'OpportunityLineItem') {
        		TMMA_OVERRIDE_FIELDS_OPPTY_PROD.add(otos.Field_Name__c);	
        	}
        }
    }
   
    interface ClaimValueType {
        void setOpptyProdClaimValue(Opportunity oppty, OpportunityLineItem opptyLineItem, List<OpportunitySchedule__c> opptyScheds);
    }
    
    class LifetimeClaimValueType implements ClaimValueType {
        public void setOpptyProdClaimValue(Opportunity oppty, OpportunityLineItem opptyLineItem, List<OpportunitySchedule__c> opptyScheds) {
        	p('setOpptyProdClaimValue');
			List<Double> quarterQtys = new List<Double>();
			
            for (OpportunitySchedule__c opptySched : opptyScheds) {
            	quarterQtys.add(opptySched.Frozen_Oppty_Sched_Qty__c);
            }
           
            opptyLineItem.Claim_Value__c = calcOpptyProdClaimValue(oppty, opptyLineItem, quarterQtys);
            opptyLineItem.LT_Value__c = opptyLineItem.Claim_Value__c;            
        }
        
        private void p(String msg) {
			CommonUtils.p(this, '//-c', msg);
		}
    }
    
    class ShortLivedClaimValueType implements ClaimValueType {
        public void setOpptyProdClaimValue(Opportunity oppty, OpportunityLineItem opptyLineItem, List<OpportunitySchedule__c> opptyScheds) {
        	p('setOpptyProdClaimValue');
        	List<Double> quarterQtys = new List<Double>();
        	List<Double> claimValueQtrQtys = new List<Double>();
    		Date prodDate = oppty.Production_Date__c;
    		String prodYrQtr = prodDate.year() + '0' + (((prodDate.month() - 1) / 3) + 1);
            Integer startIndex = -1;
    	
    		for (Integer i = 0; i < opptyScheds.size(); i++) {
    			OpportunitySchedule__c opptySched = opptyScheds.get(i);
    			Date schedDate = opptySched.Sched_Date__c;
    			String yrQtr = schedDate.year() + '0' + (((schedDate.month() - 1) / 3) + 1); 	
    		
    			if (yrQtr.equals(prodYrQtr)) {
    				startIndex = i;
    			}
    		
    			quarterQtys.add(opptySched.Frozen_Oppty_Sched_Qty__c);
    		}
        	
        	Integer magClaimValueQuarters = Integer.valueOf(MAG_CLAIM_VALUE_QUARTERS.get(opptyLineItem.MAG__c));
            Integer endIndex = startIndex + magClaimValueQuarters;
            
            for (Integer i = startIndex; (i < endIndex && i < quarterQtys.size()); i++) {
            	claimValueQtrQtys.add(quarterQtys.get(i));     
            }
            
            opptyLineItem.Claim_Value__c = calcOpptyProdClaimValue(oppty, opptyLineItem, claimValueQtrQtys);
            opptyLineItem.LT_Value__c = calcOpptyProdClaimValue(oppty, opptyLineItem, quarterQtys);            
        } 
        
        private void p(String msg) {
			CommonUtils.p(this, '//-c', msg);
		}       
    }
    
    public static void setOpportunityProductClaimValues(List<OpportunityLineItem> opptyLineItems) {
        p2('setOpportunityProductClaimValues');
        if (!(Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate) && isUpdatable())) return;
                
        setOpptyProdClaimValues(opptyLineItems);
    }
    
    private static void setOpptyProdClaimValues(List<OpportunityLineItem> opptyLineItems) {
        p2('setOpptyProdClaimValues');
        if (opptyLineItems.size() == 0) return;
                	
        Map<ID, Opportunity> opptyDetails = getOpptyDetails(opptyLineItems);
        ClaimValueType claimValueType;
        
    	List<OpportunitySchedule__c> opptysScheds = new OpportunitySchedulesSelector().selectByOpptyId(opptyDetails.keySet());
    		
    	if (opptysScheds.size() == 0) return;
            
        for (OpportunityLineItem oli : opptyLineItems) {
        	Opportunity oppty = opptyDetails.get(oli.OpportunityId);
            	
            List<OpportunitySchedule__c> opptyScheds = getOpptyScheds(opptysScheds, oppty);
                    
			claimValueType = getClaimValueType(oppty, oli);
            claimValueType.setOpptyProdClaimValue(oppty, oli, opptyScheds);
                    
            setOpptyProdCancelledClaimValue(oli);
			System.debug('//J SFDC type oppty prod => lost/cancelled: ' + oli.Prod_Lost_Cancelled__c + ', claim value: ' + oli.Claim_Value__c + ', cancelled claim value: ' + oli.Lost_Cancelled_Claim_Value__c + ', lifetime value: ' + oli.LT_Value__c + ', cancelled lifetime value: ' + oli.Lost_Cancelled_LT_Value__c);
        }
    }
    
    private static Map<ID, Opportunity> getOpptyDetails(List<OpportunityLineItem> opptyLineItems) {
    	p2('getOpptyDetails');
        Set<ID> opptyIds = OpportunityProductHelper.getOpptyIDs(opptyLineItems);
          
        Map<ID, Opportunity> result = new Map<ID, Opportunity>(new OpportunitiesSelector().selectByIdWithAccountAndOwner(opptyIds)); 
         
        return result;
    }
    
    private static ClaimValueType getClaimValueType(Opportunity oppty, OpportunityLineItem opptyLineItem) {
    	p2('getClaimValueType');
		if (isLifetime(oppty, opptyLineItem)) {
  			return new LifetimeClaimValueType();           
        } else {
            return new ShortLivedClaimValueType();
        }
    }
    
    @TestVisible
    private static Boolean isLifetime(Opportunity oppty, OpportunityLineItem opptyLineItem) {  
    	p2('isLifetime');  	
   		if (oppty.AccountId == null || oppty.Account.CMD_Industry_Segment__c == null) {
    		return true;	
    	}
    	
        String opptyAcctCBG = oppty.Account.CMD_Industry_Segment__c;
		String magClaimValueQuarters = MAG_CLAIM_VALUE_QUARTERS.get(opptyLineItem.MAG__c);
        
        if ((magClaimValueQuarters == null) && Test.isRunningTest()) {
        	return true;	
        }
        
        if ((opptyAcctCBG == ACCOUNT_CBG) || !magClaimValueQuarters.isNumeric()) {
        	return true;    
        } else {
            return false;
        }
    }
    
    private static void setOpptyProdCancelledClaimValue(OpportunityLineItem opptyLineItem) {
    	p2('setOpptyProdCancelledClaimValue');
    	opptyLineItem.Lost_Cancelled_Claim_Value__c = 0;
    	opptyLineItem.Lost_Cancelled_LT_Value__c = 0;
    	
        if (OpportunityProductHelper.isOpptyProdLostCancelled(opptyLineItem)) {
            opptyLineItem.Lost_Cancelled_Claim_Value__c = opptyLineItem.Claim_Value__c;
            opptyLineItem.Claim_Value__c = 0;
            opptyLineItem.Lost_Cancelled_LT_Value__c = opptyLineItem.LT_Value__c;
            opptyLineItem.LT_Value__c = 0;
        }    
    }
    
    private static List<OpportunitySchedule__c> getOpptyScheds(List<OpportunitySchedule__c> opptyScheds, Opportunity oppty) {
    	p2('getOpptyScheds');
    	List<OpportunitySchedule__c> result = new List<OpportunitySchedule__c>();
    	
    	for (OpportunitySchedule__c os : opptyScheds) {
    		if (os.Opportunity__c == oppty.Id) {
    			result.add(os);
    		}
    	}
    	
    	return result;
    }
    
    private static Double calcOpptyProdClaimValue(Opportunity oppty, OpportunityLineItem opptyLineItem, List<Double> quarterQtys) {
    	p2('calcOpptyProdClaimValue');
    	Decimal price = 0;
    	Decimal sumQuarterValue = 0;
    	
    	for (Integer i = 0; i < quarterQtys.size(); i++) {
    		price = OpportunityProductHelper.calcOpportunityProductSchedulePrice(opptyLineItem.UnitPrice, opptyLineItem.Price_Erosion_Rate__c, i);
    		sumQuarterValue += (quarterQtys.get(i) != null ? quarterQtys.get(i) : 0) * price;
    	}
    	
    	Double result = sumQuarterValue * opptyLineItem.Component_Multiplier__c * (opptyLineItem.Share__c / 100);
    	
    	return result;
    }
    
    private static Boolean isUpdatable() {
    	p2('isUpdatable');
        return (isUpdatable || CROSS_UPDATE_ALLOWED) ? true : false;    
    }
    
    private static Map<Id, Opportunity> getOpptyRecordTypeIds(List<OpportunityLineItem> opptyLineItems) {
    	p2('getOpptyRecordTypeIds');
        Set<Id> opptyIds = new Set<Id>();
        
        for (OpportunityLineItem oli : opptyLineItems) {
            opptyIds.add(oli.OpportunityId);
        }
        
        Map<Id, Opportunity> result = new Map<Id, Opportunity>(new OpportunitiesSelector().selectById(opptyIds));
        
        return result;
    }
    
    // TMMA
    public static void bypassOpportunityProductMnUpdateForTmmaOverride(Map<ID, OpportunityLineItem> opptyLineItemsOld, Map<ID, OpportunityLineItem> opptyLineItemsNew) {
    	p2('bypassOpportunityProductMnUpdateForTmmaOverride');
    	Map<ID, Opportunity> opptys = getOpptyRecordTypeIDs(opptyLineItemsNew.values());
        
        for (OpportunityLineItem oliNew : opptyLineItemsNew.values()) {
        	OpportunityLineItem oliOld = opptyLineItemsOld.get(oliNew.Id);    
            Opportunity oppty = opptys.get(oliNew.OpportunityId);
            
            if (OpportunityHelper.isRecordTypeMN(oppty) && OpportunityHelper.isTmmaOverride(oppty) && CommonUtils.isIntegrationUser()) {
            	setTmmaOverrideFields(oliOld, oliNew, TMMA_OVERRIDE_FIELDS_OPPTY_PROD);
            }
        }	
    }
    
    public static void updateTmmaOverrideIfOpportunityProductMnUpdatedByTmma(Map<ID, OpportunityLineItem> opptyLineItemsOld, Map<ID, OpportunityLineItem> opptyLineItemsNew, fflib_ISObjectUnitOfWork uow) {
    	p2('updateTmmaOverrideIfOpportunityProductMnUpdatedByTmma');
    	Map<ID, Opportunity> opptys = getOpptyRecordTypeIDs(opptyLineItemsNew.values());
    	
    	Map<ID, Opportunity> opptyMNs = new Map<ID, Opportunity>();
    	
    	for (Opportunity o : opptys.values()) {
    		if (OpportunityHelper.isRecordTypeMN(o)) {
    			opptyMNs.put(o.Id, o);
    		}
    	}
    	
    	if (opptyMNs.size() == 0) return;
    	
    	for (OpportunityLineItem oliNew : opptyLineItemsNew.values()) {
    		OpportunityLineItem oliOld = opptyLineItemsOld.get(oliNew.Id);    
            Opportunity oppty = opptyMNs.get(oliNew.OpportunityId);
            
            if (oppty != null && OpportunityHelper.isRecordTypeMN(oppty) && !CommonUtils.isIntegrationUser() && isTmmaOverrideFieldsChanged(oliOld, oliNew, TMMA_OVERRIDE_FIELDS_OPPTY_PROD)) {
            	oppty.TMMA_Override__c = true;
            	uow.registerDirty(oppty);
            }		
    	}
    }
    
    public static void bypassOpportunityMnUpdateForTmmaOverride(Map<Id, Opportunity> opptysOld, Map<Id, Opportunity> opptysNew) {
    	p2('bypassOpportunityMnUpdateForTmmaOverride');
    	Set<Id> opptyIds = new Set<Id>();
    	
    	for (Opportunity oNew : opptysNew.values()) {
    		if (OpportunityHelper.isRecordTypeMN(oNew)) opptyIds.add(oNew.Id);
    	}
    	
    	if (opptyIds.size() == 0) return;
    	
    	Map<Id, Opportunity> oppties = new Map<Id, Opportunity>(new OpportunitiesSelector().selectByIdWithAccountAndOwner(opptyIds));
    	
    	for (Opportunity oNew : opptysNew.values()) {
        	Opportunity oOld = opptysOld.get(oNew.Id);    
                        
            if (OpportunityHelper.isRecordTypeMN(oNew) && OpportunityHelper.isTMMA(oppties.get(oOld.Id)) && CommonUtils.isIntegrationUser()) {
            	oNew.AccountId = oOld.AccountId;
            }
            
            if (OpportunityHelper.isRecordTypeMN(oNew) && OpportunityHelper.isTmmaOverride(oNew) && CommonUtils.isIntegrationUser()) {
            	setTmmaOverrideFields(oOld, oNew, TMMA_OVERRIDE_FIELDS_OPPTY);
            }
        }	
    }
    
    public static void updateTmmaOverrideIfOpportunityMnUpdatedByTmma(Map<ID, Opportunity> opptysOld, Map<ID, Opportunity> opptysNew) {
    	p2('updateTmmaOverrideIfOpportunityMnUpdatedByTmma');
    	for (Opportunity oNew : opptysNew.values()) {
        	Opportunity oOld = opptysOld.get(oNew.Id);
        	
        	if (OpportunityHelper.isRecordTypeMN(oNew) && !CommonUtils.isIntegrationUser() && isTmmaOverrideFieldsChanged(oOld, oNew, TMMA_OVERRIDE_FIELDS_OPPTY)) {
            	oNew.TMMA_Override__c = true;	
            }
    	}	
    }
    
    private static void setTmmaOverrideFields(SObject soOld, SObject soNew, List<String> fieldNames) {
    	p2('setTmmaOverrideFields');
    	for (String fn : fieldNames) {
        	soNew.put(fn, soOld.get(fn));	
        }	
    }
    
    private static Boolean isTmmaOverrideFieldsChanged(SObject soOld, SObject soNew, List<String> fieldNames) {
    	p2('isTmmaOverrideFieldsChanged');
    	Boolean result = false;
    	
    	for (String fn : fieldNames) {
    		result |= (soOld.get(fn) != soNew.get(fn));
    	}
    	
    	return result;
    }
    
    private static void p2(String msg) {
		CommonUtils.p(OpportunityProductClaimValue.class, '//-c', msg);
	}
	
}