src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NXP_GID__c</fullName>
        <externalId>true</externalId>
        <label>NXP GID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <inlineHelpText>Customer address - state/province</inlineHelpText>
        <label>State/ Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aceh</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Andaman And Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>An Giang</fullName>
                </value>
                <value>
                    <fullName>Anhui Province</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bac Giang</fullName>
                </value>
                <value>
                    <fullName>Bac Kan</fullName>
                </value>
                <value>
                    <fullName>Bac Lieu</fullName>
                </value>
                <value>
                    <fullName>Bac Ninh</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California S</fullName>
                </value>
                <value>
                    <fullName>Bali</fullName>
                </value>
                <value>
                    <fullName>Banten</fullName>
                </value>
                <value>
                    <fullName>Ba Ria Vung Tau</fullName>
                </value>
                <value>
                    <fullName>Beijing City</fullName>
                </value>
                <value>
                    <fullName>Bengkulu</fullName>
                </value>
                <value>
                    <fullName>Ben Tre</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Binh Dinh</fullName>
                </value>
                <value>
                    <fullName>Binh Duong</fullName>
                </value>
                <value>
                    <fullName>Binh Phuoc</fullName>
                </value>
                <value>
                    <fullName>Binh Thuan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LeadOwnerAssignment__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_ZIP_Code__c</fullName>
        <label>End ZIP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LeadOwnerAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_ZIP_Code__c</fullName>
        <label>Start ZIP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>city</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LeadOwnerAssignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>LeadOwnerAssignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LeadOwnerAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadOwnerAssignmentHandlerTest.cls
/*************************************************************************
@Created By:     Jewelslyn
@Description:    Test class for lead owner Assignment.
**************************************************************************/

@isTest
public class LeadOwnerAssignmentHandlerTest {
    
    
    public static final String TEST_USER_PROFILE = 'Standard User';
    public static final String TEST_USER_EMAIL_0 = 'testuser@testorg.com.test';
    public static final String TEST_USER_EMAIL_1 = 'testuser1@testorg.com.test';
    public static final String TEST_USER_EMAIL_2 = 'testuser2@testorg.com.test';
    public static final String TEST_USER_EMAIL_3 = 'testuser3@testorg.com.test';
    public static list<User> listUser=new list<user>();
    public static list<contact> listContact=new list<contact>();
             
    @testSetup
    static void setup(){
        map<id,string> mapUserName=new map<id,String>();
        LeadOwnerAssignmentHandler.init();
                
        Profile p = [SELECT Id FROM Profile WHERE Name = :TEST_USER_PROFILE];
        
        // insert a test user
        
        User u = new User(Alias = 'test', Email = TEST_USER_EMAIL_0, 
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id, UserName = TEST_USER_EMAIL_0);
        listUser.add(u);
        User u2 = new User(Alias = 'test1', Email = TEST_USER_EMAIL_1, 
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id, UserName = TEST_USER_EMAIL_1);
        listUser.add(u2);
        insert listUser;
        
        
        // Insert  accounts
        List<account> listAcc=new list<Account>();
        account a3=new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 1',
                                NXP_GID__c='12045',recordTypeId=LeadOwnerAssignmentHandler.PARENT_RECORD_TYPE);
        insert a3;
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 4 - TMMA',
                               NXP_GID__c='12145',ParentId=a3.Id,country__c='Test Country',state_province__c='Test State'));                
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 4 - ROM',
                                NXP_GID__c='12345',ParentId=a3.Id,country__c='Test Country',state_province__c='Test State'));                
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 1',
                                NXP_GID__c='12245',ParentId=a3.Id));                       
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 1',
                                ParentId=a3.Id,country__c='Test Country',state_province__c='Test State'));                
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 4 - TMMA',
                               NXP_GID__c='12145',ParentId=a3.Id,country__c='Test Country',city__c='Test City'));                       
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 1',
                                NXP_GID__c='12245',ParentId=a3.Id,country__c='Test Country',city__c='Test city'));                
        listAcc.add(new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 1',
                                NXP_GID__c='12245',ParentId=a3.Id,country__c='Test Country1',city__c='Test citys'));        
        insert listAcc;        
        
        // Insert contacts
        
        for(account a:listAcc){
            listContact.add(new Contact(FirstName='Test',LastName='Contact',  Title = 'strTitle',
                                  email = TEST_USER_EMAIL_0,AccountId=a.Id));                
        	listContact.add(new Contact(FirstName='Test',LastName='Contact',  Title = 'strTitle',
                                  email = TEST_USER_EMAIL_1,AccountId=a.Id));                
        	listContact.add(new Contact(FirstName='Test',LastName='Contact',  Title = 'strTitle',
                                  email = TEST_USER_EMAIL_2,AccountId=a.Id));
        }                
        insert listContact;
        
        //Insert Lead Owner assignment
        list<LeadOwnerAssignment__c> listLeadOwnerAssignmt=new list<LeadOwnerAssignment__c>();
        listLeadOwnerAssignmt.add(new LeadOwnerAssignment__c(Country__c='Test Country',city__c='Test City1',End_ZIP_Code__c='14',
                                                             Lead_Owner__c=u.Id,Start_ZIP_Code__c='10',State__c='Test State 1'));
        listLeadOwnerAssignmt.add(new LeadOwnerAssignment__c(Country__c='Test Country',city__c='Test City',
                                                             Lead_Owner__c=u.Id,State__c='Test State'));
        listLeadOwnerAssignmt.add(new LeadOwnerAssignment__c(Country__c='Test Country',city__c='Test City',
                                                             Lead_Owner__c=u.Id,State__c='Test State 1'));
        insert listLeadOwnerAssignmt;
        
        //Insert Leads
        
        list<lead> listLead=new list<lead>();
    
        DateTime d = System.now().addHours(-3);
        listLead.add(new lead(firstName='Test', LastName='Lead', Company='Test Company',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',state='Test State',email=TEST_USER_EMAIL_0,
                             createdDate=d));                             
    	listLead.add(new lead(FirstName='Test',LastName='Lead1', Company='Test Company1',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',state='Test State',email=TEST_USER_EMAIL_1,
                             createdDate=d));
    	listLead.add(new lead(FirstName='Test',LastName='Lead2', Company='Test Company2',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',state='Test State',email=TEST_USER_EMAIL_2,
                             createdDate=d));    
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',state='Test State',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='12345',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',state='Test State',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='12145',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',state='Test State',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='12245',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country1', city='Test City1',state='Test State',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='12045',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='12045',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', state='Test State',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='12045',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='Test Country', state='Test State',email=TEST_USER_EMAIL_3,
                              NXP_Global_Customer_Master_ID__c='120456',createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.UNCATEGORIZED_RECORD_TYPE, 
                              status='Open',country='TCN', state='TST',email=TEST_USER_EMAIL_3,createdDate=d));
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.ROM_LEAD_RECORD_TYPE, 
                              status='Open',country='Test Country', postalCode='12',email=TEST_USER_EMAIL_3,createdDate=d)); 
                                                         
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.ROM_LEAD_RECORD_TYPE, 
                              status='Open',country='Test Country', state='Test State',email=TEST_USER_EMAIL_3,createdDate=d));
                             
        listLead.add(new lead(FirstName='Test',LastName='Lead3', Company='Test compan3',RecordTypeId=LeadOwnerAssignmentHandler.ROM_LEAD_RECORD_TYPE, 
                              status='Open',country='Test Country', city='Test City',email=TEST_USER_EMAIL_3,createdDate=d                            
                              ));      
                             
        
                              
        insert listLead;                                                                                   
    }
    @isTest
    static void testContactBasedMapping(){
        Test.starttest();
       
         DateTime d = System.now().addHours(-2);
        list<Lead> listLeadUncategorized=[SELECT id,name,NXP_Global_Customer_Master_ID__c,Email,Status,OwnerId,
                                          RecordTypeId,Description,street,city,country,state,company from Lead
                                          where RecordType.Name='Uncategorized Leads'And createdDate <=:d];
        system.assert(listLeadUncategorized.size()!=0);        
        LeadOwnerAssignmentBatch batchController = new LeadOwnerAssignmentBatch();
        Database.executebatch(batchController);                 
        Test.stopTest();
    }
    @isTest
    static void testGidBasedMapping(){
        Test.startTest();
        DateTime d = System.now().addHours(-2);
        list<Lead> listLeadUncategorized=[SELECT id,name,NXP_Global_Customer_Master_ID__c,Email,Status,OwnerId,
                                          RecordTypeId,Description,street,city,country,state,company from Lead
                                          where RecordType.Name='Uncategorized Leads'And createdDate <=:d];
        system.assert(listLeadUncategorized.size()!=0);        
        LeadOwnerAssignmentBatch batchController = new LeadOwnerAssignmentBatch();
        Database.executebatch(batchController); 
        Test.stopTest();
    }        
}