src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <label>Segment Approval Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Automotive &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Computing</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Energy Management</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Home/Building Automation (HABA)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Secure Identity</fullName>
                </value>
                <value>
                    <fullName>Secure Transactions</fullName>
                </value>
                <value>
                    <fullName>Tagging &amp; Authentication</fullName>
                </value>
                <value>
                    <fullName>Wireless Infrastructure and RF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <description>Region Specific Sales Area</description>
        <inlineHelpText>Under each Region, Sales Areas are defined.</inlineHelpText>
        <label>Sales Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>AUT EMEA HQ</fullName>
                </value>
                <value>
                    <fullName>AUT EMEA TN</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>AUTO CAR OEM</fullName>
                </value>
                <value>
                    <fullName>AUTO EMEA</fullName>
                </value>
                <value>
                    <fullName>AUTO EMEA MM</fullName>
                </value>
                <value>
                    <fullName>BAY</fullName>
                </value>
                <value>
                    <fullName>BOSCH</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>CENTRAL</fullName>
                </value>
                <value>
                    <fullName>CONTINENTAL</fullName>
                </value>
                <value>
                    <fullName>EAST</fullName>
                </value>
                <value>
                    <fullName>EMEA CIS</fullName>
                </value>
                <value>
                    <fullName>EMEA ID Remaining</fullName>
                </value>
                <value>
                    <fullName>EMEA North/Central</fullName>
                </value>
                <value>
                    <fullName>EMEA South/East</fullName>
                </value>
                <value>
                    <fullName>EMEA Strategic</fullName>
                </value>
                <value>
                    <fullName>GC Automotive</fullName>
                </value>
                <value>
                    <fullName>GC Foxconn</fullName>
                </value>
                <value>
                    <fullName>GC Identification</fullName>
                </value>
                <value>
                    <fullName>GC Mass Market China</fullName>
                </value>
                <value>
                    <fullName>GC Mass Market Taiwan</fullName>
                </value>
                <value>
                    <fullName>GC N. China</fullName>
                </value>
                <value>
                    <fullName>GC S. China</fullName>
                </value>
                <value>
                    <fullName>GC Taiwan</fullName>
                </value>
                <value>
                    <fullName>GC Wire. Infra.</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Japan Automotive</fullName>
                </value>
                <value>
                    <fullName>Japan ID</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Child_Account</fullName>
        <active>true</active>
        <label>Child Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Service_Level_Criteria__c.object
<CustomObject>
    <description>Created by shridevi, as part of SIR 1329(2016.11): This object is to store the email addresses(patterns) and Contact service level data.</description>
    <fields>
        <fullName>Contact_Service_Level__c</fullName>
        <description>Created by Shridevi, as part of SIR 1329(2016.11): This field is used to store the Contact Service Level value.</description>
        <label>Contact Service Level</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_Name__c</fullName>
        <description>Created By Shridevi, as part of SIR 1329(2016.11) : This field is to store the field name of the contact, which is used for identifying the Contact Service Level.</description>
        <label>Criteria Field Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_Value__c</fullName>
        <description>Created by Shridevi, as part of SIR 1329(2016.11): This field is used for storing the value of the criteria field which we are using for identifying the Contact Service Level.</description>
        <label>Criteria Field Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Contact Service Level Criteria</label>
    <nameField>
        <displayFormat>CSL-{00000}</displayFormat>
        <label>CSL Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Service Level Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TS_customer_category_with_CSL_values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting includes the account&apos;s customer category and respective Contact Service Level values.</description>
    <fields>
        <fullName>Contact_Service_Level__c</fullName>
        <label>Contact Service Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TS customer category with CSL values</label>
</CustomObject>

src/classes/ContactClassTest.cls
/*  
  
   @Last Modified By   : Shridevi Badiger
   @Last Modified Date : 20-Oct-2016
   @Description : SIR 1329-test the functionality to Populate value for Contact Service Level field.

**********************************************************************
 @Last Modified By   : Shridevi Badiger
 @Last Modified Date : 20-Mar-2017
 @Description : SIR 324-test the functionality to Populate value for Contact Service Level field with new values and custom setting.

**********************************************************************/
@isTest
public class ContactClassTest{
    private static final String ACCOUNT_CHILDACCOUNT = 'Child_Account';
    private static final String ACCOUNT_ParentACCOUNT = 'Parent_Account';
    
    public static RecordType childAccount;
    public static RecordType parentAccount;
    public static User objUser{get;set;}
    public static List<Account> lstChildAccount=new list<Account>();
    public static Contact objContact1{get;set;}
    public static Account objChildAccount{get;set;}

    private static void CreateContactServiceLevelCriteria()
    {
        list<Contact_Service_Level_Criteria__c> lstCSLC=new list<Contact_Service_Level_Criteria__c>();
        lstCSLC.add(new Contact_Service_Level_Criteria__c(Criteria_Field_Name__c='Email',Criteria_Field_Value__c='toni@zollikofer.eu',Contact_Service_Level__c='A-DirectCust'));
        lstCSLC.add(new Contact_Service_Level_Criteria__c(Criteria_Field_Name__c='Email',Criteria_Field_Value__c='CN.ABB.COM',Contact_Service_Level__c='A-DirectCust'));
        lstCSLC.add(new Contact_Service_Level_Criteria__c(Criteria_Field_Name__c='Email',Criteria_Field_Value__c='CN.BOSCH.COM',Contact_Service_Level__c='A-DirectCust'));
        
        insert lstCSLC;
    
    }
    
    private static void fetchRecordTypes()
    {
        for(RecordType rt : [Select Id, DeveloperName
                              From RecordType
                              Where IsActive=true and
                               (SobjectType = 'Account' and (DeveloperName =: ACCOUNT_CHILDACCOUNT or DeveloperName =: ACCOUNT_ParentACCOUNT) 
                              )
                              Limit 2])
        {
            if(rt.DeveloperName == ACCOUNT_CHILDACCOUNT)
            {
                childAccount = rt;
            }
            else if(rt.DeveloperName == ACCOUNT_ParentACCOUNT)
            {
                parentAccount = rt; 
            }            
        }
    } 
    //Added By Shridevi as part of SIR 1329-to create parent account
    private static Account createParentAccount()
    {
        fetchRecordTypes();
        //Method to create a Parent Account
        Account objParentAccount;
        objParentAccount = new Account(RecordTypeID= parentAccount.ID,
                                                Name = 'Bosch', Customer_Category__c= 'Channel');
        return  objParentAccount;
    }
    //Added By Shridevi as part of SIR 1329-to create user
    private static void createTestUser()
    {
   //  UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
   //,UserRoleId = portalRole.Id
        Profile objProfile = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        system.assert(objProfile.Id != null);
        
        objUser= new User(alias = 'nUser' , email= 'testing@test.com', emailencodingkey='UTF-8', lastname='test',languagelocalekey='en_US', localesidkey='en_US', 
                                 profileid = objProfile.Id, timezonesidkey='America/Los_Angeles', username= 'prakhartest' + datetime.now().millisecond() +'@test.com' );
            
        insert objUser;
    }
    
    //Added By Shridevi as part of SIR 1329-to create child account
     private static Account createChildAccount(ID parentAccountId,string customerCategory)
    {
       
        objChildAccount = new Account(RecordTypeID= childAccount.ID,ParentId =parentAccountId,ownerId=objUser.id,  
                                            Name = 'Bosch Japan', Region__c = 'Japan',
                                             Sales_Area__c = 'Japan ID', Industry_Segment__c = 'Mobile',
                                             Country__c = 'Japan',customer_category__c=customerCategory);
        return objChildAccount;    
    }
     //Added By Shridevi as part of SIR 1329-to create conatcts
   // @future
    private static Contact createTestContact(id AccountId)    
    {   
       
       objContact1=new Contact(FirstName='test1',LastName='strLastName', Title = 'strTitle',
                                          Phone = '8123978919', email = 'test1@CN.BOSCH.COM', AccountID = AccountId,CanAllowPortalSelfReg=false,contact_service_level__c=''); 
        
    
         return objContact1 ;
     }
     //Added by Shridevi as part of SIR 324.
   public static void createCustomSetting()
    {
            list<TS_customer_category_with_CSL_values__c> listCustomerCategorySetting=new list<TS_customer_category_with_CSL_values__c>(); //Custom Setting for Contact Fields
            listCustomerCategorySetting.add(new TS_customer_category_with_CSL_values__c(Name='Tier1',contact_service_level__c='A1_Tier_1'));
            
            listCustomerCategorySetting.add(new TS_customer_category_with_CSL_values__c(Name='Tier2',contact_service_level__c='A1_Tier_2'));
            
            listCustomerCategorySetting.add(new TS_customer_category_with_CSL_values__c(Name='Tier3',contact_service_level__c='A1_Tier_3'));
            
            listCustomerCategorySetting.add(new TS_customer_category_with_CSL_values__c(Name='Tier4 - TMMA',contact_service_level__c='A1_NXP'));
            
            listCustomerCategorySetting.add(new TS_customer_category_with_CSL_values__c(Name='Tier4 - RoM',contact_service_level__c='B1_Tier_4_ROM'));
            
            listCustomerCategorySetting.add(new TS_customer_category_with_CSL_values__c(Name='Tier4 - Long Tail',contact_service_level__c='B1_Tier_4_Longtail'));
            
            insert listCustomerCategorySetting;
    }
   //Added By Shridevi as part of SIR 1329-to test the functionality to Populate value for Contact Service Level field.   
 @isTest
    public static void TestCSLIdentification()
    { 
        List<Contact> lstContact=new List<Contact>();
        createTestUser();
        createCustomSetting();
        CreateContactServiceLevelCriteria();
        Account objParentAccount = createParentAccount();
        insert objParentAccount;
        system.assert(objParentAccount.id!=null);
        
        lstChildAccount.add(createChildAccount(objParentAccount.id,'Tier1'));
        lstChildAccount.add(createChildAccount(objParentAccount.id,'Tier2'));
        insert lstChildAccount;
        lstChildAccount=[select id,customer_category__c,name from account where id in:lstChildAccount];
        
        system.debug(lstChildAccount);
        
        lstContact.add(createTestContact( lstChildAccount[0].id));
        lstContact.add(createTestContact( lstChildAccount[1].id));
        lstContact.add(createTestContact( lstChildAccount[0].id));
        test.starttest();
        //system.debug('acc 2:'+lstChildAccount[1]);
        lstContact[0].Email='test@zollikofer.eu';
        lstContact[1].Email='toni@zollikofer.eu';
        lstContact[2].Email='shridevi@CN.ABB.COM';
        lstContact[2].AccountId=null;
        
        insert lstContact;
        
        lstContact=[select id,name,Email,AccountID,contact_service_level__c from contact where id in:lstContact];
          
        System.debug(lstContact[0].contact_service_level__c);
        System.debug(lstContact[1].contact_service_level__c);
        system.assert(lstContact[0].contact_service_level__c=='A1_Tier_1');
      
        system.assert(lstContact[1].contact_service_level__c=='A-DirectCust');  
        system.assert(lstContact[2].contact_service_level__c=='A-DirectCust'); 
        lstContact[0].Email='test@test.eu';
        lstContact[0].AccountId=null;
        update lstContact;
        lstContact=[select id,name,Email,AccountID,contact_service_level__c from contact where id in:lstContact];
        system.assert(lstContact[0].contact_service_level__c=='B2-OtherCompany'); 
        test.stoptest();
    }  
}