src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <label>Segment Approval Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Automotive &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Computing</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Energy Management</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Home/Building Automation (HABA)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Secure Identity</fullName>
                </value>
                <value>
                    <fullName>Secure Transactions</fullName>
                </value>
                <value>
                    <fullName>Tagging &amp; Authentication</fullName>
                </value>
                <value>
                    <fullName>Wireless Infrastructure and RF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <description>Region Specific Sales Area</description>
        <inlineHelpText>Under each Region, Sales Areas are defined.</inlineHelpText>
        <label>Sales Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>AUT EMEA HQ</fullName>
                </value>
                <value>
                    <fullName>AUT EMEA TN</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>AUTO CAR OEM</fullName>
                </value>
                <value>
                    <fullName>AUTO EMEA</fullName>
                </value>
                <value>
                    <fullName>AUTO EMEA MM</fullName>
                </value>
                <value>
                    <fullName>BAY</fullName>
                </value>
                <value>
                    <fullName>BOSCH</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>CENTRAL</fullName>
                </value>
                <value>
                    <fullName>CONTINENTAL</fullName>
                </value>
                <value>
                    <fullName>EAST</fullName>
                </value>
                <value>
                    <fullName>EMEA CIS</fullName>
                </value>
                <value>
                    <fullName>EMEA ID Remaining</fullName>
                </value>
                <value>
                    <fullName>EMEA North/Central</fullName>
                </value>
                <value>
                    <fullName>EMEA South/East</fullName>
                </value>
                <value>
                    <fullName>EMEA Strategic</fullName>
                </value>
                <value>
                    <fullName>GC Automotive</fullName>
                </value>
                <value>
                    <fullName>GC Foxconn</fullName>
                </value>
                <value>
                    <fullName>GC Identification</fullName>
                </value>
                <value>
                    <fullName>GC Mass Market China</fullName>
                </value>
                <value>
                    <fullName>GC Mass Market Taiwan</fullName>
                </value>
                <value>
                    <fullName>GC N. China</fullName>
                </value>
                <value>
                    <fullName>GC S. China</fullName>
                </value>
                <value>
                    <fullName>GC Taiwan</fullName>
                </value>
                <value>
                    <fullName>GC Wire. Infra.</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Japan Automotive</fullName>
                </value>
                <value>
                    <fullName>Japan ID</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Child_Account</fullName>
        <active>true</active>
        <label>Child Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AfterInsert_CaseTest.cls
/*
@Created By :       Syed Jameel
@Created Date:      07 Nov 2012
@Description:       Test Class for AfterInsert_Case trigger
*/
/*********************************************************************************************
@Modified By :       Prakhar Gupta
@Modified Date :    15 Dec 2014
Description :       Trigger to set Auto Notification Rules to for Contact When Record types is 'TS_Community'
********************************************************************************************/
@isTest
private class AfterInsert_CaseTest 
{

    //commented the below line as part of SIR 518-Discable Tech Support record Type
    //final static String CASE_TECHSUPPORT = 'Tech_Support';
    final static String CASE_TSWEBMASTER = 'TS_Webmaster';
    final static String CASE_TSCOMMUNITY = 'TS_Community';
    
    private final static String CHILD_ACCOUNT = 'Child_Account';
    private final static String PARENT_ACCOUNT = 'Parent_Account';    
    
    private Static RecordType objAccountChild;
    private static RecordType objAccountParent;
    
     private static void fetchRecordType()
    {        
        for(RecordType rt : [Select Id, DeveloperName
                              From RecordType Where IsActive=true and  
                              ((SobjectType = 'Account' and (DeveloperName =: Child_Account or 
                                                             DeveloperName =: Parent_Account))                              
                              ) Limit 2])
         if(rt.DeveloperName == CHILD_ACCOUNT)
        {
            objAccountChild = rt; 
        }
        else if(rt.DeveloperName == PARENT_ACCOUNT)
        {
            objAccountParent = rt;
        }   
        
    } 
    
    static testMethod void AfterInsert_CaseTest1() 
    {
        //prepare test data
        
        fetchRecordType();
        
        Account objNXPAccount = new Account(RecordTypeID= objAccountParent.ID,
                                                Name = 'NXP Community', Customer_Category__c= 'Longtail');
        insert objNXPAccount;
        System.assert(objNXPAccount.Id != null);
        
        Account objOtherAccount = new Account(RecordTypeID= objAccountParent.ID,
                                                Name = 'Other', Customer_Category__c= 'Longtail');
        insert objOtherAccount;
        System.assert(objOtherAccount.Id != null);
        
        Account objTechServicesAccount = new Account(RecordTypeID= objAccountChild.ID,ParentId = objOtherAccount.Id,  
                                            Name = 'Technical Services', Region__c = 'Japan',
                                             Sales_Area__c = 'Japan ID', Industry_Segment__c = 'Mobile',
                                             Country__c = 'Austria');
        insert objTechServicesAccount;
        System.assert(objTechServicesAccount.Id != null);
             
        Account objAccount = new Account(Name = 'unittest_account');
        insert objAccount;
        system.assert(objAccount.Id != null);
        
        Contact objContact = new Contact(LastName = 'test', AccountId = objAccount.Id , Email = 'test.contact@test.com');
        insert objContact;
        system.assert(objContact.Id != null); 
        
        //get the record type
        List<RecordType> lstRecordTypes = [Select Id, DeveloperName 
                                           From RecordType
                                           Where SobjectType = 'Case' and ( DeveloperName =: CASE_TSWEBMASTER  or DeveloperName =: CASE_TSCOMMUNITY) 
                                           and IsActive=true
                                           Limit 2];
        
        system.debug('lstRecordTypes>>'+lstRecordTypes);
        
        List<Case> lstCases = new List<Case>();
                                       
        //start the test        
        Test.startTest();        
        if(lstRecordTypes.size() > 0)
        {
            //lstCases.add(new Case(Subject='test 1', RecordTypeId = lstRecordTypes[0].Id , ContactId = objContact.Id));
            lstCases.add(new Case(Subject='test 2', RecordTypeId = lstRecordTypes[0].Id , ContactId = objContact.Id)); 
            lstCases.add(new Case(Subject='test 3', RecordTypeId = lstRecordTypes[1].Id , ContactId = objContact.Id)); 
        }       
        insert lstCases;
        
        //stop the test
        Test.stopTest();
    }
}