src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Consolidated_Account_Code__c</fullName>
        <formula>CASE(
     RecordType.Name,
    &apos;Parent Account&apos;, NXP_Global_ID__r.Consolidated_Account_Code__c , 
    &apos;Child Account&apos;, NXP_Global_ID__r.Consolidated_Account_Code__c ,
    &apos;&apos;
)</formula>
        <inlineHelpText>Consolidated Account Code (CACC) attach to the parent account</inlineHelpText>
        <label>Consolidated Account Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consolidated_Account_Code__c.object
<CustomObject>
    <description>Master object to store Consolidated Account codes</description>
    <fields>
        <fullName>Code_Description__c</fullName>
        <label>Code Description</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consolidated Account Code</label>
    <nameField>
        <label>Consolidated Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consolidated Account Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/eRebate__c.object
<CustomObject>
    <description>Rebate</description>
    <fields>
        <fullName>Consolidated_Account_Code_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New Lookup field to replace lookup relation to CACC codes object. Implemented as part of CACC code analysis Line Item# 8 Date: 20-May-2015 By: Balaji G</description>
        <inlineHelpText>Pls select Consolidate Account Code if rebate is per Consoliate Code level</inlineHelpText>
        <label>Consolidated Account Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose active consolidated account code.</errorMessage>
            <filterItems>
                <field>Consolidated_Account_Code__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Consolidated_Account_Code__c</referenceTo>
        <relationshipLabel>Rebate</relationshipLabel>
        <relationshipName>RebateToConsolidatedAccountCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <inlineHelpText>If there is no specific End Customer, please type &quot;N/A&quot;. For Distribution ODM Fullfillment Rebate, please type &quot;Multiple EC&quot; if more than one End Customer.</inlineHelpText>
        <label>End Customer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate_Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rebate Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Rebate</relationshipLabel>
        <relationshipName>Rebate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_Effective_Date__c</fullName>
        <label>Rebate Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rebate_End_Date__c</fullName>
        <label>Rebate End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rebate_Program_Name__c</fullName>
        <description>Rebate program name</description>
        <label>Rebate Program Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rebate</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Rebate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/eRebate_Product__c.object
<CustomObject>
    <description>It will store eRebate Products(Line Items).</description>
    <fields>
        <fullName>End_Customer__c</fullName>
        <description>1508 Release. Request by Pauline Ng. It&apos;s used for capturing more Rebate information.</description>
        <label>End Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>Product__r.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eRebate__c</fullName>
        <label>eRebate</label>
        <referenceTo>eRebate__c</referenceTo>
        <relationshipName>eRebate_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rebate Product</label>
    <nameField>
        <displayFormat>eRP-{0000}</displayFormat>
        <label>eRebate Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Item__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sales Item</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/AddERebateProductControllerTest.cls
/*
@Created By :       Nisha Agrawal
@Created Date:      02 Jan 2013
@Description:       Test Class for Controller class AddERebateProductController
*/

/*
@Modified By :       Balaji Gunasekaran
@Modified Date:      20 May 2015
@Description:       As Part of CACC code impact analysis LineItem#21 
                    - Replaced CACC code object with Consolidated Account Code object and replaced field Consolidate_Code_Description__c with Consolidated_Account_Code_Description__c
*/

/*
@Created By :       Nisha Agrawal
@Created Date:      02 Jan 2013
@Description:       Test Class for Controller class AddERebateProductController
*/

/*
@Modified By :       Balaji Gunasekaran
@Modified Date:      20 May 2015
@Description:       As Part of CACC code impact analysis LineItem#21 
                    - Replaced CACC code object with Consolidated Account Code object and replaced field Consolidate_Code_Description__c with Consolidated_Account_Code_Description__c
*/

/*
@Modified By :       Scarlett Kang
@Modified Date:      16 Nov 2015
@Description:       Modified for changing Sales item, Sales Item must be unique
*/

@isTest(SeeAllData=true)
private class AddERebateProductControllerTest 
{

    static testMethod void AddERebateProductControllerTest1() 
    {
        //prepare test data
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
                
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD',  Consolidated_Account_Code_Description__c = objCACC.Id);
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfProducts = 100;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfProducts ;  i++)
        {
            objProduct = new Product2(Name = 'ut_product' + i , ProductCode = 'ut_code' + i, MAG__c = 'ut_mag' + i, isActive = true);
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products       
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
        
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        
        //start the Test
        Test.startTest();
        
        PageReference pgRef = Page.AddERebateProduct;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        AddERebateProductController extension = new AddERebateProductController(controller);
        
        system.assert(extension.objERebate.Id == objeRebate.Id);
        system.assert(extension.lstResults != null);
        system.assert(extension.lstResults.size() > 0);
        system.assert(extension.total_size >= numOfProducts); //due to See All Data true        
        system.assert(!extension.isStep2);
        
        //stop the Test
        Test.stopTest();
    }
    
    /*************************************************************************
                    CASE - SEARCH PRODUCTS - Filter without Price
    **************************************************************************/
    
    static testmethod void AddERebateProductControllerTest2() 
    {
        //prepare test data
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
                
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD',  Consolidated_Account_Code_Description__c = objCACC.Id);
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfProducts = 50;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfProducts ;  i++)
        {
            /***Modified by Scarlett on Nov 16***/
            objProduct = new Product2(Name = 'ut_product' + i , ProductCode = 'ut_code' + i, MAG__c = 'ut_mag' + i, Sales_Item__c = 'ut_SI' + i , isActive = true);
			/***Modified by Scarlett on Nov 16 - END***/
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products       
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
        
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        
        //start the Test
        Test.startTest();
        
        PageReference pgRef = Page.AddERebateProduct;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        AddERebateProductController extension = new AddERebateProductController(controller);
                        
        //invoke searchProducts
        extension.searchProducts();
        
        List<AddERebateProductController.SearchResult> lstActualResult = extension.lstResults;
        
        System.assert(Apexpages.hasMessages(ApexPages.severity.Error));
        List<Apexpages.Message> lstMessages = ApexPages.getMessages();
        System.assert(lstMessages[0].getSummary() == AddERebateProductController.NO_SEARCH_CRITERIA_ERROR);
        
        //Set some filter 
        extension.ProductName = 'ut';
        extension.ProductCode = 'ut';
        extension.SalesItem = 'ut';
        extension.MAG = 'ut';
        
        //invoke searchProducts
        extension.searchProducts();
        
        lstActualResult = extension.lstResults;
        system.assert(extension.foundResult);
        
        //invoke clearResults method
        extension.clearResults();
        system.assert(extension.ProductName == '');
        system.assert(extension.ProductCode == '');
        system.assert(extension.SalesItem == '');
        system.assert(extension.MAG == '');
        system.assert(extension.filterId == '0');
               
        //stop the Test
        Test.stopTest();
    }
    
    /*************************************************************************
                    CASE - SEARCH PRODUCTS - Unit Price Filter
    **************************************************************************/
    static testmethod void AddERebateProductControllerTest3() 
    {
        //prepare test data
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
               
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD' ,  Consolidated_Account_Code_Description__c = objCACC.Id);
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfProducts = 50;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfProducts ;  i++)
        {
            objProduct = new Product2(Name = 'ut_product' + i , ProductCode = 'ut_code' + i, MAG__c = 'ut_mag' + i, isActive = true);
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products       
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
        
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        
        //start the Test
        Test.startTest();
        
        PageReference pgRef = Page.AddERebateProduct;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        AddERebateProductController extension = new AddERebateProductController(controller);
        
        //Set Price Filter
        extension.filterId = '1';
        extension.filterPrice = '5';
        
        //invoke searchProducts
        extension.searchProducts();
        
        List<AddERebateProductController.SearchResult> lstActualResult = extension.lstResults;
        
        extension.filterId = '2';
        extension.searchProducts();
        
        extension.filterId = '3';
        extension.filterPrice = '0';
        extension.searchProducts();
        
        extension.filterId = '4';
        extension.filterPrice = '5';
        extension.searchProducts();
              
        extension.filterId = '5';
        extension.filterPrice = '-1';
        extension.searchProducts();
        
        extension.filterId = '6';
        extension.filterPrice = '5';
        extension.searchProducts();
           
        //stop the Test
        Test.stopTest();
    }
    
    /*************************************************************************
                    CASE - SEARCH PRODUCTS - SAVE LINE ITEMS
    **************************************************************************/
    
    static testmethod void AddERebateProductControllerTest4() 
    {
        //prepare test data
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
                
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD',  Consolidated_Account_Code_Description__c = objCACC.Id);
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfProducts = 50;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfProducts ;  i++)
        {
            /***Modified by Scarlett on Nov 16***/
            objProduct = new Product2(Name = 'ut_product' + i , ProductCode = 'ut_code' + i, MAG__c = 'ut_mag' + i, Sales_Item__c = 'ut_SI' + i, isActive = true);
            /***Modified by Scarlett on Nov 16 - END***/
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products       
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
        
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        
        //start the Test
        Test.startTest();
        
        PageReference pgRef = Page.AddERebateProduct;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        AddERebateProductController extension = new AddERebateProductController(controller);
                        
        //Set some filter 
        extension.ProductName = 'ut';
        extension.ProductCode = 'ut';
        extension.SalesItem = 'ut';
        extension.MAG = 'ut';
        
        //invoke searchProducts
        extension.searchProducts();
        
        List<AddERebateProductController.SearchResult> lstActualResult = extension.lstResults;
        system.assert(extension.foundResult);
                
        //invoke processSelectedProducts
        extension.processSelectedProducts();
        System.assert(Apexpages.hasMessages(ApexPages.severity.Error));
        List<Apexpages.Message> lstMessages = ApexPages.getMessages();
        system.assert(lstMessages[0].getSummary() == AddERebateProductController.SELECT_PRODUCT_TO_ADD_ERROR);
         
        //select some products
        for(i=0; i < lstActualResult.size(); i=i+5)
        {
            lstActualResult[i].IsSelected = true;
        }
        
        //invoke processSelectedProducts
        extension.processSelectedProducts();
        
        system.assert(extension.isStep2);
        system.assert(extension.lsteRebateLines != null);
        system.assert(extension.lsteRebateLines.size() > 0);
        
        //invoke saveProducts method
        PageReference resultPage = extension.saveProducts();
        system.assert(resultPage != null);
        system.assert(resultPage.getUrl().contains(objeRebate.Id));
        
        //stop the Test
        Test.stopTest();
    }
    
    /*************************************************************************
                    CASE - SEARCH PRODUCTS - SAVE MORE PRODUCTS
    **************************************************************************/
    
    static testmethod void AddERebateProductControllerTest5() 
    {
        //prepare test data
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
                
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD',  Consolidated_Account_Code_Description__c = objCACC.Id);
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfProducts = 30;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfProducts ;  i++)
        {
            /***Modified by Scarlett on Nov 16***/
            objProduct = new Product2(Name = 'ut_product' + i , ProductCode = 'ut_code' + i, MAG__c = 'ut_mag' + i, Sales_Item__c = 'ut_SI' + i, isActive = true);
            /***Modified by Scarlett on Nov 16 - END***/
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products       
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
        
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        
        //start the Test
        Test.startTest();
        
        PageReference pgRef = Page.AddERebateProduct;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        AddERebateProductController extension = new AddERebateProductController(controller);
                        
        //Set some filter 
        extension.ProductName = 'ut';
        extension.ProductCode = 'ut';
        extension.SalesItem = 'ut';
        extension.MAG = 'ut';
        
        //invoke searchProducts
        extension.searchProducts();
        
        List<AddERebateProductController.SearchResult> lstActualResult = extension.lstResults;
		system.assert(extension.foundResult);
                
        //select some products
        for(i=0; i < lstActualResult.size(); i=i+5)
        {
            lstActualResult[i].IsSelected = true;
        }
        
        //invoke processSelectedProducts
        extension.processSelectedProducts();
        
        system.assert(extension.isStep2);
        system.assert(extension.lsteRebateLines != null);
        system.assert(extension.lsteRebateLines.size() > 0);
        
        //invoke saveProducts method
        extension.saveMoreProducts();
        system.assert(!extension.isStep2);
        system.assert(extension.lsteRebateLines == null);
        
        //stop the Test
        Test.stopTest();
    }
    
    /*************************************************************************
                    CASE - PAGER & ALPHABETICAL FILTERS
    **************************************************************************/
    
    static testmethod void AddERebateProductControllerTest6() 
    {
        //prepare test data        
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
               
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD' ,  Consolidated_Account_Code_Description__c = objCACC.Id);
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfProducts = 100;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfProducts ;  i++)
        {
            objProduct = new Product2(Name = 'ut_product' + i , ProductCode = 'ut_code' + i, MAG__c = 'ut_mag' + i, isActive = true);
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products       
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
        
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        
        //start the Test
        Test.startTest();
        
        PageReference pgRef = Page.AddERebateProduct;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        AddERebateProductController extension = new AddERebateProductController(controller);
        
        List<AddERebateProductController.SearchResult> lstActualResult = extension.lstResults;
        
        system.assert(extension.objERebate.Id == objeRebate.Id);
        system.assert(lstActualResult != null);
        system.assert(lstActualResult.size() > 0);
        system.assert(extension.foundResult);
        
        Boolean disablePrevious = extension.getDisablePrevious();
        system.assert(disablePrevious == true);
        
        Boolean disableNext = extension.getDisableNext();
        system.assert(disableNext == false);
        
        integer pageNo = extension.getPageNumber();
        system.assert(pageNo == 1);
        
        integer totalSize = extension.getTotal_size();
        system.assert(extension.total_size >= numOfProducts); //due to See All Data true
        
        integer totalPages = extension.getTotalPages();
         
        Boolean disableLast = extension.getDisableLast();
        system.assert(disableLast == (totalPages * 10 > 2000 ? true : false));
        
        extension.next();
        
        disablePrevious = extension.getDisablePrevious();
        system.assert(disablePrevious == false);
        
        //select some products
        for(i=0; i < lstActualResult.size(); i=i+5)
        {
            lstActualResult[i].IsSelected = true;
        }
        
        extension.first();
        
        if(!disableLast)
        {
            extension.last();
            disableNext = extension.getDisableNext();
            system.assert(disableNext == true);
        }
        
        for(i=0; i < lstActualResult.size(); i = i+10)
        {
            lstActualResult[i].IsSelected = false;
        }
            
        extension.alphaFilter = 't';
        extension.filterByAlphabets();
                
        extension.alphaFilter = 'u';
        extension.filterByAlphabets();
        
        totalPages = extension.getTotalPages();
        
        if(extension.lstResults.size() > 0)
        {
            disableLast = extension.getDisableLast();
            system.assert(disableLast == (totalPages * 10 > 2000 ? true : false));
            
            if(!disableLast)
            {
                extension.last();
                disableNext = extension.getDisableNext();
                system.assert(disableNext == true);
                
                extension.previous();
            }   
        }   
        //stop the Test
        Test.stopTest();    
    }    
}