src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Key Account Manager for DW to Revenue Tracking</description>
        <label>(NOT USED) Account Manager Global</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Manager_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Manager_prechild__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <description>Dun and Bradstreet Number</description>
        <inlineHelpText>DUNS # from Hoovers D&amp;B database</inlineHelpText>
        <label>DUNS</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS_Ultimate__c</fullName>
        <description>Duns and Bradstreet Global Ultimate Name</description>
        <label>DUNS Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Account_Name__c</fullName>
        <label>D&amp;B Account Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Annual_Revenue__c</fullName>
        <label>D&amp;B Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>D_B_City__c</fullName>
        <label>D&amp;B City</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Country__c</fullName>
        <label>D&amp;B Country</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Employees__c</fullName>
        <label>D&amp;B Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>D_B_Global_Ultimate_Company_Name__c</fullName>
        <label>D&amp;B Global Ultimate Company Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_NAICS_Code__c</fullName>
        <label>D&amp;B NAICS Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Number__c</fullName>
        <label>D&amp;B Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_SIC_Code_Description__c</fullName>
        <label>D&amp;B SIC Code Description</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_SIC_Code__c</fullName>
        <label>D&amp;B SIC Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_State_Province__c</fullName>
        <label>D&amp;B State/Province</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_Street__c</fullName>
        <label>D&amp;B Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_B_ZIP_Postal_Code__c</fullName>
        <label>D&amp;B ZIP/Postal Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAICS__c</fullName>
        <description>North American Industry Classification</description>
        <label>NAICS Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <inlineHelpText>Customer address - state/province</inlineHelpText>
        <label>State/ Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aceh</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Andaman And Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>An Giang</fullName>
                </value>
                <value>
                    <fullName>Anhui Province</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bac Giang</fullName>
                </value>
                <value>
                    <fullName>Bac Kan</fullName>
                </value>
                <value>
                    <fullName>Bac Lieu</fullName>
                </value>
                <value>
                    <fullName>Bac Ninh</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California S</fullName>
                </value>
                <value>
                    <fullName>Bali</fullName>
                </value>
                <value>
                    <fullName>Banten</fullName>
                </value>
                <value>
                    <fullName>Ba Ria Vung Tau</fullName>
                </value>
                <value>
                    <fullName>Beijing City</fullName>
                </value>
                <value>
                    <fullName>Bengkulu</fullName>
                </value>
                <value>
                    <fullName>Ben Tre</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Binh Dinh</fullName>
                </value>
                <value>
                    <fullName>Binh Duong</fullName>
                </value>
                <value>
                    <fullName>Binh Phuoc</fullName>
                </value>
                <value>
                    <fullName>Binh Thuan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_of_D_B_Cleansing__c</fullName>
        <label>DNB Verified</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DNB Accepted</fullName>
                </value>
                <value>
                    <fullName>DNB Rejected: Poor Match</fullName>
                    <color>#FFCC33</color>
                    <label>DNB Rejected: Poor Match</label>
                </value>
                <value>
                    <fullName>DNB Rejected: Not Found</fullName>
                    <color>#FF0000</color>
                    <label>DNB Rejected: Not Found</label>
                </value>
                <value>
                    <fullName>DNB Rejected: Address Retained</fullName>
                </value>
                <value>
                    <fullName>D&amp;B Excluded: Technical Services</fullName>
                    <color>#641CCF</color>
                    <label>D&amp;B Excluded: Technical Services</label>
                </value>
                <value>
                    <fullName>D&amp;B Excluded: AOP</fullName>
                    <color>#33CCFF</color>
                    <label>D&amp;B Excluded: AOP</label>
                </value>
                <value>
                    <fullName>D&amp;B Excluded: Other Exceptions</fullName>
                    <color>#0B6FCE</color>
                    <label>D&amp;B Excluded: Other Exceptions</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <inlineHelpText>Customer address - postal code</inlineHelpText>
        <label>ZIP / Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Child_Account</fullName>
        <active>true</active>
        <label>Child Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pre_Account</fullName>
        <active>true</active>
        <description>This Pre-account is used for account manager to create child account and submit for approval</description>
        <label>Pre-Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BeforeTrigger_AccountTest.cls
/***********************************************************************************************************
@Created By :       Nisha Agrawal
@Created Date:      10 Apr 2013
@Description:       Test Class for Trigger BeforeTrigger_Account
*************************************************************************************************************/

@isTest
private class BeforeTrigger_AccountTest 
{

	/**********************************************************************
    //Case - Child Account D&B Data update
    ***********************************************************************/
   
    static testmethod void BeforeTrigger_AccountTest1()
    {
        //get the record type
        List<RecordType> lstRecordTypes = [Select Id, DeveloperName, SobjectType  
											From RecordType
                                           	Where SobjectType = 'Account' and DeveloperName = 'Child_Account' and IsActive=true
                                           	Limit 1];
        RecordType childAccount;
        if(lstRecordTypes.size() > 0)
        {
            childAccount = lstRecordTypes[0];
        }
        
        //start the Test       
        Test.startTest();
        //prepare test data
        Account objAccount = new Account(Name='Unit Test Account', RecordTypeId = childAccount.Id , Status_of_D_B_Cleansing__c = 'D&B Data Accepted' , D_B_Account_Name__c = 'DB Name' , 
        									D_B_Street__c = 'DB Street' , D_B_State_Province__c = 'DB State' , D_B_City__c = 'DB City' , D_B_Country__c = 'DB Country' , 
        									D_B_ZIP_Postal_Code__c = 'DB Zip' , D_B_SIC_Code__c = 'DB Sic' , D_B_SIC_Code_Description__c = 'DB Sic Desc' );
        insert objAccount;
       
        //assert the results
        System.assert(objAccount.Id != null);
       
        //fetch the account details 
        objAccount = [Select Id , Name, Street__c , City__c  , ZIP_Postal_Code__c , Country__c , State_Province__c , Sic, SicDesc ,
                        NAICS__c, AnnualRevenue , NumberOfEmployees ,DUNS_Ultimate__c, DUNS_Number__c, D_B_Account_Name__c , D_B_Street__c , 
                        D_B_City__c , D_B_ZIP_Postal_Code__c , D_B_Country__c , D_B_State_Province__c, D_B_SIC_Code__c , D_B_SIC_Code_Description__c,
                        D_B_NAICS_Code__c , D_B_Annual_Revenue__c , D_B_Employees__c , D_B_Global_Ultimate_Company_Name__c , D_B_Number__c
                     From Account
                     Where Id= :objAccount.Id Limit 1  ];
                 
        System.assert(objAccount.Name == objAccount.D_B_Account_Name__c);                   
        System.assert(objAccount.Street__c == objAccount.D_B_Street__c);
        System.assert(objAccount.City__c == objAccount.D_B_City__c);
        System.assert(objAccount.ZIP_Postal_Code__c == objAccount.D_B_ZIP_Postal_Code__c);
        System.assert(objAccount.Country__c == objAccount.D_B_Country__c);
        System.assert(objAccount.State_Province__c == objAccount.D_B_State_Province__c);
        System.assert(objAccount.Sic == objAccount.D_B_SIC_Code__c);
        System.assert(objAccount.SicDesc == objAccount.D_B_SIC_Code_Description__c);
        System.assert(objAccount.NAICS__c == objAccount.D_B_NAICS_Code__c);
        System.assert(objAccount.DUNS_Ultimate__c == objAccount.D_B_Global_Ultimate_Company_Name__c);
        System.assert(objAccount.DUNS_Number__c == objAccount.D_B_Number__c);
        
       //Stop the Test
       Test.stopTest();
    }
    
    /**********************************************************************
    //Case - Single Record - Pre Account Type Record
    ***********************************************************************/
    
    static testmethod void BeforeTrigger_AccountTest2()
    {
    	List<Profile> lstProfiles =[Select Id, Name From Profile Where Name = 'Standard User' Limit 1 ];
    	
    	if(lstProfiles.size() > 0)
        {
        	//prepare test data
        	Profile objProfile = lstProfiles[0];
            
            //insert User
            User objUser = TestUtil.createTestUser('ut.abc@test.com', 'utuser', objProfile.Id);
            insert objUser;
            system.assert(objUser.Id != null);
            
			String PARENT_ACCOUNT = 'Parent_Account';
			String PRE_ACCOUNT = 'Pre_Account'; 
			
			RecordType parentAccount;
			RecordType preChildAccount;
			
			for(RecordType rt : [Select Id, DeveloperName
                           From RecordType
                           Where SobjectType = 'Account' and ( DeveloperName =: PARENT_ACCOUNT or DeveloperName =: PRE_ACCOUNT ) and IsActive=true
                           Limit 2])
			{
				if(rt.DeveloperName == PARENT_ACCOUNT)
		   		{
		   			parentAccount = rt;
		   		}
		   		else if(rt.DeveloperName == PRE_ACCOUNT)
		   		{
		   			preChildAccount = rt;
		   		}
			}
			
            //insert Parent Account
            Account objParent = new Account(Name = 'ut_parent', Account_Manager__c = objUser.Id, RecordTypeId = parentAccount.Id);
            insert objParent;
            system.assert(objParent.Id != null);
            
            //start the Test       
	        Test.startTest();
	        
	        Account objPreAccount = new Account(Name='Unit Test Account', RecordTypeId = preChildAccount.Id, ParentId = objParent.Id);
	        insert objPreAccount;
	        
	        //assert the results
	        System.assert(objPreAccount.Id != null);
	       
	        //fetch the account details
	        objPreAccount = [Select Id , Name, Parent.Account_Manager__c , Account_Manager_prechild__c
	                     	From Account
	                     	Where Id= :objPreAccount.Id 
	                     	Limit 1 ];
	                           
	        System.assert(objPreAccount.Account_Manager_prechild__c != null);
	        System.assert(objPreAccount.Parent.Account_Manager__c != null);
	        System.assert(objPreAccount.Account_Manager_prechild__c == objPreAccount.Parent.Account_Manager__c);
	        System.assert(objPreAccount.Account_Manager_prechild__c == objUser.Id);
	       
	       //Stop the Test
	       Test.stopTest();            
        } 
    }
}