src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/STAR_Access__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityAccessLevel__c</fullName>
        <description>Read-Only or Read/Write</description>
        <label>Opportunity Access Level</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity this User has access to</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>STAR Access</relationshipLabel>
        <relationshipName>STAR_Access</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RowCause__c</fullName>
        <description>How this User is getting sharing of this STAR Opportunity</description>
        <label>Sharing Reason</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User who has access to the Opportunity</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>STAR_Access</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>STAR Access</label>
    <nameField>
        <label>OpportunityId + UserId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>STAR Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MassDeleteStarAccessDataBatchTest.cls
/**********************************************************************************
@Created By :       Nisha Agrawal
@Created Date:      04 Sep 2017
@Description:       Test Class for the class MassDeleteStarAccessDataBatch
**********************************************************************************/
@isTest
private class MassDeleteStarAccessDataBatchTest 
{
    static testMethod void MassDeleteStarAccessDataBatchTest1()
    {
        //prepare test data
        
        Id parentAccountRecordTypeId = AccountHelper.getParentRecordTypeID();
        Id childAccountRecordTypeId = AccountHelper.getChildRecordTypeID();
        
        //create parent account
        Account parentAccount =  new Account(Name = 'STAR', RecordTypeId = parentAccountRecordTypeId, Region__c = 'Americas'); 
        insert parentAccount;
        system.assert(parentAccount.Id != null);
        
        //create child account
        Account childAccount =  new Account(Name = 'STAR', ParentId = parentAccount.Id,  RecordTypeId = childAccountRecordTypeId); 
        insert childAccount;
        system.assert(childAccount.Id != null);
        
        //create opportunities
        
        List<Opportunity> lstOpportunities = new List<Opportunity>();
        Date closeDate = Date.valueOf('2020-06-22');
        for(integer i =0; i < 200; i++)
        {
            Opportunity objOpp = new Opportunity(Name = 'test Opp' + i , AccountId = childAccount.Id, StageName = 'Initial Analysis', CloseDate = closeDate );
            lstOpportunities.add(objOpp );
        }
        
        insert lstOpportunities;
        for(Opportunity obj : lstOpportunities)
        {
            system.assert(obj.Id != null);
        }
        
        
        //create StarAccessScanner records
        List<Star_Access__c> lstStarAccess = new List<Star_Access__c>();
        String strKey;
        Date createdDate = date.today().addDays(-8);
        
        for( OpportunityShare objShare : [SELECT  OpportunityId,UserOrGroupId, OpportunityAccessLevel, RowCause FROM OpportunityShare])
        {
            if( String.valueOf(objShare.UserOrGroupId).left(3) == '005' )
            {
                strKey = String.valueOf(objShare.OpportunityId) + String.valueOf(objShare.UserOrGroupId);
                
                lstStarAccess.add(new STAR_Access__c (Name = strKey, OpportunityId__c = objShare.OpportunityId,
                        UserId__c = objShare.UserOrGroupId,OpportunityAccessLevel__c = objShare.OpportunityAccessLevel,
                        RowCause__c = objShare.RowCause , createdDate = createdDate ));
            }
       }
        
        insert lstStarAccess;
        
        for(Star_Access__c obj : lstStarAccess)
        {
            system.assert(obj.Id != null);
        }
        
        //start the test
        Test.startTest();
        Database.executeBatch(new MassDeleteStarAccessDataBatch(), 2000);
        Test.stopTest();
        
    //assert the results
    List<Star_Access__c> lstResults = [Select Id , Name From Star_Access__c];
        system.assert(lstResults.size() ==0);
  }
}