src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Consolidated_Account_Code__c</fullName>
        <formula>CASE(
     RecordType.Name,
    &apos;Parent Account&apos;, NXP_Global_ID__r.Consolidated_Account_Code__c , 
    &apos;Child Account&apos;, NXP_Global_ID__r.Consolidated_Account_Code__c ,
    &apos;&apos;
)</formula>
        <inlineHelpText>Consolidated Account Code (CACC) attach to the parent account</inlineHelpText>
        <label>Consolidated Account Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consolidated_Account_Code__c.object
<CustomObject>
    <description>Master object to store Consolidated Account codes</description>
    <fields>
        <fullName>Code_Description__c</fullName>
        <label>Code Description</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consolidated Account Code</label>
    <nameField>
        <label>Consolidated Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consolidated Account Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/eRebate__c.object
<CustomObject>
    <description>Rebate</description>
    <fields>
        <fullName>Consolidated_Account_Code_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New Lookup field to replace lookup relation to CACC codes object. Implemented as part of CACC code analysis Line Item# 8 Date: 20-May-2015 By: Balaji G</description>
        <inlineHelpText>Pls select Consolidate Account Code if rebate is per Consoliate Code level</inlineHelpText>
        <label>Consolidated Account Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose active consolidated account code.</errorMessage>
            <filterItems>
                <field>Consolidated_Account_Code__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Consolidated_Account_Code__c</referenceTo>
        <relationshipLabel>Rebate</relationshipLabel>
        <relationshipName>RebateToConsolidatedAccountCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <inlineHelpText>If there is no specific End Customer, please type &quot;N/A&quot;. For Distribution ODM Fullfillment Rebate, please type &quot;Multiple EC&quot; if more than one End Customer.</inlineHelpText>
        <label>End Customer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate_Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rebate Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Rebate</relationshipLabel>
        <relationshipName>Rebate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_Effective_Date__c</fullName>
        <label>Rebate Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rebate_End_Date__c</fullName>
        <label>Rebate End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rebate_Program_Name__c</fullName>
        <description>Rebate program name</description>
        <label>Rebate Program Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rebate</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Rebate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/eRebate_Product__c.object
<CustomObject>
    <description>It will store eRebate Products(Line Items).</description>
    <fields>
        <fullName>End_Customer__c</fullName>
        <description>1508 Release. Request by Pauline Ng. It&apos;s used for capturing more Rebate information.</description>
        <label>End Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Description__c</fullName>
        <label>Line Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Gap__c</fullName>
        <label>Price Gap</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>eRebate_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>eRebate__c</fullName>
        <label>eRebate</label>
        <referenceTo>eRebate__c</referenceTo>
        <relationshipName>eRebate_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rebate Product</label>
    <nameField>
        <displayFormat>eRP-{0000}</displayFormat>
        <label>eRebate Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EditAllERebateProductsControllerTest.cls
/*
@Created By :       Nisha Agrawal
@Created Date:      03 Jan 2012
@Description:       Test Class for Controller class EditAllERebateProductsControllerTest
*/
/*
@Modified By :       Balaji Gunasekaran
@Modified Date:      21 May 2015
@Description:       As Part of CACC code impact analysis LineItem#25 
                    - Replaced CACC code object with Consolidated Account Code object and replaced field Consolidate_Code_Description__c with Consolidated_Account_Code_Description__c
*/
@isTest
private class EditAllERebateProductsControllerTest 
{
    @isTest(SeeAllData=true)
    static void EditAllERebateProductsControllerTest1() 
    {
        //prepare test data
        //fetch the Rebate Currency
        List<FX_Rates__c> lstRates = [Select Id , Name From FX_Rates__c Where Name = 'USD' Limit 1];
        FX_Rates__c rebateCurrency;
        
        if(lstRates.size() > 0)
        {
            rebateCurrency = lstRates[0];           
        }
        else
        {
            rebateCurrency = new FX_Rates__c(Name = 'USD' , Currency_Code__c = 'USD');
            insert rebateCurrency;
            
            system.assert(rebateCurrency.Id != null);
        }
        
        //insert Consolidated Account code
        Consolidated_Account_Code__c objCACC = new Consolidated_Account_Code__c();
        objCACC.Code_Description__c='123';
        insert objCACC;
        system.assert(objCACC.Id != null);
                
        eRebate__c objeRebate = new eRebate__c(Rebate_Program_Name__c = 'unittest_program' , End_Customer__c ='unittest_endcustomer', Rebate_End_Date__c = date.today().addDays(30) , Rebate_Effective_Date__c = date.today() , Sales_Region__c = 'EMEA' , Rebate_Currency__c = rebateCurrency.Id,  CurrencyIsoCode = 'USD', Consolidated_Account_Code_Description__c= objCACC.Id);
        
        insert objeRebate;
        system.assert(objeRebate.Id != null);
        
        integer numOfERebateLines = 10;
        integer i;
        
        //insert products
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct;
        
        for(i =0; i < numOfERebateLines ;  i++)
        {
            objProduct = new Product2(Name = 'unittest_product' + i);
            lstProducts.add(objProduct);
        }
        insert lstProducts;
        
        //assert products
        
        for(Product2 p : lstProducts)
        {
            system.assert(p.Id != null);
        }
                
        List<eRebate_Product__c> eRebateLines = new List<eRebate_Product__c>();
        eRebate_Product__c objRebateLine;
        
        for(i =0; i < numOfERebateLines ;  i++)
        {
            objRebateLine = new eRebate_Product__c( eRebate__c = objeRebate.Id , Price_Gap__c = (i * 10.0) , Quantity__c = 5, Product__c = lstProducts[i].Id);
            eRebateLines.add(objRebateLine);
        }
        
        insert eRebateLines;
        
        //assert eRebate products
        
        for(eRebate_Product__c rebateProduct : eRebateLines)
        {
            system.assert(rebateProduct.Id != null);
        }
        
        //start the test
        Test.startTest();
        
        PageReference pgRef = Page.EditAllERebateProducts;
        pgRef.getParameters().put('Id', objeRebate.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardSetController controller = new Apexpages.StandardSetController(eRebateLines);
        EditAllERebateProductsController extension = new EditAllERebateProductsController(controller);
        
        system.assert(extension.objERebate.Id == objeRebate.Id);
        system.assert(extension.lsteRebateLines.size() > 0);
        system.assert(extension.lsteRebateLines.size() == numOfERebateLines);
        
        for(eRebate_Product__c rebateProduct : extension.lsteRebateLines)
        {
            rebateProduct.Line_Description__c = 'test';
            rebateProduct.Quantity__c = 2;
            rebateProduct.Price_Gap__c = 200;
        }
        
        //invoke saveProducts method        
        
        PageReference pgRedirect = extension.saveProducts();
        
        //assert the results
        system.assert(pgRedirect != null);
        system.assert(pgRedirect.getUrl() == '/' + objeRebate.Id);
        
        eRebateLines = [Select Id , Product__c, Price_Gap__c, Line_Description__c , Quantity__c
                        From eRebate_Product__c
                        Where eRebate__c =: objERebate.Id];
        
        system.assert(eRebateLines.size() > 0);
        system.assert(eRebateLines.size() == numOfERebateLines);
                
        for(eRebate_Product__c rebateProduct : eRebateLines)
        {
            system.assert(rebateProduct.Line_Description__c == 'test');
            system.assert(rebateProduct.Quantity__c == 2);
            system.assert(rebateProduct.Price_Gap__c == 200);
        }
        
        //stop the test
        Test.stopTest();        
    }
}