src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMD_Industry_Segment__c</fullName>
        <description>Customer Buying Group</description>
        <inlineHelpText>Customer Buying Group</inlineHelpText>
        <label>CBG</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim_Value_USD_SYS__c</fullName>
        <description>This field is updated by Process Builder to capture the historical trending of Opportunity.Claim_Value_USD__c.</description>
        <label>Oppty Claim Value (USD) - Audit Trail</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Claim_Value__c</fullName>
        <description>Opportunity claim value in opportunity currency.</description>
        <inlineHelpText>Summary of all products&apos; [Prod Claim Value] in opportunity currency. 
Lost/Cancelled products are excluded from this calculation.</inlineHelpText>
        <label>Oppty Claim Value</label>
        <summarizedField>OpportunityLineItem.Claim_Value__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Process__c</fullName>
        <label>Design Win Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discovery_Date__c</fullName>
        <inlineHelpText>The date when Opportunity Stage changes to Discovery.</inlineHelpText>
        <label>Discovery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LT_Value_USD__c</fullName>
        <description>Opportunity lifetime value in USD.</description>
        <formula>IF (Locked_Exchange_Rate__c &lt;&gt; 0, LT_Value__c / ROUND(Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summary of all products&apos; [Prod LT Value] converted to USD.</inlineHelpText>
        <label>Oppty LT Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Locked_Exchange_Rate__c</fullName>
        <inlineHelpText>The Exchange Rate against USD which is locked when opportunity is Approved</inlineHelpText>
        <label>Locked Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Program</label>
        <referenceTo>OpportunityProgram__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>War_Room_Completed__c</fullName>
        <label>War Room Completed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Claim_Value_MAG_Setting__mdt.object
<CustomObject>
    <description>Store claim value year at the MAG level</description>
    <fields>
        <fullName>Claim_Value_Quarters__c</fullName>
        <label>Claim Value Quarters</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lifetime</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                    <default>true</default>
                    <label>12</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q69</fullName>
                </value>
                <value>
                    <fullName>R01</fullName>
                    <default>true</default>
                    <label>R01</label>
                </value>
                <value>
                    <fullName>R05</fullName>
                </value>
                <value>
                    <fullName>R06</fullName>
                </value>
                <value>
                    <fullName>R07</fullName>
                </value>
                <value>
                    <fullName>R08</fullName>
                </value>
                <value>
                    <fullName>R09</fullName>
                </value>
                <value>
                    <fullName>R10</fullName>
                </value>
                <value>
                    <fullName>R12</fullName>
                </value>
                <value>
                    <fullName>R13</fullName>
                </value>
                <value>
                    <fullName>R14</fullName>
                </value>
                <value>
                    <fullName>R16</fullName>
                </value>
                <value>
                    <fullName>R21</fullName>
                </value>
                <value>
                    <fullName>R22</fullName>
                </value>
                <value>
                    <fullName>R23</fullName>
                </value>
                <value>
                    <fullName>R24</fullName>
                </value>
                <value>
                    <fullName>R25</fullName>
                </value>
                <value>
                    <fullName>R26</fullName>
                </value>
                <value>
                    <fullName>R27</fullName>
                </value>
                <value>
                    <fullName>R28</fullName>
                </value>
                <value>
                    <fullName>R29</fullName>
                </value>
                <value>
                    <fullName>R30</fullName>
                </value>
                <value>
                    <fullName>R31</fullName>
                </value>
                <value>
                    <fullName>R32</fullName>
                </value>
                <value>
                    <fullName>R33</fullName>
                </value>
                <value>
                    <fullName>R34</fullName>
                </value>
                <value>
                    <fullName>R35</fullName>
                </value>
                <value>
                    <fullName>R36</fullName>
                </value>
                <value>
                    <fullName>R37</fullName>
                </value>
                <value>
                    <fullName>R38</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Claim Value MAG Setting</label>
    <pluralLabel>Opportunity Claim Value MAG Settings</pluralLabel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <formula>PricebookEntry.Product2.BL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim_Value__c</fullName>
        <description>Opportunity product claim value in opportunity currency.</description>
        <inlineHelpText>Opportunity product claim value in opportunity currency.</inlineHelpText>
        <label>Prod Claim Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LT_Value_USD__c</fullName>
        <description>Opportunity product lifetime value in USD.</description>
        <formula>IF (Opportunity.Locked_Exchange_Rate__c &lt;&gt; 0, LT_Value__c / ROUND(Opportunity.Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity product lifetime value in USD.</inlineHelpText>
        <label>Prod LT Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Program</label>
        <referenceTo>OpportunityProgram__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OpportunitySchedule__c.object
<CustomObject>
    <description>Opportunity Schedule</description>
    <fields>
        <fullName>Frozen_Oppty_Sched_Qty__c</fullName>
        <label>Frozen Oppty Sched Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Schedules</relationshipLabel>
        <relationshipName>Opportunity_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Oppty_Sched_Qty__c</fullName>
        <label>Oppty Sched Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sched_Date__c</fullName>
        <label>Sched Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Opportunity Schedule</label>
    <nameField>
        <displayFormat>OS-{0000}</displayFormat>
        <label>Opportunity Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OpportunitiesTest.cls
@isTest
private class OpportunitiesTest {
	
	private static final String TEST_USER_PROFILE = 'Standard User';
	private static final String TEST_USER = 't_user_1';
	private static final String MAG_SHORT_LIVED;
    private static final String MAG_LIFETIME;
    private static final String BL1 = 'BL01';
    private static final String BL2 = 'BLM1';
	private static final String CCY_CODE_USD = 'USD';
    private static final String CCY_CODE_EUR = 'EUR';
    private static final String CCY_CODE_DEFAULT = CCY_CODE_USD; // @default
    private static final Double EXCH_RATE_USD = 2.0;
    private static final Double EXCH_RATE_EUR = 0.9;
    private static final Date PRODUCTION_DATE = Date.newInstance(2016, 04, 30);
    private static final Decimal UNIT_PRICE = 2;
    private static final Double COMP_MULT = 5;
    private static final Integer PROD_COUNT = 4;
    private static final String PARENT_ACCOUNT_STAR = 'STAR';
	private static final String PARENT_ACCOUNT_SAMSUNG = 'Samsung';
	private static final String CBG_AUTOMOTIVE = 'Automotive';
    
    private static List<OpportunityLineItem> opptyProds = new List<OpportunityLineItem>();
    private static OpportunityLineItem opptyProd;
    
    static {
    	Opportunity_Claim_Value_MAG_Setting__mdt claimValueMagSetting = 
            [select MAG__c 
               from Opportunity_Claim_Value_MAG_Setting__mdt 
              where Claim_Value_Quarters__c != 'Lifetime'
                and IsActive__c = true
              limit 1];
        
        MAG_SHORT_LIVED = claimValueMagSetting.MAG__c;
               
        claimValueMagSetting = 
            [select MAG__c 
               from Opportunity_Claim_Value_MAG_Setting__mdt 
              where Claim_Value_Quarters__c = 'Lifetime'
                and IsActive__c = true
              limit 1];
        
        MAG_LIFETIME = claimValueMagSetting.MAG__c;
        
        List<OpportunityLineItem> opptyLineItems = [select Id, OpportunityId, Program__c, PricebookEntry.Product2.MAG__c from OpportunityLineItem]; 
        
        for (OpportunityLineItem oli : opptyLineItems) {
        	opptyProds.add(oli);    
        }
        
        if (opptyProds.size() > 0) {
        	opptyProd = opptyProds.get(0);
        }
    }
    	
	@testSetup
    static void setup() {
    	Profile p = [select Id from Profile where Name = :TEST_USER_PROFILE];
    	
    	// insert a test user
    	User u = createUser(TEST_USER, TEST_USER, p.Id, false);
                
        // insert FX Rates
        // There is a workflow which sets Opportunity.Locked_Exchange_Rate__c to 
        // Opportunity.Currency__r.Exchange_Rate__c, which refers to FX_Rates__c.Exchange_Rate__c
        List<FX_Rates__c> fxrs = new List<FX_Rates__c>();
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_USD, Currency_Code__c = CCY_CODE_USD, CurrencyIsoCode = CCY_CODE_USD, Exchange_Rate__c = EXCH_RATE_USD));
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_EUR, Currency_Code__c = CCY_CODE_EUR, CurrencyIsoCode = CCY_CODE_EUR, Exchange_Rate__c = EXCH_RATE_EUR));
        insert fxrs;
        
        Map<String, FX_Rates__c> fxRates = new Map<String, FX_Rates__c>();
        fxRates.put(CCY_CODE_USD, fxrs.get(0));
        fxRates.put(CCY_CODE_EUR, fxrs.get(1));
        
        // Insert accounts
        createAccount(PARENT_ACCOUNT_STAR, AccountsSelector.getParentRecordTypeID(), null, null);
        createAccount(PARENT_ACCOUNT_SAMSUNG, AccountsSelector.getParentRecordTypeID(), null, null);
        Account parentGeneral = createAccount('Parent Account - General', AccountsSelector.getParentRecordTypeID(), null, null);
        Account a = createAccount('Test Account', AccountsSelector.getChildRecordTypeID(), parentGeneral.Id, CBG_AUTOMOTIVE);
         
        // Insert an opportunity
        Opportunity o = new Opportunity(Name = 'Test Oppty', OwnerId = u.Id, AccountId = a.Id, StageName = 'Initial Engagement');
        o.Production_Date__c = PRODUCTION_DATE;
        o.CloseDate = PRODUCTION_DATE - 60;
        o.Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id; // Locked_Exchange_Rate__c will be set to this by workflow.
        o.CurrencyIsoCode = CCY_CODE_DEFAULT; // CurrencyIsoCode and Currency__c are correlated.
        o.Bypass_Validation_Sched_Start_Date__c = true;
        insert o;
        
        System.debug('//J ========== after insert oppty');  
        
        createOpportunitySchedules(o.Id, 1000);
        
        // Insert products
        List<Product2> prods = new List<Product2>();
        
        for (Integer i = 0; i < PROD_COUNT; i++) {
            Integer rem = Math.mod(i, 2);
            
            if (rem == 0) {
                prods.add(new Product2(Name = 'Test Product' + i, MAG__c = MAG_SHORT_LIVED, BL__c = BL1, IsActive = true));
            } else {
                prods.add(new Product2(Name = 'Test Product' + i, MAG__c = MAG_LIFETIME, BL__c = BL2, IsActive = true));
            }            
        }
        
        insert prods;
        
        List<PricebookEntry> pbes = [select Id from PricebookEntry where Product2Id in :prods and CurrencyIsoCode = :CCY_CODE_DEFAULT];
        
        // Insert opportunity products
        List<OpportunityLineItem> olis = new List<OpportunityLineItem>();
        
        for (PricebookEntry pbe : pbes) {
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = o.Id, PricebookEntryId = pbe.Id);
            oli.UnitPrice = UNIT_PRICE;
            oli.Component_Multiplier__c = COMP_MULT;
            olis.add(oli);
        }
        
        insert olis;
        
        System.debug('//J ========== after insert oppty prods');
    } 
    
    static void createOpportunitySchedules(ID opptyID, Double totalQty) {
    	List<OpportunitySchedule__c> opptyScheds = new List<OpportunitySchedule__c>();
    	Double qty = totalQty / 4;
    	
    	OpportunitySchedule__c opptySched;
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 01, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 04, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 07, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);
		opptySched = new OpportunitySchedule__c(Opportunity__c = opptyID, Sched_Date__c = Date.newInstance(2016, 10, 01), Oppty_Sched_Qty__c = qty, Frozen_Oppty_Sched_Qty__c = qty);
		opptyScheds.add(opptySched);	
    	
    	insert opptyScheds;
    }

	@isTest
    static void testOpptyProdProgramSyncedWithOppty() {
        Test.startTest();
        OpportunityProgram__c opptyProg = new OpportunityProgram__c(Name = 'Test Program');
        insert opptyProg; 
        
        Opportunity oppty = getOpportunity(opptyProd.OpportunityId);
        oppty.Program__c = opptyProg.Id;
        update oppty;
        Test.stopTest();
        
        opptyProd = [select Program__c from OpportunityLineItem where Id = :opptyProd.Id];
        
        System.assertEquals(opptyProg.Id, opptyProd.Program__c);
    }
    
    @isTest
    static void testOpptyProgramEditable() {
    	User user = [select Id from User where Alias = :TEST_USER];
    	
    	Test.startTest();
    	Opportunity oppty = getOpportunity(opptyProd.OpportunityId);
	    oppty.Design_Win_Approval_Process__c = 'Approved';
	    update oppty;
	    
	    System.runAs(user) {
	    	OpportunityProgram__c opptyProg = new OpportunityProgram__c(Name = 'Test Program 1');
	    	insert opptyProg;
	        
	        oppty.Program__c = opptyProg.Id;
	        resetOpptyFirstRun();
	        update oppty;
	        
	        opptyProd = [select Program__c from OpportunityLineItem where Id = :opptyProd.Id];
	        
	        System.assertEquals(opptyProg.Id, opptyProd.Program__c);
	        
	        try {
	        	opptyProg = new OpportunityProgram__c(Name = 'Test Program 2');
	        	insert opptyProg;
	        	
	        	// Only Program can be edited all the time.
	        	oppty.Program__c = opptyProg.Id;
	        	oppty.Name = 'Name 1';
	        	resetOpptyFirstRun();
	        	update oppty;	
	        	
	        	System.assert(false);
	        } catch (Exception e) {
	        	System.assert(true);
	        }
	        
	        try {
	        	// Only War Room Completed can be edited all the time.
	        	oppty.War_Room_Completed__c = 'Yes';
	        	oppty.Name = 'Name 2';
	        	resetOpptyFirstRun();
	        	update oppty;	
	        	
	        	System.assert(false);
	        } catch (Exception e) {
	        	System.assert(true);
	        }
	    }
	    
	    oppty.StageName = 'Commitment';
	    oppty.RecordTypeId = OpportunitiesSelector.getMnRecordTypeId();
	    update oppty;
	    
	    System.runAs(user) {
	    	OpportunityProgram__c opptyProg = new OpportunityProgram__c(Name = 'Test Program 3');
	        insert opptyProg;
	        
	        oppty.Program__c = opptyProg.Id;
	        resetOpptyFirstRun();
	        update oppty;
	        
	        opptyProd = [select Program__c from OpportunityLineItem where Id = :opptyProd.Id];
	        
	        System.assertEquals(opptyProg.Id, opptyProd.Program__c);
	        
	        try {
	        	opptyProg = new OpportunityProgram__c(Name = 'Test Program 4');
	        	insert opptyProg;
	        	
	        	// Only Program can be edited all the time.
	        	oppty.Program__c = opptyProg.Id;
	        	oppty.Name = 'Name 3';
	        	resetOpptyFirstRun();
	        	update oppty;
	        	
	        	System.assert(false);
	        } catch (Exception e) {
	        	System.assert(true);
	        }	
	        
	        try {
	        	// Only War Room Completed can be edited all the time.
	        	oppty.War_Room_Completed__c = 'No';
	        	oppty.Name = 'Name 4';
	        	resetOpptyFirstRun();
	        	update oppty;	
	        	
	        	System.assert(false);
	        } catch (Exception e) {
	        	System.assert(true);
	        }
	    }
	    Test.stopTest();
    }
    
    @isTest
    static void testOpptyDiscoveryDate() {
		Test.startTest();
		// Case 1: update oppty to discovery stage
    	Opportunity oppty = getOpportunity(opptyProd.OpportunityId);
    	
	    oppty.StageName = Opportunities.STAGES.get(Opportunities.Stage.DISCOVERY);
	    update oppty;
	    
	    oppty = getOpportunity(opptyProd.OpportunityId);
	    system.assertEquals(date.today(), oppty.Discovery_Date__c);
	    
	    //Case 2: insert oppty with Discovery stage
	    Opportunity opptyDiscovery = new Opportunity(
	    	Name = 'Test Disc Oppty',
	    	Production_Date__c = PRODUCTION_DATE,
        	CloseDate = PRODUCTION_DATE - 60,
	    	StageName = Opportunities.STAGES.get(Opportunities.Stage.DISCOVERY)
	    );
	    insert opptyDiscovery; 
        
        oppty = getOpportunity(opptyDiscovery.Id);
	    system.assertEquals(date.today(), oppty.Discovery_Date__c);
	    
	    Test.stopTest();
    }
    
    @isTest
    static void testOpptyClaimValueHistoryTracking() {
    	Test.startTest();
    	
        //Case 1: Locked Exchange Rate != null && Claim Value != null
    	Opportunity oppty = getOpportunity(opptyProd.OpportunityId);
    	
    	system.assertNotEquals(null, oppty.Claim_Value__c);
    	system.assertNotEquals(null, oppty.Locked_Exchange_Rate__c);
    	system.assertEquals(oppty.Claim_Value__c/oppty.Locked_Exchange_Rate__c, oppty.Claim_Value_USD_SYS__c);
    	
    	//Case 2: Locked Exchange Rate == null && Claim Value == null
    	Fx_Rates__c fxRate= [SELECT Id, Exchange_Rate__c, CurrencyIsoCode FROM Fx_Rates__c WHERE CurrencyIsoCode = :CCY_CODE_USD];
	    fxRate.Exchange_Rate__c = 0;
	    update fxRate;
    	
    	Opportunity opptyWoProduct = new Opportunity(
	    	Name = 'Test Oppty w/o product',
	    	Production_Date__c = PRODUCTION_DATE,
        	CloseDate = PRODUCTION_DATE - 60,
	    	StageName = Opportunities.STAGES.get(Opportunities.Stage.DISCOVERY),
	    	CurrencyIsoCode = CCY_CODE_USD
	    );
	    insert opptyWoProduct; 
	    	    
	    oppty = getOpportunity(opptyWoProduct.Id);
	    
	    system.assertEquals(0, oppty.Locked_Exchange_Rate__c);
	 	system.assertEquals(null, oppty.Claim_Value_USD_SYS__c);
        
        delete fxRate;
        update oppty;
        oppty = getOpportunity(opptyWoProduct.Id);
	    
	    system.assertEquals(0, oppty.Locked_Exchange_Rate__c);
    	
    	Test.stopTest();
    }
  
    static User createUser(String alias, String lastName, ID profileID, Boolean signedARIA) {
    	User user = newUser(alias, lastName, profileID, signedARIA); 
    	insert user;
        
        return user;	
    }
    
    static User newUser(String alias, String lastName, ID profileID, Boolean signedARIA) {
    	String email = CommonUtils.generateGUID() + '@nxp.com.test123';
    	
    	User user = new User(EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles');
		user.Alias = alias;
		user.LastName = lastName;
		user.ProfileId = profileID;
		user.Email = email;
		user.UserName = email;
		user.Signed_ARIA__c = signedARIA;
		        
        return user;	
    }
    
    static Account createAccount(String name, ID recordTypeID, ID parentID, String cbg) {
    	Account account = new Account(Region__c = 'EMEA');
    	account.Name = name;
    	account.RecordTypeId = recordTypeID;
    	account.ParentId = parentID;
    	account.CMD_Industry_Segment__c = cbg;
    	insert account;
    	
    	return account;
    }
    
    static Opportunity getOpportunity(ID opptyID) {
        return [select LT_Value_USD__c, Sales_Director_Approver__c, Regional_VP_Approver__c, VP_Approver_2__c, 
        			   MAG_Approver_1__c, MAG_Approver_2__c, BL_Approver_1__c, BL_Approver_2__c, Program__c,    
        			   Account.ParentId, Owner.MT_2__c, StageName, Discovery_Date__c, Claim_Value__c, Locked_Exchange_Rate__c,
        			   Claim_Value_USD_SYS__c, CurrencyIsoCode
        		  from Opportunity 
        		 where Id = :opptyID];    
    }
    
    static void resetOpptyFirstRun() {
    	Opportunities.isFirstRunBeforeUpdate = true;
	    Opportunities.isFirstRunAfterUpdate = true;
    }

}