src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMD_Industry_Segment__c</fullName>
        <description>Customer Buying Group</description>
        <inlineHelpText>Customer Buying Group</inlineHelpText>
        <label>CBG</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria_2__c</fullName>
        <description>This field is to capture the region when approver type is sales director</description>
        <label>Criteria 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_1__c</fullName>
        <label>Threshold 1</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cross_Reference_Customer__c.object
<CustomObject>
    <description>Cross Reference for Customer</description>
    <fields>
        <fullName>Child_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>TMMA Child Account</description>
        <label>Child Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account Customer Category must be Tier 4 - TMMA</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>TMMA Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.Customer_Category__c</field>
                <operation>equals</operation>
                <value>Tier 4 - TMMA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cross Reference - Customers</relationshipLabel>
        <relationshipName>Cross_Reference_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Location__c</fullName>
        <description>Customer Location</description>
        <label>Customer Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>Customer Name</description>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cross Reference - Customer</label>
    <nameField>
        <displayFormat>XRF-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Reference - Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FX_Rates__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>FX Rates</label>
    <nameField>
        <label>FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FX Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FX_Rates__c.CurrencyIsoCode</field>
                <operation>equals</operation>
                <valueField>$Source.CurrencyIsoCode</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FX_Rates__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <formula>TEXT(Account.Customer_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_End_Customer_Name_and_Location__c</fullName>
        <description>This field contains End customer&apos;s Name and Location.</description>
        <label>z_OBSOLET_End Customer Name and Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locked_Exchange_Rate__c</fullName>
        <inlineHelpText>The Exchange Rate against USD which is locked when opportunity is Approved</inlineHelpText>
        <label>Locked Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MN_Account_Id_Old__c</fullName>
        <description>MN previous Account Id</description>
        <label>MN Account Id Old</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>One_Year_Pieces__c</fullName>
        <description>This field contains PROJECT_UNITS from Model N system.</description>
        <label>One Year Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2010_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2010 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legacy_1_Year_Prod__c</fullName>
        <description>This field contains the VALUE_1_YR_PROD from Model N system.</description>
        <label>One Year Prod Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prod_Lost_Cancelled__c</fullName>
        <label>Prod Lost/Cancelled</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prod_Lost__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prod Lost</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/XrfCustomerUpdateBatchTest.cls
/* Last ModifiedBy : Baji
   Last ModifiedDate : 02 Jun 2017
   Description : Updated to remove the test data related to Opportunity Approval Setting.
*/ 

@isTest
public class XrfCustomerUpdateBatchTest
{
    private static final string TYPE_MN_OPPTY='Model N Oppty';
    private static final string TYPE_SFDC_OPPTY='SFDC Oppty';
    private static final String TEST_USER_PROFILE = 'Standard User';
    private static final String TEST_USER_EMAIL = 'testuser@testorg.com.test';
    private static final String CBG_AUTOMOTIVE = 'Automotive';
    private static final String CBG_NON_AUTOMOTIVE = 'Non-Automotive';
    private static final String CBG_DEFAULT = CBG_NON_AUTOMOTIVE; // @default
    private static final String MAG_SHORT_LIVED;
    private static final String MAG_LIFETIME;
    private static final String MAG_DEFAULT;
    private static final String CCY_CODE_USD = 'USD';
    private static final String CCY_CODE_EUR = 'EUR';
    private static final String CCY_CODE_DEFAULT = CCY_CODE_USD; // @default
    private static final Double EXCH_RATE_USD = 2.0;
    private static final Double EXCH_RATE_EUR = 0.9;
    private static final Double EXCH_RATE_DEFAULT = EXCH_RATE_USD; // @default
    private static final Decimal UNIT_PRICE = 2;
    private static final Double COMP_MULT = 5;
    private static final Double UP_CM = UNIT_PRICE * COMP_MULT;
    private static final Integer TOTAL_YEARLY_PIECES_LIFETIME = 13800;
    private static final Double CLAIM_VALUE_LIFETIME = ((TOTAL_YEARLY_PIECES_LIFETIME * UP_CM) / EXCH_RATE_DEFAULT);
    private static final Double CLAIM_VALUE_SHORT_LIVED;
    private static final Double CLAIM_VALUE_DEFAULT;
    private static final Double ONE_YEAR_PROD = 1500;
    private static final Double ONE_YEAR_PIECES = 500;
    private static final Double LOCKED_EXCHANGE_RATE = 1.5;    
    private static final Double CLAIM_VALUE_MN = ((UP_CM *ONE_YEAR_PIECES * 3) / LOCKED_EXCHANGE_RATE);    
    private static final Date PRODUCTION_DATE = Date.newInstance(2016, 04, 30);
    private static final String PROD_LOST = 'Lost';
    private static final String PROD_CANCELLED = 'Cancelled';
    private static final String STAGE_NAME = 'Initial Engagement';

    @testSetup
    static void setup()
    {
        OpportunityTrigger.fetchOppRecordTypes();
       
   
        Profile p = [SELECT Id FROM Profile WHERE Name = :TEST_USER_PROFILE];
        
        // insert a test user
        User u = new User(Alias = 'test', Email = TEST_USER_EMAIL, 
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id, UserName = TEST_USER_EMAIL);
        insert u;
        
        // insert approvers
        List<Approvers_Matrix__c> amcs = new List<Approvers_Matrix__c>();
        amcs.add(new Approvers_Matrix__c(Type__c = 'Regional VP', criteria_2__c = 'EMEA', Approver__c = u.Id, Threshold_1__c = 0));
        amcs.add(new Approvers_Matrix__c(Type__c = 'Regional VP', criteria_2__c = 'Americas', Approver__c = u.Id, Threshold_1__c = 0));
        amcs.add(new Approvers_Matrix__c(Type__c = 'Regional Controller', criteria_2__c = 'EMEA', Approver__c = u.Id, Threshold_1__c = 0));
        amcs.add(new Approvers_Matrix__c(Type__c = 'Regional Controller', criteria_2__c = 'Americas', Approver__c = u.Id, Threshold_1__c = 0));
        insert amcs;
        
        List<FX_Rates__c> fxrs = new List<FX_Rates__c>();
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_USD, Currency_Code__c = CCY_CODE_USD, CurrencyIsoCode = CCY_CODE_USD, Exchange_Rate__c = EXCH_RATE_USD));
        fxrs.add(new FX_Rates__c(Name = CCY_CODE_EUR, Currency_Code__c = CCY_CODE_EUR, CurrencyIsoCode = CCY_CODE_EUR, Exchange_Rate__c = EXCH_RATE_EUR));
        insert fxrs;
        
        Map<String, FX_Rates__c> fxRates = new Map<String, FX_Rates__c>();
        fxRates.put(CCY_CODE_USD, fxrs.get(0));
        fxRates.put(CCY_CODE_EUR, fxrs.get(1));
        
        Map<Integer,Account> mapAccount = new Map<Integer,Account>();
        
        // Insert an account
        Account a = new Account(Name = 'Test0 Account', Region__c = 'EMEA');
        a.CMD_Industry_Segment__c = CBG_DEFAULT; // CMD_Industry_Segment__c: One of the criteria to determine claim values
        a.Customer_Category__c = 'Tier 4 - TMMA';
        insert a;
        mapAccount.put(0,a);

        // Insert an account (Tier1)
        Account a1 = new Account(Name = 'Test1 Account', Region__c = 'EMEA');
        a1.CMD_Industry_Segment__c = CBG_DEFAULT; // CMD_Industry_Segment__c: One of the criteria to determine claim values
        a1.Customer_Category__c = 'Tier 1';
        insert a1;
        mapAccount.put(1,a1);

        // Insert an account (Tier2)
        Account a2 = new Account(Name = 'Test2 Account', Region__c = 'EMEA');
        a2.CMD_Industry_Segment__c = CBG_DEFAULT; // CMD_Industry_Segment__c: One of the criteria to determine claim values
        a2.Customer_Category__c = 'Tier 2';
        insert a2;
        mapAccount.put(2,a2);

        // Insert an account (Tier3)
        Account a3 = new Account(Name = 'Test3 Account', Region__c = 'EMEA');
        a3.CMD_Industry_Segment__c = CBG_DEFAULT; // CMD_Industry_Segment__c: One of the criteria to determine claim values
        a3.Customer_Category__c = 'Tier 3';
        insert a3;
        mapAccount.put(3,a3);

        // Insert an account
        Account a4 = new Account(Name = 'Test4 Account', Region__c = 'EMEA');
        a3.CMD_Industry_Segment__c = CBG_DEFAULT; // CMD_Industry_Segment__c: One of the criteria to determine claim values
        a3.Customer_Category__c = 'Tier 4 - ROM';
        insert a4;
        
        // Insert an Unknown account
        Account b = new Account(Name = 'Unknown', Region__c = 'EMEA');
        b.CMD_Industry_Segment__c = CBG_DEFAULT; // CMD_Industry_Segment__c: One of the criteria to determine claim values
        insert b;
        
        /*
        Cross_Reference_Customer__c cust=new Cross_Reference_Customer__c(Customer_Name__c='Test Account',
                                         Customer_Location__c='EMEA',Child_Account__c=a.Id);
        */
        List<Cross_Reference_Customer__c> lstCrossRef = new List<Cross_Reference_Customer__c>();
        for (Integer i = 0; i <= 3; i++) {
            System.debug('@@@@@ ' + 'Test' + i + ' Account' + '-EMEA');
            Cross_Reference_Customer__c cust = new Cross_Reference_Customer__c(Customer_Name__c='Test' + i + ' Account',
                                         Customer_Location__c='EMEA',Child_Account__c=mapAccount.get(i).Id);
            lstCrossRef.add(cust);
        }
        
        insert lstCrossRef;
        
        list<Opportunity> listOpp=new list<opportunity>();
        listOpp.add(new Opportunity(Name = 'Test Oppty1', AccountId = a4.Id,
                                      StageName = 'Initial Engagement', Legacy_End_Customer_Name_and_Location__c='Test1 Account-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                    One_Year_Pieces__c= ONE_YEAR_PIECES));
        
        listOpp.add(new Opportunity(Name = 'Test Oppty2', AccountId = a4.Id,
                                      StageName = 'Initial Engagement', Legacy_End_Customer_Name_and_Location__c='Test2 Account-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                   X2010_Pieces__c = 0,One_Year_Pieces__c= ONE_YEAR_PIECES));

        listOpp.add(new Opportunity(Name = 'Test Oppty3',  AccountId = a.Id, MN_Account_Id_Old__c = null, 
                                      StageName = 'Discovery', Legacy_End_Customer_Name_and_Location__c='Unknown-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                    One_Year_Pieces__c= ONE_YEAR_PIECES));        

        listOpp.add(new Opportunity(Name = 'Test Oppty4',  AccountId = a.Id, MN_Account_Id_Old__c = a4.Id, 
                                      StageName = 'Lost', Legacy_End_Customer_Name_and_Location__c='Unknown-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                   One_Year_Pieces__c= ONE_YEAR_PIECES));        

        listOpp.add(new Opportunity(Name = 'Test Oppty11',  
                                      StageName = 'Initial Engagement', AccountId = a1.Id, MN_Account_Id_Old__c = a4.Id,
                                    Legacy_End_Customer_Name_and_Location__c='Te Account-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                    One_Year_Pieces__c= ONE_YEAR_PIECES));

        listOpp.add(new Opportunity(Name = 'Test Oppty12',  
                                      StageName = 'Initial Engagement', AccountId = a2.Id, MN_Account_Id_Old__c = a4.Id,
                                    Legacy_End_Customer_Name_and_Location__c='Te Account-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                    One_Year_Pieces__c= ONE_YEAR_PIECES));

        listOpp.add(new Opportunity(Name = 'Test Oppty13',  
                                      StageName = 'Initial Engagement', AccountId = a3.Id, MN_Account_Id_Old__c = a4.Id,
                                    Legacy_End_Customer_Name_and_Location__c='Te Account-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                    One_Year_Pieces__c= ONE_YEAR_PIECES));

        listOpp.add(new Opportunity(Name = 'Test Remove Account Oppty', MN_Account_Id_Old__c = '001D000000j3LbOIAU',
                                      StageName = 'Initial Engagement', AccountId = a3.Id, Legacy_End_Customer_Name_and_Location__c='Te Account-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                    One_Year_Pieces__c= ONE_YEAR_PIECES));
        
        insert listOpp;
        
        // Insert an OpportunityShare record
        
        
        Product2 prod=new Product2(Name = 'Test Product' , MAG__c = MAG_SHORT_LIVED, IsActive = true);        
        insert prod;
        
        List<PricebookEntry> pbes = [select Id from PricebookEntry where Product2Id =:prod.Id and CurrencyIsoCode = :CCY_CODE_DEFAULT];
        
        List<OpportunityLineItem> olis = new List<OpportunityLineItem>();

        for (opportunity opp : listOpp) {
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id, PricebookEntryId = pbes[0].Id);
            oli.UnitPrice = UNIT_PRICE;
            oli.Component_Multiplier__c = COMP_MULT;
            //oli.Legacy_1_Year_Prod__c = ONE_YEAR_PROD; 
            olis.add(oli);
        }
        
        insert olis;
        
        Opportunity opp2 = new Opportunity(Name = 'Test Oppty5',  AccountId = a.Id, MN_Account_Id_Old__c = b.Id, 
                                      StageName = 'Discovery', Legacy_End_Customer_Name_and_Location__c='Unknown-EMEA',
                                  RecordTypeId = OpportunityTrigger.mnRecordType_Id, Production_Date__c = PRODUCTION_DATE,
                                    CloseDate = PRODUCTION_DATE - 60,Locked_Exchange_Rate__c = LOCKED_EXCHANGE_RATE,
                                   Currency__c = fxRates.get(CCY_CODE_DEFAULT).Id,CurrencyIsoCode = CCY_CODE_DEFAULT,
                                           One_Year_Pieces__c= ONE_YEAR_PIECES);
        insert opp2;
        
        OpportunityLineItem oli2 = new OpportunityLineItem(OpportunityId = opp2.Id, PricebookEntryId = pbes[0].Id);
        oli2.UnitPrice = UNIT_PRICE;
        oli2.Component_Multiplier__c = COMP_MULT;
        oli2.Prod_Lost_Cancelled__c = 'Lost';
        oli2.Prod_Lost__c = true;
        insert oli2;
    }

    @isTest
    static void XrfCustomerUpdateBatchTest1()
    {
        Test.startTest();
        XrfCustomerUpdateBatch c = new XrfCustomerUpdateBatch();
        database.executebatch(c);
        Test.stopTest();
        Integer crossRef = 0;
        Integer NonCrossRef = 0;
        List<Opportunity> lstOppty2 = [Select Id, Name, MN_Account_Id_Old__c from Opportunity];
        for (Opportunity o : lstOppty2) {
            if (o.MN_Account_Id_Old__c == null)
                NonCrossRef++;
            else
                crossRef++;
        }
        System.assert(NonCrossRef == 7);
        System.assert(crossRef == 2);
    }
    
    @isTest
    static void XrfCustomerUpdateBatchTest2()
    {
        Test.startTest();
        String CRON_EXP = '0 0 0 3 9 ? 2030';
        //schedule the job
        String jobId = System.schedule('testXrfCustomerUpdateBatch', CRON_EXP, new XrfCustomerUpdateBatch());

        List<CronTrigger> lstCrons = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                    FROM CronTrigger WHERE id = :jobId Limit 1];

        System.assert(lstCrons.size() > 0);
        System.assert(lstCrons[0].CronExpression == CRON_EXP);        
        System.assert(lstCrons[0].TimesTriggered == 0);
        Test.stopTest();
    }
}