src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Pre-account approval</description>
        <label>Status (NOT IN USE)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Approver_History__c.object
<CustomObject>
    <description>Used for approver performance management
Collect records from two objects: ProcessInstanceStep and ProcessInstanceWorkItem</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approver History</relationshipLabel>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actor_Username__c</fullName>
        <description>Username of User who approved or submitted a approval</description>
        <label>Actor Username</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Actual_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actual Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Approver History</relationshipLabel>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Name__c</fullName>
        <label>Approval Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <label>Approval Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Action_Date__c</fullName>
        <label>Approver Action Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <label>Approver Group</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMD_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMD Request</label>
        <referenceTo>CMD_Request__c</referenceTo>
        <relationshipLabel>Approver History</relationshipLabel>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approver History</relationshipLabel>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rebate</label>
        <referenceTo>eRebate__c</referenceTo>
        <relationshipLabel>Approver History</relationshipLabel>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Approver Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_ID__c</fullName>
        <label>Target Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Temp Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Approver History</label>
    <nameField>
        <label>Approver History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approver History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CollectProcessInstanceWorkItem.cls
/********************************************************************************************************
Modified by Scarlett on 2014/01/15
Collect all processinstanceWorkitems and insert to Approver_History
---------------------------------------------------------------------------------------------------------
@Last Modified:  Scarlett Kang
@Last Modified:  Jan 15, 2016
@Description:  1601 Hot-fix - SIR 665 Approver History Schedule Job is failed caused by Large SOQL Queries
********************************************************************************************************/
global with sharing class CollectProcessInstanceWorkItem implements Database.batchable<sObject>{
/*
public String query = 'SELECT ProcessInstance.Status, ProcessInstance.TargetObjectId, \" + 
            ProcessInstance.TargetObject.Name, \" +
            Actor.Username, Actor.Id, CreatedDate \" +
            FROM ProcessInstanceWorkitem \" +
            WHERE ProcessInstance.CreatedDate >= 2013-01-01T00:00:00Z +'";
            */
/***Modified by Scarlett on Jan 15, 2016***/
//public String query = 'SELECT ProcessInstance.Status, ProcessInstance.TargetObjectId, ProcessInstance.TargetObject.Name, Actor.Username, Actor.Id, CreatedDate FROM ProcessInstanceWorkitem WHERE ProcessInstance.CreatedDate >= 2014-01-01T00:00:00Z';            
public String query = 'SELECT ProcessInstance.Status, ProcessInstance.TargetObjectId, ProcessInstance.TargetObject.Name, Actor.Username, Actor.Id, CreatedDate FROM ProcessInstanceWorkitem WHERE ProcessInstance.CreatedDate >= LAST_N_MONTHS: 12';
/***Modified by Scarlett on Jan 15, 2016 - END***/
    
//Start
global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);    
}
//Execute
    global void execute(Database.BatchableContext BC, list<sObject> scope) {
        //Get Object Prefix
        map<String, String> sObjectPrefixes = new map<String, String>();
        for(Schema.SObjectType sObj : Schema.getGlobalDescribe().values())
            sObjectPrefixes.put(sObj.getDescribe().getKeyPrefix(), sObj.getDescribe().getLabel());
        
        List<Group> allCMDGroups = [
            SELECT Id, Name, Type FROM Group
			WHERE Name LIKE '%CMD%'];
        
        map<Id, String> mapCMDgroup = new map<Id, String>();
        for(Group theGroup : allCMDGroups){
            mapCMDgroup.put(theGroup.Id, theGroup.Name);
        }
            
        
        List<GroupMember> allGroupMembers= [
            SELECT GroupId, Id, UserOrGroupId FROM GroupMember
        ];
        
        list<Approver_History__c> listAH = new list<Approver_History__c>();
        
         //Insert Latest ProcessInstanceWorkitems to Approver_History      
         for(ProcessInstanceWorkitem Wi : (list<ProcessInstanceWorkitem>)scope) { 
                Approver_History__c AH = new Approver_History__c
                (
                Target_Object_ID__c = Wi.ProcessInstance.TargetObjectId,
                //Object_URL_2__c = system.URL.getSalesforceBaseUrl().toExternalForm() + '/' + Wi.ProcessInstance.TargetObjectId,
                //Is_Workitem__c = true,
                Approval_Status__c = Wi.ProcessInstance.Status,
                Approver_Action_Date__c = Wi.CreatedDate,
                Approval_Name__c = Wi.ProcessInstance.TargetObject.Name,
                Temp_Record__c = false
                );
               
                if(Wi.ProcessInstance.Status == 'Pending')
                     AH.Status__c = 'Pending';
             
                if(String.valueOf(Wi.Actor.Id).left(3) == '005'){
                    AH.Actual_Approver__c = Wi.Actor.Id;
                    AH.Actor_Username__c = Wi.Actor.Username;
                }
             	//Get Approver Group
                if(String.valueOf(Wi.Actor.Id).left(3) == '00G'){
                    //String groupId = String.valueOf(Wi.Actor.Id);
                    AH.Approver_Group__c = mapCMDgroup.get(String.valueOf(Wi.Actor.Id));
                    AH.Actor_Username__c = Wi.Actor.Username;
                }
                
                String ObjId = String.valueOf(Wi.ProcessInstance.TargetObjectId);
                //If it's a Account
                if(String.valueOf(Wi.ProcessInstance.TargetObjectId).left(3) == '001') {
                    AH.Object_Type__c = sObjectPrefixes.get(ObjId.left(3));
                    AH.Account__c = Wi.ProcessInstance.TargetObjectId;
                    AH.Approval_Type__c = sObjectPrefixes.get(ObjId.left(3));
                }
                //If it's a Agreement
                if(String.valueOf(Wi.ProcessInstance.TargetObjectId).left(3) == 'a01') {
                    AH.Object_Type__c = sObjectPrefixes.get(ObjId.left(3));
                    AH.Agreement__c = Wi.ProcessInstance.TargetObjectId;
                    AH.Approval_Type__c = sObjectPrefixes.get(ObjId.left(3));
                }
                //If it's a Opportunity
                if(String.valueOf(Wi.ProcessInstance.TargetObjectId).left(3) == '006') {
                    AH.Object_Type__c = sObjectPrefixes.get(ObjId.left(3));
                    AH.Opportunity__c = Wi.ProcessInstance.TargetObjectId;
                    AH.Approval_Type__c = sObjectPrefixes.get(ObjId.left(3));
                }
                //If it's Rebate
                if(String.valueOf(Wi.ProcessInstance.TargetObjectId).left(3) == 'a1A'){
                    AH.Object_Type__c = sObjectPrefixes.get(ObjId.left(3));
                    AH.Rebate__c = Wi.ProcessInstance.TargetObjectId;
                    AH.Approval_Type__c = sObjectPrefixes.get(ObjId.left(3));
                }       
                // CMD Request
                if(String.valueOf(Wi.ProcessInstance.TargetObjectId).left(3) == 'a1S'){
                    AH.Object_Type__c = sObjectPrefixes.get(ObjId.left(3));
                    AH.CMD_Request__c = Wi.ProcessInstance.TargetObjectId;
                    AH.Approval_Type__c = sObjectPrefixes.get(ObjId.left(3));
                }
             	/*
                // SAP CMD
                if(String.valueOf(Wi.ProcessInstance.TargetObjectId).left(3) == 'a1X'){
                    AH.Object_Type__c = sObjectPrefixes.get(ObjId.left(3));
                    AH.SAP_CMD__c = Wi.ProcessInstance.TargetObjectId;
                    AH.Approval_Type__c = sObjectPrefixes.get(ObjId.left(3));
                }    
				*/
                
                listAH.add(AH);
             //}//end if
         }//end for 
         insert listAH;
    }
//Finish
    global void finish(Database.BatchableContext BC){
        if(!Test.isRunningTest()){
           CollectProcessInstanceSteps steps = new CollectProcessInstanceSteps();
           Database.executeBatch(steps, 400);
       }
    }
}