src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <label>Segment Approval Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Automotive &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Computing</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Energy Management</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Home/Building Automation (HABA)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Secure Identity</fullName>
                </value>
                <value>
                    <fullName>Secure Transactions</fullName>
                </value>
                <value>
                    <fullName>Tagging &amp; Authentication</fullName>
                </value>
                <value>
                    <fullName>Wireless Infrastructure and RF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field signifies that Opportunities associated with this Parent Account should follow Segment Approval</description>
        <inlineHelpText>An indicator to trigger segment-level approval process. If it is set, the segment approval flow would be triggered, and any opportunity tied to the account (and its child accounts) will be escalated to the segment approver.</inlineHelpText>
        <label>Segment Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <label>(NOT IN USE) Sub-Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aerospace and Defense</fullName>
                </value>
                <value>
                    <fullName>Authentication</fullName>
                </value>
                <value>
                    <fullName>Body, Safety and Comfort</fullName>
                </value>
                <value>
                    <fullName>Broadband Access</fullName>
                </value>
                <value>
                    <fullName>Broadcast</fullName>
                </value>
                <value>
                    <fullName>Building Automation</fullName>
                </value>
                <value>
                    <fullName>Car Infotainment</fullName>
                </value>
                <value>
                    <fullName>CATV</fullName>
                </value>
                <value>
                    <fullName>Chassis</fullName>
                </value>
                <value>
                    <fullName>Clinical Health</fullName>
                </value>
                <value>
                    <fullName>Consumer Health Device</fullName>
                </value>
                <value>
                    <fullName>Consumer Power Tool</fullName>
                </value>
                <value>
                    <fullName>Control system</fullName>
                </value>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Gaming (Home Gaming Console)</fullName>
                </value>
                <value>
                    <fullName>Home Audio</fullName>
                </value>
                <value>
                    <fullName>Home Automation</fullName>
                </value>
                <value>
                    <fullName>Industrial Machinery</fullName>
                </value>
                <value>
                    <fullName>Intelligent transportation systems (ITS)</fullName>
                </value>
                <value>
                    <fullName>ISM</fullName>
                </value>
                <value>
                    <fullName>Lighting (including Solid state lighting, etc.)</fullName>
                </value>
                <value>
                    <fullName>Major Home Appliances</fullName>
                </value>
                <value>
                    <fullName>Medical Imaging</fullName>
                </value>
                <value>
                    <fullName>Medical Instrumentation</fullName>
                </value>
                <value>
                    <fullName>Military/Space/Avionics</fullName>
                </value>
                <value>
                    <fullName>Mobile Accessories</fullName>
                </value>
                <value>
                    <fullName>Mobile Handset</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Netbook</fullName>
                </value>
                <value>
                    <fullName>Notebook</fullName>
                </value>
                <value>
                    <fullName>Ultrabook</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Date__c</fullName>
        <inlineHelpText>Records the date when the Design Win is approved.</inlineHelpText>
        <label>Design Win Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Process__c</fullName>
        <label>Design Win Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Design_Win_Submission_Date__c</fullName>
        <inlineHelpText>Records the date when the Design Win was submitted for approval.</inlineHelpText>
        <label>Design Win Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <label>Industry Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Data Processing</fullName>
                </value>
                <value>
                    <fullName>Networking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <label>Industry Sub Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Factory Automation</fullName>
                </value>
                <value>
                    <fullName>Home &amp; Building Control</fullName>
                </value>
                <value>
                    <fullName>Test &amp; Measurement</fullName>
                </value>
                <value>
                    <fullName>Medical Electronics</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Energy</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Home Appliances</fullName>
                </value>
                <value>
                    <fullName>Wearable &amp; Fitness</fullName>
                </value>
                <value>
                    <fullName>Toys and Gaming</fullName>
                </value>
                <value>
                    <fullName>Home Audio Video</fullName>
                </value>
                <value>
                    <fullName>Voice &amp; Music</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>ADAS</fullName>
                </value>
                <value>
                    <fullName>Infotainment &amp; connectivity</fullName>
                </value>
                <value>
                    <fullName>Powertrain</fullName>
                </value>
                <value>
                    <fullName>Chassis &amp; Safety</fullName>
                </value>
                <value>
                    <fullName>Body &amp; Convenience</fullName>
                </value>
                <value>
                    <fullName>Other Automotive</fullName>
                </value>
                <value>
                    <fullName>Computers</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Point-of-Sale</fullName>
                </value>
                <value>
                    <fullName>Retail and Logistics</fullName>
                </value>
                <value>
                    <fullName>RFID Transit, Access and Identification</fullName>
                </value>
                <value>
                    <fullName>Enterprise Servers</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Other DP</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Data Center</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Broadband Access/ Home Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X2010_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2010 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2011_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2011 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2012_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2012 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2013_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2013 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2014_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2014 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2015_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2015 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <formula>PricebookEntry.Product2.BL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>PricebookEntry.Product2.BU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/CapturingOppProductsTest.cls
/*
@Created By :       Nisha Agrawal
@Created Date:      22 Jan 2013
@Description:       Test Class for the trigger CapturingOppProducts on Opportunity


@Modified By :      Nisha Agrawal
@Modified Date:     26 Feb 2013
@Description:       Modified a s per change in original trigger which will now insert Fulfillment Parts records Per Year Per Line Item. 
*/ 

@isTest//(SeeAllData=true)
private class CapturingOppProductsTest {
    /********************************************************
        CASE - 1 Opportunitiy having 20 Line Items - 16 Quarters
    *********************************************************/
  /*  static testMethod void CapturingOppProductsTest1() {
        //prepare test data     
        //insert product
        List<Product2> lstProducts = new List<Product2>();
        integer numOfLineItems = 20;
        integer i;
        
        //insert product
        for(i=0; i < numOfLineItems; i++)
            lstProducts.add(new Product2(Name = 'unit_test_product' + i, MAG__c = 't' + (i/5), BU__c = 't' + i, BL__c = 't' + i, IsActive = true)); 
        insert lstProducts; 
        
        //assert the results
        for(Product2 obj : lstProducts) system.assert(obj.Id != null);
        
        Pricebook2 pbook = [Select Id, Name From Pricebook2  Where IsActive = true and IsStandard = true limit 1];
        List<PricebookEntry> lstPBEntries = [Select Id From PricebookEntry  Where IsActive = true and CurrencyISOCode='USD' and Pricebook2Id = : pbook.Id and Product2Id in : lstProducts];
        
        //insert opportunity
        RecordType rType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Parent Account'];
        Account acc = [Select Id From Account Where Segment_Approval__c = true And RecordTypeId =: rType.Id LIMIT 1];
        Opportunity objOpp = New Opportunity(Name='ut_test_opp', StageName = 'Assessment', Industry_Segment__c = 'Healthcare', Sub_Segment__c = 'Clinical Health',
            Production_Date__c = date.newInstance(2011, 1, 21),  CloseDate = date.newInstance(2011, 1, 20), Design_Win_Submission_Date__c = date.newInstance(2011, 1, 10),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 1, 17) , X2010_Pieces__c = 0, X2011_Pieces__c =10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, Account = acc);
        insert objOpp;
        system.assert(objOpp.Id != null);
        
        //insert line items
        List<OpportunityLineItem> lstLineItems = new List<OpportunityLineItem>();
        for(i = 0; i < numOfLineItems; i++ )
        {
            lstLineItems.add(new OpportunityLineItem(OpportunityId = objOpp.Id, PriceBookEntryId = lstPBEntries[i].Id, UnitPrice = 500.1234 * (i + 1), Quantity = 10 * (i + 1)));
                
        }
        insert lstLineItems;        
        
        //start the test
        Test.startTest();
        
        //update the opportunity
        objOpp.Design_Win_Approval_Process__c = 'Approved';     
        update objOpp;
        
        //stop the test
        Test.stopTest();
    }
    
    
    /************************************************************
        CASE - 1 Opportunitiy having 20 Line Items - 12 Quarters
    *************************************************************/
    
 /*   static testMethod void CapturingOppProductsTest2() 
    {
        //prepare test data     
        //insert product
        List<Product2> lstProducts = new List<Product2>();
        integer numOfLineItems = 20;
        integer i;
        
        //insert product
        for(i=0; i < numOfLineItems; i++)
        {
            lstProducts.add(new Product2(Name = 'unit_test_product' + i, MAG__c = 't' + (i/5), BU__c = 't' + i, BL__c = 't' + i, IsActive = true));
        }    
        insert lstProducts; 
        
        //assert the results
        for(Product2 obj : lstProducts)
        {
          system.assert(obj.Id != null);
        }
        
        Pricebook2 pbook = [Select Id, Name From Pricebook2  Where IsActive = true and IsStandard = true limit 1];
        List<PricebookEntry> lstPBEntries = [Select Id From PricebookEntry  Where IsActive = true and CurrencyISOCode='USD' and Pricebook2Id = : pbook.Id and Product2Id in : lstProducts];
        
        //insert opportunity
        RecordType rType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Parent Account'];
        Account acc = [Select Id From Account Where Segment_Approval__c = true And RecordTypeId =: rType.Id LIMIT 1];
        Opportunity objOpp = New Opportunity(Name='ut_test_opp', StageName = 'Assessment', Industry_Segment__c = 'Computing' , Sub_Segment__c = 'Ultrabook',
            Production_Date__c = date.newInstance(2011, 1, 21),  CloseDate = date.newInstance(2011, 1, 18), Design_Win_Submission_Date__c = date.newInstance(2011, 1, 15),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 1, 19) , X2010_Pieces__c = 0, X2011_Pieces__c =10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 0, Account = acc);
        insert objOpp;
        system.assert(objOpp.Id != null);
        
        //insert line items
        List<OpportunityLineItem> lstLineItems = new List<OpportunityLineItem>();
        for(i = 0; i < numOfLineItems; i++ )
        {
            lstLineItems.add(new OpportunityLineItem(OpportunityId = objOpp.Id, PriceBookEntryId = lstPBEntries[i].Id, UnitPrice = 500.1234 * (i + 1), Quantity = 10 * (i + 1)));
                
        }
        insert lstLineItems;        
        
        //start the test
        Test.startTest();
        
        //update the opportunity
        objOpp.Design_Win_Approval_Process__c = 'Approved';     
        update objOpp;
        
        //stop the test
        Test.stopTest();
    }
    
    /********************************************************
        CASE - 8 Opportunities each having 10 Line Items 
    *********************************************************/
    
  /*  static testMethod void CapturingOppProductsTest3() 
    {
        //prepare test data
        
        //insert product
        List<Product2> lstProducts = new List<Product2>();
        integer numOfLineItems = 10;
        integer i;
        
        //insert product
        for(i=0; i < numOfLineItems; i++)
        {
          lstProducts.add(new Product2(Name = 'unit_test_product' + i, MAG__c = 't' + (i/5), BU__c = 't' + i, BL__c = 't' + i, IsActive = true));
        }        
        insert lstProducts; 
        
        //assert the results
        for(Product2 obj : lstProducts)
        {
          system.assert(obj.Id != null);
        }
        
        Pricebook2 pbook = [Select Id, Name From Pricebook2  Where IsActive = true and IsStandard = true limit 1];
        List<PricebookEntry> lstPBEntries = [Select Id From PricebookEntry  Where IsActive = true and CurrencyISOCode='USD' and Pricebook2Id = : pbook.Id and Product2Id in : lstProducts];
        
        //insert opportunities
        RecordType rType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Parent Account'];
        Account acc = [Select Id From Account Where Segment_Approval__c = true And RecordTypeId =: rType.Id LIMIT 1];
        List<Opportunity> lstOpps = new List<Opportunity>();
            
        lstOpps.add(New Opportunity(Name='ut_test_opp_1' , StageName = 'Assessment', Industry_Segment__c = 'Computing' , Sub_Segment__c = 'Ultrabook' ,
            Production_Date__c = date.newInstance(2011, 1, 21),  CloseDate = date.newInstance(2011, 1, 18), Design_Win_Submission_Date__c = date.newInstance(2011, 1, 15),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 1, 19) , X2010_Pieces__c = 0, X2011_Pieces__c = 10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 0, Account = acc));
        lstOpps.add(New Opportunity(Name='ut_test_opp_2' , StageName = 'Assessment', Industry_Segment__c = 'Computing' , Sub_Segment__c = 'Ultrabook' ,
            Production_Date__c = date.newInstance(2011, 5, 21),  CloseDate = date.newInstance(2011, 5, 18), Design_Win_Submission_Date__c = date.newInstance(2011, 5, 15),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 5, 19) , X2010_Pieces__c = 0, X2011_Pieces__c = 10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, Account = acc));
        lstOpps.add(New Opportunity(Name='ut_test_opp_3' , StageName = 'Assessment', Industry_Segment__c = 'Computing' , Sub_Segment__c = 'Ultrabook' ,
            Production_Date__c = date.newInstance(2011, 8, 21),  CloseDate = date.newInstance(2011, 8, 18), Design_Win_Submission_Date__c = date.newInstance(2011, 8, 15),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 8, 19) , X2010_Pieces__c = 0, X2011_Pieces__c = 10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, Account = acc));
        lstOpps.add(New Opportunity(Name='ut_test_opp_4' , StageName = 'Assessment', Industry_Segment__c = 'Computing' , Sub_Segment__c = 'Ultrabook' ,
            Production_Date__c = date.newInstance(2011, 11, 21),  CloseDate = date.newInstance(2011, 11, 18), Design_Win_Submission_Date__c = date.newInstance(2011, 11, 15),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 11, 19) , X2010_Pieces__c = 0, X2011_Pieces__c = 10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, Account = acc));
        
        lstOpps.add(New Opportunity(Name='ut_test_opp_5', StageName = 'Assessment', Industry_Segment__c = 'Healthcare', Sub_Segment__c = 'Clinical Health' ,  
            Production_Date__c = date.newInstance(2011, 1, 21),  CloseDate = date.newInstance(2011, 1, 20), Design_Win_Submission_Date__c = date.newInstance(2011, 1, 10),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 1, 17) , X2010_Pieces__c = 0, X2011_Pieces__c =10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25 , X2015_Pieces__c = 0, Account = acc));
        lstOpps.add(New Opportunity(Name='ut_test_opp_6', StageName = 'Assessment', Industry_Segment__c = 'Healthcare', Sub_Segment__c = 'Clinical Health' ,  
            Production_Date__c = date.newInstance(2011, 5, 21),  CloseDate = date.newInstance(2011, 5, 20), Design_Win_Submission_Date__c = date.newInstance(2011, 5, 10),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 5, 17) , X2010_Pieces__c = 0, X2011_Pieces__c =10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, X2015_Pieces__c = 30, Account = acc));
        lstOpps.add(New Opportunity(Name='ut_test_opp_7', StageName = 'Assessment', Industry_Segment__c = 'Healthcare', Sub_Segment__c = 'Clinical Health' ,  
            Production_Date__c = date.newInstance(2011, 8, 21),  CloseDate = date.newInstance(2011, 8, 20), Design_Win_Submission_Date__c = date.newInstance(2011, 8, 10),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 8, 17) , X2010_Pieces__c = 0, X2011_Pieces__c =10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, X2015_Pieces__c = 30, Account = acc));
        lstOpps.add(New Opportunity(Name='ut_test_opp_8', StageName = 'Assessment', Industry_Segment__c = 'Healthcare', Sub_Segment__c = 'Clinical Health' ,  
            Production_Date__c = date.newInstance(2011, 11, 21),  CloseDate = date.newInstance(2011, 11, 20), Design_Win_Submission_Date__c = date.newInstance(2011, 11, 10),  
            Design_Win_Approval_Process__c = 'Open', Design_Win_Approval_Date__c = date.newInstance(2011, 11, 17) , X2010_Pieces__c = 0, X2011_Pieces__c =10, 
            X2012_Pieces__c = 15, X2013_Pieces__c = 20, X2014_Pieces__c = 25, X2015_Pieces__c = 30, Account = acc));
        
        insert lstOpps;
        
        for(Opportunity opp : lstOpps) system.assert(opp.Id != null);
        
        //insert line items
        List<OpportunityLineItem> lstLineItems = new List<OpportunityLineItem>();
        for(i = 0; i < numOfLineItems; i++ )
        {
            for(integer j=0; j < lstOpps.size(); j++)
            {
                lstLineItems.add(new OpportunityLineItem(OpportunityId = lstOpps[j].Id, PriceBookEntryId = lstPBEntries[i].Id, UnitPrice = 500.1234 * (i + 1), Quantity = 10 * (i + 1)));   
            }               
        }
        insert lstLineItems;        
        
        //start the test
        Test.startTest();
        
        //update opportunities
        for(Opportunity objOpp : lstOpps)
        {
            objOpp.Design_Win_Approval_Process__c = 'Approved';
        }
        
        update lstOpps;
        
        //stop the test
        Test.stopTest();
    } */
}