src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <formula>TEXT(Account.Customer_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Design_Registration_Number__c</fullName>
        <description>This field contains design registration number i.e, REG_NUM from Model N.</description>
        <label>Design Reg Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>One_Year_Pieces__c</fullName>
        <description>This field contains PROJECT_UNITS from Model N system.</description>
        <label>One Year Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Model_N_Oppty</fullName>
        <active>true</active>
        <businessProcess>NXP Indirect Sales Process</businessProcess>
        <description>NXP Indirect Sales Opportunity</description>
        <label>Model N Oppty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CommunityUpdateEntitlementTest.cls
/* Last ModifiedBy : Baji
   Last ModifiedDate : 02 Jun 2017
   Description : Updated to remove the test data related to Opportunity Approval Setting.
*/ 

@isTest
private class CommunityUpdateEntitlementTest 
    {
        private static final String PARENT_ACCOUNT_RECORD_TYPE='Parent_Account';
        private static final String MODEL_N_OPPTY_RECORD_TYPE='Model_N_Oppty';
        private  static ID PARENT_ACCOUNT_RECORD_TYPE_ID;
        private  static ID MODEL_N_OPPTY_RECORD_TYPE_ID;
       
        public static list<Recordtype> listRecordType=new list<Recordtype>();
        /*public static void fetchRecordTypes()
        {
            listRecordType=[Select Id, DeveloperName From RecordType Where IsActive=true AND (SobjectType = 'Account' and (DeveloperName =:PARENT_ACCOUNT_RECORD_TYPE) )];
           for(RecordType rt:listRecordType)
           {
            if(rt.DeveloperName ==PARENT_ACCOUNT_RECORD_TYPE) 
            PARENT_ACCOUNT_RECORD_TYPE_ID=rt.id;
          
            System.debug(rt);
           }
        }*/
    private static void fetchRecordTypes()
    {        
        for(RecordType rt : [Select Id, DeveloperName
                              From RecordType Where IsActive=true and  
                              ((SobjectType = 'Opportunity' and (DeveloperName =: MODEL_N_OPPTY_RECORD_TYPE)) or
                               (SobjectType = 'Account' and (DeveloperName =:PARENT_ACCOUNT_RECORD_TYPE))                              
                              ) Limit 2])
            
        if(rt.DeveloperName == MODEL_N_OPPTY_RECORD_TYPE)
        {
            MODEL_N_OPPTY_RECORD_TYPE_ID= rt.id;
        }
        else if(rt.DeveloperName == PARENT_ACCOUNT_RECORD_TYPE)
        {
            PARENT_ACCOUNT_RECORD_TYPE_ID= rt.id; 
        }
        
    }   
        public static opportunity createOpportunity(id testAccountId,string DRNumber,date testclosedate)
        {
            
            opportunity oppty=new opportunity(name='test',recordtypeId=MODEL_N_OPPTY_RECORD_TYPE_ID,accountId=testAccountId,Legacy_Design_Registration_Number__c=DRNumber,StageName='Discovery',closeDate=testclosedate);
            return oppty;
        }
        public static Entitlement createEntitlements(id testAccountId,string DRNumber)
    {
        //Account objParentAccount = createParentAccount();
         // insert objParentAccount;
        Entitlement ObjEntitlement=new Entitlement(AccountId=testAccountId, Name='TestEntitlement', Startdate=system.today(),Type='free',Entitlement_Sub_Type__c='development project',Priority__c='critical',Project_NXP_Design_Registration__c=DRNumber);
        //listEntitlement.add(new Entitlement(AccountId=objParentAccount.id, Name='testingname', Startdate=system.today(),Type='free',Entitlement_Sub_Type__c='development project',Priority__c='medium'));
        //listEntitlement.add(new Entitlement(AccountId=objParentAccount.id, Name='testingname', Startdate=system.today(),Type='free',Entitlement_Sub_Type__c='',Priority__c='low'));
        //listEntitlement.add(new Entitlement(AccountId=objParentAccount.id, Name='testingname', Startdate=system.today(),Type='',Entitlement_Sub_Type__c='',Priority__c='critical'));
       // listEntitlement.add(new Entitlement(AccountId=objParentAccount.id, Name='testingname', Startdate=system.today(),Type='free',Entitlement_Sub_Type__c='',Priority__c='high'));
        //insert listEntitlement;
        return ObjEntitlement;
    
    } 
 
        @isTest
        static void testEntitlementEndCustomerIdentification()
        {
            fetchRecordTypes();
            
            Test.startTest();
            list<Entitlement> listEntitlement=new list<Entitlement>();
           // MODEL_N_OPPTY_RECORD_TYPE_ID= Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Model N Oppty').getRecordTypeId();
            date testclosedate=system.today();
            list<opportunity> listOpportunity=new list<Opportunity>();
            Account testAccount = new Account(Name = 'Test Account', Region__c = 'EMEA', RecordTypeId=PARENT_ACCOUNT_RECORD_TYPE_ID);
            insert testAccount;
            Account testChildAccount=new Account(Name = 'Test Child Account', Region__c = 'EMEA', parentid=testAccount.id,customer_category__C='Tier 4 - TMMA');
            insert testChildAccount;
            
            Opportunity oppty = createOpportunity(testChildAccount.id,'12341',testclosedate); // Jason Tsai added on 4/10/2017
            oppty.Production_Date__c= testclosedate + 10;
            oppty.One_Year_Pieces__c= 1000; 
            listOpportunity.add(oppty);
                        
            insert  listOpportunity;
            listEntitlement.add(createEntitlements(testChildAccount.id,'12341'));
            insert listEntitlement; 
            System.assertNotEquals(listEntitlement[0].Entitlement_Sub_Type__c,'Tier 4 - TMMA');
            
            test.stopTest();
        }
    }