src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NXP_GID__c</fullName>
        <externalId>true</externalId>
        <label>NXP GID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Describe the role of account whom NXP sells to</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>IDH</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <inlineHelpText>Customer address - state/province</inlineHelpText>
        <label>State/ Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aceh</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Andaman And Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>An Giang</fullName>
                </value>
                <value>
                    <fullName>Anhui Province</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bac Giang</fullName>
                </value>
                <value>
                    <fullName>Bac Kan</fullName>
                </value>
                <value>
                    <fullName>Bac Lieu</fullName>
                </value>
                <value>
                    <fullName>Bac Ninh</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California S</fullName>
                </value>
                <value>
                    <fullName>Bali</fullName>
                </value>
                <value>
                    <fullName>Banten</fullName>
                </value>
                <value>
                    <fullName>Ba Ria Vung Tau</fullName>
                </value>
                <value>
                    <fullName>Beijing City</fullName>
                </value>
                <value>
                    <fullName>Bengkulu</fullName>
                </value>
                <value>
                    <fullName>Ben Tre</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Binh Dinh</fullName>
                </value>
                <value>
                    <fullName>Binh Duong</fullName>
                </value>
                <value>
                    <fullName>Binh Phuoc</fullName>
                </value>
                <value>
                    <fullName>Binh Thuan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LeadCountrySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>country_Code__c</fullName>
        <label>country Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Country Settings</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/CreatePotentialLeadTest.cls
/*************************************************************************
@Created By:     Manikanta
@Description:    Test class for CreatePotentialLead
**************************************************************************/

@istest
public class CreatePotentialLeadTest {

	public static final String TEST_USER_PROFILE = 'Standard User';
    public static final String TEST_USER_EMAIL_0 = 'testuser1@testorg.com.test';
    public static final String TEST_USER_EMAIL_1 = 'testuser2@testorg.com.test';
    public static final String TEST_USER_EMAIL_2 = 'testuser3@testorg.com.test';
    public static final String TEST_USER_EMAIL_3 = 'testuser4@testorg.com.test';
    
    
    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name = :TEST_USER_PROFILE];
        
        // insert a test user
        
        User u = new User(Alias = 'test', Email = TEST_USER_EMAIL_0, 
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id, UserName = TEST_USER_EMAIL_0);
        insert u;
        
        //Insert Accounts
        Account a = new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 4 - TMMA',
                               NXP_GID__c='12145',country__c='Austria',state_province__c='Test State',Role__c='Distributor');        
        insert a;
        
        //Insert Contact   
        Contact con3 = new Contact(FirstName='Test',LastName='Contact', Title = 'strTitle',
                                  email = TEST_USER_EMAIL_3,AccountId=a.Id);        
        insert con3;
        
        //Insert Product
        
        Product2 Prod = new Product2 (Name='Test',Product_Type__c='Test');
        insert Prod;
        
        //Insert Live chat Transcript 	
        
        
      //LiveChatTranscript lvc = new LiveChatTranscript(contactid=con3.id,LiveChatVisitorid ='00096621');
        //insert lvc;
       
        List<LeadCountrySettings__c> leadCountrySettings = new list<LeadCountrySettings__c>();
        leadCountrySettings.add(new LeadCountrySettings__c(country_Code__c='TCN', Country__c='countryValu',Name='TestCountry',
                                                          Region__c='EMEA'));
        leadCountrySettings.add(new LeadCountrySettings__c(State_Code__c='TST', State__c='stateValu',Name='TestState',
                                                          Region__c='EMEA'));
        leadCountrySettings.add(new LeadCountrySettings__c(State_Code__c='TSN', State__c='stateValu',Name='TestState1',
                                                          Region__c='EMEA'));
        leadCountrySettings.add(new LeadCountrySettings__c(country_Code__c='TCT', Country__c='countryVal',Name='TestCountry1',
                                                          Region__c='EMEA'));
        insert leadCountrySettings;
    }

  
     @istest
    static  void testgetContactDetails(){
        Test.startTest();
        Contact contactReturns = [select Id,firstname,lastname,email,phone from contact where email =: TEST_USER_EMAIL_3];
        CreatePotentialLead.getContactDetails(contactReturns.Id);
         Test.stopTest();
    }
    

    
    /*
        @istest
    static  void testgetChckDetails(){
        Test.startTest();
        Contact contactReturns1 = [select Id,firstname,lastname,email from contact where email =: TEST_USER_EMAIL_3];
        LiveChatTranscript transReturns = [select Id,name from LiveChatTranscript where contactid =: contactReturns1.id];
       CreateLeadController1.getContactDetails(contactReturns1.Id);
       Test.stopTest();
    }

*/
    
    
             @istest
    static  void testgetPrdDetails(){
        Test.startTest();
        Product2 ProductReturns = [select Id,name from Product2 where name='Test'];
        String Prod1 = ProductReturns.name;
        CreatePotentialLead.getPrdDetails(Prod1);
        
        Test.stopTest();
    }
    
     @istest
    
        static  void testfetchproducts(){
        Test.startTest();
        List<Product2> productReturns = [select Id,name from Product2 ];
        CreatePotentialLead.fetchproducts();
         Test.stopTest();
    }
    
     @istest
    
        static  void testfetchprdSearch(){
        Test.startTest();
		String searchKey = 'x' + '%'; 
        List<Product2> productReturns = [select Id,name from Product2 where name like: searchKey];
        CreatePotentialLead.fetchprdSearch(searchKey );
         Test.stopTest();
    }

    
    @isTest
    static void testgetselectOptions(){
      Test.startTest();
        Lead ld = new Lead();
       CreatePotentialLead.getselectOptions(ld,'Industry');
         
        CreatePotentialLead.getDependentOptionsImpl('Account','Country__c','State_Province__c');
        CreatePotentialLead.getprdDependentOptionsImpl('Case','Product__c', 'Product_Category__c');
        CreatePotentialLead.getprddDependentOptionsImpl('Case','Product_Category__c','Product_Sub__c');
        
        
      Test.stopTest();
    }
    
    @isTest
    static void testfetchRegion(){
       Test.startTest();
        
        CreatePotentialLead.fetchRegion('countryValu');
        Test.stopTest();
    }
    
    @isTest
    static void testCreateLead(){
      Test.startTest();
        Contact ContactReturns=[select Id,firstname,lastname,email,phone,community_web_country__c from contact where email =: TEST_USER_EMAIL_3 ];
       // contact con=[select id, email from contact where email = :TEST_USER_EMAIL_3];
        CreatePotentialLead.createLead(ContactReturns.Id,'TestFirst', 'TestLast','test@test.com',
                                       'projctDesc','EMSI','1234455','YES','NO',
                                       'NXPNotes','countryValu',
                                       'stateValu','postalCode','prodlv1','prodlv2','prodlv3','prodname','prodId','transid','company');
             
      Test.stopTest();
    }
  @isTest
    static void testCreateLeadNullCase(){
      Test.startTest();
       Contact ContactReturns=[select Id,firstname,lastname,email,phone,community_web_country__c from contact where email =: TEST_USER_EMAIL_3 ];
        
       
        
         CreatePotentialLead.createLead(ContactReturns.Id,'TestFirst', 'TestLast','test@test.com',
                                       null,null,null,null,null,
                                       'NXPNotes','countryValu',
                                       'stateValu',null,null,null,null,null,null,null,null);
      Test.stopTest();
    }
   

}