src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Service_Level_Criteria__c.object
<CustomObject>
    <description>Created by shridevi, as part of SIR 1329(2016.11): This object is to store the email addresses(patterns) and Contact service level data.</description>
    <fields>
        <fullName>Contact_Service_Level__c</fullName>
        <description>Created by Shridevi, as part of SIR 1329(2016.11): This field is used to store the Contact Service Level value.</description>
        <label>Contact Service Level</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_Name__c</fullName>
        <description>Created By Shridevi, as part of SIR 1329(2016.11) : This field is to store the field name of the contact, which is used for identifying the Contact Service Level.</description>
        <label>Criteria Field Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_Value__c</fullName>
        <description>Created by Shridevi, as part of SIR 1329(2016.11): This field is used for storing the value of the criteria field which we are using for identifying the Contact Service Level.</description>
        <label>Criteria Field Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Contact Service Level Criteria</label>
    <nameField>
        <displayFormat>CSL-{00000}</displayFormat>
        <label>CSL Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Service Level Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>The region based on the country</inlineHelpText>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Hub_Foundation__c.object
<CustomObject>
    <description>Object to store foundation data for CMD Hub.</description>
    <fields>
        <fullName>Alpha_2_Code__c</fullName>
        <description>Alpha 2 Code issued by ISO-3166 Standard</description>
        <inlineHelpText>Alpha 2 Code issued by ISO-3166 Standard</inlineHelpText>
        <label>Alpha 2 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alpha_3_Code__c</fullName>
        <description>Alpha 3 Code issued by ISO-3166 Standard</description>
        <inlineHelpText>Alpha 2 Code issued by ISO-3166 Standard</inlineHelpText>
        <label>Alpha 3 Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP - GC</fullName>
                </value>
                <value>
                    <fullName>AP - SAP</fullName>
                </value>
                <value>
                    <fullName>AM - AMEC</fullName>
                </value>
                <value>
                    <fullName>EU - EMEA</fullName>
                </value>
                <value>
                    <fullName>AP - JAPAN</fullName>
                </value>
                <value>
                    <fullName>AP - KOREA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hub Foundation</label>
    <nameField>
        <displayFormat>FDI-{0000}</displayFormat>
        <label>Foundation Data Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Foundation</pluralLabel>
    <recordTypes>
        <fullName>Country_and_Region</fullName>
        <active>true</active>
        <description>ISO 3166 Standard Companies and its mapping with NXP Sales Regions</description>
        <label>Country and Region</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactClass.cls
/*********************************************************************
Created by  : Shridevi Badiger
Created date: 20-Oct-2016
Description : SIR 1329-Populate value for Contact Service Level field.

**********************************************************************/
/*********************************************************************
Created by  : Shridevi Badiger
Created date: 20-Mar-2017
Description : SIR SFDC374-calculate the contact service level for the account's having role as Distributors and 
               customer category as Tier 4-ROM. Also removed coustomer category value from code and introduced custom setting.
**********************************************************************/
/*****************************************************************************************
@Modified By :   Ranganath C N
@Modified Date:  22 Mar 2018
@Description:    To Convert ISO-3 country values to full country names as part of SFDC-1387. 
*******************************************************************************************/
/*****************************************************************************************
@Modified By :   Anil Somani
@Modified Date:  21 May 2018
@Description:    To overcome NullPointerException error as part of SFDC-1398. 
*******************************************************************************************/
/*************************************************************************************************************
@Modified By :   Harish Gowda N.
@Modified Date:  22 May 2018
@Description:    To Update User region of a contact based on the Community web country as part of SFDC-1611. 
**************************************************************************************************************/
public class ContactClass
{
      //  private static String CASE_TSCOMMUNITY = 'TS_Community';
      //  private static String CASE_TECH_SUPPORT = 'Tech_Support'; 
       private static final String DEFAULT_REGION =  'Not Found';
       private static String SAP_REGION = 'South Asia Pacific';
       private static String GC_REGION  = 'Greater China';
       private static String JAPAN_REGION = 'Japan';
       private static String KOREA_REGION = 'Korea';
       private static String AMEC_REGION = 'Americas';
       private static String EMEA_REGION= 'EMEA'; 
       
  public static void convertISONameToFullName(List<Contact> contacts)
    {
        map<String,String> mapOdCodes= new map<String,String>(); 
        List<Hub_Foundation__c> allCodes =[select Alpha_2_Code__c,Alpha_3_Code__c,Country__c,Region__c from Hub_Foundation__c]; 
    
        for(Hub_Foundation__c hc: allCodes)
        {
            mapOdCodes.put( hc.Alpha_3_Code__c ,hc.Country__c);
        }   
        for(contact ct : contacts)
        {
        String fullCountryName = mapOdCodes.get(ct.Mailingcountry);
        if(fullCountryName != null){
            ct.Mailingcountry=fullCountryName;
        }
        }  
    } 
           
           

public static void CSLIdentification(List<Contact> lstContactnew)
     {  
           
         //List<Contact> lstContactNew=new List<Contact>();
        
         List<Contact_Service_Level_Criteria__c> lstCSL=new List<Contact_Service_Level_Criteria__c>();
         List<Id> lstId=new List<Id>();
         List<Account> lstAccount=new List<Account>();
         List<Customer__c> lstCustomer=new List<Customer__c>();
        // List<Case> lstCase=new List<Case>();
         Boolean matchFound; 
         Map<string,TS_customer_category_with_CSL_values__c> mapCustCatagory= TS_customer_category_with_CSL_values__c.getAll(); 
        // Map<string,string> mapCustCatagory=new  Map<string,string>{'Tier 4 - ROM'=>'B1_Tier_4_ROM','Tier 4 - TMMA'=>'A2_Tier_4_TMMA','Tier 3'=>'A1_Tier_3','Tier 1'=>'A1_Tier_1','Tier 2'=>'A1_Tier_2','Longtail'=>'A8-Longtail','Partner'=>'A7-Partner','Channel'=>'A6-Channel','Regional'=>'A4-Regional','Key'=>'A3-Key','Mega'=>'A2-Mega'};
         set<string> setContactEmails=new set<String>();
         string tempDomain;
         string tempCSL;
         String[] labels;
          //DomainMatching(lstContactnew);
          
         for(Contact ContactRec:lstContactNew)
            {
                if(ContactRec.AccountId!=null)
                {
                lstId.add(ContactRec.AccountId);
                }
                if(ContactRec.Email!=null && ContactRec.Email!='')
                {
                    
                   // setContactEmails.add('%'+ContactRec.Email+'%');
                    //setContactEmails.add('%'+ContactRec.Email.substringAfter('@')+'%');
                    Labels=contactRec.Email.split('\\.|\\@');
                    if(Labels[Labels.size()-2]=='com' || Labels[Labels.size()-2]=='co')
                    {
                    setContactEmails.add('%'+Labels[Labels.size()-3]+'.'+Labels[Labels.size()-2]+'.'+Labels[Labels.size()-1]+'%');
                    }
                    else
                    setContactEmails.add('%'+Labels[Labels.size()-2]+'.'+Labels[Labels.size()-1]+'%');
                }
            }
          system.debug(setContactEmails);
          lstCSL=[select id,Criteria_Field_Name__c,Criteria_Field_Value__c,Contact_Service_Level__c from Contact_Service_Level_Criteria__c where Criteria_Field_Value__c LIKE :setContactEmails];
          Map<Id,account> mapAccount=new Map<Id,account>([select id,name,Customer_Category__c,Role__c from account where id in: lstId]);
         
          system.debug(lstCSL);
         
         for(Contact contactRec:lstContactNew)
         {
            
            matchFound=false;
            tempDomain=''; 
            tempCSL='';  
            if(lstCSL.size()!=0 && lstCSL!=null)
            {    
                for(Contact_Service_Level_Criteria__c CSL:lstCSL)
                    {
                     if(contactRec.Email!=null ||contactRec.Email!='' )
                       {
                         if(contactRec.Email==CSL.Criteria_Field_Value__c )
                             {
                                 matchFound=true;
                                 contactRec.Contact_Service_Level__c=CSL.Contact_Service_Level__c;
                                 System.debug('CLS::'+contactRec.Contact_Service_Level__c);
                                 break;
                             }
                       }
                     }
             }
           //---------------Added by Shridevi as par of SIR 374 and Modified as part of SFDC-1398----------------------------------------------------------
            if(matchFound==false && ContactRec.AccountId!=null)
            {
                if(mapAccount.containsKey(ContactRec.AccountId))
                {
                    Account objAccount = mapAccount.get(ContactRec.AccountId);
                    if(objAccount.Customer_Category__c!=null && objAccount.Customer_Category__c!='--None--' && objAccount.Customer_Category__c!='')
                    {
                         if(objAccount.Role__c=='Distributor' && objAccount.Customer_Category__c=='Tier 4 - ROM')
                         {
                            contactRec.Contact_Service_Level__c='A3_Distributor';
                            matchFound=true;
                         }
                         else if(mapCustCatagory!=null)
                         {
                            if( mapCustCatagory.get(objAccount.Customer_Category__c)!=null                                      
                            && mapCustCatagory.get(objAccount.Customer_Category__c).Contact_Service_Level__c!=null 
                            && mapCustCatagory.get(objAccount.Customer_Category__c).Contact_Service_Level__c!='')
                                 
                            {
                                 System.debug(mapCustCatagory.get(objAccount.Customer_Category__c).Contact_Service_Level__c);
                                 contactRec.Contact_Service_Level__c=(string)(mapCustCatagory.get(objAccount.Customer_Category__c).Contact_Service_Level__c);
                                 matchFound=true;
                            }
                         }
                     }
                }
             }    
           //----------------------------------------------------------------------------------------------------------------------    
        
                   if(matchFound==false && lstCSL.size()!=0 && lstCSL!=null)
            
                         {
                           for(Contact_Service_Level_Criteria__c CSL:lstCSL)
                              {
                                 if(contactRec.Email!=null && contactRec.Email!='' )
                                   {
                                     if(contactRec.Email.substringAfter('@')==CSL.Criteria_Field_Value__c)
                                         {
                                             System.debug('CLS1::'+contactRec.Contact_Service_Level__c);
                                             matchFound=true;
                                             contactRec.Contact_Service_Level__c=CSL.Contact_Service_Level__c;
                                             break;
                                         }
                                    if(contactRec.Email.substringAfter('@').contains(CSL.Criteria_Field_Value__c))
                                         {
                                         if(tempDomain=='' || tempDomain==null)
                                            {
                                             tempDomain=CSL.Criteria_Field_Value__c;
                                             tempCSL=CSL.Contact_Service_Level__c;
                                            }
                                         else if(tempDomain.length()<CSL.Criteria_Field_Value__c.length())
                                            {
                                             tempDomain=CSL.Criteria_Field_Value__c;
                                             tempCSL=CSL.Contact_Service_Level__c;
                                            
                                            } 
                                             system.debug('tempDomain:'+tempDomain);
                                              system.debug('tempCSL:'+tempCSL);
                                         } 
                                   }
                             }
                     }
                   
            if(matchFound==false)
            {
                if(tempCSL!=null && tempCSL!='')
                    contactRec.Contact_Service_Level__c=tempCSL;
                else
                   contactRec.Contact_Service_Level__c='B2-OtherCompany';
            }
            System.debug('CLS2::'+contactRec.Contact_Service_Level__c);
        
     } 
    }
  //added as a part of SFDC-1611, Method to update region based on the country from Hub foundation
   public static void AssignRegionByCountryForContact(List<Contact> lstContacts, Map<Id, Contact> oldContactsMap, Boolean IsInsert, Boolean IsUpdate)
    {
        Set<String> countries = new Set<String>(); 
        Map<String, String> mapCountryToRegions = new Map<String, String>();
          
        for(Contact objContact : lstContacts)
        {
            if((objContact.Community_web_country__c != null) &&( IsInsert || (IsUpdate && oldContactsMap.get(objContact .Id).Community_web_country__c != objContact.Community_web_country__c)))
            {
                countries.add(objContact.Community_web_country__c);
            }
        }
          
        if(countries.size() > 0)
        {
            //Fetch the Record Type for Country and Region Mapping
            List<RecordType> lstRecordTypes = [Select Id, DeveloperName From RecordType Where DeveloperName = 'Country_and_Region' and SobjectType = 'Hub_Foundation__c'];
            
            if(lstRecordTypes.size() > 0)
            {
                for (Hub_Foundation__c objRegion : [select Alpha_2_Code__c,Alpha_3_Code__c,Country__c,Region__c from Hub_Foundation__c Where Alpha_3_Code__c in :countries and RecordTypeId =: lstRecordTypes[0].Id ])
                {
                    mapCountryToRegions.put(objRegion.Alpha_3_Code__c , objRegion.Region__c);
                } 
            }      
        }
          
        String strRegion;
        for(Contact objContactUpdate : lstContacts)
        {
            if((IsInsert) || (IsUpdate && oldContactsMap.get(objContactUpdate.Id).Community_web_country__c!= objContactUpdate.Community_web_country__c))
            {
                if(objContactUpdate.Community_web_country__c!= null)
                { 
                   if(mapCountryToRegions.get(objContactUpdate.Community_web_country__c) == 'AP - SAP'){
                     strRegion = SAP_REGION ;
                   }
                   else if(mapCountryToRegions.get(objContactUpdate.Community_web_country__c) == 'AP - GC'){
                     strRegion = GC_REGION ;
                   }
                   else if(mapCountryToRegions.get(objContactUpdate.Community_web_country__c) == 'AP - JAPAN'){
                     strRegion = JAPAN_REGION ;
                   }
                   else if(mapCountryToRegions.get(objContactUpdate.Community_web_country__c) == 'AP - KOREA'){
                     strRegion = KOREA_REGION ;
                   }
                   else if(mapCountryToRegions.get(objContactUpdate.Community_web_country__c) == 'AM - AMEC'){
                     strRegion = AMEC_REGION ;
                   }
                   else if(mapCountryToRegions.get(objContactUpdate.Community_web_country__c) == 'EU - EMEA'){
                     strRegion = EMEA_REGION ;
                   }
                }
                //objContactUpdate.User_Region__c =(strRegion != null ? strRegion : DEFAULT_REGION);  
                
                if(strRegion != null){
                objContactUpdate.User_Region__c = strRegion;
                }
                else{objContactUpdate.User_Region__c = DEFAULT_REGION;}
                }            
        }  
    }
}