src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NXP_GID__c</fullName>
        <externalId>true</externalId>
        <label>NXP GID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Describe the role of account whom NXP sells to</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>IDH</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <inlineHelpText>Customer address - state/province</inlineHelpText>
        <label>State/ Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aceh</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Andaman And Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>An Giang</fullName>
                </value>
                <value>
                    <fullName>Anhui Province</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bac Giang</fullName>
                </value>
                <value>
                    <fullName>Bac Kan</fullName>
                </value>
                <value>
                    <fullName>Bac Lieu</fullName>
                </value>
                <value>
                    <fullName>Bac Ninh</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California S</fullName>
                </value>
                <value>
                    <fullName>Bali</fullName>
                </value>
                <value>
                    <fullName>Banten</fullName>
                </value>
                <value>
                    <fullName>Ba Ria Vung Tau</fullName>
                </value>
                <value>
                    <fullName>Beijing City</fullName>
                </value>
                <value>
                    <fullName>Bengkulu</fullName>
                </value>
                <value>
                    <fullName>Ben Tre</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Binh Dinh</fullName>
                </value>
                <value>
                    <fullName>Binh Duong</fullName>
                </value>
                <value>
                    <fullName>Binh Phuoc</fullName>
                </value>
                <value>
                    <fullName>Binh Thuan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Pre-account approval</description>
        <label>Status (NOT IN USE)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Some Action</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Downloaded</fullName>
                </value>
                <value>
                    <fullName>Requested Sales Follow-up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_to_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Lead Activity(Eloqua)</relationshipLabel>
        <relationshipName>Lead_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specific_Interest__c</fullName>
        <label>Specific Interest</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Activity</label>
    <nameField>
        <displayFormat>LA-{000000000}</displayFormat>
        <label>Activity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ShareLeadActivityTest.cls
/*************************************************************************
@Created By:     Manikanta
@Description:    Test class for ShareLeadActivity
**************************************************************************/

@istest
 
public class ShareLeadActivityTest {
    public static final String TEST_USER_PROFILE = 'Standard User';
    public static final String TEST_USER_EMAIL_0 = 'testuser1@testorg.com.test';
    public static final String TEST_USER_EMAIL_1 = 'testuser2@testorg.com.test';
    public static final String TEST_USER_EMAIL_2 = 'testuser3@testorg.com.test';
    public static final String TEST_USER_EMAIL_3 = 'testuser4@testorg.com.test';
    
    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name = :TEST_USER_PROFILE];
        // insert a test user
            User u = new User(Alias = 'test', Email = TEST_USER_EMAIL_0, 
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id, UserName = TEST_USER_EMAIL_0);
        insert u;
             //Insert Accounts
        Account a = new Account(Name = 'Test Account', Region__c = 'EMEA',OwnerId=u.Id,customer_category__c='Tier 4 - TMMA',
                               NXP_GID__c='12145',country__c='Austria',state_province__c='Test State',Role__c='Distributor');        
        insert a;
              //Insert Contact   
        Contact con3 = new Contact(FirstName='Test',LastName='Contact', Title = 'strTitle',
                                  email = TEST_USER_EMAIL_3,AccountId=a.Id);        
        insert con3;
        
        //Insert Lead

        Lead leadrec = new Lead( LastName = 'TestLead', 
                                company= 'Testcompany', 
                                Job_Description__c = 'Director', Normalized_Title__c ='Consultant',
                                Industry = 'TestIndustry',email = TEST_USER_EMAIL_3,Phone = '12345',HasOptedOutOfEmail = false,DoNotCall =false,city = 'testcity',
                                state='teststate',street='teststreet',PostalCode = '12345',Country ='India',Rating = '5',Status = 'Open');  
        insert leadrec;
        
        // Insert Lead Activities
        
        Lead_activity__c leadact =new Lead_activity__c(Action__c ='Ordered',Object__c='TestObject',Specific_Interest__c='Test',related_to_lead__c = leadrec.id);    
        Insert leadact;
        
        // Insert Distributor_Lead_Tracker__c
         Distributor_Lead_Tracker__c disit = new Distributor_Lead_Tracker__c(Status__c ='Assigned',Lead_Id__c = leadrec.id,Distributor_Contact__c = con3.id );
        Insert disit;
         Distributor_Lead_Tracker__c disit1 = new Distributor_Lead_Tracker__c(Status__c ='Queued',Lead_Id__c = leadrec.id,Distributor_Contact__c = con3.id );
            Insert disit1;
    }
    
     @istest
    static  void testgetleads(){
        Test.startTest();
        lead LeadReturns = [select id,Name,company,Job_Description__c,Normalized_Title__c,Address,Industry,Email,
              Phone,HasOptedOutOfEmail,DoNotCall,city,state,street,PostalCode,Country,Rating,Status,Owner.Email from lead];
        ShareLeadActivity.getleads(LeadReturns.Id);
         ShareLeadActivity.fetchLeadact(LeadReturns.Id);
        List<String> ss = new List<String> ();
        ss.add('Test');
        ss.add('Test1');
       
       ShareLeadActivity.getDistiContactsForLead(LeadReturns.Id,ss);
     //  LeadDistiContactDetails ldc = new LeadDistiContactDetails();
     //  DistiContact dis =new DistiContact(LeadReturns.id,'test','test1','Open');
         Test.stopTest();
    }
    
     @isTest
    static void testshareLead(){
      Test.startTest();
        Lead LeadReturns=[select id,Name,company,Job_Description__c,Normalized_Title__c,Industry,Email,
              Phone,HasOptedOutOfEmail,DoNotCall,city,state,street,PostalCode,Country,Rating,Status,Owner.Email from lead];
       List<Lead_activity__c> leadac = [select id from Lead_activity__c where related_to_lead__c =:LeadReturns.Id ];
        List<Id> idds = new List<Id>();
        for(Lead_activity__c lds: leadac){
            idds.add(lds.id);
        }
        Contact c = [select id from contact];
                         
             ShareLeadActivity.shareLead(LeadReturns.Id,'Testname','Testcompany','Director','Consultant','TestIndustry','test@test.com',
                                        '12345',true,false,idds,'teststreet','testcity','teststate','India','254585',c.id,'tetr@test.com','testrer@test.com','notestodisti');
        ShareLeadActivity.shareLead(LeadReturns.Id,'Testname','Testcompany','Director','Consultant','TestIndustry','test@test.com',
                                        '12345',true,false,idds,'teststreet','testcity','teststate','India','254585',c.id,null,'testrer@test.com','notestodisti');
                                   
                                  
             
      Test.stopTest();
    }
    
  
}