src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMD_Request_Id__c</fullName>
        <description>This field will store 18 digit Id of the CMD Request record so that we can connect Customer record with CMD Request.</description>
        <label>CMD Request Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <inlineHelpText>Customer&apos;s Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Pre-account approval</description>
        <label>Status (NOT IN USE)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>CMD_Request_Id__c</fullName>
        <description>This field will store 18 digit Id of the CMD Request record so that we can connect Customer record with CMD Request.</description>
        <inlineHelpText>Please provide the Id of the CMD Request record.</inlineHelpText>
        <label>CMD Request Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <inlineHelpText>Indicate if the customer is currently active</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FunLoc__c.object
<CustomObject>
    <description>FunLoc database  - a store all the FunLocs used in NXP ( includes the migrated FunLoc from Lotus Notes Database )</description>
    <fields>
        <fullName>Call_Name__c</fullName>
        <description>Call Name</description>
        <inlineHelpText>Call Name</inlineHelpText>
        <label>Call Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name</description>
        <inlineHelpText>Name</inlineHelpText>
        <label>Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Place_Name__c</fullName>
        <description>Place Name</description>
        <inlineHelpText>Place Name</inlineHelpText>
        <label>Place Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <description>Street Name</description>
        <inlineHelpText>Street Name</inlineHelpText>
        <label>Street Name</label>
        <type>TextArea</type>
    </fields>
    <label>FunLoc</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>FunLoc ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FunLocs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SAP_CMD_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Ready to Submit</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMD_Request__c</fullName>
        <label>CMD Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMD_Request__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>SAP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CMD_Request__c</referenceTo>
        <relationshipLabel>SAP CMD</relationshipLabel>
        <relationshipName>SAP_CMD_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pending_Approval_Since__c</fullName>
        <label>Pending Approval Since</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pending_Approver__c</fullName>
        <label>Pending Approver</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_CMD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP CMD</label>
        <referenceTo>SAP_CMD__c</referenceTo>
        <relationshipLabel>CMD Requests</relationshipLabel>
        <relationshipName>SAP_CMD_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SAP CMD Request</label>
    <nameField>
        <displayFormat>SAPCMDR{0000000000}</displayFormat>
        <label>SAP CMD Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP CMD Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SAP_CMD_Request_Trigger_Test.cls
@isTest
private class SAP_CMD_Request_Trigger_Test {
    
    private static RecordType SAPrt;
    private static string SAPrtId = '012D0000000QlBaIAK';
    private static RecordType Z001rt;
    private static string Z001rtId;
    private static Funloc__c objFunloc;
    private static List<Customer__c> lstCustomer;
    private static Customer__c objCustomer;
    
    Private Static list<CMD_Request__c> lstCmdRequest;
    Private Static list<SAP_CMD__c> lstSapCmd;
    Private Static list<SAP_CMD_Request__c> lstSapCmdRequest;
    private static CMD_Request__c testRequest;
    private static SAP_CMD__c testSAPCMD;
    private static SAP_CMD_Request__c testSAPCMDRequest;

    @isTest(SeeAllData=true)     
    private static void fetchRecordTypes()
    {
        for(RecordType rt : 
            [   
                Select Id, DeveloperName
                From RecordType
                WHERE SobjectType = 'CMD_Request__c' 
                AND DeveloperName LIKE '%SAP%' 
                AND IsActive=true
                Limit 1
            ]
        )
        {
            SAPrt = rt;
            SAPrtId = String.valueOf(rt.Id);            
        }    
        for(RecordType rt : 
            [   
                Select Id, DeveloperName
                From RecordType
                WHERE SobjectType = 'SAP_CMD__c' 
                AND IsActive=true
            ]
        )
        {
            if( rt.DeveloperName == 'Z001_SoldTo_ShipTo_BillTo_Payer' ){
                Z001rt = rt;
                Z001rtId = String.valueOf(rt.Id);
            }               
        }    
    }
    
    private static void createFunloc(){
        objFunloc = new Funloc__c(
            Name__c = 'Test Convert',
            Call_Name__c = 'Test Convert',
            Street_Name__c = 'Test Convert',
            Place_Name__c = 'Test Convert',
            Country_Name__c = 'Test Convert'
        );

        insert objFunloc;
    }
    
    

    static  void thePositiveTest(){
        lstCmdRequest=new list<CMD_Request__c>();
        lstSapCmd=new list<SAP_CMD__c>();
      	lstSapCmdRequest= new list<SAP_CMD_Request__c>();
        
        fetchRecordTypes();
	            
        testRequest = new CMD_Request__c(
            RecordTypeId = SAPrtId,
            Business_Background_Comments__c = 'Test Business Background Comments',
            Global_Account__c = 'Test Global Account',
            Sales_Organisation__c = 'Test Sales Organisation',            
            SP_Name__c = 'Test Name',
            SP_Street__c = 'Test Street',
            SP_City__c = 'Test City',
            SP_Country__c = 'Test Country',
            Con_Acct_SP_EMS__c = 'Test',
            Cust_pric_proc__c = 'Test',
            Grp_1_Sls_Channel_SP__c = 'Test',
            Currency__c = 'Test Currency',
            PD_Key_Account__c = 'Test PD Key Account',
            Reprice_Basis__c = 'Test Reprice Basis',
            Sales_Office__c = 'Test Sales_Office__c',
            S_O_Sub_Group__c = 'Test S O Sub Group'
        );
        
        lstCmdRequest.add(testRequest);
        insert lstCmdRequest;
        
        testSAPCMD = new SAP_CMD__c(
            RecordTypeId = Z001rtId,
            CMD_Request_ID__c = lstCmdRequest[0].Id,
            FunLoc__c = objFunloc.Id,
            HUB_Customer__c = lstCustomer[0].Id,
            Legal_Name__c = 'Test Legal Name'
        );
        lstSapCmd.add(testSAPCMD);
        insert lstSapCmd;
        
        SAP_CMD_Request_Trigger.upsertSAP_CMD_Request( lstSapCmd );
        
        LIST<SAP_CMD_Request__c> listSAPCMDRequests = [SELECT Id ,
                                                     		Approval_Status__c ,
                                                     		Pending_Approver__c ,
                                                      		Pending_Approval_Since__c
                                                      	FROM  SAP_CMD_Request__c
                                                      	WHERE CMD_Request__c = :lstCmdRequest[0].Id
                                                      	AND	SAP_CMD__c = :lstSapCmd[0].Id
                                                     ];
       
        if( listSAPCMDRequests.size() > 0 )
            testSAPCMDRequest = listSAPCMDRequests[0];

        System.assert( testSAPCMDRequest.id != null );

        for(SAP_CMD__c sap:lstSapCmd)
        {
            sap.Status__c = 'Draft';
            sap.Pending_Approver__c = 'Export Control';
        }        
        update lstSapCmd;
        
        SAP_CMD_Request_Trigger.syncSAP_CMD_Approval_Fields(lstSapCmd);
		        
        System.assertEquals( testSAPCMD.Status__c , testSAPCMDRequest.Approval_Status__c );
//        System.assertEquals( testSAPCMD.Pending_Approver__c , testSAPCMDRequest.Pending_Approver__c );
        System.assertEquals( testSAPCMD.Pending_Approval_Since__c , testSAPCMDRequest.Pending_Approval_Since__c );
    }  
}