src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>Taiwan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Former &quot;Account Classification&quot; Field</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <description>Dun and Bradstreet Number</description>
        <inlineHelpText>DUNS # from Hoovers D&amp;B database</inlineHelpText>
        <label>DUNS</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Customer email contact</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Channel__c</fullName>
        <inlineHelpText>The channel type the customer comes through.</inlineHelpText>
        <label>Fulfillment Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>House_Number__c</fullName>
        <inlineHelpText>Part of customer address.</inlineHelpText>
        <label>z_OBSOLETED_House Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <label>Segment Approval Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Automotive &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Computing</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>Energy Management</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Home/Building Automation (HABA)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Secure Identity</fullName>
                </value>
                <value>
                    <fullName>Secure Transactions</fullName>
                </value>
                <value>
                    <fullName>Tagging &amp; Authentication</fullName>
                </value>
                <value>
                    <fullName>Wireless Infrastructure and RF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <inlineHelpText>Customer&apos;s Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NXP_GID__c</fullName>
        <externalId>true</externalId>
        <label>NXP GID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Change the field label fm &quot;Region&quot; to &quot;Account Region&quot; to give more clear info. in reporting</description>
        <inlineHelpText>The geographical region the account belongs to. Determined by country.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Describe the role of account whom NXP sells to</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>IDH</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <inlineHelpText>Customer address - state/province</inlineHelpText>
        <label>State/ Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aceh</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Andaman And Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>An Giang</fullName>
                </value>
                <value>
                    <fullName>Anhui Province</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bac Giang</fullName>
                </value>
                <value>
                    <fullName>Bac Kan</fullName>
                </value>
                <value>
                    <fullName>Bac Lieu</fullName>
                </value>
                <value>
                    <fullName>Bac Ninh</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California S</fullName>
                </value>
                <value>
                    <fullName>Bali</fullName>
                </value>
                <value>
                    <fullName>Banten</fullName>
                </value>
                <value>
                    <fullName>Ba Ria Vung Tau</fullName>
                </value>
                <value>
                    <fullName>Beijing City</fullName>
                </value>
                <value>
                    <fullName>Bengkulu</fullName>
                </value>
                <value>
                    <fullName>Ben Tre</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Binh Dinh</fullName>
                </value>
                <value>
                    <fullName>Binh Duong</fullName>
                </value>
                <value>
                    <fullName>Binh Phuoc</fullName>
                </value>
                <value>
                    <fullName>Binh Thuan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street2__c</fullName>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line 2</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street3__c</fullName>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line 3</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <inlineHelpText>Customer address - postal code</inlineHelpText>
        <label>ZIP / Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Child_Account</fullName>
        <active>true</active>
        <label>Child Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent_Account</fullName>
        <active>true</active>
        <label>Parent Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>PreAccount</fullName>
        <active>true</active>
        <description>New PreAccount  type record would be created when customer record would be flowed from Hub to CRM.</description>
        <label>PreAccount</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pre_Account</fullName>
        <active>true</active>
        <description>This Pre-account is used for account manager to create child account and submit for approval</description>
        <label>Pre-Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PreAccountController_Test.cls
@isTest(SeeAllData=true) 
private class PreAccountController_Test 
{
    private static final string PRE_ACCOUNT = 'PreAccount';
    private static final string PARENT_ACCOUNT = 'Parent_Account';
    private static final string CHILD_ACCOUNT = 'Child Account';

    private static RecordType preAccountRecordType;
    private static RecordType parentAccountRecordType;
    private static RecordType childAccountRecordType;

	private static void fetchPreAccountRecordType()
	{
	    for( RecordType rt : [	SELECT Id, DeveloperName
								FROM RecordType
	                           	WHERE SobjectType = 'Account' 
	                           	AND DeveloperName = :PRE_ACCOUNT 
	                           	AND IsActive = TRUE
	                           	LIMIT 1
	                        ])
	    {
	        preAccountRecordType = rt;
	    }		
	}

	private static void fetchParentAccountRecordType()
	{
	    for( RecordType rt : [	SELECT Id, DeveloperName
								FROM RecordType
	                           	WHERE SobjectType = 'Account' 
	                           	AND DeveloperName = :PARENT_ACCOUNT 
	                           	AND IsActive = TRUE
	                           	LIMIT 1
	                        ])
	    {
	        parentAccountRecordType = rt;
	    }		
	}

	private static void fetchChildAccountRecordType()
	{
	    for( RecordType rt : [	SELECT Id, DeveloperName
								FROM RecordType
	                           	WHERE SobjectType = 'Account' 
	                           	AND DeveloperName = :CHILD_ACCOUNT 
	                           	AND IsActive = TRUE
	                           	LIMIT 1
	                        ])
	    {
	        childAccountRecordType = rt;
	    }		
	}

    User testUser = new User(	FirstName = 'Test' ,
            					LastName = 'User' ,
            					Username = 'test@test.com' ,
            					Email = 'test@test.com'
        					);

    static testMethod void preAccountToParentTest()
    {
    	fetchPreAccountRecordType();
    	fetchParentAccountRecordType();
    	
        Account testAccount = new Account(	RecordTypeId = preAccountRecordType.Id ,
            								NXP_GID__c = '88888888' ,
     										Name = 'TEST ACCOUNT' ,
     										Legal_Name__c = 'TEST LEGAL NAME' ,
            								DUNS_Number__c = '1234567890' ,
            								House_Number__c = 'HOUSE123' ,
            								Street__c = 'TEST STREET 1',
            								Street2__c = 'TEST STREET 2',
            								Street3__c = 'TEST STREET 3',
            								City__c = 'TEST CITY' ,
            								State_Province__c = 'TEST STATE',
            								ZIP_Postal_Code__c = 'ZIP',
            								Country__c = 'Taiwan',
								            Website = 'www.web.com',
            								Email__c = 'email@email.com',
            								Phone = '+1234567890',
            								Fax = '+1234567890',
            								Region__c = 'Greater China',
            								Fulfillment_Channel__c = 'Direct' ,
            								Customer_Category__c = 'Focused' ,
            								Role__c = 'OEM' ,
            								Type = 'Customer' ,
            								Industry_Segment__c = 'Appliances',
            								Sub_Segment__c = 'Major Home Appliances',
            								SIC_Code__c = '1234 - SIC TEST',
            								NAICS_Code__c = '123 - NAICS TEST'         		
        								);
        insert testAccount;
        
        preAccountController testController = new preAccountController( testAccount ); 
        testController.makeParentAccount();
    }

    static testMethod void preAccountToChildTest()
    {
    	fetchPreAccountRecordType();
    	fetchParentAccountRecordType();
    	
        Account testAccount = new Account(	RecordTypeId = preAccountRecordType.Id ,
            								NXP_GID__c = '88888888' ,
     										Name = 'TEST ACCOUNT' ,
     										Legal_Name__c = 'TEST LEGAL NAME' ,
            								DUNS_Number__c = '1234567890' ,
            								House_Number__c = 'HOUSE123' ,
            								Street__c = 'TEST STREET 1',
            								Street2__c = 'TEST STREET 2',
            								Street3__c = 'TEST STREET 3',
            								City__c = 'TEST CITY' ,
            								State_Province__c = 'TEST STATE',
            								ZIP_Postal_Code__c = 'ZIP',
            								Country__c = 'Taiwan',
								            Website = 'www.web.com',
            								Email__c = 'email@email.com',
            								Phone = '+1234567890',
            								Fax = '+1234567890',
            								Region__c = 'Greater China',
            								Fulfillment_Channel__c = 'Direct' ,
            								Customer_Category__c = 'Focused' ,
            								Role__c = 'OEM' ,
            								Type = 'Customer' ,
            								Industry_Segment__c = 'Appliances',
            								Sub_Segment__c = 'Major Home Appliances',
            								SIC_Code__c = '1234 - SIC TEST',
            								NAICS_Code__c = '123 - NAICS TEST'         		
        								);
        insert testAccount;
        
        preAccountController testController = new preAccountController( testAccount ); 
        testController.makeChildAccount();
    }

    static testMethod void preAccountToComboTest()
    {
    	fetchPreAccountRecordType();
    	fetchParentAccountRecordType();
    	
        Account testAccount = new Account(	RecordTypeId = preAccountRecordType.Id ,
            								NXP_GID__c = '88888888' ,
     										Name = 'TEST ACCOUNT' ,
     										Legal_Name__c = 'TEST LEGAL NAME' ,
            								DUNS_Number__c = '1234567890' ,
            								House_Number__c = 'HOUSE123' ,
            								Street__c = 'TEST STREET 1',
            								Street2__c = 'TEST STREET 2',
            								Street3__c = 'TEST STREET 3',
            								City__c = 'TEST CITY' ,
            								State_Province__c = 'TEST STATE',
            								ZIP_Postal_Code__c = 'ZIP',
            								Country__c = 'Taiwan',
								            Website = 'www.web.com',
            								Email__c = 'email@email.com',
            								Phone = '+1234567890',
            								Fax = '+1234567890',
            								Region__c = 'Greater China',
            								Fulfillment_Channel__c = 'Direct' ,
            								Customer_Category__c = 'Focused' ,
            								Role__c = 'OEM' ,
            								Type = 'Customer' ,
            								Industry_Segment__c = 'Appliances',
            								Sub_Segment__c = 'Major Home Appliances',
            								SIC_Code__c = '1234 - SIC TEST',
            								NAICS_Code__c = '123 - NAICS TEST'         		
        								);
        insert testAccount;
        
        preAccountController testController = new preAccountController( testAccount ); 
        testController.makeAccountCombo();
    }
}