src/objects/Answer_Like__c.object
<CustomObject>
    <description>New object to store answer likes.</description>
    <fields>
        <fullName>ReplyId__c</fullName>
        <description>Master detail to reply object.</description>
        <label>Reply</label>
        <referenceTo>Reply</referenceTo>
        <relationshipLabel>Answer Like</relationshipLabel>
        <relationshipName>Answer_Like</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Like</label>
    <nameField>
        <label>Answer Like Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Like</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CommunitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Consists of Community related URLS</description>
    <fields>
        <fullName>Answer_Like__c</fullName>
        <description>The points for answer like.</description>
        <label>Answer Like</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_BestReply__c</fullName>
        <description>The points For question best Reply</description>
        <label>Question BestReply</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CommunitySettings</label>
</CustomObject>

src/classes/CommunityReply_AfterupdateTest.cls
/***************************************************************************************************************************************************************************************************************** 
@Created By :       Avichal Kumar
@Created Date:      7th August  2015
@Description:       Test class for  CommunityReply_AfterUpdate trigger
******************************************************************************************************************************************************************************************************************/
@isTest
private class CommunityReply_AfterupdateTest {
   private Static question createQuestions()
    {
        Question objQue=new Question();
        objQue.title='testing1';
        objQue.body='testing1';
        return objQue;
    } 
    
    private Static Reply createAnswers()
    {
        Reply objRep=new Reply();
        objRep.body='testing';
        return objRep;
    }
    
    //Answer Likes
    static testmethod void CommunityReply_AfterupdateTest1 ()
        
    {
        CommunitySettings__c setting = new CommunitySettings__c();
        setting.Name = 'CommunityUrl';
        setting.Question_BestReply__c= 20;
        insert setting;
        system.assert(setting.Id!=null);
        
        Community objCom= [SELECT Id FROM Community WHERE Name = 'NXP Community'];
        Test.startTest();
         
        Question objQue1=new Question();
        objQue1=createQuestions();
        objQue1.CommunityId=objCom.id;
        
        objQue1.Product_Category__c='Automotive';
        insert objQue1;
        
        Reply objRep= new Reply();
        objRep=createAnswers();
        objRep.QuestionId=objQue1.id;
        insert objRep; 
        
        Answer_like__c objAnswerlike = new Answer_like__c();
        objAnswerlike.ReplyID__c=objRep.id;
        insert objAnswerlike;
        
        update objRep;
        
        Test.stopTest();
    }
}