src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Approver_Table__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc Approver</fullName>
                </value>
                <value>
                    <fullName>BL Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>BU / BL (Marketing) Manager</fullName>
                </value>
                <value>
                    <fullName>BU / BL Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>BU Controller</fullName>
                </value>
                <value>
                    <fullName>BU GM</fullName>
                </value>
                <value>
                    <fullName>BU Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>BU Quality Manager</fullName>
                </value>
                <value>
                    <fullName>BU SCM Manager</fullName>
                </value>
                <value>
                    <fullName>Channel Controller</fullName>
                </value>
                <value>
                    <fullName>Chief Purchasing Officer</fullName>
                </value>
                <value>
                    <fullName>Corporate Control</fullName>
                </value>
                <value>
                    <fullName>CTC</fullName>
                </value>
                <value>
                    <fullName>Customer Program Manager</fullName>
                </value>
                <value>
                    <fullName>Director Marketing</fullName>
                </value>
                <value>
                    <fullName>EM Controller</fullName>
                </value>
                <value>
                    <fullName>EMS Head</fullName>
                </value>
                <value>
                    <fullName>EM SVP</fullName>
                </value>
                <value>
                    <fullName>Global Sales &amp; Ops Manager</fullName>
                </value>
                <value>
                    <fullName>Global Pricing</fullName>
                </value>
                <value>
                    <fullName>GSM Controller</fullName>
                </value>
                <value>
                    <fullName>GSM Credit Control Manager</fullName>
                </value>
                <value>
                    <fullName>GSM Functional</fullName>
                </value>
                <value>
                    <fullName>GSM Global Disti GM</fullName>
                </value>
                <value>
                    <fullName>GSM Head</fullName>
                </value>
                <value>
                    <fullName>GSM Process &amp; Operations Manager</fullName>
                </value>
                <value>
                    <fullName>Head of General Purchasing</fullName>
                </value>
                <value>
                    <fullName>Head of Outsourcing</fullName>
                </value>
                <value>
                    <fullName>Head of Sourcing</fullName>
                </value>
                <value>
                    <fullName>IP Department</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsNER__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Apttus_Approver_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Apttus Approver Table</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apttus Approver Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rebate_Approver_Matrix__c.object
<CustomObject>
    <description>This object will keep track of Approvers for Rebate records.</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rebate_Approver_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apttus Aggrement Checker</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Corporate Control</fullName>
                </value>
                <value>
                    <fullName>Regional Controller</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Controller</fullName>
                </value>
                <value>
                    <fullName>Global Channel Controller</fullName>
                </value>
                <value>
                    <fullName>BL Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Sales Manager</fullName>
                </value>
                <value>
                    <fullName>GSM Controller</fullName>
                </value>
                <value>
                    <fullName>Global Sales &amp; OPS Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Disti Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rebate Approver Matrix</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Rebate Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Approver Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FindApprover.cls
/******************************************************************************
@Created By :    Scarlett Kang   
@Created Date:   June 9, 2014
@Description:    Help system admin to find approver and mark   
********************************************************************************/

global with sharing class FindApprover implements Database.Batchable<sObject> {
    public String query = 'SELECT Id, Name, Approver__c, Opportunity_Approver__c, Rebate_Approver__c, Apttus_Approver__c, SAP_CMD_Approver__c  FROM User ' + 
        				  'WHERE IsActive = TRUE AND ' +
        				  '(Profile.Name != \'Customer Portal Manager Standard\' AND ' + 
        				  'Profile.Name != \'NXP Community Profile\' AND ' + 
        				  'Profile.Name != \'Customer Community Login User\' AND ' + 
        				  'Profile.Name != \'Partner Community User\' AND ' + 
        				  'Profile.Name != \'NXP Customer Community Login User\' AND ' + 
        				  'Profile.Name != \'Overage High Volume Customer Portal User\' AND ' + 
        				  'Profile.Name != \'Community Profile\' AND ' + 
        				  'Profile.Name != \'NXP - Overage High Volume Customer Portal User\' AND ' + 
        				  'Profile.Name != \'NXP - Customer Portal Debugging Profile\' AND ' + 
        				  'Profile.Name != \'Gold Partner User\' AND ' + 
        				  'Profile.Name != \'NXP Partner User\' AND ' + 
        				  'Profile.Name != \'Partner Community User\' AND Profile.Name != \'NXP Partner User - EMEA\') ';
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
         return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, list<sObject> scope) { 
        List<User> users = (list<User>)scope;
        
        //Apporver Matrix used by opportunity
        List<Approvers_Matrix__c> approverM = [
            SELECT Type__c, Approver__c FROM Approvers_Matrix__c
        ];     

        //Apttus Approver Table
        List<Apttus_Approver_Table__c> approverT = [
            SELECT Id, User__c, Role__c FROM Apttus_Approver_Table__c
        ];
        //Rebate Approver Matrix
        List<Rebate_Approver_Matrix__c> approverR = [
            SELECT Id, Approver__c, Role__c FROM Rebate_Approver_Matrix__c
        ];

        Map<Id, Group> groupMap = new Map<Id, Group>([
            SELECT Id, Name
            FROM Group
            WHERE TYPE = 'Queue' AND Name LIKE '%SAP CMD%' 
        ]);
        
        List<GroupMember> groupMembers = [
            SELECT GroupId, Id, UserOrGroupId FROM GroupMember
            WHERE GroupId In : groupMap.KeySet()
        ];
        
        Set<Id> userOrGroupIds = new Set<Id>();
        for(GroupMember member : groupMembers){
            userOrGroupIds.add(member.UserOrGroupId);
        }
        
        Map<Id, User> userMap = new Map<Id, User>([
            SELECT Id, Name
            From User
            WHERE Id In :UserOrGroupIds
        ]);
        
        //Added by Scarlett on Sep 1, 2015
        //CRM CMD user group
        Map<Id, Group> groupCRMCMDMap = new Map<Id, Group>([
            SELECT Id, Name
            FROM Group
            WHERE TYPE = 'Queue' AND Name LIKE '%CRM CMD%' 
        ]);

		 List<GroupMember> groupCRMCMDMembers = [
            SELECT GroupId, Id, UserOrGroupId FROM GroupMember
            WHERE GroupId In : groupCRMCMDMap.KeySet()
        ];
        
        Set<Id> userOrGroupCRMCMDIds = new Set<Id>();
        for(GroupMember member : groupCRMCMDMembers){
            userOrGroupCRMCMDIds.add(member.UserOrGroupId);
        }
        
        Map<Id, User> userCRMCMDMap = new Map<Id, User>([
            SELECT Id, Name
            From User
            WHERE Id In :userOrGroupCRMCMDIds
        ]);
        //End --- Added by Scarlett on Sep 1, 2015
        
        for(Integer i = 0 ; i < users.size() ; i++){
            users[i].Approver__c = false;
            users[i].Opportunity_Approver__c = false;
            users[i].Rebate_Approver__c = false;
            users[i].Apttus_Approver__c = false;
            users[i].SAP_CMD_Approver__c = false;
            users[i].CRM_CMD_Approver__c = false;
        }
       
        for(Integer i = 0 ; i < users.size() ; i++){                   
            //Apporver Matrix
            for(Approvers_Matrix__c m : approverM){
                if(users[i].Id == String.valueOf(m.Approver__c)){
                    users[i].Approver__c = true;
                    users[i].Opportunity_Approver__c = true;
                }
            }

            //Apttus Approver Table
            for(Apttus_Approver_Table__c t : approverT){
                if(users[i].Id == String.valueOf(t.User__c)){
                    users[i].Approver__c = true;
                    users[i].Apttus_Approver__c = true;
                }
            }

            //Rebate Approver Matrix
            for(Rebate_Approver_Matrix__c r : approverR){
                if(users[i].Id == String.valueOf(r.Approver__c)){
                    users[i].Approver__c = true;
                    users[i].Rebate_Approver__c = true;
                }
            }
            
            //SAP CMD Queues    
            if(userMap.containsKey(users[i].Id)){
                users[i].Approver__c = true;
                users[i].SAP_CMD_Approver__c =true;
            }

            /***Modified by Scarlett on Sep 1***/
            /***Retrive CRM CMD Approvers from queues***/
            //CRM CMD Queues
            if(userCRMCMDMap.containsKey(users[i].Id)){
                users[i].Approver__c = true;
                users[i].CRM_CMD_Approver__c =true;
            }
            
        }
        update users;

    }
    global void finish(Database.BatchableContext BC) {
    }
}