src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria_1__c</fullName>
        <label>Criteria 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_2__c</fullName>
        <description>This field is to capture the region when approver type is sales director</description>
        <label>Criteria 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Former_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Former Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Region__c</fullName>
        <formula>TEXT(Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BL_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate Bl approver</description>
        <label>BL Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGaS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGac</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGaT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGar</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGb1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Process__c</fullName>
        <label>Design Win Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MAG_Approver_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFyk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFyu</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFz9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Account_Segment_Approval__c</fullName>
        <formula>Account.Parent.Segment_Approval__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account Segment Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Regional_VP_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFJpr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Director_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Sales Director approver for opportunity</description>
        <label>Sales Director Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesF8rX</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Approver_Matrix_Extension_Controller.cls
/****************************************************************************************************************
@Created By :   Scarlett Kang
@Created Date:  May 22, 2015
@Description:   Replace button on Approver Matrix to update opportunities when system admin change approver
******************************************************************************************************************/
/**********************
@ Updated By: Scarlett Kang
@ Update Date: 1506 Release
@ Description: Changed to Batch 
*******************************************
@ Updated By: Jewelslyn
@ Update Date: 1605 Release
@ Description: added new approver fields and removed old approver fields as part DW approval revision
*******************************************/
public with sharing class Approver_Matrix_Extension_Controller {
    private Approvers_Matrix__c ApproverM;
    public List<Opportunity> lstAffectedOpps;
    
    public Approver_Matrix_Extension_Controller( ApexPages.StandardController stdController ) {
        
        this.ApproverM = (Approvers_Matrix__c)stdController.getRecord();
        
        ApproverM = [
            SELECT  Id,
                    Approver__c,
                    Former_Approver__c,
                    criteria_2__c,
                    Type__c,
                    Criteria_1__c
            FROM    Approvers_Matrix__c
            WHERE   Id = :ApproverM.Id
        ];
    }
    
    public pageReference Approvers() {

        lstAffectedOpps = [
            SELECT  Id,
                    Account_Region__c,
                    Parent_Account_Segment_Approval__c
            FROM    Opportunity
            WHERE   (                    
                    BL_Approver_1__c=:ApproverM.Former_Approver__c
                    OR BL_Approver_2__c=:ApproverM.Former_Approver__c
                    OR BL_Approver_3__c=:ApproverM.Former_Approver__c
                    OR BL_Approver_4__c=:ApproverM.Former_Approver__c
                    OR BL_Approver_5__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_1__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_2__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_3__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_4__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_5__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_6__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_7__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_8__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_9__c=:ApproverM.Former_Approver__c
                    OR MAG_Approver_10__c=:ApproverM.Former_Approver__c
                    OR Sales_Director_Approver__c=:ApproverM.Former_Approver__c
                    OR Regional_VP_Approver__c=:ApproverM.Former_Approver__c 
                    ) 
                    AND 
                    (Design_Win_Approval_Process__c = 'Pending'
                    OR Design_Win_Approval_Process__c = 'Open')
        ];
         

        
        //update opportunity by batch job
        
        UpdateOpportunityBatch updateOpps = new UpdateOpportunityBatch();
        updateOpps.ApproverId = string.valueof(ApproverM.Former_Approver__c);
        ID batchprocessid = Database.executeBatch(updateOpps, 50);
        
        
                
        PageReference Approver_Matrix_Page = new PageReference('/' + ApproverM.Id);
        Approver_Matrix_Page.setRedirect(true);
        return Approver_Matrix_Page;
    }
}