src/objects/Approver_History__c.object
<CustomObject>
    <description>Used for approver performance management
Collect records from two objects: ProcessInstanceStep and ProcessInstanceWorkItem</description>
    <fields>
        <fullName>Actor_Username__c</fullName>
        <description>Username of User who approved or submitted a approval</description>
        <label>Actor Username</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Actual_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actual Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approver_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Name__c</fullName>
        <label>Approval Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Action_Date__c</fullName>
        <label>Approver Action Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Approver Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_ID__c</fullName>
        <label>Target Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Temp Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Approver History</label>
    <nameField>
        <label>Approver History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approver History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RemoveExistingApproverHistoryTest.cls
@isTest
public class RemoveExistingApproverHistoryTest{
    static testMethod void theTest(){     
        Test.StartTest();
        Approver_History__c AH = new Approver_History__c
        (
            //Target_Object_ID__c = PISi.ProcessInstance.TargetObjectId,
            //Object_URL_2__c = system.URL.getSalesforceBaseUrl().toExternalForm() + '/' + PISi.ProcessInstance.TargetObjectId,
            //Is_Workitem__c = false,
            //Approval_Status__c = PISi.ProcessInstance.Status,
            //Actor_Username__c = PISi.Actor.Username,
            //Actual_Approver__c = PISi.Actor.Id,
            //Approver_Action_Date__c = PISi.CreatedDate,
            Comments__c = 'NULL',
            Approval_Name__c = 'Test delete',
            Status__c = 'Approved Test',
            Temp_Record__c = false
        );
        insert AH;
        
        RemoveExistingApproverHistory RemoveEAH = new RemoveExistingApproverHistory();
        Database.executeBatch(RemoveEAH);
        Test.StopTest();
        
        Integer i = [SELECT COUNT() FROM Approver_History__c];
        System.assertEquals(i, 1);
    }   
}