src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria_2__c</fullName>
        <description>This field is to capture the region when approver type is sales director</description>
        <label>Criteria 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_1__c</fullName>
        <label>Threshold 1</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Approver_Table__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc Approver</fullName>
                </value>
                <value>
                    <fullName>BL Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>BU / BL (Marketing) Manager</fullName>
                </value>
                <value>
                    <fullName>BU / BL Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>BU Controller</fullName>
                </value>
                <value>
                    <fullName>BU GM</fullName>
                </value>
                <value>
                    <fullName>BU Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>BU Quality Manager</fullName>
                </value>
                <value>
                    <fullName>BU SCM Manager</fullName>
                </value>
                <value>
                    <fullName>Channel Controller</fullName>
                </value>
                <value>
                    <fullName>Chief Purchasing Officer</fullName>
                </value>
                <value>
                    <fullName>Corporate Control</fullName>
                </value>
                <value>
                    <fullName>CTC</fullName>
                </value>
                <value>
                    <fullName>Customer Program Manager</fullName>
                </value>
                <value>
                    <fullName>Director Marketing</fullName>
                </value>
                <value>
                    <fullName>EM Controller</fullName>
                </value>
                <value>
                    <fullName>EMS Head</fullName>
                </value>
                <value>
                    <fullName>EM SVP</fullName>
                </value>
                <value>
                    <fullName>Global Sales &amp; Ops Manager</fullName>
                </value>
                <value>
                    <fullName>Global Pricing</fullName>
                </value>
                <value>
                    <fullName>GSM Controller</fullName>
                </value>
                <value>
                    <fullName>GSM Credit Control Manager</fullName>
                </value>
                <value>
                    <fullName>GSM Functional</fullName>
                </value>
                <value>
                    <fullName>GSM Global Disti GM</fullName>
                </value>
                <value>
                    <fullName>GSM Head</fullName>
                </value>
                <value>
                    <fullName>GSM Process &amp; Operations Manager</fullName>
                </value>
                <value>
                    <fullName>Head of General Purchasing</fullName>
                </value>
                <value>
                    <fullName>Head of Outsourcing</fullName>
                </value>
                <value>
                    <fullName>Head of Sourcing</fullName>
                </value>
                <value>
                    <fullName>IP Department</fullName>
                </value>
                <value>
                    <fullName>Management Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsNER__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Apttus_Approver_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Apttus Approver Table</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apttus Approver Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rebate_Approver_Matrix__c.object
<CustomObject>
    <description>This object will keep track of Approvers for Rebate records.</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rebate_Approver_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apttus Aggrement Checker</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Corporate Control</fullName>
                </value>
                <value>
                    <fullName>Regional Controller</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Controller</fullName>
                </value>
                <value>
                    <fullName>Global Channel Controller</fullName>
                </value>
                <value>
                    <fullName>BL Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Sales Manager</fullName>
                </value>
                <value>
                    <fullName>GSM Controller</fullName>
                </value>
                <value>
                    <fullName>Global Sales &amp; OPS Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Disti Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rebate Approver Matrix</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Rebate Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Approver Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FindApproverTest.cls
@isTest
private class FindApproverTest{
    private static final String TEST_USER_PROFILE = 'Standard User';
    private static integer USER_NUM = 10;
    private static String CRM_CMD_APPROVER_GROUP = 'Test CRM CMD Approver';
    private static String SAP_CMD_APPROVER_GROUP = 'Test SAP CMD Approver';
    
	@testSetup
    static void setup(){
        List<User> testUsers = new List<User>();
        List<Approvers_Matrix__c> approverMatrixes = new List<Approvers_Matrix__c>();
        
        Profile p = [SELECT Id FROM Profile WHERE Name =: TEST_USER_PROFILE];
        
        // Inser Users
        for (Integer i = 0; i < USER_NUM ; i++) {
            User u = new User(
                Alias = 'test' + (i+1),
                Email = 'test.user' + (i+1) + '@testorg.com.test',
                EmailEncodingKey = 'UTF-8', 
                LastName = 'Testing', 
                LanguageLocaleKey = 'en_US', 
                LocaleSidKey = 'en_US', 
                TimeZoneSidKey = 'America/Los_Angeles',
                ProfileId = p.Id, 
                UserName = 'test.user' + (i+1) + '@testorg.com.test',
                IsActive = True
            );
            testUsers.add(u);
        }
        insert testUsers;
        
        // Insert Approver Matrxi
        Approvers_Matrix__c salesDirector = new Approvers_Matrix__c(
            Approver__c = testUsers[0].Id,
            Type__c = 'Sales Director Approver',
            Criteria_2__c = 'Greater China',
            Threshold_1__c = 0
        );
        insert salesDirector;
        
        Approvers_Matrix__c RVP = new Approvers_Matrix__c(
            Approver__c = testUsers[1].Id,
            Type__c = 'Regional VP Approver',
            Criteria_2__c = 'Greater China',
            Threshold_1__c = 0
        );
        insert RVP;
        
        // Insert Apttus Approver Table
        Apttus_Approver_Table__c apptusApproverTable = new Apttus_Approver_Table__c(
            User__c = testUsers[2].Id,
            Role__c = 'Management Team'
        );
        insert apptusApproverTable;
        
        // Insert Rebate Approver Table
        Rebate_Approver_Matrix__c rebateApproverMatrix = new Rebate_Approver_Matrix__c(
            Approver__c = testUsers[3].Id,
            Role__c = 'BL Marketing Manager',
            MAG__c = 'R01',
            Region__c = 'AMEC'
        );
        insert rebateApproverMatrix;
        
        // Insert Approver Group
        Group groupSAPCMDApprover = new Group(
            Name = SAP_CMD_APPROVER_GROUP,
            Type = 'Queue'
        );
        insert groupSAPCMDApprover;
        
        Group groupCRMCMDApprover = new Group(
            Name = CRM_CMD_APPROVER_GROUP,
            Type = 'Queue'
        );
        insert groupCRMCMDApprover;
    }
    
    @isTest
    static void testFindApprover(){        
        List<QueuesObject> queues = new List<QueuesObject>();
        List<GroupMember> members = new List<GroupMember>();
        List<Group> approverGroups = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND (Name = :CRM_CMD_APPROVER_GROUP OR Name = :SAP_CMD_APPROVER_GROUP)];
        User testUser = [SELECT Id FROM User WHERE Profile.Name = :TEST_USER_PROFILE LIMIT 1];
        
        for (Group g : approverGroups) {
            QueuesObject q = new QueuesObject(
                Queueid = g.Id, 
                SobjectType='CMD_Request__c'
            );
            queues.add(q);
            
            GroupMember gm = new GroupMember( 
                GroupId = g.Id, UserOrGroupId = testUser.Id
            ); 
            members.add(gm);
        }
        insert queues;
        insert members;
        
        Test.startTest();
        FindApprover testApprover = new FindApprover();
        testApprover.query = testApprover.query + ' AND Profile.Name = \'Standard User\' LIMIT 800';
        Database.executeBatch(testApprover, 800); 
        Test.stopTest();
    }
}