src/objects/Approvers_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_1__c</fullName>
        <label>Criteria 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_2__c</fullName>
        <description>This field is to capture the region when approver type is sales director</description>
        <label>Criteria 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MAG Approver</fullName>
                </value>
                <value>
                    <fullName>BL Approver</fullName>
                </value>
                <value>
                    <fullName>GAM</fullName>
                </value>
                <value>
                    <fullName>EVP</fullName>
                </value>
                <value>
                    <fullName>Segment VP</fullName>
                </value>
                <value>
                    <fullName>GSM Sales Director</fullName>
                </value>
                <value>
                    <fullName>GSM VP 1</fullName>
                </value>
                <value>
                    <fullName>GSM VP 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver Matrix</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Approver Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <recordTypes>
        <fullName>Direct_Oppty</fullName>
        <active>true</active>
        <label>Direct Oppty</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApproverMatrixHelper.cls
public class ApproverMatrixHelper {
	
	private static final String DIRECT_OPPTY_TYPE_MAG_APPROVER = 'MAG Approver';
	private static final String DIRECT_OPPTY_TYPE_BL_APPROVER = 'BL Approver';
	private static final String DIRECT_OPPTY_TYPE_GAM = 'GAM';
	private static final String DIRECT_OPPTY_TYPE_EVP = 'EVP';
	private static final String DIRECT_OPPTY_TYPE_SEGMENT_VP = 'Segment VP';
	private static final String DIRECT_OPPTY_TYPE_GSM_SALES_DIRECTOR = 'GSM Sales Director';
	private static final String DIRECT_OPPTY_TYPE_GSM_VP_1 = 'GSM VP 1';
	private static final String DIRECT_OPPTY_TYPE_GSM_VP_2 = 'GSM VP 2';
	// Account constants
	private static final String PARENT_ACCOUNT_STAR = 'STAR';
	private static final String PARENT_ACCOUNT_SAMSUNG = 'Samsung';
	private static final String CBG_AUTOMOTIVE = 'Automotive';
	private static final String REGION_GC = 'Greater China';
	private static final String REGION_SAP = 'South Asia Pacific';
	
	private static Map<Id, Approvers_Matrix__c> directOpptyApproverMatrixes;  
	
	static{
		directOpptyApproverMatrixes = getDirectOpptyApproverMatrixes(); 
	}
	
	public static Map<Id, Approvers_Matrix__c> getDirectOpptyApproverMatrixes() {
    	if (directOpptyApproverMatrixes == null) {
    		setDirectOpptyApproverMatrixes();	
    	}
    	
    	return directOpptyApproverMatrixes;
    }
    
    private static void setDirectOpptyApproverMatrixes() {
    	directOpptyApproverMatrixes = new Map<Id, Approvers_Matrix__c>(
    		new ApproverMatrixesSelector().selectByRecordTypeId(new Set<Id>{new ApproverMatrixesSelector().getRecordTypeId(ApproverMatrixesSelector.RecordType.DIRECT_OPPTY)})
    	);
	}
    
    public static Approvers_Matrix__c getDirectOpptyGamStar() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GAM && am.Criteria_1__c == PARENT_ACCOUNT_STAR) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptyGamSamsung() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GAM && am.Criteria_1__c == PARENT_ACCOUNT_SAMSUNG) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptyGamGeneral(Id accountId) {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GAM && am.Account__c == accountId) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptyEvpStar() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_EVP && am.Criteria_1__c == PARENT_ACCOUNT_STAR) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptyEvpSamsung() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_EVP && am.Criteria_1__c == PARENT_ACCOUNT_SAMSUNG) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptySegmentVpAuto() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_SEGMENT_VP && am.Criteria_1__c == CBG_AUTOMOTIVE) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptyGsmSalesDirector() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GSM_SALES_DIRECTOR) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    }
    
    public static Approvers_Matrix__c getDirectOpptyGsmVp1() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GSM_VP_1) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;	
    }
    
    public static Approvers_Matrix__c getDirectOpptyGsmVp2AutoGc() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GSM_VP_2 && am.Criteria_1__c == CBG_AUTOMOTIVE && am.Criteria_2__c == REGION_GC) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    } 
    
    public static Approvers_Matrix__c getDirectOpptyGsmVp2AutoSap() {
    	Approvers_Matrix__c result;
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_GSM_VP_2 && am.Criteria_1__c == CBG_AUTOMOTIVE && am.Criteria_2__c == REGION_SAP) {
    			result = am;
    			break;	
    		}
    	}	
    	
    	return result;
    } 
    
    public static List<Approvers_Matrix__c> getDirectOpptyMagApprovers(Set<String> mags) {
    	List<Approvers_Matrix__c> result = new List<Approvers_Matrix__c>();
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_MAG_APPROVER && mags.contains(am.Criteria_1__c) && am.Criteria_2__c == null) {
    			result.add(am);
    		}
    	}	
    	
    	return result;		
    }
    
    public static List<Approvers_Matrix__c> getDirectOpptyMagApproversStar(Set<String> mags) {
    	List<Approvers_Matrix__c> result = new List<Approvers_Matrix__c>();
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_MAG_APPROVER && mags.contains(am.Criteria_1__c) && am.Criteria_2__c == PARENT_ACCOUNT_STAR) {
    			result.add(am);
    		}
    	}	
    	
    	return result;		
    }
    
    public static List<Approvers_Matrix__c> getDirectOpptyBlApprovers(Set<String> bls) {
    	List<Approvers_Matrix__c> result = new List<Approvers_Matrix__c>();
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_BL_APPROVER && bls.contains(am.Criteria_1__c) && am.Criteria_2__c == null) {
    			result.add(am);
    		}
    	}	
    	
    	return result;		
    }
    
    public static List<Approvers_Matrix__c> getDirectOpptyBlApproversStar(Set<String> bls) {
    	List<Approvers_Matrix__c> result = new List<Approvers_Matrix__c>();
    	
    	for (Approvers_Matrix__c am : directOpptyApproverMatrixes.values()) {
    		if (am.Type__c == DIRECT_OPPTY_TYPE_BL_APPROVER && bls.contains(am.Criteria_1__c) && am.Criteria_2__c == PARENT_ACCOUNT_STAR) {
    			result.add(am);
    		}
    	}	
    	
    	return result;		
    }
    
}