src/objects/Approver_History__c.object
<CustomObject>
    <description>Used for approver performance management
Collect records from two objects: ProcessInstanceStep and ProcessInstanceWorkItem</description>
    <fields>
        <fullName>Temp_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Temp Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Approver History</label>
    <nameField>
        <label>Approver History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approver History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RemoveExistingApproverHistory.cls
/*
Modified by Scarlett on 2014/01/15
Remove Existing Approver History
*/
global with sharing class RemoveExistingApproverHistory implements Database.batchable<sObject>{ 
//global String query;
//Start
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        return Database.getQueryLocator([SELECT Id FROM Approver_History__c]);
        //return Database.getQueryLocator(query);
    }
//Execute
    global void execute(Database.BatchableContext BC, list<sObject> scope) {
        delete Scope;
    }
//Finish
    global void finish(Database.BatchableContext BC){
        Approver_History__c tempRecord = new Approver_History__c (Temp_Record__c = true);
        insert tempRecord;
        
        CollectProcessInstanceWorkItem  insertWorkitem = new CollectProcessInstanceWorkItem();
        Database.executeBatch(insertWorkitem);
    }
}