src/objects/CMD_Request_SAP_Mass_Update_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>SAP_CMD__r.Account_Name__c</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMD_Request__c</fullName>
        <label>CMD Request</label>
        <referenceTo>CMD_Request__c</referenceTo>
        <relationshipLabel>CMD Request SAP Mass Update Details</relationshipLabel>
        <relationshipName>CMD_Request_SAP_Mass_Update_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City_New__c</fullName>
        <label>City New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_New__c</fullName>
        <label>Country New</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funloc__c</fullName>
        <label>Funloc</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name_New__c</fullName>
        <label>Legal Name New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mass_Update_Type__c</fullName>
        <formula>TEXT(CMD_Request__r.Mass_Update_Type__c)</formula>
        <label>Mass Update Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_2_New__c</fullName>
        <label>Name 2 New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_3_New__c</fullName>
        <label>Name 3 New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_4_New__c</fullName>
        <label>Name 4 New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_CMD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP CMD</label>
        <referenceTo>SAP_CMD__c</referenceTo>
        <relationshipLabel>CMD Request SAP Mass Update Details</relationshipLabel>
        <relationshipName>CMD_Request_SAP_Mass_Update</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Province_New__c</fullName>
        <label>State / Province New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_4_New__c</fullName>
        <label>Street 4 New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_New__c</fullName>
        <label>Street New</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZA_New__c</fullName>
        <label>ZA New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZS_New__c</fullName>
        <label>ZS New</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_New__c</fullName>
        <label>Zip New</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CMD Request SAP Mass Update Detail</label>
    <nameField>
        <displayFormat>CRSMUD{0000000000}</displayFormat>
        <label>CMD Request SAP Mass Update Detail Numbe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CMD Request SAP Mass Update Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Short Name of the Customer</description>
        <inlineHelpText>Short Name of the Customer</inlineHelpText>
        <label>Account Name  ( Short Name )</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <description>Street Line 2</description>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type</description>
        <inlineHelpText>The type of the customer. Default value is set to Customer.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Subcontractor</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Function__c.object
<CustomObject>
    <description>Partner Functions of a Customer</description>
    <fields>
        <fullName>FunLoc__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Functions   ( Relation between a  Customer and a FunLoc )</description>
        <inlineHelpText>Partner Functions   ( Relation between a  Customer and a FunLoc )</inlineHelpText>
        <label>FunLoc</label>
        <referenceTo>FunLoc__c</referenceTo>
        <relationshipLabel>Partner Functions</relationshipLabel>
        <relationshipName>Partner_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Function</label>
    <nameField>
        <displayFormat>PF-{00000000}</displayFormat>
        <label>Partner Function ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Functions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SAP_Customer__c.object
<CustomObject>
    <description>Holds SAP Sold To and Ship information for the Rebate and Channel Map objects.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funloc__c</fullName>
        <description>SAP Funloc Number</description>
        <label>Funloc</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_2__c</fullName>
        <label>Name 2</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_3__c</fullName>
        <label>Name 3</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_4__c</fullName>
        <label>Name 4</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/ Province</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SAP Customer</label>
    <nameField>
        <label>SAP Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SAPCMDMassUpdateController.cls
/*********************************************************************************************************************************************/
// Last Modified by      : shridevi
// Last Modification Date: 27-7-2016
// Description           : Optimised the code as part of SIR 1114-to load less data so that hitting the governer limits(Heap size) can be avoided.
/***************************************************************************************************************** */
/*********************************************************************************************************************************************/
// Last Modified by      : shridevi
// Last Modification Date: 27-7-2016
// Description           : Modified the code as part of SIR 1014-to load ZA Picklist Values which starts with "MX" & "CN" & "US5" & "RO" & "CZ" and to load ZS Picklist Values except the values which starts with "MX" & "CN" & "US5" & "RO" & "CZ"
/***************************************************************************************************************** */
/*********************************************************************************************************************************************/
// Last Modified by      : shridevi
// Last Modification Date: 3-8-2016
// Description           : SIR 215- Enable the Delete Row, Copy row, and Add Row buttons irrespective of status for ZS mass update type on SAPCMDMassUpdate page.
/*********************************************************************************************************************************************/
/*********************************************************************************************************************************************/
// Last Modified by      : shridevi
// Last Modification Date: 21-11-2016
// Description           : SIR 1371- Error in saving funlocs
/*********************************************************************************************************************************************
   Last Modified by      : Baji
   Last Modification Date: Mar 03, 2017
   Description           : SFDC 348 - To fix Apex CPU Time limit Exceeded error   
**********************************************************************************************/

public class SAPCMDMassUpdateController {
    
    //private static final String CMD_REQUEST_SAP_MASS_UPDATE_RECORD_TYPE_ID = '012D0000000QmBTIA0';
        
    private final CMD_Request__c theRequest;
    private static final Set<String> statusSet=new Set<String>{'Draft','Ready to Submit','Pending for Approval'};
    private static final List<String> headerZa=new List<String>{'Customer FunLoc Number','SAP CMD','Legal Name','Person Name old','Person Name'};
    private static final List<String> headerZs=new List<String>{'Customer FunLoc Number','SAP CMD','Legal Name','Person Name old','Person Name'};
    private static final List<String> headerAddress=new List<String>{'Customer FunLoc Number','SAP CMD','Legal Name','Name 2','Name 3','Name 4','Street','City','State','Country','Zip'};
                    
    private static final String MASSUPDATETYPE_ZA='ZA';
    private static final String MASSUPDATETYPE_ZS='ZS';
    private static final String MASSUPDATETYPE_ADDRESS='Address';
    private static final Integer COLUMN_SIZE_ZA=5;
    private static final Integer COLUMN_SIZE_ZA_TWO=2;
    private static final Integer COLUMN_SIZE_ZS=5;
    private static final Integer COLUMN_SIZE_ZS_TWO=2;
    private static final Integer COLUMN_SIZE_ADDRESS=12;
    private static final String COLUMN_EXCEEDED_ZA='Number of column exceded in csv file Please mention only 5 columns in csv file';
    private static final String COLUMN_EXCEEDED_ZS='Number of column exceded in csv file Please mention only 5 columns in csv file';
    private static final String COLUMN_EXCEEDED_ADDRESS='Number of column exceded in csv file Please mention only 12 columns in csv file';
    private static final String COLUMN_ORDER_ZA='Order of column or Header name of column is not as per template in csv file Please refer template';
    private static final String COLUMN_ORDER_ZS='Order of column or Header name of column is not as per template in csv file Please refer template';
    private static final String COLUMN_ORDER_ADDRESS='Order of column or Header name of column is not as per template in csv file Please refer template';
   
   // pulbic Map<id,Customer__c> mapCustomers=new map<id,Customer__c>();
    public integer count{get;set;}
    public ApexPages.StandardController stdController1 { get; set; }
    public boolean refreshPage{get;set;}
    public boolean blEnableEdit{get; set;}
    public List<FunlocWrapper> listFunlocWrapper { get; set; }
    public Boolean showTextbox { get; set; }
    public static String massUpdateType { get; set; }
    public String RequestStatus { get;set; }
    public Boolean ticketOpen { get;set; }
    public String rowToBeRemoved { get; set; }
    public String rowToBeReplicated { get; set; }
    public String columnToBeReplicated { get; set; }
    public List<String> ZAList { get; set; }
    public List<String> ZSList { get; set; }
    public static Blob contentFile { get; set; }
    public static String fileString { get; set; }
    public static String nameFile { get; set; }
    public List<ProcessInstance> processInstance=new  List<ProcessInstance>();
    public static list<id> customerId=new list<id>();
    private static List<SAP_CMD__c> allSAPCMDs = new List<SAP_CMD__c>();
    private static Map<String,SAP_CMD__c> mapFunlocSAPCMD = new Map<String,SAP_CMD__c>();
    private static List<Partner_Function__c> allPartnerFunctions = new List<Partner_Function__c>();
    private static Map<String,Map<Id,Partner_Function__c>> mapSAPCMDPartnerFunctions = new Map<String,Map<Id,Partner_Function__c>>();
    private static List<FunlocWrapper> theProcessedCSV = new List<FunlocWrapper>();
    public id requestId{get;set;}
    public Map<id,Customer__c> mapCustomers = new Map<id,Customer__c>();
    public String Actor{get;set;}
    public id urlid{get;set;}
    public class FunlocWrapper {
        public String funloc { get; set; }
        public String index { get; set; }
        public Boolean isDupe { get; set; }
        public String rowStyleClass { get; set; }
        public String detailId { get; set; }
        public String sapCMD { get; set; }
        public String sapCMDName { get; set; }
        public String accountName { get; set; }
        public String oldLegalName { get; set; }
        public String newLegalName { get; set; }
        public String oldName2 { get; set; }
        public String newName2 { get; set; }
        public String oldName3 { get; set; }
        public String newName3 { get; set; }
        public String oldName4 { get; set; }
        public String newName4 { get; set; }
        public String oldStreet { get; set; }
        public String newStreet { get; set; }
        public String oldStreet4 { get; set; }
        public String newStreet4 { get; set; }
        public String oldCity { get; set; }
        public String newCity { get; set; }
        public String oldStateProvince { get; set; }
        public String newStateProvince { get; set; }
        public String oldCountry { get; set; }
        public String newCountry { get; set; }
        public String oldZip { get; set; }
        public String newZip { get; set; }
        public String oldZA { get; set; }
        public String newZA { get; set; }
        public String oldZS { get; set; }
        public String newZS { get; set; }
        public String SapCMDRecordType{ get; set; }
        public String Name1ServiceProvider{ get; set;}
        
    }    
public List<ProcessInstanceStep> Processsteps=new List<ProcessInstanceStep>();

public SAPCMDMassUpdateController(ApexPages.StandardController stdController) 
{   
    urlid=apexpages.currentpage().getparameters().get('id');
    system.debug('urlid'+urlid);
    refreshPage=false;
    stdController1= stdController;  
        this.theRequest = (CMD_Request__c)stdController.getRecord();
         //actor='<script> func(); </script>';
         System.debug(' this.theRequest :::'+this.theRequest);
       
        requestId=this.theRequest.id;
        
        CMD_Request__c theCMDRequest = [
            SELECT  Id, 
                    Name,
                    RecordType.Name,
                    Mass_Update_Type__c,
                    Request_Status__c
            FROM    CMD_Request__c
            WHERE IsDeleted = FALSE
            AND     Id = :this.theRequest.Id
        ];
        
      System.debug('theCMDRequest:::'+theCMDRequest );
       
    //Actor='test';
     visibility(theCMDRequest);
     
        //modified by Ghanalingamurthy
        //Add validation to prevent approved tickets from being edited or deleted 
      
       
        
        
        massUpdateType = theCMDRequest.Mass_Update_Type__c;
        System.debug('mass'+theCMDRequest.Mass_Update_Type__c);

        RequestStatus = theCMDRequest.Request_Status__c;
        if( theCMDRequest.Request_Status__c == 'Draft' 
            || theCMDRequest.Request_Status__c == 'Ready to Submit'  
        ){
            ticketOpen = true;  
        } else {
            ticketOpen = false;  
        }

        listFunlocWrapper = new List<FunlocWrapper>();
        
        showTextbox = false;

        querySAPCMD();
        queryPartnerFunction();
    
     /*   
        List<CMD_Request_SAP_Mass_Update_Detail__c> theRequestDetails = [
            SELECT  Id,
                    Funloc__c,
                    Legal_Name_New__c,
                    Name_2_New__c,
                    Name_3_New__c,
                    Name_4_New__c,
                    Street_New__c,
                    Street_4_New__c,
                    City_New__c,
                    State_Province_New__c,
                    Country_New__c,
                    Zip_New__c,
                    ZA_New__c,
                    ZS_New__c
            FROM CMD_Request_SAP_Mass_Update_Detail__c
            WHERE CMD_Request__c = :theRequest.Id
        ];
        */
        for( CMD_Request_SAP_Mass_Update_Detail__c theDetail : [SELECT  Id,Funloc__c,Legal_Name_New__c,Name_2_New__c,Name_3_New__c,Name_4_New__c,Street_New__c,Street_4_New__c,City_New__c,State_Province_New__c,Country_New__c,Zip_New__c,ZA_New__c,ZS_New__c  FROM CMD_Request_SAP_Mass_Update_Detail__c WHERE CMD_Request__c = :theRequest.Id]) 
        {
            FunlocWrapper theFunlocWrapper = new FunlocWrapper();
            if( theDetail.Funloc__c != null ) {
                theFunlocWrapper.funloc = theDetail.Funloc__c;
                theFunlocWrapper.detailId = theDetail.Id;
                if( querySAPCMD( theDetail.Funloc__c ) != null ) {
                    theFunlocWrapper.sapCMD = querySAPCMD( theDetail.Funloc__c ).Id;
                    theFunlocWrapper.sapCMDName = querySAPCMD( theDetail.Funloc__c ).Name;
                    theFunlocWrapper.accountName = querySAPCMD( theDetail.Funloc__c ).Account_Name__c;
                    theFunlocWrapper.oldLegalName = querySAPCMD( theDetail.Funloc__c ).Legal_Name__c;
                    theFunlocWrapper.oldName2 = querySAPCMD( theDetail.Funloc__c ).Name_2__c;
                    theFunlocWrapper.oldName3 = querySAPCMD( theDetail.Funloc__c ).Name_3__c;
                    theFunlocWrapper.oldName4 = querySAPCMD( theDetail.Funloc__c ).Name_4__c;
                    theFunlocWrapper.oldStreet = querySAPCMD( theDetail.Funloc__c ).Street_1__c;
                    theFunlocWrapper.oldStreet4 = querySAPCMD( theDetail.Funloc__c ).Street_2__c;
                    theFunlocWrapper.oldCity = querySAPCMD( theDetail.Funloc__c ).City__c;
                    theFunlocWrapper.oldStateProvince = querySAPCMD( theDetail.Funloc__c ).State_Province__c;
                    theFunlocWrapper.oldCountry = querySAPCMD( theDetail.Funloc__c ).Country__c;
                    theFunlocWrapper.oldZip = querySAPCMD( theDetail.Funloc__c ).Zip__c;
                    theFunlocWrapper.oldZA = queryPartnerFunction( 'ZA', theFunlocWrapper.sapCMD );
                    theFunlocWrapper.oldZS = queryPartnerFunction( 'ZS', theFunlocWrapper.sapCMD );
                    theFunlocWrapper.SapCMDRecordType=querySAPCMD( theDetail.Funloc__c ).RecordType.Name;
                    theFunlocWrapper.Name1ServiceProvider=querySAPCMD( theDetail.Funloc__c ).Name_1_Service_Provider__c;
                    System.debug('rec type:'+theFunlocWrapper.SapCMDRecordType);
                    System.debug('theFunlocWrapper.Name1ServiceProvider:'+theFunlocWrapper.Name1ServiceProvider);
                }
                theFunlocWrapper.newLegalName = theDetail.Legal_Name_New__c;
                theFunlocWrapper.newName2 = theDetail.Name_2_New__c;
                theFunlocWrapper.newName3 = theDetail.Name_3_New__c;
                theFunlocWrapper.newName4 = theDetail.Name_4_New__c;
                theFunlocWrapper.newStreet = theDetail.Street_New__c;
                theFunlocWrapper.newStreet4 = theDetail.Street_4_New__c;
                theFunlocWrapper.newCity = theDetail.City_New__c;
                theFunlocWrapper.newStateProvince = theDetail.State_Province_New__c;
                theFunlocWrapper.newCountry = theDetail.Country_New__c;
                theFunlocWrapper.newZip = theDetail.Zip_New__c;
                theFunlocWrapper.newZA = theDetail.ZA_New__c;
                theFunlocWrapper.newZS = theDetail.ZS_New__c;
                //theFunlocWrapper.Name1ServiceProvider=theDetail.Name_1_Service_Provider__c;
            }
            
             System.debug('the funloc:'+theFunlocWrapper);
            listFunlocWrapper.add( theFunlocWrapper );
        }
        this.reindex();
    }
    
 // Added by Shridevi- SIR 215- to lock the record when the approval goes to cmd officer or status becomes approved.   
public void visibility(CMD_Request__c theCMDRequest)
{

      if(statusSet.contains(theCMDRequest.Request_Status__c))
        {
            blEnableEdit=true;        
        }
        else
        {
            blEnableEdit=false;
        }
          
         for(ProcessInstance instance :[SELECT Id, targetObjectId,(select id,actor.name from Workitems) FROM ProcessInstance where targetObjectId=:requestId])
          {
          for(ProcessInstanceWorkitem Workitems: instance.Workitems)
                { 
                  if(Workitems.Actor.Name=='CMD Officers')
                        blEnableEdit=false; 
                }
          }
      

}
    private static void querySAPCMD() {
    
        
       /************************ Modified by shridevi as part of SIR 1114*********************************/ 
     /*   allSAPCMDs = [
            SELECT  Id, 
                    Name,
                    RecordType.Name,
                    FunLoc__c,
                    Customer_FunLoc_Number__c,
                    Account_Name__c,
                    Legal_Name__c,
                    Name_2__c,
                    Name_3__c,
                    Name_4__c,
                    Street_1__c,
                    Street_2__c,
                    City__c,
                    State_Province__c,
                    Country__c,
                    Zip__c
            FROM    SAP_CMD__c
            WHERE IsDeleted = FALSE
        ];*/
 /*************************************************************************************************************/
        for( SAP_CMD__c theSAPCMD : [SELECT  Id,Name_1_Service_Provider__c,Name,RecordType.Name,HUB_Customer__c,FunLoc__c,Customer_FunLoc_Number__c,Account_Name__c,Legal_Name__c,Name_2__c,Name_3__c,Name_4__c,Street_1__c,Street_2__c,City__c,State_Province__c,Country__c,Zip__c FROM SAP_CMD__c WHERE IsDeleted = FALSE]) //modified as part of SIR 1114- Replaced the list allSAPCMDs by query
         {
            mapFunlocSAPCMD.put( theSAPCMD.Customer_FunLoc_Number__c , theSAPCMD );
            System.debug('RecordType.Name='+theSAPCMD.RecordType.Name);
            System.debug('RecordType.Name='+theSAPCMD.Name_1_Service_Provider__c);
            customerId.add(theSAPCMD.HUB_Customer__c);
        }
    }

    private static SAP_CMD__c querySAPCMD( String theFunloc ) {
        if( mapFunlocSAPCMD.containsKey(theFunloc) ) {
            return mapFunlocSAPCMD.get(theFunloc);
        } else {
            return null;
        }
    }

    private static void queryPartnerFunction() {
    /*********************** Modified by shridevi as part of SIR 1114*********************************/ 
      /* allPartnerFunctions = [
            SELECT  Id, 
                    Partner_Function_Type__c,
                    SAP_Customer__c, 
                    Person_Name__c  
            FROM Partner_Function__c 
            WHERE IsDeleted = FALSE 
        ];*/
     /*****************************************************************************************************/   
        Map<Id,Partner_Function__c> mapZAs = new Map<Id,Partner_Function__c>();
        Map<Id,Partner_Function__c> mapZIs = new Map<Id,Partner_Function__c>();
        Map<Id,Partner_Function__c> mapZSs = new Map<Id,Partner_Function__c>();

        for( Partner_Function__c thePartnerFunction : [SELECT  Id, Partner_Function_Type__c,SAP_Customer__c, Person_Name__c FROM Partner_Function__c  WHERE IsDeleted = FALSE ]) //modified as part of SIR 1114- Replaced the list allPartnerFunctions  by query
        {
            System.debug('GSAS_DEBUG:thePartnerFunction.Partner_Function_Type__c.left(2)='+thePartnerFunction.Partner_Function_Type__c.left(2));
            if( thePartnerFunction.Partner_Function_Type__c.left(2) == 'ZA' ) {
                mapZAs.put( thePartnerFunction.SAP_Customer__c , thePartnerFunction ); 
            } else if( thePartnerFunction.Partner_Function_Type__c.left(2) == 'ZI' ) {
                mapZIs.put( thePartnerFunction.SAP_Customer__c , thePartnerFunction ); 
            } else if( thePartnerFunction.Partner_Function_Type__c.left(2) == 'ZS' ) {
                mapZSs.put( thePartnerFunction.SAP_Customer__c , thePartnerFunction ); 
            }
        }
        mapSAPCMDPartnerFunctions.put( 'ZA' , mapZAs );
        mapSAPCMDPartnerFunctions.put( 'ZI' , mapZIs );
        mapSAPCMDPartnerFunctions.put( 'ZS' , mapZSs );
    }
    
    private static String queryPartnerFunction( String theType , String theSAPCMD ) {
        if( mapSAPCMDPartnerFunctions.get(theType).containsKey(theSAPCMD) ) {
            return mapSAPCMDPartnerFunctions.get(theType).get(theSAPCMD).Person_Name__c;
        } else {
            return null;
        }
    }
/*
    public void getMassUpdateTypes() {
        Schema.DescribeFieldResult fieldResult = CMD_Request__c.Mass_Update_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        massUpdateTypeOptions = new List<SelectOption>();
        for( Schema.PicklistEntry f : ple ) {
            massUpdateTypeOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) );
        }            
    }
 */   
    public List<SelectOption> getCountryOptions() {
        Schema.DescribeFieldResult fieldResult = SAP_CMD__c.Country__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<SelectOption> theCountryOptions = new List<SelectOption>();
        for( Schema.PicklistEntry f : ple ) {
            theCountryOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) );
        }
        return theCountryOptions;
    }
/*****
    public List<SelectOption> getZAOptions() {
        Schema.DescribeFieldResult fieldResult = Partner_Function__c.Person_Name__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<SelectOption> theZAOptions = new List<SelectOption>();
        for( Schema.PicklistEntry f : ple ) {
            if( f.getLabel().startsWith('HU')
               || f.getLabel().startsWith('TW')
               || f.getLabel().startsWith('US0')
            ) {
                theZAOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) );
            }
        }            
        return theZAOptions;
    }

    public List<SelectOption> getZSOptions() {
        Schema.DescribeFieldResult fieldResult = Partner_Function__c.Person_Name__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<SelectOption> theZSOptions = new List<SelectOption>();
        for( Schema.PicklistEntry f : ple ) {
            if( !(f.getLabel().startsWith('HU'))
               && !(f.getLabel().startsWith('TW'))
               && !(f.getLabel().startsWith('US0'))
            ) {
               theZSOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) );
            }
        }
        return theZSOptions;
    }
*****/

    public List<SelectOption> getZAOptions() {
        Schema.DescribeFieldResult fieldResult = Partner_Function__c.Person_Name__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<String> thePicklist = new List<String>();
        List<SelectOption> theZAOptions = new List<SelectOption>();
        for( Schema.PicklistEntry f : ple ) {
            if( f.getLabel().startsWith('HU')
               || f.getLabel().startsWith('TW')
               || f.getLabel().startsWith('US0')
               || f.getLabel().startsWith('MX')
               || f.getLabel().startsWith('CN')            
               || f.getLabel().startsWith('US5')
               || f.getLabel().startsWith('RO')
               || f.getLabel().startsWith('CZ')
            ) {
               // thePicklist.add( f.getLabel().substring(8) );  // commented to fix Apex CPU Time limit Exceeded error(SFDC-348)
                theZAOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) ); // Added to fix Apex CPU Time limit Exceeded error(SFDC-348)
                
            }
        }
        theZAOptions.sort(); // Added to fix Apex CPU Time limit Exceeded error(SFDC-348)
        
     // commented below code to fix Apex CPU Time limit Exceeded error(SFDC-348) 
     /* thePicklist.sort();
       for( String theList : thePicklist ){
            for( Schema.PicklistEntry f : ple ){
                if( f.getLabel().substring(8) == theList ){
                    theZAOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) );
                }
            }
        } */
        return theZAOptions;
    }

    public List<SelectOption> getZSOptions() {
        Schema.DescribeFieldResult fieldResult = Partner_Function__c.Person_Name__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<String> thePicklist = new List<String>();
        List<SelectOption> theZSOptions = new List<SelectOption>();
        System.debug('PLE'+ple);
        for( Schema.PicklistEntry f : ple ) {
            if( !(f.getLabel().startsWith('HU'))
               && !(f.getLabel().startsWith('TW'))
               && !(f.getLabel().startsWith('US0'))
               && !(f.getLabel().startsWith('MX'))
               && !(f.getLabel().startsWith('CN'))
               && !(f.getLabel().startsWith('US5'))
               && !(f.getLabel().startsWith('RO'))
               && !(f.getLabel().startsWith('CZ'))
           
               ) {
               // thePicklist.add( f.getLabel().substring(8) );   // commented to fix Apex CPU Time limit Exceeded error(SFDC-348) 
                theZSOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) ); // Added to fix Apex CPU Time limit Exceeded error(SFDC-348)
                System.debug(' ZSlabel :::'+f.getLabel());
            }
        }
        theZSOptions.sort(); // Added to fix Apex CPU Time limit Exceeded error(SFDC-348)
        
       // commented below code to fix Apex CPU Time limit Exceeded error(SFDC-348)   
       /* thePicklist.sort();
        for( String theList : thePicklist ){
            for( Schema.PicklistEntry f : ple ){
                if( f.getLabel().substring(8) == theList ){
                    theZSOptions.add( new SelectOption( f.getLabel() , f.getLabel() ) );
                }
            }
        } */
        return theZSOptions;
    }

   public List<SelectOption> getPDKeyOptions() {
        List<SelectOption> theOptions = new List<SelectOption>();
        List<SAP_CMD__c> queriedPDKeys = [
            SELECT PD_Key_Account__c 
            FROM SAP_CMD__c 
            WHERE PD_Key_Account__c != NULL 
            LIMIT 1000
        ];
        for( SAP_CMD__c CMD : queriedPDKeys ) {
            theOptions.add(new SelectOption((String)CMD.get('PD_Key_Account__c'),(String)CMD.get('PD_Key_Account__c')));
        }            
        return theOptions;
    } 
   
    public PageReference addRow() {
        FunlocWrapper newEmptyFunlocWrapper = new FunlocWrapper();
        this.listFunlocWrapper.add( newEmptyFunlocWrapper );
        this.refresh();
        return null;
    }

    public PageReference add5Rows() {
        FunlocWrapper newEmptyFunlocWrapper1 = new FunlocWrapper();
        FunlocWrapper newEmptyFunlocWrapper2 = new FunlocWrapper();
        FunlocWrapper newEmptyFunlocWrapper3 = new FunlocWrapper();
        FunlocWrapper newEmptyFunlocWrapper4 = new FunlocWrapper();
        FunlocWrapper newEmptyFunlocWrapper5 = new FunlocWrapper();
        this.listFunlocWrapper.add( newEmptyFunlocWrapper1 );
        this.listFunlocWrapper.add( newEmptyFunlocWrapper2 );
        this.listFunlocWrapper.add( newEmptyFunlocWrapper3 );
        this.listFunlocWrapper.add( newEmptyFunlocWrapper4 );
        this.listFunlocWrapper.add( newEmptyFunlocWrapper5 );
        this.refresh();
        return null;
    }

    public PageReference removeRow() {
        Map<String,CMD_Request_SAP_Mass_Update_Detail__c> mapRequestDetails = new Map<String,CMD_Request_SAP_Mass_Update_Detail__c>();
        for( CMD_Request_SAP_Mass_Update_Detail__c theRequestDetail : [
            SELECT  Id, Name,
                    CMD_Request__c,
                    Funloc__c,
                    SAP_CMD__c,
                    ZA_Old__c,
                    ZA_New__c,
                    ZS_Old__c,
                    ZS_New__c
            FROM    CMD_Request_SAP_Mass_Update_Detail__c
            WHERE   CMD_Request__c = :theRequest.Id
        ]) {
            mapRequestDetails.put( String.valueOf(theRequestDetail.Id), theRequestDetail );
        }
        
        if( listFunlocWrapper.get( Integer.valueOf(rowToBeRemoved)-1 ).detailId != null ) {
            delete mapRequestDetails.get( listFunlocWrapper.get( Integer.valueOf(rowToBeRemoved)-1 ).detailId );
        }
        this.listFunlocWrapper.remove( Integer.valueOf(rowToBeRemoved)-1 );
        this.refresh();
        return null;
    }
    
    public PageReference replicateColumn() {
        String theNewZA ;
        String theNewZS ;
        
        this.refresh();

        if( columnToBeReplicated == 'ZA') {        
            theNewZA = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newZA;
            for( FunlocWrapper theFunlocWrapper : listFunlocWrapper ) {
                if( theFunlocWrapper.sapCMD != null ) {
                    theFunlocWrapper.newZA = theNewZA;    
                } else {
                    theFunlocWrapper.newZA = null;
                }
            }
        }

        if( columnToBeReplicated == 'ZS') {        
            theNewZS = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newZS;
            for( FunlocWrapper theFunlocWrapper : listFunlocWrapper ) {
                if( theFunlocWrapper.sapCMD != null ) {
                    theFunlocWrapper.newZS = theNewZS;    
                } else {
                    theFunlocWrapper.newZS = null;
                }
            }
        }

        if( columnToBeReplicated == 'Address') {        
            for( FunlocWrapper theFunlocWrapper : listFunlocWrapper ) {
                if( theFunlocWrapper.sapCMD != null ) {
                    theFunlocWrapper.newLegalName 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newLegalName;    
                    theFunlocWrapper.newName2 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newName2;    
                    theFunlocWrapper.newName3 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newName3;    
                    theFunlocWrapper.newName4 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newName4;    
                    theFunlocWrapper.newStreet 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newStreet;    
                    theFunlocWrapper.newStreet4 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newStreet4;    
                    theFunlocWrapper.newCity 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newCity;    
                    theFunlocWrapper.newStateProvince 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newStateProvince;    
                    theFunlocWrapper.newCountry 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newCountry;    
                    theFunlocWrapper.newZip 
                        = listFunlocWrapper.get(Integer.valueOf(rowToBeReplicated)-1).newZip;    
                } else {
                    theFunlocWrapper.newLegalName = null;
                    theFunlocWrapper.newStreet = null;
                    theFunlocWrapper.newCity = null;
                    theFunlocWrapper.newCountry = null;
                }
            }
        }

        this.refresh();
        return null;
    }
    
    public void scanForDupes() {
        Map<String, FunlocWrapper> checkedFunlocs = new Map<String, FunlocWrapper>();
        for( FunlocWrapper theFunlocWrapper : listFunlocWrapper ) {
            if( checkedFunlocs.containsKey( theFunlocWrapper.funloc ) && theFunlocWrapper.funloc != '' ) {
                theFunlocWrapper.isDupe = true;
                checkedFunlocs.get( theFunlocWrapper.funloc ).isDupe = true;
            } else {
                theFunlocWrapper.isDupe = false;
                checkedFunlocs.put( theFunlocWrapper.funloc, theFunlocWrapper );
            }
        }
    }
    
    public PageReference refresh() {
        querySAPCMD();
        queryPartnerFunction();
        for( FunlocWrapper theFunlocWrapper : listFunlocWrapper ) {
            if( theFunlocWrapper.funloc != null && querySAPCMD( theFunlocWrapper.funloc ) != null ) {
                theFunlocWrapper.sapCMD = querySAPCMD( theFunlocWrapper.funloc ).Id;
                theFunlocWrapper.sapCMDName = querySAPCMD( theFunlocWrapper.funloc ).Name;
                theFunlocWrapper.accountName = querySAPCMD( theFunlocWrapper.funloc ).Account_Name__c;
                theFunlocWrapper.oldLegalName = querySAPCMD( theFunlocWrapper.funloc ).Legal_Name__c;
                theFunlocWrapper.oldStreet = querySAPCMD( theFunlocWrapper.funloc ).Street_1__c;
                theFunlocWrapper.oldCity = querySAPCMD( theFunlocWrapper.funloc ).City__c;
                theFunlocWrapper.oldCountry = querySAPCMD( theFunlocWrapper.funloc ).Country__c;
                theFunlocWrapper.oldZA = queryPartnerFunction( 'ZA', theFunlocWrapper.sapCMD );
                theFunlocWrapper.oldZS = queryPartnerFunction( 'ZS', theFunlocWrapper.sapCMD );
                theFunlocWrapper.SapCMDRecordType=querySAPCMD( theFunlocWrapper.funloc ).RecordType.Name;
                if(refreshPage==false)
                theFunlocWrapper.Name1ServiceProvider=querySAPCMD( theFunlocWrapper.funloc ).Name_1_Service_Provider__c;
            }
        }
        this.scanForDupes();
        this.reindex();
        return null;        
    }
    
    private void reindex() {
        Integer i = 1;
        for( FunlocWrapper theFunloc : listFunlocWrapper ) {
            theFunloc.index = String.valueOf(i);
            if( Math.mod( i , 2 ) == 1 ) {
                theFunloc.rowStyleClass = 'oddRow';
            } else {
                theFunloc.rowStyleClass = 'evenRow';
            }
            i++;
        }
    }
    
    public PageReference uploadCSV() {    
       if( contentFile != null ){
            fileString = contentFile.toString();
            List<FunlocWrapper> allProcessedCSV = processCSV(fileString, true, theRequest.Mass_Update_Type__c);
            if(allProcessedCSV==null)
            {
                return null;
            }
            for( FunlocWrapper theRow : allProcessedCSV ) {
                this.listFunlocWrapper.add( theRow );
            }
        }
        this.scanForDupes();
        this.reindex();
        this.refresh();
        return null;
    }

    private static List<FunlocWrapper> processCSV(String contents,Boolean skipHeaders, String updateType) {
        System.debug('contents:'+contents);
        querySAPCMD();
        queryPartnerFunction();
        theProcessedCSV = new List<FunlocWrapper>();
        List<List<String>> parsedCSV = parseCSV(contents, skipHeaders, updateType);
        if(parsedCSV==null)
            {
                return null;
            }
        FunlocWrapper theProcessedRow = new FunlocWrapper();
        
        for( List<String> row : parsedCSV ) {
            theProcessedRow = new FunlocWrapper();
            
            if( row[0].trim() != null ) {
                if( row[0].trim().startsWith('0') ||
                    row[0].trim().startsWith('1') ||
                    row[0].trim().startsWith('2') ||
                    row[0].trim().startsWith('3') ||
                    row[0].trim().startsWith('4') ||
                    row[0].trim().startsWith('5') ||
                    row[0].trim().startsWith('6') ||
                    row[0].trim().startsWith('7') ||
                    row[0].trim().startsWith('8') ||
                    row[0].trim().startsWith('9') 
                   ) {
                    theProcessedRow.funloc = row[0].trim();
                    if( updateType == 'ZA' ){
                        //System.debug('');e
                        theProcessedRow.newZA = row[1].trim();
                    }
                    if( updateType == 'ZS' ){
                        //System.debug('');e
                        theProcessedRow.newZS = row[1].trim();
                    }
                    if( updateType == 'Address' ){
                        theProcessedRow.newLegalName = row[1].trim();
                        //theProcessedRow.Name1ServiceProvider= row[2].trim()
                        theProcessedRow.newName2 = row[2].trim();
                        theProcessedRow.newName3 = row[3].trim();
                        theProcessedRow.newName4 = row[4].trim();
                        theProcessedRow.newStreet = row[5].trim();
                        theProcessedRow.newStreet4 = row[6].trim();
                        theProcessedRow.newCity = row[7].trim();
                        theProcessedRow.newStateProvince = row[8].trim();
                        theProcessedRow.newCountry = row[9].trim();
                        theProcessedRow.newZip = row[10].trim();
                        
                    }
                }
            }
            theProcessedCSV.add( theProcessedRow );
        }
        return theProcessedCSV;
    }
    
    private static List<List<String>> parseCSV(String contents,Boolean skipHeaders,String updateType) {
        List<List<String>> allFields = new List<List<String>>();
//  if( contents.contains('\n')
        // replace instances where a double quote begins a field containing a comma
        // in this case you get a double quote followed by a doubled double quote
        // do this for beginning and end of a field
        contents = contents.replaceAll(',"""',',"DBLQT').replaceall('""",','DBLQT",');
        // now replace all remaining double quotes - we do this so that we can reconstruct
        // fields with commas inside assuming they begin and end with a double quote
        contents = contents.replaceAll('""','DBLQT');
        // we are not attempting to handle fields with a newline inside of them
        // so, split on newline to get the spreadsheet rows
        List<String> lines = new List<String>();
        try {
            if( contents.contains('\n') ){
                lines = contents.split('\n'); //correction: this only accomodates windows files
            }
            if( contents.contains('\r') ){
                lines = contents.split('\r'); // using carriage return accomodates windows, unix, and mac files
            }
            //http://www.maxi-pedia.com/Line+termination+line+feed+versus+carriage+return+0d0a
        } catch (System.ListException e) {
            System.debug('Limits exceeded?' + e.getMessage());
        }
        
        Integer num = 0;
        
       if(lines.get(0).Contains(','))
        {
            String[] inputvalues = new String[]{};
            inputvalues.clear();
            inputvalues = lines.get(0).split(',');
            System.debug('inputvalues :'+inputvalues+'::size::'+inputvalues.size());
            
            if(updateType.equalsIgnoreCase(MASSUPDATETYPE_ZA))
            {
                if(!((inputvalues.size()==COLUMN_SIZE_ZA) || (inputvalues.size()==COLUMN_SIZE_ZA_TWO)))
                {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_EXCEEDED_ZA));
                        return null;
                }
                if(inputvalues.size()==COLUMN_SIZE_ZA_TWO)
                {
                    if(((headerZa.get(0).equalsIgnoreCase(inputvalues[0])) && (headerZa.get(4).equalsIgnoreCase(inputvalues[1])))) 
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZA));
                        return null;
                    }
                }
                else if(inputvalues.size()== COLUMN_SIZE_ZA)
                {
                    if(     (headerZa.get(0).equalsIgnoreCase(inputvalues[0]))
                         && (headerZa.get(1).equalsIgnoreCase(inputvalues[1]))
                         && (headerZa.get(2).equalsIgnoreCase(inputvalues[2])) 
                         && (headerZa.get(3).equalsIgnoreCase(inputvalues[3])) 
                         && (headerZa.get(4).equalsIgnoreCase(inputvalues[4])) 
                        )
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZA));
                        return null;
                    }
                }
            }
            else if(updateType.equalsIgnoreCase(MASSUPDATETYPE_ZS))
            {
                if(!((inputvalues.size()==COLUMN_SIZE_ZS) || (inputvalues.size()==COLUMN_SIZE_ZS_TWO)))
                {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_EXCEEDED_ZS));
                        return null;
                }
                if(inputvalues.size()==COLUMN_SIZE_ZS_TWO)
                {
                    if(((headerZs.get(0).equalsIgnoreCase(inputvalues[0])) && (headerZs.get(4).equalsIgnoreCase(inputvalues[1])))) 
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZS));
                        return null;
                    }
                }
                else if(inputvalues.size()== COLUMN_SIZE_ZS)
                {
                    if(     (headerZs.get(0).equalsIgnoreCase(inputvalues[0]))
                         && (headerZs.get(1).equalsIgnoreCase(inputvalues[1]))
                         && (headerZs.get(2).equalsIgnoreCase(inputvalues[2])) 
                         && (headerZs.get(3).equalsIgnoreCase(inputvalues[3])) 
                         && (headerZs.get(4).equalsIgnoreCase(inputvalues[4])) 
                        )
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZS));
                        return null;
                    }
                }
            }
            else if(updateType.equalsIgnoreCase(MASSUPDATETYPE_ADDRESS))
            {
                if(inputvalues.size()!=COLUMN_SIZE_ADDRESS)
                {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_EXCEEDED_ADDRESS));
                    return null;
                }
                if(inputvalues.size()==COLUMN_SIZE_ADDRESS)
                {
                   
                    if((( (headerAddress.get(0).equalsIgnoreCase(inputvalues[0])) && (headerAddress.get(1).equalsIgnoreCase(inputvalues[1])) && (headerAddress.get(2).equalsIgnoreCase(inputvalues[2])) && (headerAddress.get(3).equalsIgnoreCase(inputvalues[3])) && (headerAddress.get(4).equalsIgnoreCase(inputvalues[4]))
                         &&(headerAddress.get(5).equalsIgnoreCase(inputvalues[5])) &&  (headerAddress.get(6).equalsIgnoreCase(inputvalues[6])) &&  (headerAddress.get(7).equalsIgnoreCase(inputvalues[7]))&&  (headerAddress.get(8).equalsIgnoreCase(inputvalues[8]))
                         &&  (headerAddress.get(9).equalsIgnoreCase(inputvalues[9]))&&  (headerAddress.get(10).equalsIgnoreCase(inputvalues[10]))&&  (headerAddress.get(11).equalsIgnoreCase(inputvalues[11]))
                        )))
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ADDRESS));
                        return null;
                    }
                }
            }
            
        for(String line: lines) {
            // check for blank CSV lines (only commas)
            if( line.replaceAll(',','').trim().length() == 0 ) 
                break;
            List<String> fields = line.split(',');
            System.debug('fields'+fields);
            List<String> cleanFields = new List<String>();
            String compositeField;
            Boolean makeCompositeField = false;
            for(String field: fields) {
                if (field.startsWith('"') && field.endsWith('"')) {
                    cleanFields.add(field.replaceAll('DBLQT','"'));
                } else if (field.startsWith('"')) {
                    makeCompositeField = true;
                    compositeField = field;
                } else if (field.endsWith('"')) {
                    compositeField += ',' + field;
                    cleanFields.add(compositeField.replaceAll('DBLQT','"'));
                    makeCompositeField = false;
                } else if (makeCompositeField) {
                    compositeField +=  ',' + field;
                } else {
                    cleanFields.add(field.replaceAll('DBLQT','"'));
                }
            }
            allFields.add(cleanFields);
        }
        }
        else
        {
            String[] inputvalues = new String[]{};        
            inputvalues = lines.get(0).split(';');

            if(updateType.equalsIgnoreCase(MASSUPDATETYPE_ZA))
            {
                if(!((inputvalues.size()==COLUMN_SIZE_ZA) || (inputvalues.size()==COLUMN_SIZE_ZA_TWO)))
                {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_EXCEEDED_ZA));
                        return null;
                }
                if(inputvalues.size()==COLUMN_SIZE_ZA_TWO)
                {
                    if(((headerZa.get(0).equalsIgnoreCase(inputvalues[0])) && (headerZa.get(4).equalsIgnoreCase(inputvalues[1])))) 
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZA));
                        return null;
                    }
                }
                else if(inputvalues.size()==COLUMN_SIZE_ZA)
                {
                    if((( (headerZa.get(0).equalsIgnoreCase(inputvalues[0]))&&(headerZa.get(1).equalsIgnoreCase(inputvalues[1])) && (headerZa.get(2).equalsIgnoreCase(inputvalues[2])) && (headerZa.get(3).equalsIgnoreCase(inputvalues[3]))  && (headerZa.get(4).equalsIgnoreCase(inputvalues[4])))))
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZA));
                        return null;
                    }
                }
               
            }
            if(updateType.equalsIgnoreCase(MASSUPDATETYPE_ZS))
            {
                if(!((inputvalues.size()==COLUMN_SIZE_ZS) || (inputvalues.size()==COLUMN_SIZE_ZS_TWO)))
                {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_EXCEEDED_ZS));
                        return null;
                }
                if(inputvalues.size()==COLUMN_SIZE_ZS_TWO)
                {
                    if(((headerZs.get(0).equalsIgnoreCase(inputvalues[0])) && (headerZs.get(4).equalsIgnoreCase(inputvalues[1])))) 
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZS));
                        return null;
                    }
                }
                else if(inputvalues.size()==COLUMN_SIZE_ZS)
                {
                    if((( (headerZs.get(0).equalsIgnoreCase(inputvalues[0]))&&(headerZs.get(1).equalsIgnoreCase(inputvalues[1])) && (headerZs.get(2).equalsIgnoreCase(inputvalues[2])) && (headerZs.get(3).equalsIgnoreCase(inputvalues[3]))  && (headerZs.get(4).equalsIgnoreCase(inputvalues[4])))))
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ZS));
                        return null;
                    }
                }
               
            }
            else if(updateType.equalsIgnoreCase(MASSUPDATETYPE_ADDRESS))
            {
                if(inputvalues.size()!=COLUMN_SIZE_ADDRESS)
                {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_EXCEEDED_ADDRESS));
                        return null;
                }
                if(inputvalues.size()==COLUMN_SIZE_ADDRESS)
                {
                   
                    if((( (headerAddress.get(0).equalsIgnoreCase(inputvalues[0])) && (headerAddress.get(1).equalsIgnoreCase(inputvalues[1])) && (headerAddress.get(2).equalsIgnoreCase(inputvalues[2])) && (headerAddress.get(3).equalsIgnoreCase(inputvalues[3])) && (headerAddress.get(4).equalsIgnoreCase(inputvalues[4]))
                         &&(headerAddress.get(5).equalsIgnoreCase(inputvalues[5])) &&  (headerAddress.get(6).equalsIgnoreCase(inputvalues[6])) &&  (headerAddress.get(7).equalsIgnoreCase(inputvalues[7]))&&  (headerAddress.get(8).equalsIgnoreCase(inputvalues[8]))
                         &&  (headerAddress.get(9).equalsIgnoreCase(inputvalues[9]))&&  (headerAddress.get(10).equalsIgnoreCase(inputvalues[10]))&&  (headerAddress.get(11).equalsIgnoreCase(inputvalues[11]))
                        )))
                    {
                        
                    }
                    else
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,COLUMN_ORDER_ADDRESS));
                        return null;
                    }
                }
            }
            for(String line: lines) {
            // check for blank CSV lines (only commas)
            if( line.replaceAll(';','').trim().length() == 0 ) 
                break;
            List<String> fields = line.split(';');
            System.debug('fields'+fields);
            List<String> cleanFields = new List<String>();
            String compositeField;
            Boolean makeCompositeField = false;
            for(String field: fields) {
                if (field.startsWith('"') && field.endsWith('"')) {
                    cleanFields.add(field.replaceAll('DBLQT','"'));
                } else if (field.startsWith('"')) {
                    makeCompositeField = true;
                    compositeField = field;
                } else if (field.endsWith('"')) {
                    compositeField += ',' + field;
                    cleanFields.add(compositeField.replaceAll('DBLQT','"'));
                    makeCompositeField = false;
                } else if (makeCompositeField) {
                    compositeField +=  ',' + field;
                } else {
                    cleanFields.add(field.replaceAll('DBLQT','"'));
                }
            }
            allFields.add(cleanFields);
        }    
        }
        
        
        if (skipHeaders) allFields.remove(0);
        return allFields;       
    } 

    public void save() {
        refreshPage=true;
        this.refresh();
        
        Map<String,CMD_Request_SAP_Mass_Update_Detail__c> mapRequestDetails = new Map<String,CMD_Request_SAP_Mass_Update_Detail__c>();
        for( CMD_Request_SAP_Mass_Update_Detail__c theRequestDetail : [
            SELECT  Id, Name,
                    CMD_Request__c,
                    Funloc__c,
                    SAP_CMD__c,
                    Legal_Name_Old__c,
                    Legal_Name_New__c,
                    Name_2_New__c,
                    Name_2_Old__c,
                    Name_3_New__c,
                    Name_3_Old__c,
                    Name_4_New__c,
                    Name_4_Old__c,
                    Street_New__c,
                    Street_Old__c,
                    Street_4_New__c,
                    Street_4_Old__c,
                    City_New__c,
                    City_Old__c,
                    State_Province_New__c,
                    State_Province_Old__c,
                    Country_New__c,
                    Country_Old__c,
                    Zip_New__c,
                    Zip_Old__c,
                    ZA_Old__c,
                    ZA_New__c,
                    ZS_Old__c,
                    ZS_New__c
            FROM    CMD_Request_SAP_Mass_Update_Detail__c
            WHERE   CMD_Request__c = :theRequest.Id
        ]) {
            mapRequestDetails.put( String.valueOf(theRequestDetail.Id), theRequestDetail );
        }
        List<CMD_Request_SAP_Mass_Update_Detail__c> detailsToBeUpdated = new List<CMD_Request_SAP_Mass_Update_Detail__c>(); 
        List<CMD_Request_SAP_Mass_Update_Detail__c> detailsToBeInserted = new List<CMD_Request_SAP_Mass_Update_Detail__c>(); 
        List<SAP_CMD__c> detailsToBeUpdatedToSAPCMD= new List<SAP_CMD__c>();
        List<id> sapCmdId=new List<id>();
        Map<id,string> mapSapCmd=new Map<id,string>();
        for( FunlocWrapper theFunlocWrapper : listFunlocWrapper ) {
            if( mapRequestDetails.containsKey( theFunlocWrapper.detailId ) ) {
             System.debug('Entered If-1');
                mapRequestDetails.get( theFunlocWrapper.detailId ).Funloc__c = theFunlocWrapper.funloc;
                mapRequestDetails.get( theFunlocWrapper.detailId ).SAP_CMD__c = theFunlocWrapper.sapCMD;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Legal_Name_Old__c = theFunlocWrapper.oldLegalName;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Legal_Name_New__c = theFunlocWrapper.newLegalName;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Name_2_Old__c = theFunlocWrapper.oldName2;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Name_2_New__c = theFunlocWrapper.newName2;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Name_3_Old__c = theFunlocWrapper.oldName3;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Name_3_New__c = theFunlocWrapper.newName3;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Name_4_Old__c = theFunlocWrapper.oldName4;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Name_4_New__c = theFunlocWrapper.newName4;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Street_New__c = theFunlocWrapper.newStreet;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Street_Old__c = theFunlocWrapper.newStreet;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Street_4_New__c = theFunlocWrapper.newStreet4;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Street_4_Old__c = theFunlocWrapper.newStreet4;
                mapRequestDetails.get( theFunlocWrapper.detailId ).City_Old__c = theFunlocWrapper.oldCity;
                mapRequestDetails.get( theFunlocWrapper.detailId ).City_New__c = theFunlocWrapper.newCity;
                mapRequestDetails.get( theFunlocWrapper.detailId ).State_Province_Old__c = theFunlocWrapper.oldStateProvince;
                mapRequestDetails.get( theFunlocWrapper.detailId ).State_Province_New__c = theFunlocWrapper.newStateProvince;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Country_Old__c = theFunlocWrapper.oldCountry;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Country_New__c = theFunlocWrapper.newCountry;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Zip_Old__c = theFunlocWrapper.oldZip;
                mapRequestDetails.get( theFunlocWrapper.detailId ).Zip_New__c = theFunlocWrapper.newZip;
                mapRequestDetails.get( theFunlocWrapper.detailId ).ZA_Old__c = theFunlocWrapper.oldZA;
                mapRequestDetails.get( theFunlocWrapper.detailId ).ZA_New__c = theFunlocWrapper.newZA;
                mapRequestDetails.get( theFunlocWrapper.detailId ).ZS_Old__c = theFunlocWrapper.oldZS;
                mapRequestDetails.get( theFunlocWrapper.detailId ).ZS_New__c = theFunlocWrapper.newZS;
                //mapRequestDetails.get( theFunlocWrapper.detailId ).ZS_Old__c = theFunlocWrapper.oldZS;
               // mapRequestDetails.get( theFunlocWrapper.detailId ).ZS_New__c = theFunlocWrapper.newZS;
                
               
                 
                detailsToBeUpdated.add( mapRequestDetails.get( theFunlocWrapper.detailId ) );
            } else if( theFunlocWrapper.isDupe == false && theFunlocWrapper.sapCMD != null ) {
            System.debug('Entered If2');
                CMD_Request_SAP_Mass_Update_Detail__c newRequestDetail = new CMD_Request_SAP_Mass_Update_Detail__c(
                    CMD_Request__c = theRequest.Id,
                    Funloc__c = theFunlocWrapper.funloc,
                    SAP_CMD__c = theFunlocWrapper.sapCMD,
                    Legal_Name_Old__c = theFunlocWrapper.oldLegalName,
                    Legal_Name_New__c = theFunlocWrapper.newLegalName,
                    Name_2_Old__c = theFunlocWrapper.oldName2,
                    Name_2_New__c = theFunlocWrapper.newName2,
                    Name_3_Old__c = theFunlocWrapper.oldName3,
                    Name_3_New__c = theFunlocWrapper.newName3,
                    Name_4_Old__c = theFunlocWrapper.oldName4,
                    Name_4_New__c = theFunlocWrapper.newName4,
                    Street_New__c = theFunlocWrapper.newStreet,
                    Street_Old__c = theFunlocWrapper.newStreet,
                    Street_4_New__c = theFunlocWrapper.newStreet4,
                    Street_4_Old__c = theFunlocWrapper.newStreet4,
                    City_Old__c = theFunlocWrapper.oldCity,
                    City_New__c = theFunlocWrapper.newCity,
                    State_Province_Old__c = theFunlocWrapper.oldStateProvince,
                    State_Province_New__c = theFunlocWrapper.newStateProvince,
                    Country_Old__c = theFunlocWrapper.oldCountry,
                    Country_New__c = theFunlocWrapper.newCountry,
                    Zip_Old__c = theFunlocWrapper.oldZip,
                    Zip_New__c = theFunlocWrapper.newZip,
                    ZA_Old__c = theFunlocWrapper.oldZA,
                    ZA_New__c = theFunlocWrapper.newZA,
                    ZS_Old__c = theFunlocWrapper.oldZS,
                    ZS_New__c = theFunlocWrapper.newZS
                    //theFunlocWrapper.SapCMDRecordType
                   // Name_1_Service_Provider__c=theFunlocWrapper.Name1ServiceProvider
                );
                
                detailsToBeInserted.add( newRequestDetail );
            }
             System.debug('theFunlocWrapper::'+theFunlocWrapper);
             SapCmdId.add(theFunlocWrapper.sapCMD);
             System.debug('SAP CMD ID:'+SapCmdId);
             mapSapCmd.put(theFunlocWrapper.sapCMD,theFunlocWrapper.Name1ServiceProvider);
        }
        
     
       if(theRequest.Mass_Update_Type__c=='Address')
       {
        for(SAP_CMD__c SapCmdRecord:[select id,Type__c,Name_1_Service_Provider__c,HUB_Customer__C,Customer_FunLoc_Number__c from SAP_CMD__c where id in:SapCmdId])
            {
               System.debug('SapCmdRecord::'+SapCmdRecord);
                    if(SapCmdRecord.Type__c=='Service Provider' && (mapSapCmd.get(SapCmdRecord.id)!=null && mapSapCmd.get(SapCmdRecord.id)!=''))
                      {
                        SapCmdRecord.Name_1_Service_Provider__c=mapSapCmd.get(SapCmdRecord.id);
                        detailsToBeUpdatedToSAPCMD.add(SapCmdRecord);
                        System.debug('updates::'+mapSapCmd.get(SapCmdRecord.id));
                      }
                   /* else if(mapSapCmd.get(SapCmdRecord.id)!=null && mapSapCmd.get(SapCmdRecord.id)!='')
                      { 
                         System.debug('else error updates');
                         refreshPage=false;
                         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Funloc-'+SapCmdRecord.Customer_FunLoc_Number__c+': Name1(Service Provider) field can be filled only if the Customer is of type Service Provider.'));
                          
                      }*/
                }
            
        if( detailsToBeUpdatedToSAPCMD.size()!=0)
            update detailsToBeUpdatedToSAPCMD;
        System.debug(detailsToBeUpdatedToSAPCMD);
        }
        
       
        
        update detailsToBeUpdated;
        insert detailsToBeInserted;
         System.debug(detailsToBeUpdatedToSAPCMD);
         // this.reindex();
         // refreshPage=true;
         // if(refreshPage==true)
         //  {
        actor='<script> pageReload(); </script>';
       
         //  }
         //stdController1.save();
       
       
        // PageReference pageRef = ApexPages.currentPage();
        // pageRef.setRedirect(true);
        //return pageRef;
    }
}