src/objects/CommunitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Consists of Community related URLS</description>
    <fields>
        <fullName>Question_BestReply__c</fullName>
        <description>The points For question best Reply</description>
        <label>Question BestReply</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Like__c</fullName>
        <description>The points For question like</description>
        <label>Question Like</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CommunitySettings</label>
</CustomObject>

src/objects/Question_Like__c.object
<CustomObject>
    <description>New object to store the likes of question object.</description>
    <fields>
        <fullName>QuestionID__c</fullName>
        <description>Id of the question which is liked by user</description>
        <label>Question</label>
        <referenceTo>Question</referenceTo>
        <relationshipName>Question_Answer_Like</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Like</label>
    <nameField>
        <label>Question Answer Like Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Like</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommunityQuestion_AfterUpdateTest.cls
/***************************************************************************************************************************************************************************************************************** 
@Created By :       Avichal Kumar
@Created Date:      7th August  2015
@Description:       Test class for  CommunityQuestion_AfterUpdate trigger
******************************************************************************************************************************************************************************************************************/
@isTest
private class CommunityQuestion_AfterUpdateTest {
   private Static question createQuestions()
    {
        Question objQue=new Question();
        objQue.title='testing1';
        objQue.body='testing1';
        return objQue;
    } 
    
    private Static Reply createAnswers()
    {
        Reply objRep=new Reply();
        objRep.body='testing';
        return objRep;
    }
    //Question Likes And Best Answer
    static testmethod void CommunityQuestion_AfterUpdateTest1 ()
        
    {
        CommunitySettings__c setting = new CommunitySettings__c();
        setting.Name = 'CommunityUrl';
        setting.Question_BestReply__c= 20;
        insert setting;
        system.assert(setting.Id!=null);
        
        Community objCom= [SELECT Id FROM Community WHERE Name = 'NXP Community'];
        Test.startTest();
         
        Question objQue1=new Question();
        objQue1=createQuestions();
        objQue1.CommunityId=objCom.id;
        objQue1.Product_Category__c='Automotive';
        insert objQue1;
        
        Reply objRep= new Reply();
        objRep=createAnswers();
        objRep.QuestionId=objQue1.id;
        insert objRep; 
        
        Question_like__c objQuestionlike = new question_like__c();
        objQuestionlike.QuestionID__c=objQue1.id;
        insert objQuestionlike;
        
        objque1.bestReplyid=objrep.id;
        update objque1;

        Test.stopTest();
    }
}