src/objects/Contact_Service_Level_Criteria__c.object
<CustomObject>
    <description>Created by shridevi, as part of SIR 1329(2016.11): This object is to store the email addresses(patterns) and Contact service level data.</description>
    <fields>
        <fullName>Contact_Service_Level__c</fullName>
        <description>Created by Shridevi, as part of SIR 1329(2016.11): This field is used to store the Contact Service Level value.</description>
        <label>Contact Service Level</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_Name__c</fullName>
        <description>Created By Shridevi, as part of SIR 1329(2016.11) : This field is to store the field name of the contact, which is used for identifying the Contact Service Level.</description>
        <label>Criteria Field Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_Value__c</fullName>
        <description>Created by Shridevi, as part of SIR 1329(2016.11): This field is used for storing the value of the criteria field which we are using for identifying the Contact Service Level.</description>
        <label>Criteria Field Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Contact Service Level Criteria</label>
    <nameField>
        <displayFormat>CSL-{00000}</displayFormat>
        <label>CSL Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Service Level Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/contactServiceLevelCriteriaSchedulerTest.cls
@IsTest
public class contactServiceLevelCriteriaSchedulerTest{
    static testmethod void testCSL() { 
        Test.startTest();
        list<Contact_Service_Level_Criteria__c> lstCSLC=new list<Contact_Service_Level_Criteria__c>();
        lstCSLC=CreateContactServiceLevelCriteria();
        
        contact objContact1=new Contact(FirstName='test1',LastName='strLastName', Title = 'strTitle',
                                          Phone = '8123978919', email = 'test1@CN.BOSCH.COM',CanAllowPortalSelfReg=false,contact_service_level__c=''); 
        
    
        insert objContact1;
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        //schedule the job
        String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new contactServiceLevelCriteriaScheduler());

        List<CronTrigger> lstCrons = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                    FROM CronTrigger WHERE id = :jobId Limit 1];

        System.assert(lstCrons.size() > 0);
        System.assert(lstCrons[0].CronExpression == CRON_EXP);        
        System.assert(lstCrons[0].TimesTriggered == 0);
        
        contactServiceLevelCriteriaBatch CSLB=new contactServiceLevelCriteriaBatch();
        CSLB.execute(null,lstCSLC);
        Test.stopTest();
    }
    
     private static list<Contact_Service_Level_Criteria__c>CreateContactServiceLevelCriteria()
    {
        list<Contact_Service_Level_Criteria__c> lstCSLC=new list<Contact_Service_Level_Criteria__c>();
        lstCSLC.add(new Contact_Service_Level_Criteria__c(Criteria_Field_Name__c='Email',Criteria_Field_Value__c='toni@zollikofer.eu',Contact_Service_Level__c='A-DirectCust'));
        lstCSLC.add(new Contact_Service_Level_Criteria__c(Criteria_Field_Name__c='Email',Criteria_Field_Value__c='CN.ABB.COM',Contact_Service_Level__c='A-DirectCust'));
        lstCSLC.add(new Contact_Service_Level_Criteria__c(Criteria_Field_Name__c='Email',Criteria_Field_Value__c='CN.BOSCH.COM',Contact_Service_Level__c='A-DirectCust'));
        
        insert lstCSLC;
        return lstCSLC;
    
    }
}