src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Short Name of the Customer</description>
        <inlineHelpText>Short Name of the Customer</inlineHelpText>
        <label>Account Name  ( Short Name )</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DNB_Verified__c</fullName>
        <description>Verified with DNB</description>
        <inlineHelpText>Indicate if customer information is found and the degree of match in Hoovers D&amp;B database.
Comparing the following 5 parameters: legal name, street, city, zipcode, country</inlineHelpText>
        <label>DNB Verified</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DNB Accepted</fullName>
                    <default>true</default>
                    <label>DNB Accepted</label>
                </value>
                <value>
                    <fullName>DNB Rejected: Poor Match</fullName>
                </value>
                <value>
                    <fullName>DNB Rejected: Not Found</fullName>
                </value>
                <value>
                    <fullName>DNB Accepted: Out of Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GSM_Classification__c</fullName>
        <description>GSM Customer Category</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Global_Enterprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</description>
        <inlineHelpText>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</inlineHelpText>
        <label>NXP Ultimate Parent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Global_Enterprise</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Division, Location</value>
            </filterItems>
            <infoMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers ( NXP Ultimate Parent)</relationshipLabel>
        <relationshipName>NXPUltimateParent_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>House_Number__c</fullName>
        <description>House number</description>
        <inlineHelpText>Part of customer address</inlineHelpText>
        <label>House Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <description>Industry Segment</description>
        <inlineHelpText>Customer Buying Group (CBG)</inlineHelpText>
        <label>Industry Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA - Automotive</fullName>
                </value>
                <value>
                    <fullName>BB - C&amp;I</fullName>
                </value>
                <value>
                    <fullName>CC - Computing</fullName>
                </value>
                <value>
                    <fullName>DD - Distribution</fullName>
                </value>
                <value>
                    <fullName>EE - EMS</fullName>
                </value>
                <value>
                    <fullName>FF - Infrastructure</fullName>
                </value>
                <value>
                    <fullName>GG - Mobile</fullName>
                </value>
                <value>
                    <fullName>HH - Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The immediate parent division of the entity.</description>
        <inlineHelpText>The immediate parent division of the entity.</inlineHelpText>
        <label>Parent Division</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = Division can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Division</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Only a Record Type = Division can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers (My Next Higher Division)</relationshipLabel>
        <relationshipName>Division_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role</description>
        <inlineHelpText>Describe the role of account whom NXP sells to</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>IDH</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Address - Street Line1</description>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line1</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP__c</fullName>
        <description>ZIP</description>
        <inlineHelpText>Customer address - postal code</inlineHelpText>
        <label>ZIP</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <recordTypes>
        <fullName>Division</fullName>
        <active>true</active>
        <description>Record Type = Division</description>
        <label>Division</label>
    </recordTypes>
    <recordTypes>
        <fullName>Global_Enterprise</fullName>
        <active>true</active>
        <description>Record Type = NXP Ultimate Parent</description>
        <label>NXP Ultimate Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Record Type = Location</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CustomerHierarchyControllerTest.cls
/**********************************************************************************************
@Created By :       Nisha Agrawal
@Created Date:      17 Jun 2013
@Description:       Test Class for Controller class CustomerHierarchyController
***********************************************************************************************/

@isTest
private class CustomerHierarchyControllerTest 
{
	private static final String TYPE_GLOBALENTERPRISE = 'Global_Enterprise';
	private static final String TYPE_LOCATION = 'Location';
	private static final String TYPE_DIVISION = 'Division';

	private static Map<String, RecordType> mapTypeNameToRecordTypes = new Map<String, RecordType>();
	
	private static void fetchCustomerRecordTypes()
    {
    	//get the record type
	    for(RecordType rt : [Select Id, DeveloperName From RecordType Where SobjectType = 'Customer__c' and IsActive=true ])
	    {
	        mapTypeNameToRecordTypes.put(rt.DeveloperName , rt);
	    }	
    }
			
	//Case - Customer Type = Location and GE -> Division -> Location 
    static testMethod void CustomerHierarchyControllerTest1() 
    {
		//prepare test data
        fetchCustomerRecordTypes();
        
        //create test customers
        
        Customer__c geCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_GLOBALENTERPRISE).Id, 
        											Legal_Name__c = 'ut_global_enterprise' , Account_Name__c = 'ut_global_enterprise', 
        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_ge_city',
        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive', 
        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM', 
        											GSM_Classification__c = 'Longtail');
        insert geCustomer;        
        system.assert(geCustomer.Id != null);        											
        
        
        Customer__c divisionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_DIVISION).Id, 
        												Global_Enterprise__c = geCustomer.Id ,
	        											Legal_Name__c = 'ut_division' , Account_Name__c = 'ut_division', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_div_city',
	        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
        insert divisionCustomer;        
        system.assert(divisionCustomer.Id != null);        										
        
        Customer__c loctaionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_LOCATION).Id, 
        												Global_Enterprise__c = geCustomer.Id , Parent_Division__c = divisionCustomer.Id ,  
	        											Legal_Name__c = 'ut_location' , Account_Name__c = 'ut_Account_Name', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_loc_city',
	        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
		insert loctaionCustomer;        
        system.assert(loctaionCustomer.Id != null);
        
        //start the test
        Test.startTest();
        
        PageReference pgRef = Page.CustomerHierarchy;
        pgRef.getParameters().put('Id', loctaionCustomer.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(loctaionCustomer);
        CustomerHierarchyController controller  = new CustomerHierarchyController(stdController);
        
        String strExpectedHierarchy = '{"data":[{"state":"open","data":"ut_global_enterprise - ut_ge_city","children":[{"state":"open","data":"ut_division - ut_div_city","children":[{"state":"open","data":"ut_location - ut_loc_city","children":[]}]}]}]}';
        String strActualHierarchy = controller.strHierarchyJson;
        
        //assert the result
        system.assert(!String.isEmpty(strActualHierarchy));
        system.assert(strActualHierarchy.trim() == strExpectedHierarchy.trim());
                
        //stop the test
        Test.stopTest();
    }     
    
    
    //Case - Customer Type = Location and GE -> Location
    static testMethod void CustomerHierarchyControllerTest2() 
    {
        //prepare test data
        fetchCustomerRecordTypes();
        
        //create test customers
        
        Customer__c geCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_GLOBALENTERPRISE).Id, 
        											Legal_Name__c = 'ut_global_enterprise' , Account_Name__c = 'ut_global_enterprise', 
        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_ge_city',
        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM',
        											GSM_Classification__c = 'Longtail');
        insert geCustomer;        
        system.assert(geCustomer.Id != null);        											
        
        Customer__c loctaionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_LOCATION).Id, 
    												Global_Enterprise__c = geCustomer.Id ,  
        											Legal_Name__c = 'ut_location' , Account_Name__c = 'ut_Account_Name', 
        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_loc_city',
        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
		insert loctaionCustomer;        
        system.assert(loctaionCustomer.Id != null);
        
        //start the test
        Test.startTest();
        
        PageReference pgRef = Page.CustomerHierarchy;
        pgRef.getParameters().put('Id', loctaionCustomer.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(loctaionCustomer);
        CustomerHierarchyController controller  = new CustomerHierarchyController(stdController);
        
        String strExpectedHierarchy = ' {"data":[{"state":"open","data":"ut_global_enterprise - ut_ge_city","children":[{"state":"open","data":"ut_location - ut_loc_city","children":[]}]}]}';
        String strActualHierarchy = controller.strHierarchyJson;
        
        //assert the result
        system.assert(!String.isEmpty(strActualHierarchy));
        system.assert(strActualHierarchy.trim() == strExpectedHierarchy.trim());
                
        //stop the test
        Test.stopTest();
    }
    
    //Case - Customer Type = Location and Division -> Location
    static testMethod void CustomerHierarchyControllerTest3() 
    {
        //prepare test data
        fetchCustomerRecordTypes();
        
        //create test customers
        
        Customer__c divisionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_DIVISION).Id, 
	        											Legal_Name__c = 'ut_division' , Account_Name__c = 'ut_division', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_div_city',
	        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
        insert divisionCustomer;        
        system.assert(divisionCustomer.Id != null);        											
        
        Customer__c loctaionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_LOCATION).Id, 
        												Parent_Division__c = divisionCustomer.Id ,  
	        											Legal_Name__c = 'ut_location' , Account_Name__c = 'ut_Account_Name', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_loc_city',
	        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
		insert loctaionCustomer;        
        system.assert(loctaionCustomer.Id != null);
        
        //start the test
        Test.startTest();
        
        PageReference pgRef = Page.CustomerHierarchy;
        pgRef.getParameters().put('Id', loctaionCustomer.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(loctaionCustomer);
        CustomerHierarchyController controller  = new CustomerHierarchyController(stdController);
        
        String strExpectedHierarchy = ' {"data":[{"state":"open","data":"ut_division - ut_div_city","children":[{"state":"open","data":"ut_location - ut_loc_city","children":[]}]}]}';
        String strActualHierarchy = controller.strHierarchyJson;
        
        //assert the result
        system.assert(!String.isEmpty(strActualHierarchy));
        system.assert(strActualHierarchy.trim() == strExpectedHierarchy.trim());
                
        //stop the test
        Test.stopTest();
    }
        
    //Case - Customer Type = Location and Location(No hierarchy)
    static testMethod void CustomerHierarchyControllerTest4() 
    {
        //prepare test data
        fetchCustomerRecordTypes();
        //create test customer
        Customer__c objCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_LOCATION).Id, 
        											Legal_Name__c = 'ut_location' , Account_Name__c = 'ut_Account_Name', 
        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_city',
        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
		insert objCustomer;
        
        system.assert(objCustomer.Id != null);
        
        //start the test
        Test.startTest();
        
        PageReference pgRef = Page.CustomerHierarchy;
        pgRef.getParameters().put('Id', objCustomer.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(objCustomer);
        CustomerHierarchyController controller  = new CustomerHierarchyController(stdController);
        
        String strExpectedHierarchy = '{"data":[{"state":"open","data":"ut_location - ut_city","children":[]}]}';
        String strActualHierarchy = controller.strHierarchyJson;
        
        //assert the result
        system.assert(!String.isEmpty(strActualHierarchy));
        system.assert(strActualHierarchy.trim() == strExpectedHierarchy.trim());
                
        //stop the test
        Test.stopTest();
    }
    
    
    //Case - Customer Type = Location and GE -> Division -> Sub Division -> Location 
    static testMethod void CustomerHierarchyControllerTest5() 
    {
        //prepare test data
        fetchCustomerRecordTypes();
        
        //create test customers
        
        Customer__c geCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_GLOBALENTERPRISE).Id, 
        											Legal_Name__c = 'ut_global_enterprise' , Account_Name__c = 'ut_global_enterprise', 
        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_ge_city',
        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM', 
        											GSM_Classification__c = 'Longtail');
        insert geCustomer;        
        system.assert(geCustomer.Id != null);        											
        
        Customer__c divisionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_DIVISION).Id, 
        												Global_Enterprise__c = geCustomer.Id ,
	        											Legal_Name__c = 'ut_division' , Account_Name__c = 'ut_division', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_div_city',
	        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
        insert divisionCustomer;        
        system.assert(divisionCustomer.Id != null);        											
        
        Customer__c subDivisionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_DIVISION).Id, 
        												Global_Enterprise__c = geCustomer.Id ,Parent_Division__c = divisionCustomer.Id ,
	        											Legal_Name__c = 'ut_sub_division' , Account_Name__c = 'ut_sub_division', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_sub_div_city',
	        											Country__c = 'India', Zip__c = '12345', Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
        insert subDivisionCustomer;        
        system.assert(subDivisionCustomer.Id != null); 
        
        Customer__c loctaionCustomer = new Customer__c(RecordTypeId = mapTypeNameToRecordTypes.get(TYPE_LOCATION).Id, 
        												Global_Enterprise__c = geCustomer.Id , Parent_Division__c = subDivisionCustomer.Id ,  
	        											Legal_Name__c = 'ut_location' , Account_Name__c = 'ut_Account_Name', 
	        											House_Number__c = 'ut_hn' , Street__c ='ut_street' , City__c = 'ut_loc_city',
	        											Country__c = 'India', Zip__c = '12345' ,
	        											Industry_Segment__c = 'Automotive',
	        											DNB_Verified__c = 'DNB Rejected : Not found', Role__c = 'OEM');
		insert loctaionCustomer;        
        system.assert(loctaionCustomer.Id != null);
        
        //start the test
        Test.startTest();
        
        PageReference pgRef = Page.CustomerHierarchy;
        pgRef.getParameters().put('Id', loctaionCustomer.Id);
        
        Test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(loctaionCustomer);
        CustomerHierarchyController controller  = new CustomerHierarchyController(stdController);
        
        String strExpectedHierarchy = ' {"data":[{"state":"open","data":"ut_global_enterprise - ut_ge_city","children":[{"state":"open","data":"ut_division - ut_div_city","children":[{"state":"open","data":"ut_sub_division - ut_sub_div_city","children":[{"state":"open","data":"ut_location - ut_loc_city","children":[]}]}]}]}]}';
        String strActualHierarchy = controller.strHierarchyJson;
        
        //assert the result
        system.assert(!String.isEmpty(strActualHierarchy));
        system.assert(strActualHierarchy.trim() == strExpectedHierarchy.trim());
                
        //stop the test
        Test.stopTest();
    }
       
}