src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Short Name of the Customer</description>
        <inlineHelpText>Short Name of the Customer</inlineHelpText>
        <label>Account Name  ( Short Name )</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>DUNS Number for the entity</description>
        <inlineHelpText>DUNS # from Hoovers D&amp;B database</inlineHelpText>
        <label>DUNS</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Fulfillment_Channel__c</fullName>
        <inlineHelpText>The channel type customer comes through</inlineHelpText>
        <label>Fulfillment Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Disti</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GSM_Classification__c</fullName>
        <description>GSM Customer Category</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>House_Number__c</fullName>
        <description>House number</description>
        <inlineHelpText>Part of customer address</inlineHelpText>
        <label>House Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <description>Industry Segment</description>
        <inlineHelpText>Customer Buying Group (CBG)</inlineHelpText>
        <label>Industry Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA - Automotive</fullName>
                </value>
                <value>
                    <fullName>BB - C&amp;I</fullName>
                </value>
                <value>
                    <fullName>CC - Computing</fullName>
                </value>
                <value>
                    <fullName>DD - Distribution</fullName>
                </value>
                <value>
                    <fullName>EE - EMS</fullName>
                </value>
                <value>
                    <fullName>FF - Infrastructure</fullName>
                </value>
                <value>
                    <fullName>GG - Mobile</fullName>
                </value>
                <value>
                    <fullName>HH - Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Sub_Segment__c</fullName>
        <description>Industry Sub Segment</description>
        <inlineHelpText>Sub CBG</inlineHelpText>
        <label>Industry Sub Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A1 - Automotive</fullName>
                </value>
                <value>
                    <fullName>B1 - Consumer &amp; HA</fullName>
                </value>
                <value>
                    <fullName>B2 - Gaming</fullName>
                </value>
                <value>
                    <fullName>B3 - Imaging</fullName>
                </value>
                <value>
                    <fullName>B4 - Industrial</fullName>
                </value>
                <value>
                    <fullName>B5 - Lighting</fullName>
                </value>
                <value>
                    <fullName>B6 - Power Supply</fullName>
                </value>
                <value>
                    <fullName>B7 - White Goods</fullName>
                </value>
                <value>
                    <fullName>B8 - Healthcare</fullName>
                </value>
                <value>
                    <fullName>B9 - Smart Home&amp;Building</fullName>
                </value>
                <value>
                    <fullName>C1 - Computing</fullName>
                </value>
                <value>
                    <fullName>C2 - Computing - Power Supply</fullName>
                </value>
                <value>
                    <fullName>C3 - Data Center</fullName>
                </value>
                <value>
                    <fullName>D1 - Distribution</fullName>
                </value>
                <value>
                    <fullName>E1 - EMS</fullName>
                </value>
                <value>
                    <fullName>F1 - Infrastructure</fullName>
                </value>
                <value>
                    <fullName>F2 - Network</fullName>
                </value>
                <value>
                    <fullName>G1 - Mobile</fullName>
                </value>
                <value>
                    <fullName>G2 - Wearables</fullName>
                </value>
                <value>
                    <fullName>H1 - Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role</description>
        <inlineHelpText>Describe the role of account whom NXP sells to</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>IDH</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Customer Business Life cycle - Sales ?</description>
        <inlineHelpText>Customer Business Life cycle - Sales ?</inlineHelpText>
        <label>Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State / Province</description>
        <inlineHelpText>Customer address - state/province</inlineHelpText>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aceh</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Andaman And Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>An Giang</fullName>
                </value>
                <value>
                    <fullName>Anhui Province</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bac Giang</fullName>
                </value>
                <value>
                    <fullName>Bac Kan</fullName>
                </value>
                <value>
                    <fullName>Bac Lieu</fullName>
                </value>
                <value>
                    <fullName>Bac Ninh</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California S</fullName>
                </value>
                <value>
                    <fullName>Bali</fullName>
                </value>
                <value>
                    <fullName>Banten</fullName>
                </value>
                <value>
                    <fullName>Ba Ria Vung Tau</fullName>
                </value>
                <value>
                    <fullName>Beijing City</fullName>
                </value>
                <value>
                    <fullName>Bengkulu</fullName>
                </value>
                <value>
                    <fullName>Ben Tre</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Binh Dinh</fullName>
                </value>
                <value>
                    <fullName>Binh Duong</fullName>
                </value>
                <value>
                    <fullName>Binh Phuoc</fullName>
                </value>
                <value>
                    <fullName>Binh Thuan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Address - Street Line1</description>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line1</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type</description>
        <inlineHelpText>The type of the customer. Default value is set to Customer.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Subcontractor</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <recordTypes>
        <fullName>Global_Enterprise</fullName>
        <active>true</active>
        <description>Record Type = NXP Ultimate Parent</description>
        <label>NXP Ultimate Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Record Type = Location</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Hub_Foundation__c.object
<CustomObject>
    <description>Object to store foundation data for CMD Hub.</description>
    <fields>
        <fullName>State__c</fullName>
        <description>State Name</description>
        <inlineHelpText>State Name</inlineHelpText>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Hub Foundation</label>
    <nameField>
        <displayFormat>FDI-{0000}</displayFormat>
        <label>Foundation Data Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Foundation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CustomerTriggerRegionTest.cls
@isTest
public class CustomerTriggerRegionTest
{
    private static RecordType globalCustomerRT;
    private static RecordType locationCustomerRT;
    private static Hub_Foundation__c testHubFoundation;
    private static Hub_Foundation__c testHubFoundation2;

    public static testMethod void TestInsertParentChild() 
    {
        fetchRecordTypes();
        makeTestHubFoundations();
        
        Map<string,Customer__c> locationNamesMap = new Map<string,Customer__c>();

        Customer__c theGlobal = new Customer__c
        (
            RecordTypeId = globalCustomerRT.Id ,
            Type__c = 'Customer' ,
            Sales__c = true ,
            Account_Name__c = 'Test Global Parent' ,
            Legal_Name__c = 'Test Global Parent' ,
            DUNS__c = 'TestP' ,
            Industry_Segment__c = 'Test Industry Segment' ,
            Industry_Sub_Segment__c = 'Test Sub Segment' ,
            GSM_Classification__c = 'Test Classification' ,
            Role__c = 'Test Role' ,
            Fulfillment_Channel__c = 'Test Channel ' ,
            House_Number__c = 'Test' ,
            Street__c = 'Test Street' ,
            City__c = 'Test City' ,
            State__c = 'Test State' ,
            Country__c = 'Test Country' ,
            Zip__c = 'Test Zip'  ,
            DNB_Verified__c = 'true' 
        );
        insert theGlobal;

        Customer__c testGlobal = 
        [
            SELECT Id, Country__c, Region__c 
            FROM Customer__c
            WHERE Id = :theGlobal.Id
        ];
        System.assertEquals( testGlobal.Country__c , 'Test Country' ) ;
        System.assertEquals( testGlobal.Region__c , 'Test Region' ) ;

        Customer__c theLocation = new Customer__c
        (
            RecordTypeId = locationCustomerRT.Id ,
            Global_Enterprise__c = theGlobal.Id ,
            Type__c = 'Customer' ,
            Sales__c = true ,
            Account_Name__c = 'Test Location Child' ,
            Legal_Name__c = 'Test Location Child'  ,
            DUNS__c = 'TestC'  ,
            Industry_Segment__c = 'Test Industry Segment '  ,
            Industry_Sub_Segment__c = 'Test Sub Segment '  ,
            GSM_Classification__c = 'Test Classification '  ,
            Role__c = 'Test Role '  ,
            Fulfillment_Channel__c = 'Test Channel ' ,
            House_Number__c = 'Test' ,
            Street__c = 'Test Street '  ,
            City__c = 'Test City '  ,
            State__c = 'Test State '  ,
            Country__c = 'Test Country 2' ,
            Zip__c = 'Test'  ,
            DNB_Verified__c = 'true' 
        );
        insert theLocation;
        
        Customer__c testLocation = 
        [
            SELECT Id, Country__c, Region__c 
            FROM Customer__c
            WHERE Id = :theLocation.Id
        ];
        System.assertEquals( testLocation.Country__c , 'Test Country 2' ) ; 
        System.assertEquals( testLocation.Region__c , 'Test Region 2' ) ;                        
    }    
   
    private static void makeTestHubFoundations()
    {
        testHubFoundation = new Hub_Foundation__c 
        (
            Country__c = 'Test Country' ,
            Region__c = 'Test Region' ,
            Alpha_2_Code__c = 'TT' ,
            Alpha_3_Code__c = 'TTT'
        );
        insert testHubFoundation ;
        
        testHubFoundation2 = new Hub_Foundation__c 
        (
            Country__c = 'Test Country 2' ,
            Region__c = 'Test Region 2' ,
            Alpha_2_Code__c = 'T2' ,
            Alpha_3_Code__c = 'TT2'
        );
        insert testHubFoundation2 ;
    }

    @isTest(SeeAllData=true)
    private static void fetchRecordTypes()
    {
        for( RecordType RT : 
            [
                SELECT  Id, DeveloperName
                FROM    RecordType
                WHERE   SobjectType = 'Customer__c' 
                AND (   DeveloperName = 'Global_Enterprise'
                    OR DeveloperName = 'Location' ) 
                AND IsActive = true
             ] )
        {
            if( RT.DeveloperName == 'Global_Enterprise' )
            {
                globalCustomerRT = RT;
            }
            else if( RT.DeveloperName == 'Location' )
            {
                locationCustomerRT = RT;
            }
        }    
    }
}