src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Enterprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</description>
        <inlineHelpText>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</inlineHelpText>
        <label>NXP Ultimate Parent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Global_Enterprise</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Division, Location</value>
            </filterItems>
            <infoMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers ( NXP Ultimate Parent)</relationshipLabel>
        <relationshipName>NXPUltimateParent_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The immediate parent division of the entity.</description>
        <inlineHelpText>The immediate parent division of the entity.</inlineHelpText>
        <label>Parent Division</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = Division can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Division</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Only a Record Type = Division can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers (My Next Higher Division)</relationshipLabel>
        <relationshipName>Division_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <recordTypes>
        <fullName>Division</fullName>
        <active>true</active>
        <description>Record Type = Division</description>
        <label>Division</label>
    </recordTypes>
    <recordTypes>
        <fullName>Global_Enterprise</fullName>
        <active>true</active>
        <description>Record Type = NXP Ultimate Parent</description>
        <label>NXP Ultimate Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Record Type = Location</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CustomerHierarchyController.cls
/******************************************************************************
@Created By :       Nisha Agrawal
@Created Date:      27 May 2013
@Description:       Extension class for VF Page CustomerHierarchy - (CMD Hub App)
*******************************************************************************/

public with sharing class CustomerHierarchyController 
{
	private static final String TYPE_GLOBALENTERPRISE = 'Global_Enterprise';
	
	private static final String TYPE_DIVISION = 'Division';
	
	private static final String TYPE_LOCATION = 'Location';
	 
	private Customer__c objCustomer {get; set; }
	 
	public String strHierarchyJson { get; set; }
	
    public CustomerHierarchyController(ApexPages.StandardController controller) 
    {
    	if(Apexpages.currentPage().getParameters().get('Id') != null)
    	{
    		objCustomer = [Select Id , Name, Legal_Name__c, RecordTypeId, RecordType.Name , City__c,  Global_Enterprise__c , Global_Enterprise__r.Legal_Name__c , Global_Enterprise__r.City__c ,  
    						Parent_Division__c , Parent_Division__r.Legal_Name__c, Parent_Division__r.City__c
    						From Customer__c 
    						Where Id =: Apexpages.currentPage().getParameters().get('Id')];
    						
			// parentNode             
    		TreeNode parentNode;
    		TreeNode locationNode = new TreeNode(objCustomer.Legal_Name__c + ' - ' + objCustomer.City__c,  'open');
    			
    		if(objCustomer.RecordType.Name == TYPE_LOCATION)
    		{
    			//check if it have Global Enterprise and Parent division
    			if((objCustomer.Global_Enterprise__c != null)  && (objCustomer.Parent_Division__c != null))
    			{
    				//GE->Division->Location
    				parentNode = new TreeNode(objCustomer.Global_Enterprise__r.Legal_Name__c  + ' - ' + objCustomer.Global_Enterprise__r.City__c , 'open');
    				TreeNode divNode = fetchParentDivision(objCustomer.Parent_Division__c, locationNode);
    				parentNode.children = new List<TreeNode>{divNode};
    			}
    			else if(objCustomer.Global_Enterprise__c != null) //check if it have Global Enterprise
    			{
    				//GE ->Location
    				parentNode = new TreeNode(objCustomer.Global_Enterprise__r.Legal_Name__c  + ' - ' + objCustomer.Global_Enterprise__r.City__c , 'open');
    				parentNode.children = new List<TreeNode>{locationNode};
    			}
    			else if(objCustomer.Parent_Division__c != null) //check if it have Parent division
    			{
    				//Division -> Location
    				parentNode = fetchParentDivision(objCustomer.Parent_Division__c, locationNode);
    			}
    			else
    			{
    				//Location (No hierarchy)
    				parentNode = locationNode;
    			}		
    		}
    		
    		OriginNode treeRoot = new OriginNode(new List<TreeNode>{parentNode});
    		strHierarchyJson  = JSON.serialize(treeRoot);
    		
            system.debug('====JSON ' + strHierarchyJson);
    	} 
    }
    
     
    private TreeNode fetchParentDivision(Id divisionId, TreeNode childNode)
    {
    	if(divisionId == null)
    	{
    		return childNode;
    	}
    	else
    	{
    		//fetch the parent division
    		Customer__c objDivision = [Select Id , Name, Legal_Name__c, City__c,  Parent_Division__c , Parent_Division__r.Legal_Name__c
    									From Customer__c 
    									Where Id =: divisionId];
			
    		TreeNode currentNode = new TreeNode(objDivision.Legal_Name__c + ' - ' + objDivision.City__c, 'open',  new List<TreeNode>{childNode});
    		
    		return fetchParentDivision(objDivision.Parent_Division__c, currentNode);
    	}
    }    
       
    
    //Wrapper Class to generate the hierarchy in JSON format
    
    public class OriginNode
    {
    	public List<TreeNode> data{get; set;}
    	
    	public OriginNode(List<TreeNode> lstNodes)
    	{
    		data = lstNodes;
    	}
    }
    public class TreeNode    
    {        
    	public List<TreeNode> children {get; set;}                
    	public String data {get; set;}                
    	public String state {get; set;}
    	
    	/*
    	public TreeNode()        
    	{            
    		children = new List<TreeNode>();
    		state = 'closed';        
    	}                
    	public TreeNode(String strTitle)        
    	{            
    		data = strTitle;            
    		children = new List<TreeNode>();
    		state = 'closed';        
    	}                
    	public TreeNode(String strTitle, List<TreeNode> childNodes)        
    	{            
    		data = strTitle;            
    		children = childNodes;
    		state = 'closed';        
    	} */   	
    	public TreeNode(String strTitle, string strState)        
    	{            
    		data = strTitle;
    		state = strState;
    		children = new List<TreeNode>();        
    	}   
    	public TreeNode(String strTitle, string strState, List<TreeNode> childNodes)        
    	{            
    		data = strTitle;            
    		children = childNodes;
    		state = strState;        
    	}    
    } 

}