src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Short Name of the Customer</description>
        <inlineHelpText>Short Name of the Customer</inlineHelpText>
        <label>Account Name  ( Short Name )</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DNB_Verified__c</fullName>
        <description>Verified with DNB</description>
        <inlineHelpText>Indicate if customer information is found and the degree of match in Hoovers D&amp;B database.
Comparing the following 5 parameters: legal name, street, city, zipcode, country</inlineHelpText>
        <label>DNB Verified</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DNB Accepted</fullName>
                    <default>true</default>
                    <label>DNB Accepted</label>
                </value>
                <value>
                    <fullName>DNB Rejected: Poor Match</fullName>
                </value>
                <value>
                    <fullName>DNB Rejected: Not Found</fullName>
                </value>
                <value>
                    <fullName>DNB Accepted: Out of Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>DUNS Number for the entity</description>
        <inlineHelpText>DUNS # from Hoovers D&amp;B database</inlineHelpText>
        <label>DUNS</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GSM_Classification__c</fullName>
        <description>GSM Customer Category</description>
        <inlineHelpText>T1:Rev in 100s M$/ $100Ms growth over 3 yrs 
T2:Rev in 20-100M$/$50Ms growth over 3 yrs 
T3:Rev 3-20M$/$5M growth over 3 yrs
T4 TMMA:supported by both NXP FSE &amp; Disti
T4 RoM:supported by Disti, lead by NXP manager
T4 Longtail:catalog/web user/startup</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Long Tail</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - ROM</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - TMMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Global_Enterprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</description>
        <inlineHelpText>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</inlineHelpText>
        <label>NXP Ultimate Parent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Global_Enterprise</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Division, Location</value>
            </filterItems>
            <infoMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers ( NXP Ultimate Parent)</relationshipLabel>
        <relationshipName>NXPUltimateParent_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>House_Number__c</fullName>
        <description>House number</description>
        <inlineHelpText>Part of customer address</inlineHelpText>
        <label>House Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Segment__c</fullName>
        <description>Industry Segment</description>
        <inlineHelpText>Customer Buying Group (CBG)</inlineHelpText>
        <label>Industry Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA - Automotive</fullName>
                </value>
                <value>
                    <fullName>BB - C&amp;I</fullName>
                </value>
                <value>
                    <fullName>CC - Computing</fullName>
                </value>
                <value>
                    <fullName>DD - Distribution</fullName>
                </value>
                <value>
                    <fullName>EE - EMS</fullName>
                </value>
                <value>
                    <fullName>FF - Infrastructure</fullName>
                </value>
                <value>
                    <fullName>GG - Mobile</fullName>
                </value>
                <value>
                    <fullName>HH - Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Sub_Segment__c</fullName>
        <description>Industry Sub Segment</description>
        <inlineHelpText>Sub CBG</inlineHelpText>
        <label>Industry Sub Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A1 - Automotive</fullName>
                </value>
                <value>
                    <fullName>B1 - Consumer &amp; HA</fullName>
                </value>
                <value>
                    <fullName>B2 - Gaming</fullName>
                </value>
                <value>
                    <fullName>B3 - Imaging</fullName>
                </value>
                <value>
                    <fullName>B4 - Industrial</fullName>
                </value>
                <value>
                    <fullName>B5 - Lighting</fullName>
                </value>
                <value>
                    <fullName>B6 - Power Supply</fullName>
                </value>
                <value>
                    <fullName>B7 - White Goods</fullName>
                </value>
                <value>
                    <fullName>B8 - Healthcare</fullName>
                </value>
                <value>
                    <fullName>B9 - Smart Home&amp;Building</fullName>
                </value>
                <value>
                    <fullName>C1 - Computing</fullName>
                </value>
                <value>
                    <fullName>C2 - Computing - Power Supply</fullName>
                </value>
                <value>
                    <fullName>C3 - Data Center</fullName>
                </value>
                <value>
                    <fullName>D1 - Distribution</fullName>
                </value>
                <value>
                    <fullName>E1 - EMS</fullName>
                </value>
                <value>
                    <fullName>F1 - Infrastructure</fullName>
                </value>
                <value>
                    <fullName>F2 - Network</fullName>
                </value>
                <value>
                    <fullName>G1 - Mobile</fullName>
                </value>
                <value>
                    <fullName>G2 - Wearables</fullName>
                </value>
                <value>
                    <fullName>H1 - Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal code</description>
        <inlineHelpText>Postal code</inlineHelpText>
        <label>Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>The region based on the country</inlineHelpText>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role</description>
        <inlineHelpText>Describe the role of account whom NXP sells to</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>IDH</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Customer Business Life cycle - Sales ?</description>
        <inlineHelpText>Customer Business Life cycle - Sales ?</inlineHelpText>
        <label>Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Address - Street Line1</description>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line1</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP__c</fullName>
        <description>ZIP</description>
        <inlineHelpText>Customer address - postal code</inlineHelpText>
        <label>ZIP</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <recordTypes>
        <fullName>Global_Enterprise</fullName>
        <active>true</active>
        <description>Record Type = NXP Ultimate Parent</description>
        <label>NXP Ultimate Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Record Type = Location</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SearchCustomerControllerTest.cls
/**********************************************************************************************
@Created By :       Nisha Agrawal
@Created Date:      17 Jun 2013
@Description:       Test Class for Controller class SearchCustomerController

@Continued By : Stan Hsu
**************************************************************************************/
@isTest
private class SearchCustomerControllerTest 
{
    private static RecordType globalCustomer;
    private static RecordType locationCustomer;

    static testMethod void NoSearchResultTest() 
    {
        findRecordTypes();
        
        Customer__c theGlobal = new Customer__c
        (
            RecordTypeId = globalCustomer.Id ,
            Account_Name__c = 'Test Global Parent' ,
            Legal_Name__c = 'Test Global Parent' ,
            DUNS__c = 'Test' ,
            Industry_Segment__c = 'Test Industry Segment' ,
            Industry_Sub_Segment__c = 'Test Sub Segment' ,
            GSM_Classification__c = 'Test Classification' ,
            Role__c = 'Test Role' ,
            Region__c = 'Test Region' ,
            House_Number__c = 'Test' ,
            Street__c = 'Test Street' ,
            City__c = 'Test City' ,
            Country__c = 'Test Country' ,
            Zip__c = 'Test Zip' ,
            DNB_Verified__c = 'true'
        );
        insert theGlobal;

        List<Customer__c> locationCustomers = new List<Customer__c>();
        
        integer i=0;        
        for(i=0; i < 10; i++)
        {          
            Customer__c theLocation = new Customer__c
            (
                Global_Enterprise__c = theGlobal.Id ,
                RecordTypeId = locationCustomer.Id ,
                Sales__c = true ,
                Account_Name__c = 'Test Location Child ' + String.valueOf(i) ,
                Legal_Name__c = 'Test Location Child ' + String.valueOf(i) ,
                DUNS__c = 'Test' + String.valueOf(i) ,
                Industry_Segment__c = 'Test Industry Segment ' + String.valueOf(i) ,
                Industry_Sub_Segment__c = 'Test Sub Segment ' + String.valueOf(i) ,
                GSM_Classification__c = 'Test Classification ' + String.valueOf(i) ,
                Role__c = 'Test Role ' + String.valueOf(i) ,
                Region__c = 'Test Region ' + String.valueOf(i) ,
                House_Number__c = String.valueOf(i) ,
                Street__c = 'Test Street ' + String.valueOf(i) ,
                City__c = 'Test City ' + String.valueOf(i) ,
                Country__c = 'Test Country ' + String.valueOf(i) ,
                Postal_Code__c = 'Test' + String.valueOf(i) , 
                Zip__c = 'Test' + String.valueOf(i) ,
                DNB_Verified__c = 'true'
            );
            locationCustomers.add( theLocation );
        }
        insert locationCustomers;
        
        ApexPages.StandardSetController setController = new Apexpages.StandardSetController(new List<Customer__c>());
        SearchCustomerController controller = new SearchCustomerController(setController);
        controller.clearResults();
        
        Test.startTest();
            controller.filterCustomer.Legal_Name__c = 'Test' ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();

            controller.filterCustomer.DUNS__c = 'Test' ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();

            controller.filterCustomer.RecordTypeId = globalCustomer.Id ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();

            controller.filterCustomer.Country__c = 'Test' ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();

            controller.filterCustomer.Postal_Code__c = 'Test' ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();

            controller.filterCustomer.City__c = 'Test' ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();

            controller.filterCustomer.Street__c = 'Test' ;
            controller.searchCustomers();
            System.assert(controller.lstCustomerType != null);
            System.assert(controller.lstCustomerType.size() > 0);               
            controller.clearResults();
        Test.stopTest();        

    }   

    private static void findRecordTypes()
    {
        for( RecordType RT : 
            [
                SELECT  Id, DeveloperName
                FROM    RecordType
                WHERE   SobjectType = 'Customer__c' 
                AND (   DeveloperName = 'Global_Enterprise'
                    OR DeveloperName = 'Location' ) 
                AND IsActive = true
             ] )
        {
            if( RT.DeveloperName == 'Global_Enterprise' )
            {
                globalCustomer = RT;
            }
            else if( RT.DeveloperName == 'Location' )
            {
                locationCustomer = RT;
            }
        }    
    }
}