src/objects/Customer__c.object
<CustomObject>
    <description>Object to store the Customer and its generic attribute in the Customer Hub. 
The object has three record types - NXP Ultimate Parent ( Global Enterprise ), Division and Location.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>Customer address - city</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Customer address - country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Akrotiri And Dhekelia</fullName>
                </value>
                <value>
                    <fullName>Åland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <description>DUNS Number for the entity</description>
        <inlineHelpText>DUNS # from Hoovers D&amp;B database</inlineHelpText>
        <label>DUNS</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Global_Enterprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</description>
        <inlineHelpText>Look up to the NXP Ultimate Parent (Global Enterprise) of the entity.</inlineHelpText>
        <label>NXP Ultimate Parent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Global_Enterprise</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Division, Location</value>
            </filterItems>
            <infoMessage>Only a Record Type = NXP Ultimate Parent ( Global Enterprise ) can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers ( NXP Ultimate Parent)</relationshipLabel>
        <relationshipName>NXPUltimateParent_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <description>Legal Name of the Customer</description>
        <inlineHelpText>Legal Name of the Customer</inlineHelpText>
        <label>Legal Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The immediate parent division of the entity.</description>
        <inlineHelpText>The immediate parent division of the entity.</inlineHelpText>
        <label>Parent Division</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only a Record Type = Division can be associated with this field.</errorMessage>
            <filterItems>
                <field>Customer__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Division</value>
            </filterItems>
            <filterItems>
                <field>Customer__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Only a Record Type = Division can be associated with this field.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Customers (My Next Higher Division)</relationshipLabel>
        <relationshipName>Division_MyLowerLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal code</description>
        <inlineHelpText>Postal code</inlineHelpText>
        <label>Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Address - Street Line1</description>
        <inlineHelpText>Customer address. Maximum 35 characters.</inlineHelpText>
        <label>Street Line1</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>NXP Global ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SearchCustomerController.cls
/******************************************************************************
@Created By :       Nisha Agrawal
@Created Date:      23 May 2013
@Description:       Extension class for VF Page SearchCustomer - (CMD Hub App)
*******************************************************************************/

public with sharing class SearchCustomerController 
{
	public static final String NO_SEARCH_CRITERIA_ERROR = 'Please select some search criteria before searching.';
       
    private string strFilter;
    
    public List<SelectOption> lstCustomerType {get; private set;}
    public List<SelectOption> lstCountry {get; private set;}
    
    public String strGlobalId {get; set;}
    public String strCountry {get; set;}
    public String customerTypeId {get; set;}
    public Customer__c filterCustomer {get; set;}
    
    public List<Customer__c> lstResults {get; set;}
    public Boolean foundResult {get; set;}
    
    public SearchCustomerController(ApexPages.StandardSetController controller) 
    {
    	
        filterCustomer = new Customer__c();
        
		//init customer type picklist         
        lstCustomerType = new List<SelectOption>();
        lstCustomerType.add(new SelectOption('', '-----Select----'));
        
        for(RecordType rt : [Select Id, Name From RecordType Where SobjectType = 'Customer__c' and IsActive=true])
        { 
			lstCustomerType.add(new SelectOption(rt.Id, rt.Name));
        }
        
        //init country picklist
        
        lstCountry = new List<SelectOption>();
        lstCountry.add(new SelectOption('', '-----Select----'));
        
		for( Schema.PicklistEntry f : Customer__c.Country__c.getDescribe().getPicklistValues())
		{
			lstCountry.add(new SelectOption(f.getValue(), f.getLabel())); 	      
		}
        
        strFilter = '';  
    }
    
    private void createFilterString()
    {
        strFilter = ''; 
        
        if(filterCustomer.Legal_Name__c.trim() != '')
        {
			strFilter = 'Legal_Name__c like \'%' + String.escapeSingleQuotes(filterCustomer.Legal_Name__c.trim()) + '%\''; 
        }
        if(filterCustomer.DUNS__c.trim() != '')
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' DUNS__c like \'%' + String.escapeSingleQuotes(filterCustomer.DUNS__c.trim()) + '%\'';
        }
        if(strGlobalId != null && strGlobalId.trim() != '')
        {
            strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' Name like \'%' + String.escapeSingleQuotes(strGlobalId.trim()) + '%\'';
        }
        if(strCountry != null && strCountry.trim() != '')
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' Country__c like \'%' + String.escapeSingleQuotes(strCountry.trim()) + '%\'';
        }
        if(filterCustomer.City__c.trim() != '')
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' City__c like \'%' + String.escapeSingleQuotes(filterCustomer.City__c.trim()) + '%\'';
        }
        if(filterCustomer.Postal_Code__c.trim() != '')
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' Postal_Code__c like \'%' + String.escapeSingleQuotes(filterCustomer.Postal_Code__c.trim()) + '%\'';
        }
        if(filterCustomer.Street__c.trim() != '')
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' Street__c like \'%' + String.escapeSingleQuotes(filterCustomer.Street__c.trim()) + '%\'';
        }
                
        if(customerTypeId != null && customerTypeId.trim() != '')
        {
            strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') + ' RecordTypeId = \'' + customerTypeId + '\'' ;
        }
        
        if(filterCustomer.Global_Enterprise__c != null)
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' Global_Enterprise__c = \'' + String.escapeSingleQuotes(filterCustomer.Global_Enterprise__c) + '\'';
        }
        
        if(filterCustomer.Parent_Division__c != null)
        {
			strFilter = (strFilter.trim() != '' ?  strFilter + ' AND ' : '') +  ' Parent_Division__c = \'' + String.escapeSingleQuotes(filterCustomer.Parent_Division__c) + '\'';
        }        
    }
    
    public void searchCustomers()
    {
		foundResult = false;
        lstResults = new List<Customer__c>();
        
        createFilterString();
        
        if(strFilter.trim() != '')
        {
            String strQuery ='Select Id, Name , Legal_Name__c, DUNS__c, City__c, Country__c , RecordType.Name, Postal_Code__c, Street__c, Global_Enterprise__r.Legal_Name__c ,Parent_Division__r.Legal_Name__c  From Customer__c Where ';
            strQuery = strQuery + strFilter + ' Order By Name Limit 200';
            
            system.debug('==== strQuery : ' + strQuery);
            
            lstResults = database.query(strQuery);
            foundResult = (lstResults.size() > 0);               
        }
        else
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, NO_SEARCH_CRITERIA_ERROR));
        }
    }
    
    public void clearResults()
    {
        lstResults = new List<Customer__c>();
        foundResult = false;
        
        filterCustomer.Legal_Name__c = '';
        filterCustomer.DUNS__c = '';
        filterCustomer.City__c ='';
        filterCustomer.Street__c = '';
        filterCustomer.Postal_Code__c = '';
        filterCustomer.Global_Enterprise__c = null;
        filterCustomer.Parent_Division__c = null;
        strGlobalId='';
        strCountry='';
        
        customerTypeId = null;          
    }

}