src/objects/Customer_Project__c.object
<CustomObject>
    <description>CAS: Customer Project</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is created to lookup to Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Projects</relationshipLabel>
        <relationshipName>CAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Phase__c</fullName>
        <label>Project Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Selection</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                    <color>#33FF33</color>
                    <default>true</default>
                    <label>Green</label>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                    <color>#FFCC66</color>
                    <label>Yellow</label>
                </value>
                <value>
                    <fullName>Red</fullName>
                    <color>#FF0000</color>
                    <label>Red</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Board Pilot</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Disti</fullName>
                </value>
                <value>
                    <fullName>EMS</fullName>
                </value>
                <value>
                    <fullName>ODM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <description>Executive summary of the customer, the application, and the NXP parts used in the Opportunity.</description>
        <inlineHelpText>Executive summary of the customer, the application, and the NXP parts. Do not mentioned final ASP</inlineHelpText>
        <label>Executive Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Probability_to_Win__c</fullName>
        <description>1607 Release SIR 1030 - Probability to Win &amp; Help Needed &amp; Description on Oppty Object</description>
        <inlineHelpText>80-100%, Include in Most Likely for Qtr;					
50-80%, Define what is needed to win this Qtr. Actively working to move to 80-100% cat. List actions needed to secure win this Qtr  in Help Needed;					
0-50%, Unlikely to close this Qtr. Not counted in Most</inlineHelpText>
        <label>z_OBSOLETED_Probability to Win</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>80% - 100%</fullName>
                </value>
                <value>
                    <fullName>50% - 80%</fullName>
                </value>
                <value>
                    <fullName>0% - 50%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2010_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2010 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2011_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2011 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2012_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2012 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2013_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2013 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2014_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2014 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2015_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2015 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2016_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2016 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2017_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2017 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2018_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2018 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2019_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2019 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2020_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2020 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2021_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2021 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2022_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2022 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2023_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2023 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2024_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2024 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2025_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2025 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2026_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2026 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2027_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2027 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2028_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2028 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2029_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2029 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2030_Pieces__c</fullName>
        <defaultValue>0</defaultValue>
        <label>z_OBSOLETED_2030 Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Technical_Support_Team__c.object
<CustomObject>
    <description>CAS: Technical Support Team</description>
    <fields>
        <fullName>CAS_1_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAS 1 Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Project_Support</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAS_2_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAS 2 Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Project_Support1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <label>Customer Project</label>
        <referenceTo>Customer_Project__c</referenceTo>
        <relationshipName>Customer_Project_Support</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Technical Support Team</label>
    <nameField>
        <displayFormat>TST-{0000000}</displayFormat>
        <label>Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Support Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomerObjectSharingTest.cls
/* Last ModifiedBy : Baji
   Last ModifiedDate : 02 Jun 2017
   Description : Updated to remove the test data related to Opportunity Approval Setting.
*/ 

@istest
public class CustomerObjectSharingTest
{

    static testmethod void CustomerObjectSharingTest1()
    {
       date mydate1 = date.parse('05/24/2017');
       date mydate2 = date.parse('05/01/2017');
       
       //Create Parent Account
       Account a = new Account();
       a.Name='Test parent';
       insert a;
       
       //Create Child Account
       Account Child = new Account();
       child.name='Test Child';
       child.Parent=a;
       child.RecordtypeId=Schema.SObjectType.account.getRecordTypeInfosByName().get('Child Account').getRecordTypeId();
       insert child;
       
       //Create opportunity
       Opportunity Opp = new Opportunity();
       Opp.Name='Test opty';
       Opp.CloseDate=mydate1;
       Opp.Production_Date__c=mydate2;
       Opp.CurrencyIsoCode='USD';
       Opp.Probability_to_Win__c='80% - 100%';
       Opp.Account=Child;
       opp.Channel__c='Direct';
       opp.StageName='Discovery';
       opp.X2010_Pieces__c=1;
       opp.X2011_Pieces__c=1;
       opp.X2012_Pieces__c=1;
       opp.X2013_Pieces__c=1;
       opp.X2014_Pieces__c=1;
       opp.X2015_Pieces__c=1;
       opp.X2010_Pieces__c=1;
       opp.X2016_Pieces__c=1;
       opp.X2017_Pieces__c=1;
       opp.X2018_Pieces__c=1;
       opp.X2019_Pieces__c=1;
       opp.X2020_Pieces__c=1;
       opp.X2021_Pieces__c=1;
       opp.X2022_Pieces__c=1;
       opp.X2023_Pieces__c=1;
       opp.X2024_Pieces__c=1;
       opp.X2025_Pieces__c=1;
       opp.X2026_Pieces__c=1;
       opp.X2027_Pieces__c=1;
       opp.X2028_Pieces__c=1;
       opp.X2029_Pieces__c=1;
       opp.X2030_Pieces__c=1;
       opp.Executive_Summary__c='test';
       insert opp;
       
       
       //Insert Customer Project
       Customer_Project__c CP = new Customer_Project__c();
       CP.Name='Test Project';
       CP.Opportunity__c=opp.id;
       CP.Project_Phase__c='Development';
       CP.Project_Status__c='Green';
       insert CP;
       
       //Insert Techincal Project Team
       List<User> users = [SELECT Id FROM User WHERE IsActive = true LIMIT 2];
       Id User1Id = users[0].Id;
       Id User2Id = users[1].Id;
       
       Technical_Support_Team__c Team = new Technical_Support_Team__c();
       Team.Customer_Project__c=CP.Id;
       Team.CAS_1_Engineer__c=User1Id ;
       Team.CAS_2_Engineer__c=User2Id ;
       
       insert Team;
       
       list<Customer_Project__share> shares=[SELECT Id, UserOrGroupId, AccessLevel,RowCause FROM Customer_Project__share WHERE ParentId = :CP.Id AND (UserOrGroupId= :user2Id OR UserOrGroupId= :user1Id) ];
       
       System.assertEquals(shares.size(), 2);
       //for delete condition
       
       delete team;
       
 }

}