src/objects/Live_Chat_Survey_Answer__c.object
<CustomObject>
    <fields>
        <fullName>ChatKey__c</fullName>
        <label>ChatKey</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chat_Survey_Answer__c</fullName>
        <label>Chat Survey Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chat_Survey_Question__c</fullName>
        <label>Chat Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Live Chat Survey Answers</relationshipLabel>
        <relationshipName>Live_Chat_Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Live_Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Live Chat Survey Answers</relationshipLabel>
        <relationshipName>Live_Chat_Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Chat Survey Answer</label>
    <nameField>
        <label>Live Chat Survey Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Chat Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <description>Object to store community survey questions.</description>
    <fields>
        <fullName>Question__c</fullName>
        <description>Field to store question title.</description>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Field to store question type.</description>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Field to store picklist values</description>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityLiveAgentChatSurveyController.cls
/*********************************************************************************************
@Created By :      Venakteshwar G
@Created Date :    3 Oct 2016
Description :      Community Live Chat survey controller where user can submit survey feedback after 
                   User Ends the chat and the Suveys are linked to respective Chat Transcript.
****************************************************************************************************/

public class CommunityLiveAgentChatSurveyController 
{
    public List<SelectOption> lstQuesValues{get;set;}
    public String chatKey{get;set;} 
    public String strResolved{get;set;}
    public String strResolutionTime{get;set;}
    public String strSupportPerson{get;set;}
    public String strLikeOurSupport{get;set;}
    public String strComment{get;set;}
    public boolean flgChinese{get;set;}
    public String RedirectionToLoginPage{get;set;}
    public CommunityLiveAgentChatSurveyController()
    {
        //below line is added by shridevi for redirecting to login page upon logout.
        RedirectionToLoginPage=(Site.getPathPrefix()+Label.Community_Login_URL);
     
    }
       
    //create picklist values based on question value field
    public List<SelectOption> getQuesValues()
    {
        lstQuesValues = new List<SelectOption>();
        List<Survey_question__c> objSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Resolved ?' LIMIT 1];
        if(objSurveyQues.size()!=0 || objSurveyQues!=null)
        {
            List<String> lstStrQuesValue= objSurveyQues[0].value__c.split(',');
            for(string strValue: lstStrQuesValue)
            {
                lstQuesValues.add(new SelectOption(strValue,strValue));
            }            
        }
        return lstQuesValues;
    }
    
    //create picklist values based on question value field
    public List<SelectOption> getQuesValues1()
    {
        lstQuesValues = new List<SelectOption>();
        List<Survey_question__c> objSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Like Our Support ?' LIMIT 1];
        if(objSurveyQues.size()!=0 || objSurveyQues!=null)
        {
            List<String> lstStrQuesValue= objSurveyQues[0].value__c.split(',');
            for(string strValue: lstStrQuesValue)
            {
                lstQuesValues.add(new SelectOption(strValue,strValue));
            }            
        }
        return lstQuesValues;
    }
       
    //method to submit survey answers for five question records
   
    public Pagereference submitSurvey()
    {
        List<Survey_question__c> lstSurveyQues = new List<Survey_question__c>();
        List<Live_Chat_Survey_Answer__c> lstSurveyAns = new List<Live_Chat_Survey_Answer__c>();
        lstSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Resolved ?' LIMIT 1];
        if(lstSurveyQues.size()!=0 || lstSurveyQues!=null)
        {
            Live_Chat_Survey_Answer__c objAns= new Live_Chat_Survey_Answer__c();
            Id quesId;
            objAns.ChatKey__c = chatkey;
            quesId=lstSurveyQues[0].id;
            objAns.Chat_Survey_Question__c= quesId;
            objAns.Chat_Survey_Answer__c= strResolved;
            lstSurveyAns.add(objAns);
        }
        lstSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Resolution Time ?' LIMIT 1];
        if(lstSurveyQues.size()!=0 || lstSurveyQues!=null)
        {
            Live_Chat_Survey_Answer__c objAns= new Live_Chat_Survey_Answer__c();
            objAns.ChatKey__c = chatkey;
            objAns.Chat_Survey_Question__c= lstSurveyQues[0].id;
            objAns.Chat_Survey_Answer__c= strResolutionTime;
            lstSurveyAns.add(objAns);
        }
        lstSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Support Person ?' LIMIT 1];
        if(lstSurveyQues.size()!=0 || lstSurveyQues!=null)
        {
            Live_Chat_Survey_Answer__c objAns= new Live_Chat_Survey_Answer__c();
            objAns.ChatKey__c = chatkey;
            objAns.Chat_Survey_Question__c= lstSurveyQues[0].id;
            objAns.Chat_Survey_Answer__c= strSupportPerson;
            lstSurveyAns.add(objAns);
        }
        lstSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Like Our Support ?' LIMIT 1];
        if(lstSurveyQues.size()!=0 || lstSurveyQues!=null)
        {
            Live_Chat_Survey_Answer__c objAns= new Live_Chat_Survey_Answer__c();
            objAns.ChatKey__c = chatkey;
            objAns.Chat_Survey_Question__c= lstSurveyQues[0].id;
            objAns.Chat_Survey_Answer__c= strLikeOurSupport;
            lstSurveyAns.add(objAns);
        }
        lstSurveyQues= [Select id, name, question__c,type__c,value__c from survey_question__c 
                                           where name='Chat Comments' LIMIT 1];
        if((lstSurveyQues.size()!=0 || lstSurveyQues!=null) && (strComment!=null || strComment!=''))
        {
            Live_Chat_Survey_Answer__c objAns= new Live_Chat_Survey_Answer__c();
            objAns.ChatKey__c = chatkey;
            objAns.Chat_Survey_Question__c= lstSurveyQues[0].id;
            objAns.Chat_Survey_Answer__c= strComment;
            lstSurveyAns.add(objAns);
        }
        
        try 
        {
            insert lstSurveyAns;  
            PageReference pageRef;
            pageRef=new PageReference('/CommunityLiveChatSurveySuccess');
            if(flgChinese==True)
            {  
            pageRef=new PageReference('/CommtyLiveSurveyChineseSuccessPage');
            }
            
            pageref.setRedirect(true);
            return pageref;
        }
        catch (DMLException e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in submitting survey feedback'));           
            return null;
        }
        
    }
    
    //method to link the Chat Surveys with the respective Live Chat Transcript records based on the Chta key
   Public static void linkChatSurveyToTranscript(List<LiveChatTranscript> lstliveChatTranscript)
   {   
   List<Live_Chat_Survey_Answer__c> lstChatSurvey= new List<Live_Chat_Survey_Answer__c>();
   List<Live_Chat_Survey_Answer__c> lstUpdateChatSurvey= new List<Live_Chat_Survey_Answer__c>();
   lstChatSurvey=[Select Id, ChatKey__c,  Chat_Survey_Answer__c,  Chat_Survey_Question__c, Live_Chat_Transcript__c From 
                Live_Chat_Survey_Answer__c where ChatKey__c!= null And Live_Chat_Transcript__c= null];
      
   Set<Live_Chat_Survey_Answer__c> setChatSurvey = new Set<Live_Chat_Survey_Answer__c>(lstChatSurvey); 
          
      for(LiveChatTranscript livchTrans :lstliveChatTranscript)
      {  
        for(Live_Chat_Survey_Answer__c objSur : setChatSurvey)
        {
          if(objSur.ChatKey__c == livchTrans.chatKey)
          {
             objSur.Live_Chat_Transcript__c = livchTrans.Id;
             lstUpdateChatSurvey.add(objSur);
             setChatSurvey.remove(objSur);
          }
        }  
              
      }
               update  lstUpdateChatSurvey;
           
  
 }
 
 //method to delete the related Chat survey answers of the Live Chat Transcript when the Chta Transcript is deleted
 Public static void deleteChatSurveyOfTranscript(List<LiveChatTranscript> lstliveChatTranscript)
 {
 List<Live_Chat_Survey_Answer__c> lstdelChatSurvey= new List<Live_Chat_Survey_Answer__c>();
 lstdelChatSurvey=[Select Id, ChatKey__c,  Chat_Survey_Answer__c,  Chat_Survey_Question__c, Live_Chat_Transcript__c From 
                Live_Chat_Survey_Answer__c where Live_Chat_Transcript__c In: lstliveChatTranscript];
 delete lstdelChatSurvey;
 }

}