src/objects/Model_N__c.object
<CustomObject>
    <description>This objects captures the information required for Model N user registeration</description>
    <fields>
        <fullName>Access_Type__c</fullName>
        <label>Access Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New User</fullName>
                </value>
                <value>
                    <fullName>Change Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Org_VAR__c</fullName>
        <label>Assigned Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VAR AMEC - ATMI</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - BAE</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - CJR</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - CTC</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - DYNE-A-MARK</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - GIESTING</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - LOGIX SALES</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - MERCER TECH SALES</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - PHOENIX</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - SELTEC</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - STARVOY</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - TAI</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC -THE NOVUS GROUP</fullName>
                </value>
                <value>
                    <fullName>VAR AMEC - THOM LUKE SALES</fullName>
                </value>
                <value>
                    <fullName>VAR EMEA - EKOM</fullName>
                </value>
                <value>
                    <fullName>VAR EMEA -MECHIONI</fullName>
                </value>
                <value>
                    <fullName>VAR EMEA - MT SYSTEMS</fullName>
                </value>
                <value>
                    <fullName>VAR EMEA - SCANTEC</fullName>
                </value>
                <value>
                    <fullName>VAR EMEA - SPECIAL-IND</fullName>
                </value>
                <value>
                    <fullName>VAR EMEA - TRITECH</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  AGIANT SEMICONDUCTORS</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  ANTEXUN</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  ARCOTEK</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  BOCCN</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  BRITESTONE</fullName>
                </value>
                <value>
                    <fullName>VAR GC - CHUNDGA</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  CHUNGDA</fullName>
                </value>
                <value>
                    <fullName>VAR GC - COMTECH INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>VAR GC -  DADOUTEK</fullName>
                </value>
                <value>
                    <fullName>VAR GC - DCT TECH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Edit_Org__c</fullName>
        <label>Edit Org.</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NXP Semiconductors</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Worldwide Distribution</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_email_address__c</fullName>
        <label>Manager email address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Read_Org__c</fullName>
        <label>Read Org.</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NXP Semiconductors</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Worldwide Distribution</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>South Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Hierarchy_Country_Region__c</fullName>
        <label>Role Hierarchy - Country Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Role_Hierarchy_Sub_Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Abkhazia</fullName>
                </value>
                <value>
                    <fullName>Arrow EMEA</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Avnet EMEA</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Baltics</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                </value>
                <value>
                    <fullName>British Islands</fullName>
                </value>
                <value>
                    <fullName>Central Other</fullName>
                </value>
                <value>
                    <fullName>East North</fullName>
                </value>
                <value>
                    <fullName>East Other</fullName>
                </value>
                <value>
                    <fullName>East South</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Future EMEA</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Iberia</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Moldova</fullName>
                </value>
                <value>
                    <fullName>Nagorno-Karabakh</fullName>
                </value>
                <value>
                    <fullName>Nordic</fullName>
                </value>
                <value>
                    <fullName>North Other</fullName>
                </value>
                <value>
                    <fullName>Regional EMEA</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>South Ossetia</fullName>
                </value>
                <value>
                    <fullName>South Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Roles_Category__c</fullName>
        <label>Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Lines</fullName>
                </value>
                <value>
                    <fullName>Disti Sales</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>F&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Support 1st line</fullName>
                </value>
                <value>
                    <fullName>Support 2nd line</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>User a/c created</fullName>
                </value>
                <value>
                    <fullName>Change made</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tel_Mobile__c</fullName>
        <label>Tel/Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NXP User</fullName>
                </value>
                <value>
                    <fullName>Disti User</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Model N User Registration</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Model N User Registeration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model N User Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserRegistrationController.cls
/*******************************************************************************************************
Name        :     UserRegistrationController
page        :     UserRegistration
Author      :     
Date        :        17 May,2011
Description :     class for page UserRegistration, to provide the user registartion functionality
*******************************************************************************************************/

public class UserRegistrationController{//
    public Boolean changeAcc{get;set;}
    public Boolean Flag{get;set;}
    public Boolean First{get;set;}
    public String accesstype{get;set;}
    public Boolean nxp{get;set;}
    public Boolean disti{get;set;}
    public Boolean sales {get;set;}
    public Boolean var{get;set;}
    public Model_N__c modelN{get;set;}
    public String usertype{get;set;}
    public boolean success{get;set;}
    public boolean nextnxp{get;set;}
    public boolean nextdisti{get;set;}
    public boolean nextSales{get;set;}
    public boolean nextvar{get;set;}
    private String errorMessage='';
    private boolean isValid=true;
    public void init(){
        First = true;
        Flag = false;
        nxp = false;
        disti = false;
        sales = false;
        var = false;
        success = false;
        nextnxp = false;
        nextdisti = false;
        nextSales = false;
        nextvar = false;
        modelN = new Model_N__c();
    }
    public UserRegistrationController(){
        Flag = false;
        First = true;
        nxp = false;
        disti = false;
        sales = false;
        var = false;
        changeAcc = false;
        success = false;
        nextnxp = false;
        nextdisti = false;
        nextSales = false;
        nextvar = false;
        modelN = new Model_N__c();
    }
    
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('NXP User','NXP User'));
        options.add(new SelectOption('Disti User','Disti User'));
        options.add(new SelectOption('Sales Rep','Sales Rep'));
        options.add(new SelectOption('VAR','VAR'));
        return options;
    }
    public void nextAType(){
        System.debug('### USer Type : '+usertype);
        if(accesstype.trim().length() > 0){
            if(accesstype == 'New User'){
                First = false;
                Flag = true;
            }else{
                First = false;
                Flag = true;
                changeAcc = true;
            }
            modelN.Access_Type__c = accesstype;
            modelN.User_Type__c = usertype;
            modelN.CurrencyIsoCode = 'EUR';
        }
    }
    public void Registration(){
       
        if(Flag == true && usertype != null){    
            if(usertype.trim().length() > 0){
                if(usertype == 'NXP User'){
                    Flag = false;
                    nxp = true;
                    disti = false;
                    sales = false;
                    var = false;
                }else if(usertype == 'Disti User'){
                    Flag = false;
                    nxp = false;
                    sales = false;
                    var = false;
                    disti = true;
                }else if(usertype == 'Sales Rep'){
                    Flag = false;
                    nxp = false;
                    sales = True;
                    var = false;
                    disti = false;
                }else{
                    Flag = false;
                    nxp = false;
                    sales = false;
                    var = true;
                    disti = false;
                }
                modelN.User_Type__c = usertype;
                modelN.CurrencyIsoCode = 'EUR';
            }else{
                Flag = true;
                nxp = false;
                disti = false;
                sales = false;
                var = false;
                First = false;
            }
        }
        System.Debug('@@@@Access Type is '+modelN.Access_Type__c);
    }
    
    public void save(){
        system.debug('### : USerType '+modelN.User_Type__c);
        if(modelN.User_Type__c.trim().length() > 0 && modelN.User_Type__c == 'NXP User' ){
          system.debug('### : USerType '+modelN);
          if(modelN.Region__c != null && modelN.Manager_Name__c != null && modelN.Manager_email_address__c != null && modelN.Tel_Mobile__c != null && modelN.Roles_Category__c != null /*&& modelN.Read_Org__c != null && modelN.Edit_Org__c != null*/){
            //modelN.name = modelN.Last_Name__c+' '+modelN.First_Name__c;
            modelN.Status__c= 'Submitted';
            modelN.Assigned_Org_VAR__c='';
            modelN.Role_Hierarchy_Country_Region__c='';
            modelN.Role_Hierarchy_Country_Sub_Region__c='';
            modelN.Role_Hierarchy_Region__c='';
            modelN.Role_Hierarchy_Sub_Region__c='';
            upsert modelN;
            flag=false;
            nxp=false;
            disti = false;
            sales = false;
            var = false;
            success = true;
            nextnxp = false;
            nextdisti = false;
            nextSales= false;
            nextvar = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Your application has been successfully submitted and a response to your request will arrive shortly. The user will not be able to logon to the system until the registration has been approved. If you do not receive a response, Please contact Global Sales Application support at globalsales.appsupport@nxp.com for any assistance.'));
          } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Record Not Saved !!'));
          }
        }else if(modelN.User_Type__c.trim().length() > 0 && modelN.User_Type__c == 'Disti User' ){
            if(modelN.First_Name__c != null && modelN.Last_Name__c != null && modelN.Company_Name__c != null && modelN.Company_Address__c != null && modelN.Job_Title__c != null){
            //modelN.name = modelN.Last_Name__c+' '+modelN.First_Name__c;
            modelN.Status__c= 'Submitted';
            modelN.Edit_Org__c ='';
            modelN.Read_Org__c ='';
            modelN.Edit_Org_Sub_Category__c ='';
            modelN.Read_Org_Sub_Category__c ='';
            modelN.Assigned_Org_VAR__c='';
            upsert modelN;
            flag=false;
            nxp=false;
            disti = false;
            sales = false;
            var = false;
            success = true;
            nextnxp = false;
            nextdisti = false;
            nextsales = false;
            nextvar = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Your application has been successfully submitted and a response to your request will arrive shortly. The user will not be able to logon to the system until the registration has been approved. If you do not receive a response, Please contact Global Sales Application support at globalsales.appsupport@nxp.com for any assistance.'));
          } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Record Not Saved !!'));
          }
        }else if(modelN.User_Type__c.trim().length() > 0 && modelN.User_Type__c == 'Sales Rep' ){
            if(modelN.First_Name__c != null && modelN.Last_Name__c != null && modelN.Company_Name__c != null && modelN.Company_Address__c != null && modelN.Job_Title__c != null && modelN.Manager_Name__c != null && modelN.Manager_email_address__c != null && modelN.Tel_Mobile__c != null){
            modelN.Status__c= 'Submitted';
            modelN.Edit_Org_Sub_Category__c ='';
            modelN.Read_Org_Sub_Category__c ='';
            modelN.Assigned_Org_VAR__c='';
            upsert modelN;
            flag=false;
            nxp=false;
            disti = false;
            sales = false;
            var = false;
            success = true;
            nextnxp = false;
            nextdisti = false;
            nextsales = false;
            nextvar = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Your application has been successfully submitted and a response to your request will arrive shortly. The user will not be able to logon to the system until the registration has been approved. If you do not receive a response, Please contact Global Sales Application support at globalsales.appsupport@nxp.com for any assistance.'));    
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Record Not Saved !!'));
            }
        }else{
            if(modelN.First_Name__c != null && modelN.Last_Name__c != null && modelN.Company_Name__c != null && modelN.Company_Address__c != null && modelN.Job_Title__c != null && modelN.Tel_Mobile__c != null){
            modelN.Status__c= 'Submitted';
            
            modelN.Edit_Org_Sub_Category__c ='';
            modelN.Read_Org_Sub_Category__c ='';
            modelN.Role_Hierarchy_Country_Region__c='';
            modelN.Role_Hierarchy_Country_Sub_Region__c='';
            modelN.Role_Hierarchy_Region__c='';
            modelN.Role_Hierarchy_Sub_Region__c='';
            modelN.Read_Org__c='';
            modelN.Edit_Org__c='';
            modelN.Manager_email_address__c='';
            modelN.Manager_Name__c='';
            
            upsert modelN;
            flag=false;
            nxp=false;
            disti = false;
            sales = false;
            var = false;
            success = true;
            nextnxp = false;
            nextdisti = false;
            nextsales = false;
            nextvar = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Your application has been successfully submitted and a response to your request will arrive shortly. The user will not be able to logon to the system until the registration has been approved. If you do not receive a response, Please contact Global Sales Application support at globalsales.appsupport@nxp.com for any assistance.'));    
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Record Not Saved !!'));
            }
        }
    }
    
    public void back(){
        if(Flag){
            First = true;
            Flag = false;
        }else{
            Flag = false;
            First = true;
        }
        if(nxp){
            nxp = false;
            Flag = true;
            First = false;
        }
        disti = false;
        sales = false;
        var = false;
        nextnxp = false;
        nextdisti = false;
        nextsales = false;
        nextvar = false;
    }
    
    public void backnxp(){
        Flag = false;
        nxp = true;
        disti = false;
        sales = false;
        var = false;
        nextnxp = false;
        nextdisti = false;
        nextsales = false;
        nextvar = false;
        if(accesstype == 'Change Access'){
            changeacc = true;
        }
    }
    
    public void backdisti (){
        Flag = false;
        nxp = false;
        disti = true;
        sales = false;
        var = false;
        nextnxp = false;
        nextdisti = false;
        nextsales = false;
        nextvar = false;
        if(accesstype == 'Change Access'){
            changeacc = true;
        }
    }
    
    public void backSales (){
        Flag = false;
        nxp = false;
        disti = false;
        sales = true;
        var = false;
        nextnxp = false;
        nextdisti = false;
        nextsales = false;
        nextvar = false;
        if(accesstype == 'Change Access'){
            changeacc = true;
        }
    }
    
    public void backVar (){
        Flag = false;
        nxp = false;
        disti = false;
        sales = false;
        var = true;
        
        nextnxp = false;
        nextdisti = false;
        nextsales = false;
        nextvar = false;
        if(accesstype == 'Change Access'){
            changeacc = true;
        }
    }
    
    private boolean validateFields(){
        if(!(validateField(modelN.User_Type__c))){
            errorMessage='<li>User Type is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.First_Name__c))){
            errorMessage+='<li>First Name is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Last_Name__c))){
            errorMessage+='<li>Last Name is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Email_Address__c))){
            errorMessage+='<li>Email Address is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Requester_Email_Address__c))){
            isValid=false;
            errorMessage+='<li>Requester Email Address is Required!</li>';
        }
        /*if(isValid==false){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }*/
        return isValid;
    }
    private boolean validateCompany(){
        if(!(validateField(modelN.Company_Name__c))){
            errorMessage+='<li>Company Name is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Company_Address__c))){
            errorMessage+='<li>Company Address is Required!</li>';
            isValid=false;
        }
        return isValid;
    }
    private boolean validateManager(){
        if(!(validateField(modelN.Manager_Name__c))){
            errorMessage+='<li>Manager Name is Required!</li>';
            isValid=false; 
        }
        if(!(validateField(modelN.Manager_email_address__c))){
            errorMessage+='<li>Manager Email Address is Required!</li>';
            isValid=false;
        }
        return isValid;
    }
    private boolean validateField(String value){
        if(value!=null && value.trim().length()>0)
            return true;
        return false;
    }
    private Boolean validate_EditOrgSubCategory(){
        if(validateField(modelN.Edit_Org__c)){
            List<String> stList1 = modelN.Edit_Org__c.split(';');
            for(String val :stList1){
                if(val.equalsIgnoreCase('Worldwide distribution')){
                    return true;
                }
            }
        }
        return false;
    }
    private Boolean validate_ReadOrgSubCategory(){
        if(validateField(modelN.Read_Org__c)){
            List<String> stList2 = modelN.Read_Org__c.split(';');
            for(String val :stList2){
                if(val.equalsIgnoreCase('Worldwide distribution')){
                    return true;
                }
            }
        }
        return false;
    }
    public void nxtNxp(){
        
        isValid=true;
        System.debug('@@');
        String valEn=ApexPages.currentPage().getParameters().get('j_id0:frm:nxp:pbs2:RHRN');
        System.debug('@@Enabled==#'+valEn+'#');
        String valDs=ApexPages.currentPage().getParameters().get('j_id0:frm:nxp:pbs2:RHSN');
        System.debug('@@Disabled==#'+valDs+'#');
        errorMessage='';
                
        validateFields();
        
        if(!(validateField(modelN.Region__c))){
            errorMessage+='<li>Region is Required!</li>';
            isValid=false;
        }
        validateManager();
        if(!(validateField(modelN.Tel_Mobile__c))){
            errorMessage+='<li>Tel Mobile is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Roles_Category__c))){
            errorMessage+='<li> Function is Required!</li>';
            isValid=false;
        }else if(modelN.Roles_Category__c== 'Business Lines'){
            if(!(validateField(modelN.BU__c))){
                errorMessage+='<li> BU is Required!</li>';
                isValid=false;
            }
            if(!(validateField(modelN.MAGS__c))){
                errorMessage+='<li> MAGS is Required!</li>';
                isValid=false;
            }
        }
        if(!(validateField(modelN.Role_Sub_Category__c))){
            errorMessage+='<li>Roles is Required!</li>';
            isValid=false;
        }
        /*if(!(validateField(modelN.Read_Org__c))){
            errorMessage+='<li>Read Org is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Edit_Org__c))){
            errorMessage+='<li> Edit Org is Required!</li>';
            isValid=false;
        }*/
        //*********************************
        if(validate_ReadOrgSubCategory()){
            if(!validateField(modelN.Read_Org_Sub_Category__c)){
                errorMessage+='<li>Select Read Org Sub Category For <b>Worldwide distribution</b>!</li>';
                isValid = false;
            }
        }
        if(validate_EditOrgSubCategory()){
            if(!validateField(modelN.Edit_Org_Sub_Category__c)){
                errorMessage+='<li>Select Edit Org Sub Category For <b>Worldwide distribution</b>!</li>';
                isValid = false;
            }
        }
        /*if(!(validateField(modelN.Role_Hierarchy_Region__c))){
            errorMessage+='<li>Roles Hierarchy Region is Required!</li>';
            isValid=false;
        }
        String valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:nxp:pbs2:RHSN');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Sub_Region__c))){
            errorMessage+='<li>Role Hierarchy Sub Region is Required!</li>';
            isValid=false;
        } 
        valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:nxp:pbs2:RHCN');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Country_Region__c))){
            errorMessage+='<li>Role Hierarchy Country Region is Required!</li>';
            isValid=false;
        } 
        valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:nxp:pbs2:RHCSN');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Country_Sub_Region__c))){
            errorMessage+='<li>Role Hierarchy Country Sub Region is Required!</li>';
            isValid=false;
        }*/
        if(isValid){  
            changeAcc = false;                  
            Flag = false;
            nxp = false;
            disti = false;
            sales = false;
            var = false;
            nextnxp = true;
            nextdisti = false;
            nextsales = false;
            nextvar = false;
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }
    }
    
    public void nxtDisti(){
        changeAcc = false;
        isValid=true;
         errorMessage='';
        validateFields();
        
        if(!(validateField(modelN.Job_Title__c))){
            errorMessage+='<li>Job Title is Required!</li>';
            isValid=false;
        }
       if(!(validateField(modelN.Roles_Disti_new__c))){
            errorMessage+='<li>Roles Disti is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Disti_Role_Hierarchy__c))){
            errorMessage+='<li>Assigned Org is Required!</li>';
            isValid=false;
        }
        validateCompany();
        
        if(isValid){        
            Flag = false;
            changeAcc = false;
            nxp = false;
            disti = false;
            sales = false;
            var = false;
            nextnxp = false;
            nextdisti = true;
            nextsales = false;
            nextvar = false;
        }else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }
    }
    
    public void nxtSales(){
        isValid=true;
        changeAcc = false;
         errorMessage='';
        validateFields();
        validateCompany();
        if(!(validateField(modelN.Role_Hierarchy_Region__c))){
            errorMessage+='<li>Role Hierarchy Region is required!</li>';
            isValid=false;
        }
        /*if(!(validateField(modelN.Read_Org__c))){
            errorMessage+='<li>Read Org is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Edit_Org__c))){
            errorMessage+='<li> Edit Org is Required!</li>';
            isValid=false;
        } */
        if(!(validateField(modelN.Tel_Mobile__c))){
            errorMessage+='<li>Tel/Mobile Number is Required!</li>';
            isValid=false;
        }
        String valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:Sales:pbs3:RHSS');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Sub_Region__c))){
            errorMessage+='<li>Role Hierarchy Sub Region is Required!</li>';
            isValid=false;
        } 
        valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:Sales:pbs3:RHCS');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Country_Region__c))){
            errorMessage+='<li>Role Hierarchy Country Region is Required!</li>';
            isValid=false;
        } 
        valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:Sales:pbs3:RHCSS');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Country_Sub_Region__c))){
            errorMessage+='<li>Role Hierarchy Country Sub Region is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Job_Title__c))){
            errorMessage+='<li>Job Title is required!</li>';
            isValid=false;
        }
        if(isValid){
            Flag = false;
            nxp = false;
            disti = false;
            sales = false;
            var = false;
            nextnxp = false;
            nextdisti = false;
            nextsales = true;
            nextvar = false;
        }else {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }    
    }
    
    public void nxtVar(){
        isValid=true;
        errorMessage='';
        validateFields();
        validateCompany();
        if(!(validateField(modelN.Job_Title__c))){
            errorMessage+='<li>Job Title is required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Tel_Mobile__c))){
            errorMessage+='<li>Tel Mobile is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Assigned_Org_VAR__c))){
            errorMessage+='<li> Assigned Org is Required!</li>';
            isValid=false;
        }
        //validateManager();
        /*if(!(validateField(modelN.Role_Hierarchy_Region__c))){
            errorMessage+='<li>Roles Hierarchy Region is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Read_Org__c))){
            errorMessage+='<li>Read Org is Required!</li>';
            isValid=false;
        }
        if(!(validateField(modelN.Edit_Org__c))){
            errorMessage+='<li> Edit Org is Required!</li>';
            isValid=false;
        }*/
        
        /*String valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:Var:pbs4:RHSV');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Sub_Region__c))){
            errorMessage+='<li>Role Hierarchy Sub Region is Required!</li>';
            isValid=false;
        } 
        valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:Var:pbs4:RHCV');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Country_Region__c))){
            errorMessage+='<li>Role Hierarchy Country Region is Required!</li>';
            isValid=false;
        } 
        valReg=ApexPages.currentPage().getParameters().get('j_id0:frm:Var:pbs4:RHCSV');
        if(valReg!='__' && !(validateField(modelN.Role_Hierarchy_Country_Sub_Region__c))){
            errorMessage+='<li>Role Hierarchy Country Sub Region is Required!</li>';
            isValid=false;
        }*/
        if(isValid){
            Flag = false;
            nxp = false;
            disti = false;
            sales = false;
            var = false;
            nextnxp = false;
            nextdisti = false;
            nextsales = false;
            nextvar = true;
            changeAcc = false;
        }else {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }
    }
    public pageReference register(){
        pageReference pg = new pageReference('/apex/UserRegistration');
        init();
        return pg;
    }
}