src/objects/Natterbox_Call_Reporting_Object__c.object
<CustomObject>
    <description>This is the repository for all Natterbox call data. At the end of every call, Natterbox will populate this object with over 60 data points for the call. All Natterbox reports and dashboards are generated with data from this object.</description>
    <fields>
        <fullName>Bridge_UUID__c</fullName>
        <description>Internal Use only. The unique identifier for a bridged leg of a call.</description>
        <inlineHelpText>Internal Use only. The unique identifier for a bridged leg of a call.</inlineHelpText>
        <label>Bridge UUID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wrapup_String_1__c</fullName>
        <inlineHelpText>The first Wrapup String entered by the user on the Natterbox CTI.</inlineHelpText>
        <label>Wrapup String 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wrapup_String_2__c</fullName>
        <inlineHelpText>The second Wrapup String entered by the user on the Natterbox CTI.</inlineHelpText>
        <label>Wrapup String 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Natterbox Call Reporting Object</label>
    <nameField>
        <label>Customer Service Calls Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Natterbox Call Reporting Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateWrapupCodesForNCRO.cls
@isTest
public class TestUpdateWrapupCodesForNCRO {
	@isTest
    public static void testNCRODataWrapupUpdate(){
    	List<Natterbox_Call_Reporting_Object__c> nboxdata = Test.loadData(Natterbox_Call_Reporting_Object__c.sObjectType, 'nbox_test_data_ncro');    
		List<Task> nboxtaskdata = Test.loadData(Task.sObjectType, 'nbox_test_data_task');            
        System.assert(nboxdata.size()>0);
        System.assert(nboxtaskdata.size()>0);
        System.debug(' data loaded '+nboxdata.size());
        Test.startTest();
        Database.executeBatch(new UpdateWrapupCodesForNCRO());
        Test.stopTest();
        List<Natterbox_Call_Reporting_Object__c> updatednboxdata = [SELECT Id,Wrapup_String_1__c, Wrapup_String_2__c, Bridge_UUID__c from Natterbox_Call_Reporting_Object__c where (Wrapup_String_1__c = null OR Wrapup_String_2__c = null) and Bridge_UUID__c <> null];
		System.assert(updatednboxdata == null || updatednboxdata.size()==0);
    }
}