src/objects/New_User_Registeration__c.object
<CustomObject>
    <description>This is a Custom object which captures all the information while creating a new user.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved - Awaiting user licenses.</fullName>
                </value>
                <value>
                    <fullName>User A/c Created</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Made</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>New User Registeration</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>New User Registeration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New User Registerations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FutureUpdateStatus.cls
/*********************************************************************************
Name           :    FutureUpdateStatus
Author         :    
Date           :    12 June 2011
Description    :    This Future Class is called by Trigger "UpdateStatus_NewUserRegistration".                    
**********************************************************************************/
public class FutureUpdateStatus{
    
    @Future(callout=true)
    public static void updateStatus(Set<String> ids){
        List<New_User_Registeration__c> newUserList = [Select id,name,status__c from New_User_Registeration__c where id in: ids];
        if(newUserList.size()>0){
            for(New_User_Registeration__c newUsr: newUserList){
                newUsr.status__c = 'User A/c Created';
            }
            update newUserList;
        } 
    }
}