src/objects/New_User_Registeration__c.object
<CustomObject>
    <description>This is a Custom object which captures all the information while creating a new user.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved - Awaiting user licenses.</fullName>
                </value>
                <value>
                    <fullName>User A/c Created</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Change Made</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>New User Registeration</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>New User Registeration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New User Registerations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFutureUpdateStatus.cls
/*  
   @Last Modified By     : Manoj 
   @Last Modified Date   : 09 Mar, 2015 
   @Description : Added @isTest annotation at class level. 
*/

@isTest
public class TestFutureUpdateStatus{
    @isTest
    private static void TestFutureUpdateStatus(){
        New_User_Registeration__c nur = new New_User_Registeration__c();
        nur.First_Name__c = 'Test';
        nur.Last_Name__c = 'Test';
        insert nur;                        
        Set<string> ids = new Set<string>();
        ids.add(nur.id);        
        FutureUpdateStatus.updateStatus(ids);
        List<New_User_Registeration__c> nwList = [select id,name,status__C from New_User_Registeration__c where id in: ids and status__C = 'User A/c Created'];
        system.assert(ids.size() != nwLIst.size(), 'Updation Failed');
    }
}