src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BL_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate Bl approver</description>
        <label>BL Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGaS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGac</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGaT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGar</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGb1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFyk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFyu</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFz9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_VP_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFJpr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Director_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Sales Director approver for opportunity</description>
        <label>Sales Director Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesF8rX</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesqnFo</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityApproverPlugin.cls
global class OpportunityApproverPlugin implements Process.Plugin {
	@TestVisible
	private static final Map<ApproverLabel, String> APPROVER_LABELS = new Map<ApproverLabel, String>();
	    
	static {
		APPROVER_LABELS.put(ApproverLabel.SALES_DIRECTOR_APPROVER, Opportunity.Sales_Director_Approver__c.getDescribe().getLabel());	
		APPROVER_LABELS.put(ApproverLabel.REGIONAL_VP_APPROVER, Opportunity.Regional_VP_Approver__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.VP_APPROVER_2, Opportunity.VP_Approver_2__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_1, Opportunity.MAG_Approver_1__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_2, Opportunity.MAG_Approver_2__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_3, Opportunity.MAG_Approver_3__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_4, Opportunity.MAG_Approver_4__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_5, Opportunity.MAG_Approver_5__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_6, Opportunity.MAG_Approver_6__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_7, Opportunity.MAG_Approver_7__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_8, Opportunity.MAG_Approver_8__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_9, Opportunity.MAG_Approver_9__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.MAG_APPROVER_10, Opportunity.MAG_Approver_10__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.BL_APPROVER_1, Opportunity.BL_Approver_1__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.BL_APPROVER_2, Opportunity.BL_Approver_2__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.BL_APPROVER_3, Opportunity.BL_Approver_3__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.BL_APPROVER_4, Opportunity.BL_Approver_4__c.getDescribe().getLabel());
		APPROVER_LABELS.put(ApproverLabel.BL_APPROVER_5, Opportunity.BL_Approver_5__c.getDescribe().getLabel());
	}

	@TestVisible
	enum ApproverLabel {SALES_DIRECTOR_APPROVER,
						REGIONAL_VP_APPROVER, VP_APPROVER_2, 
						MAG_APPROVER_1, MAG_APPROVER_2, MAG_APPROVER_3, MAG_APPROVER_4, MAG_APPROVER_5, 
        				MAG_APPROVER_6, MAG_APPROVER_7, MAG_APPROVER_8, MAG_APPROVER_9, MAG_APPROVER_10,
						BL_APPROVER_1, BL_APPROVER_2, BL_APPROVER_3, BL_APPROVER_4, BL_APPROVER_5}
    
    global Process.PluginResult invoke(Process.PluginRequest request) {
        String OpptyId = (String) request.inputParameters.get('Id');
        Map<String,String> result = new Map<String,String>();
        try
        {
            Map<String,String> allApprovers = OpportunityApproval.getAllApprovers(OpptyId);
            for(String key : allApprovers.keySet())
            {
				result.put(key, allApprovers.get(key));
                System.debug('@@@' + key + ',' + allApprovers.get(key));
            }
            result.put('Message', 'Success');
        } catch (Exception err)
        {
            System.debug('@@@' + err.getMessage());
            System.debug('@@@' + err.getStackTraceString());
            result.put('Message', 'EXCEPTION: ' + err.getMessage());
        }
        return new Process.PluginResult(result);
    }
    
    global Process.PluginDescribeResult describe() {
        Process.PluginDescribeResult result = new Process.PluginDescribeResult();
		result.Name = 'Look Up Approver Name';
		result.Tag = 'Approver';
		result.inputParameters = new
		List<Process.PluginDescribeResult.InputParameter> {
			new Process.PluginDescribeResult.InputParameter('Id',
			Process.PluginDescribeResult.ParameterType.STRING, true)
			};

        result.outputParameters = new
		List<Process.PluginDescribeResult.OutputParameter> {
			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.SALES_DIRECTOR_APPROVER),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.REGIONAL_VP_APPROVER), 
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.VP_APPROVER_2),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_1),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_2),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_3),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_4),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_5),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_6),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_7),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_8),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_9),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.MAG_APPROVER_10),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.BL_APPROVER_1),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.BL_APPROVER_2),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.BL_APPROVER_3),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.BL_APPROVER_4),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter(APPROVER_LABELS.get(ApproverLabel.BL_APPROVER_5),
                Process.PluginDescribeResult.ParameterType.STRING),
   			new Process.PluginDescribeResult.OutputParameter('Message',
                Process.PluginDescribeResult.ParameterType.STRING)                
			};
		return result;
    }
}