src/objects/Opportunity_Claim_Value_Setting__mdt.object
<CustomObject>
    <description>General setting for Opportunity Claim Value calculation</description>
    <fields>
        <fullName>Account_CBG__c</fullName>
        <description>If opportunity account CBG equals the value, claim value is lifetime.</description>
        <label>Account CBG</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cross_Update_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, allow products claim values to be updated if triggered from objects other than Opportunity or Opportunity Product.</description>
        <label>Cross Update Allowed</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Claim Value Setting</label>
    <pluralLabel>Opportunity Claim Value Settings</pluralLabel>
</CustomObject>

src/classes/OpportunityClaimValueSettingsSelector.cls
public class OpportunityClaimValueSettingsSelector extends ApplicationSelector {
	
	public override Schema.SObjectType getSObjectType() {
		return Opportunity_Claim_Value_Setting__mdt.SObjectType;
	}
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Opportunity_Claim_Value_Setting__mdt.Account_CBG__c,
			Opportunity_Claim_Value_Setting__mdt.Cross_Update_Allowed__c 
		};
	}
	
	public List<Opportunity_Claim_Value_Setting__mdt> selectWhere(String condition) {
		p('selectWhere');
        return (List<Opportunity_Claim_Value_Setting__mdt>)Database.query(newQueryFactory().setCondition(condition).toSOQL());        
    }
    
}