src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Help_Needed__c</fullName>
        <description>1607 Release SIR 1017 - Probability to Win &amp; Help Needed &amp; Description on Oppty Object</description>
        <inlineHelpText>Describe the internal help that is needed in order to increase Probability to Win to 80%-100%. Used for internal review of funnel.</inlineHelpText>
        <label>z_OBSOLETED_Help Needed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Probability_to_Win__c</fullName>
        <description>1607 Release SIR 1030 - Probability to Win &amp; Help Needed &amp; Description on Oppty Object</description>
        <inlineHelpText>80-100%, Include in Most Likely for Qtr;					
50-80%, Define what is needed to win this Qtr. Actively working to move to 80-100% cat. List actions needed to secure win this Qtr  in Help Needed;					
0-50%, Unlikely to close this Qtr. Not counted in Most</inlineHelpText>
        <label>z_OBSOLETED_Probability to Win</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>80% - 100%</fullName>
                </value>
                <value>
                    <fullName>50% - 80%</fullName>
                </value>
                <value>
                    <fullName>0% - 50%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Help_Needed__c</fullName>
        <inlineHelpText>Describe the internal help that is needed in order to increase Probability to Win to 80%-100%. Used for internal review of funnel.</inlineHelpText>
        <label>Help Needed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price_Erosion_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price Erosion Rate (%)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Probability_to_Win__c</fullName>
        <inlineHelpText>80-100%, Include in Most Likely for Qtr;	
50-80%, Define what is needed to win this Qtr. Actively working to move to 80-100% cat. List actions needed to secure win this Qtr in Help Needed;	
0-50%, Unlikely to close this Qtr. Not counted in Most</inlineHelpText>
        <label>Probability to Win</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>80% - 100%</fullName>
                </value>
                <value>
                    <fullName>50% - 80%</fullName>
                </value>
                <value>
                    <fullName>0% - 50%</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Name of Product</description>
        <formula>PricebookEntry.Product2.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Share (%)</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/classes/OpportunityProductController.cls
public with sharing class OpportunityProductController {
	
	private static final Map<String, String> FIELDS = new Map<String, String> {
		OpportunityLineItem.UnitPrice.getDescribe().getName() => 'price',
		OpportunityLineItem.Price_Erosion_Rate__c.getDescribe().getName() => 'priceErosionRate',
		OpportunityLineItem.Component_Multiplier__c.getDescribe().getName() => 'qtyPerSys',
		OpportunityLineItem.Share__c.getDescribe().getName() => 'share',
		OpportunityLineItem.Probability_to_Win__c.getDescribe().getName() => 'probToWin',
		OpportunityLineItem.Help_Needed__c.getDescribe().getName() => 'helpNeeded' 	
	}; 
	
	public class OpportunityProductWrapper {
		@AuraEnabled public String id { get; set; }
		@AuraEnabled public String opptyName { get; set; }
		@AuraEnabled public String opptyUrl { get; set; }
		@AuraEnabled public String ccyCode { get; set; }
		@AuraEnabled public String prodName { get; set; }
		@AuraEnabled public String opptyProdUrl { get; set; }
		@AuraEnabled public Decimal price { get; set; }
		@AuraEnabled public Decimal priceErosionRate { get; set; }
		@AuraEnabled public Decimal qtyPerSys { get; set; }
		@AuraEnabled public Decimal share { get; set; }
		@AuraEnabled public String probToWin { get; set; }
		@AuraEnabled public String helpNeeded { get; set; }
	}
	
	public class Error {
		@AuraEnabled public Map<String, ErrorDetail> rows { get; set; }
	}
	
	public class ErrorDetail {
		@AuraEnabled public String title { get; set; }
		@AuraEnabled public List<String> messages { get; set; }
		@AuraEnabled public List<String> fieldNames { get; set; }
	}
	
	@AuraEnabled
    public static List<OpportunityProductWrapper> getOpportunityProducts(Id progId) {
    	p('getOpportunityProducts');
    	List<OpportunityProductWrapper> result = new List<OpportunityProductWrapper>();
    	
    	List<Opportunity> oppties = new OpportunitiesSelector().selectByProgramIdAndOwnerIdWithAccountAndOwnerAndProducts(new Set<Id> {progId}, new Set<Id> {UserInfo.getUserId()});
    	
    	for (Opportunity o : oppties) {
    		for (OpportunityLineItem oli : o.OpportunityLineItems) {
    			OpportunityProductWrapper opw = new OpportunityProductWrapper();
    			opw.id = oli.Id;
    			opw.opptyName = o.Name;
    			opw.opptyUrl = '/' + o.Id;
    			opw.ccyCode = o.CurrencyIsoCode;
    			opw.prodName = oli.Product_Name__c;
    			opw.opptyProdUrl = '/' + oli.Id;
    			opw.price = oli.UnitPrice;
    			opw.priceErosionRate = oli.Price_Erosion_Rate__c / 100;
    			opw.qtyPerSys = oli.Component_Multiplier__c;
    			opw.share = oli.Share__c / 100;
    			opw.probToWin = oli.Probability_to_Win__c;
    			opw.helpNeeded = oli.Help_Needed__c;
    			result.add(opw);		
    		}
    	}
    	
    	return result;	
    }
    
    @AuraEnabled
    public static void updateOpportunityProducts(String changedValues) {
    	List<OpportunityLineItem> opptyProdsUpdated = new List<OpportunityLineItem>();

    	for (OpportunityProductWrapper opw : (List<OpportunityProductWrapper>)JSON.deserialize(changedValues, List<OpportunityProductWrapper>.class)) {
    		OpportunityLineItem oli = new OpportunityLineItem();
    		oli.Id = opw.id;
    		if (opw.price != null) oli.UnitPrice = opw.price;
    		if (opw.priceErosionRate != null) oli.Price_Erosion_Rate__c = opw.priceErosionRate * 100;
    		if (opw.qtyPerSys != null) oli.Component_Multiplier__c = opw.qtyPerSys;
    		if (opw.share != null) oli.Share__c = opw.share * 100;
    		//if (opw.probToWin != null) oli.Probability_to_Win__c = opw.probToWin;
    		if (opw.helpNeeded != null) oli.Help_Needed__c = opw.helpNeeded;
    		opptyProdsUpdated.add(oli);  	
    	}
    	
    	List<Database.SaveResult> opptyProdsUpdateResults = Database.update(opptyProdsUpdated, false);
    	
    	Map<String, ErrorDetail> errDetailsById = new Map<String, ErrorDetail>();
    	    	
    	for (Integer i = 0; i < opptyProdsUpdateResults.size(); i++) {
    		Database.SaveResult sr = opptyProdsUpdateResults.get(i);
    		
    		if (!sr.isSuccess()) {
    			ErrorDetail errDetail = new ErrorDetail();
    			List<String> messages = new List<String>(); 
    			List<String> fieldNames = new List<String>();
    			
    			for (Database.Error e : sr.getErrors()) {
    				messages.add(e.getMessage());
    				
    				for (String f : e.getFields()) {
    					fieldNames.add(FIELDS.get(f));		
    				}
    			}
    			
    			errDetail.title = sr.getErrors().size() + ' error(s) found.';
    			errDetail.messages = messages;
    			errDetail.fieldNames = fieldNames;   
    			errDetailsById.put(opptyProdsUpdated.get(i).Id, errDetail);
    		}
    	}
    	
    	if (errDetailsById.size() > 0) {
    		Error err = new Error();
    		err.rows = errDetailsById;
    		
    		throw new AuraHandledException(JSON.serialize(err));	
    	}
    }
    
    private static void p(String msg) {
		CommonUtils.p(OpportunityScheduleMasterController.class, '//-c', msg);
	}

}