src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Claim_Value_USD__c</fullName>
        <description>Opportunity claim value in USD.</description>
        <formula>IF (Locked_Exchange_Rate__c &lt;&gt; 0, Claim_Value__c / ROUND(Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summary of all products&apos; [Prod Claim Value] converted to USD.</inlineHelpText>
        <label>Oppty Claim Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Compliance_Assessment_Evidence__c</fullName>
        <defaultValue>false</defaultValue>
        <description>1602 Release - SIR 590: Oppty Mgmt - Compliance Risk Line Item</description>
        <inlineHelpText>The outcome of a compliance risk assessment is an evidence report that documents the identified risks and associated risk level of the project (high/medium/low). It includes who performed the assessment and date of assessment.</inlineHelpText>
        <label>Compliance Assessment Evidence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compliance_Risk__c</fullName>
        <description>1602 Release - SIR 590: Oppty Mgmt - Compliance Risk Line Item</description>
        <inlineHelpText>The risk associated with non-compliance to NXP Code of Conduct and international rules and regulations regarding anti-bribery and competition laws.</inlineHelpText>
        <label>Compliance Risk</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Letter_of_intent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract/Letter of Intent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Date__c</fullName>
        <inlineHelpText>Records the date when the Design Win is approved.</inlineHelpText>
        <label>Design Win Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Process__c</fullName>
        <label>Design Win Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Design_Win_Submission_Date__c</fullName>
        <inlineHelpText>Records the date when the Design Win was submitted for approval.</inlineHelpText>
        <label>Design Win Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id is required for integration purpose which is OPPORTUNITY_NUM from Model N.</description>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lost_Date__c</fullName>
        <label>Lost/Cancelled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lost_Description__c</fullName>
        <inlineHelpText>Please provide description of Lost Reason</inlineHelpText>
        <label>Lost/Cancelled Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <inlineHelpText>Please change the Oppty stage to &quot; Cancelled&quot; or &quot; Lost&quot; before modifying Lost/Cancelled Reason.</inlineHelpText>
        <label>Lost/Cancelled Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Changing requirements</fullName>
                </value>
                <value>
                    <fullName>Lack of Technical Support Resources</fullName>
                </value>
                <value>
                    <fullName>Operational Performance</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project not Lost but transferred to other SFDC Project</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Relation</fullName>
                </value>
                <value>
                    <fullName>Specification</fullName>
                </value>
                <value>
                    <fullName>Stopped by Customer</fullName>
                </value>
                <value>
                    <fullName>Software/Operating System</fullName>
                </value>
                <value>
                    <fullName>Time to Market</fullName>
                </value>
                <value>
                    <fullName>Wrong Entry</fullName>
                </value>
                <value>
                    <fullName>Company Out of Business</fullName>
                </value>
                <value>
                    <fullName>Duplicate of Existing Opty</fullName>
                </value>
                <value>
                    <fullName>MPN EOL</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
                <value>
                    <fullName>No Commercial Relations</fullName>
                </value>
                <value>
                    <fullName>No Cust Contact Response</fullName>
                </value>
                <value>
                    <fullName>Not a Valid Cust/Project</fullName>
                </value>
                <value>
                    <fullName>Project Cancelled by Cust</fullName>
                </value>
                <value>
                    <fullName>Project Delayed by Cust</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG Concat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <inlineHelpText>Estimate the likely production date of this design win.</inlineHelpText>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Pre_Production_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purchase Order/ Pre-Production Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReasonWon_Description__c</fullName>
        <description>Reason Won Description</description>
        <inlineHelpText>executive summary of why NXP won the opportunity (for DW Approval only)</inlineHelpText>
        <label>Reason Won Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reason_Won__c</fullName>
        <description>Add Reason Won to opportunity</description>
        <inlineHelpText>Please provide a Reason Won for this Opportunity for tracking purposes</inlineHelpText>
        <label>Reason Won</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery Support</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Production Capacity</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
                <value>
                    <fullName>Specification</fullName>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                </value>
                <value>
                    <fullName>Time to Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Spin_Off_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spin Off Oppty</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spin Off Opportunity</relationshipLabel>
        <relationshipName>Spin_Off_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Written_Confirmation_from_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Project name must be included in the confirmation
For Japan (AUT &amp; ID): meeting minutes stating NXP
will be the selected partner is accepted as evidence.</inlineHelpText>
        <label>Written Confirmation from Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X90_Day_Maturity_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This opportunity bypasses the 30-day maturity requirement.</inlineHelpText>
        <label>Maturity Exception</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Claim_Value_USD__c</fullName>
        <description>Opportunity product claim value in USD.</description>
        <formula>IF (Opportunity.Locked_Exchange_Rate__c &lt;&gt; 0, Claim_Value__c / ROUND(Opportunity.Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity product claim value in USD.</inlineHelpText>
        <label>Prod Claim Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Component_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This field contains quantity per part from Model N.</description>
        <inlineHelpText>Qty per Sys should be integer.</inlineHelpText>
        <label>Qty per Sys</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id is required for integration purpose.</description>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prod_Lost_Cancelled_Date__c</fullName>
        <description>This field is updated by workflow.</description>
        <inlineHelpText>The date the product is Lost/Cancelled</inlineHelpText>
        <label>Prod Lost/Cancelled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prod_Lost_Cancelled__c</fullName>
        <label>Prod Lost/Cancelled</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prod_Lost__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prod Lost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Active_Flags__c</fullName>
        <formula>IMAGE( 
CASE( Product_Active_Flag__c , 
&quot;TRUE&quot;, &quot;/img/samples/flag_green.gif&quot;, 
&quot;FALSE&quot;, &quot;/img/samples/flag_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;priority flag&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spin_Off__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked products will be spun off to a new opportunity</description>
        <inlineHelpText>Checked products will be spun off to a new opportunity</inlineHelpText>
        <label>Spin Off</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/OpportunitySchedule__c.object
<CustomObject>
    <description>Opportunity Schedule</description>
    <fields>
        <fullName>Frozen_Oppty_Sched_Qty__c</fullName>
        <label>Frozen Oppty Sched Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Schedules</relationshipLabel>
        <relationshipName>Opportunity_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Oppty_Sched_Qty__c</fullName>
        <label>Oppty Sched Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sched_Date__c</fullName>
        <label>Sched Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Opportunity Schedule</label>
    <nameField>
        <displayFormat>OS-{0000}</displayFormat>
        <label>Opportunity Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Legacy Id from FSL</description>
        <externalId>true</externalId>
        <label>Legacy Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OpportunityCloneController.cls
public with sharing class OpportunityCloneController {
    public static final String FUNC_CLONE = 'clone';
    public static final String FUNC_SPINOFF = 'spin off';
    public static final String FUNC_REOPEN = 'reopen';
    
    public class OpportunityWrapper {
        @AuraEnabled public Opportunity oppty {get; set;}
        @AuraEnabled public String newOpptyName {get; set;}
        @AuraEnabled public List<OpportunitySpinOffWrapper> lstWrappers {get; set;}
    }
    
    public class OpportunitySpinOffWrapper {
        @AuraEnabled public OpportunityLineItem opptyLineItem {get; set;}
        @AuraEnabled public Boolean isSelected {get; set;}
    }

    @AuraEnabled
    public static OpportunityCloneController.OpportunityWrapper getOpptyProdsByOpptyId(String opptyId, String func) {
        Opportunity oppty = [Select Id, Name, StageName, Design_Win_Approval_Process__c from Opportunity Where Id =: opptyId];
        List<OpportunityLineItem> lstOpptyProds = 
            [Select Id, Product2.Name, MAG__c, Product_Active_Flags__c, UnitPrice, Component_Multiplier__c, Claim_Value_USD__c, Product2.IsActive, Prod_Lost_Cancelled__c 
             from OpportunityLineItem Where OpportunityId =: opptyId];
        List<OpportunitySpinOffWrapper> lstWrappers = new List<OpportunitySpinOffWrapper>();
        
        for (OpportunityLineItem item : lstOpptyProds) {
            OpportunitySpinOffWrapper wrapper = new OpportunitySpinOffWrapper();
            wrapper.opptyLineItem = item;
            wrapper.isSelected = (func == OpportunityCloneController.FUNC_SPINOFF || !item.Product2.IsActive) ? false : true;
            lstWrappers.add(wrapper);
        }
        OpportunityWrapper opptyWrapper = new OpportunityWrapper();
        opptyWrapper.oppty = oppty;
        opptyWrapper.lstWrappers = lstWrappers;
        return opptyWrapper;
    }
    
    public static String doCloneAndSpinOff(OpportunityCloneController.OpportunityWrapper wrapper, String func, 
                                           OpportunityCloneController.OpportunityCloneWrapper myclone) {
        //spin off products
        List<OpportunityLineItem> spinoffProds = new List<OpportunityLineItem>();
        
        //keep savepoint
        Savepoint sp = Database.setSavepoint();
        String newOpptyId = null;
        
        try {
            //insert new opportunity
            Opportunity newOppty = myclone.resetOpptyFields();
            newOppty.Name = wrapper.newOpptyName;
            insert newOppty;
            newOpptyId = newOppty.Id;
            
            //insert opportunity schedule
            if (myclone.clonedSObjectOpptyScheds != null) {
                myclone.resetOpptySchedFields();
                insert myclone.clonedSObjectOpptyScheds;            
            }
    
            //create oppty prod map
            Map<String,Boolean> mapOpptyProds = new Map<String,Boolean>();
            for(OpportunitySpinOffWrapper w : wrapper.lstWrappers) {
                mapOpptyProds.put(w.opptyLineItem.Id,w.isSelected);
                if (w.isSelected) spinoffProds.add(w.opptyLineItem);
            }
            
            if (myclone.clonedSObjectOpptyProds != null) {
                for(Integer i = myclone.clonedSObjectOpptyProds.size() - 1; i >= 0; i--) {
                    sObject obj = myclone.clonedSObjectOpptyProds.get(i);
                    obj.put('Spin_Off__c', false);
                    String strId = String.valueOf(obj.get('Id'));
                    if(Boolean.valueOf(mapOpptyProds.get(strId)) == false) {
                        myclone.clonedSObjectOpptyProds.remove(i);
                    }
                }
                myclone.resetOpptyProdFields();
                insert myclone.clonedSObjectOpptyProds;            
            }
            
            if (func == OpportunityCloneController.FUNC_SPINOFF) {
                //remove spin off prods from original opportunity
                delete spinoffProds;
            }
        } catch (Exception err) {
            system.debug('@@@@@ ' + err.getMessage());
            Database.rollback(sp);
            throw err;
        }
        
        return newOpptyId;
    }
    
    @AuraEnabled
    public static String doCloneAndSpinOff(String opptyWrapper, String func) {
        OpportunityCloneController.OpportunityWrapper wrapper = 
            (OpportunityCloneController.OpportunityWrapper)System.JSON.deserialize(opptyWrapper, OpportunityCloneController.OpportunityWrapper.class);

        OpportunityCloneController.OpportunityCloneWrapper myclone = 
            new OpportunityCloneController.OpportunityCloneWrapper(wrapper.oppty.Id, (func == OpportunityCloneController.FUNC_CLONE ? false : true));
        
        return OpportunityCloneController.doCloneAndSpinOff(wrapper, func, myclone);
    }

    public class OpportunityCloneWrapper {
        public Opportunity originalOppty {get; set;}
        public List<sObject> clonedSObjectOppty {get; set;}
        public List<sObject> clonedSObjectOpptyProds {get; set;}
        public List<sObject> clonedSObjectOpptyScheds {get; set;}
        
        public OpportunityCloneWrapper(String opptyId, boolean keepSystemFields) {
            List<Opportunity> lstOppty = [Select Id, Name,Legacy_Id__c, Spin_Off_Opportunity__c, Design_Win_Approval_Process__c, RecordType.Name,
                                          (Select Id, Product2.Name, MAG__c, Product_Active_Flags__c, UnitPrice, Component_Multiplier__c, Claim_Value_USD__c, Spin_Off__c from OpportunityLineItems), 
                                          (Select Id, Opportunity__c, Oppty_Sched_Qty__c, Sched_Date__c, Frozen_Oppty_Sched_Qty__c from Opportunity_Schedules__r) 
                                          from opportunity where Id =: OpptyId];
            originalOppty = lstOppty.get(0);
            List<OpportunityLineItem> currentProds = getOpptyProds();
            List<OpportunitySchedule__c> currentScheds = originalOppty.getSObjects('Opportunity_Schedules__r');
            List<sObject> currentOppty = new List<sObject>{(sObject)originalOppty};
                
            //opportunity
            clonedSObjectOppty = cloneObjects(currentOppty, currentOppty.get(0).getsObjectType(), keepSystemFields);
            
            //opportunity schedule
            if (currentScheds != null && currentScheds.size() > 0) {
                clonedSObjectOpptyScheds = cloneObjects(currentScheds, currentScheds.get(0).getsObjectType(), keepSystemFields);
            }
            
            //opportunity products
            if (currentProds != null && currentProds.size() > 0) {
                clonedSObjectOpptyProds = cloneObjects(currentProds, currentProds.get(0).getsObjectType(), keepSystemFields);
            }
        }
        
        public List<OpportunityLineItem> getOpptyProds() {
            if (originalOppty == null) return null;
            return originalOppty.getSObjects('OpportunityLineItems');
        }
        
        public Opportunity resetOpptyFields() {
            Opportunity clonedOppty = (Opportunity)clonedSObjectOppty.get(0);
            //reset fields
            clonedOppty.Id = null;
            clonedOppty.Legacy_Id__c = null;
            clonedOppty.StageName = 'Initial Engagement';
            clonedOppty.Amount = 0;
            
            clonedOppty.Design_Win_Approval_Process__c = 'Open';
            clonedOppty.X90_Day_Maturity_Exception__c = false;
            clonedOppty.Design_Win_Approval_Date__c = null;
            clonedOppty.Design_Win_Submission_Date__c = null;
            
            clonedOppty.Lost_Date__c = null;
            clonedOppty.Lost_Description__c = null;
            clonedOppty.Lost_Reason__c = null;
            
            clonedOppty.Reason_Won__c = null;
            clonedOppty.ReasonWon_Description__c = null;
            
            clonedOppty.Compliance_Assessment_Evidence__c = false;
            clonedOppty.Compliance_Risk__c = null;
            
            clonedOppty.Contract_Letter_of_intent__c = false;
            clonedOppty.Purchase_Order_Pre_Production_Order__c = false;
            clonedOppty.Written_Confirmation_from_Customer__c = false;
            
            //update opportunity name
            clonedOppty.Name = clonedOppty.Name + '(cloned)';
            
            //check close date & production date
            Date today = Date.today();
            Date closeDate = clonedOppty.CloseDate;
            if (today > closeDate) {
                clonedOppty.CloseDate = today.addDays(1);
            }
   
            Date productionDate = clonedOppty.Production_Date__c;
            if (today > productionDate) {
                clonedOppty.Production_Date__c = today.addDays(1);
                
                if (clonedSObjectOpptyScheds != null) {
                    //reset opportunity schedule
                    OpportunitySchedule__c opptySched = new OpportunitySchedule__c();
                    opptySched.Oppty_Sched_Qty__c = 1000;
                    opptySched.Frozen_Oppty_Sched_Qty__c = 1000;
                    opptySched.Sched_Date__c = clonedOppty.Production_Date__c;
                    clonedSObjectOpptyScheds = new List<sObject>{(sObject)opptySched};                    
                }
            }
            return clonedOppty;
        }
        
        public void resetOpptySchedFields() {
            Opportunity clonedOppty = (Opportunity)clonedSObjectOppty.get(0);
            //insert && update opportunity id (Opportunity__c)
            if (clonedSObjectOpptyScheds != null) {
                for(sObject obj : clonedSObjectOpptyScheds) {
                    obj.put('Id', null);
                    obj.put('Opportunity__c', clonedOppty.Id);
                }
            }
        }
        
        public void resetOpptyProdFields() {
            Opportunity clonedOppty = (Opportunity)clonedSObjectOppty.get(0);
            //update OpportunityId
            if (clonedSObjectOpptyProds != null) {
                for(sObject obj : clonedSObjectOpptyProds) {
                    obj.put('Id', null);
                    obj.put('OpportunityId', clonedOppty.Id);
                    obj.put('Legacy_Id__c', null);
                    obj.put('Prod_Lost__c', false);
                    obj.put('Prod_Lost_Cancelled__c', null);
                    obj.put('Prod_Lost_Cancelled_Date__c', null);
                    obj.put('Prod_Lost_Reason__c', null);
                    obj.put('Prod_Lost_Cancelled_Reason__c', null);
                }                
            }
        }
        /*
        public String insertCloneOppty() {
            //keep savepoint
            Savepoint sp = Database.setSavepoint();
            try {
                //reset oppty fields
                Opportunity clonedOppty = resetOpptyFields();                
                insert clonedOppty;
                
                //update opportunity__c
                resetOpptySchedFields();
                if (clonedSObjectOpptyScheds != null) {
                    insert clonedSObjectOpptyScheds;
                }

                //reset oppty prod fields
                resetOpptyProdFields();
                if (clonedSObjectOpptyProds != null) {
                    insert clonedSObjectOpptyProds;
                }
                
                return clonedOppty.Id;
            } catch (Exception err) {
                system.debug('@@@@@ ' + err.getMessage());
                Database.rollback(sp);
                throw err;
            }
        }*/
    }
        
  // Clone a list of objects to a particular object type
  // Parameters 
  // - List<sObject> sObjects - the list of objects to be cloned 
  // - Schema.SobjectType objectType - the type of object to be cloned.
  // The sObjects you pass in must include the ID field, 
  // and the object must exist already in the database, 
  // otherwise the method will not work.
  public static List<sObject> cloneObjects(List<sObject> sObjects,
                                        Schema.SObjectType objectType, boolean keepSystemFields) {
    
    // A list of IDs representing the objects to clone
    List<Id> sObjectIds = new List<Id>{};
    // A list of fields for the sObject being cloned
    List<String> sObjectFields = new List<String>{};
    // A list of new cloned sObjects
    List<sObject> clonedSObjects = new List<sObject>{};
    
    // Get all the fields from the selected object type using 
    // the get describe method on the object type.
    if(objectType != null){
      sObjectFields.addAll(
        objectType.getDescribe().fields.getMap().keySet());
    }
    
    // If there are no objects sent into the method, 
    // then return an empty list
    if (sObjects != null && 
        !sObjects.isEmpty() && 
        !sObjectFields.isEmpty()){
    
      // Strip down the objects to just a list of Ids.
      for (sObject objectInstance: sObjects){
        sObjectIds.add(objectInstance.Id);
      }

      /* Using the list of sObject IDs and the object type, 
         we can construct a string based SOQL query 
         to retrieve the field values of all the objects.*/
    
      String allSObjectFieldsQuery = 'SELECT ' + sObjectFields.get(0); 
    
      for (Integer i=1 ; i < sObjectFields.size() ; i++){
        String tmpFieldName = sObjectFields.get(i);
        if (tmpFieldName.equalsIgnoreCase('totalprice')) continue;
        allSObjectFieldsQuery += ', ' + sObjectFields.get(i);
      }
    
      allSObjectFieldsQuery += ' FROM ' + 
                               objectType.getDescribe().getName() + 
                               ' WHERE ID IN (\'' + sObjectIds.get(0) + 
                               '\'';

      for (Integer i=1 ; i < sObjectIds.size() ; i++){
        allSObjectFieldsQuery += ', \'' + sObjectIds.get(i) + '\'';
      }
    
      allSObjectFieldsQuery += ')';

        //try{
        // Execute the query. For every result returned, 
        // use the clone method on the generic sObject 
        // and add to the collection of cloned objects
        for (SObject sObjectFromDatabase:
             Database.query(allSObjectFieldsQuery)){
          //clone(preserveId, isDeepClone, preserveReadonlyTimestamps, preserveAutonumber)
          // 2015-08-28 by Rex: set preserveReadonlyTimestamps flag to true to clone CreatedDate from parent oppty
          clonedSObjects.add(sObjectFromDatabase.clone(true,true,keepSystemFields,false));
        }
    
      //} catch (exception err){
        // Write exception capture method 
        // relevant to your organisation. 
        // Debug message, Apex page message or 
        // generated email are all recommended options.
        //system.debug(err.getMessage());
      //}
    }    
    // return the cloned sObject collection.
    return clonedSObjects;
  }
}