src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BL_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate Bl approver</description>
        <label>BL Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGaS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGac</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGaT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGar</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BL_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate BL Approvers</description>
        <label>BL Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesSGb1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design_Win_Approval_Process__c</fullName>
        <label>Design Win Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level1_RVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Regional VP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level1_Reg_Controller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Regional Controller</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesAbqd</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesAbpA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesAbpf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level2_PM9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>z_OBSOLETED_Product Marketing 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesAbq9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFyk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFyu</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFz9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAG_Approver_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to populate MAG Approvers</description>
        <label>MAG Approver 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFFzi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_VP_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesFJpr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Director_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Sales Director approver for opportunity</description>
        <label>Sales Director Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesF8rX</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateOpportunityBatch.cls
/********************************************************************************************
@Created By :    Scarlett Kang
@Created Date:   19 Apr 2015
@Description:    Batch update Opportunity, called by Approver_Matrix_Extension_Controller
********************************************************************************************/
/**********************
@ Updated By: Scarlett Kang
@ Update Date: 1506 Release
@ Description: Changed to Batch 
******************************************
@ Updated By: Jewelslyn
@ Update Date: 1605 Release
@ Description: added new approver fields and removed old approver fields as part DW approval revision
*******************************************
@ Updated By: Balaji G
@ Update Date: 1610 Release
@ Description: SIR1174 Commented usage of fields Level2_PM11__c and Level2_PM12__c to delete them
*******************************************/

global with sharing class UpdateOpportunityBatch implements Database.Batchable<sObject>{
 
global String ApproverId;

//Start
    global Database.QueryLocator start(Database.BatchableContext BC) { 
         
        //return Database.getQueryLocator(query);
        
        return Database.getQueryLocator(
            [SELECT Id 
             FROM   Opportunity 
             WHERE
                    (Level1_RVP__c =: ApproverId 
                    OR Level1_Reg_Controller__c =: ApproverId
                    OR Level2_PM1__c =: ApproverId
                    OR Level2_PM2__c =: ApproverId
                    OR Level2_PM3__c =: ApproverId
                    OR Level2_PM4__c =: ApproverId
                    OR Level2_PM5__c =: ApproverId
                    OR Level2_PM6__c =: ApproverId
                    OR Level2_PM7__c =: ApproverId
                    OR Level2_PM8__c =: ApproverId
                    OR Level2_PM9__c =: ApproverId
                    OR Level2_PM10__c =: ApproverId
//                    OR Level2_PM11__c =: ApproverId
//                    OR Level2_PM12__c =: ApproverId
                    OR BL_Approver_1__c=:ApproverId
                    OR BL_Approver_2__c=:ApproverId
                    OR BL_Approver_3__c=:ApproverId
                    OR BL_Approver_4__c=:ApproverId
                    OR BL_Approver_5__c=:ApproverId
                    OR MAG_Approver_1__c=:ApproverId
                    OR MAG_Approver_2__c=:ApproverId
                    OR MAG_Approver_3__c=:ApproverId
                    OR MAG_Approver_4__c=:ApproverId
                    OR MAG_Approver_5__c=:ApproverId
                    OR MAG_Approver_6__c=:ApproverId
                    OR MAG_Approver_7__c=:ApproverId
                    OR MAG_Approver_8__c=:ApproverId
                    OR MAG_Approver_9__c=:ApproverId
                    OR MAG_Approver_10__c=:ApproverId 
                    OR Sales_Director_Approver__c=:ApproverId 
                    OR Regional_VP_Approver__c=:ApproverId 
                   )
                    AND (Design_Win_Approval_Process__c = 'Open' 
                    OR Design_Win_Approval_Process__c = 'Pending')
                    AND RecordTypeId = '012D0000000Qp1V'
                    AND StageName = 'Decision']
        );
    }
    
//Execute
    global void execute(Database.BatchableContext BC, list<sObject> scope) {    
        list<Opportunity> affectedOppty = (list<Opportunity>)scope;
        
        if(affectedOppty.size() > 0)
            update affectedOppty;
    }

//Finish
    global void finish(Database.BatchableContext BC){
    }
    
}