src/objects/Opportunity_TMMA_Override_Setting__mdt.object
<CustomObject>
    <description>Control Opportunity fields which can be overridden by TSE for TMMA</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opportunity TMMA Override Setting</label>
    <pluralLabel>Opportunity TMMA Override Settings</pluralLabel>
</CustomObject>

src/classes/OpportunityTmmaOverrideSettingsSelector.cls
public class OpportunityTmmaOverrideSettingsSelector extends ApplicationSelector {
    
    public override Schema.SObjectType getSObjectType() {
		return Opportunity_TMMA_Override_Setting__mdt.SObjectType;
	}
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Opportunity_TMMA_Override_Setting__mdt.Field_Name__c,
			Opportunity_TMMA_Override_Setting__mdt.Object_Name__c 
		};
	}
	
	public List<Opportunity_TMMA_Override_Setting__mdt> selectAll() {
		p('selectAll');
        return (List<Opportunity_TMMA_Override_Setting__mdt>)Database.query(newQueryFactory().toSOQL());        
    }
    
}