src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <formula>PricebookEntry.Product2.BL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LT_Value_USD__c</fullName>
        <description>Opportunity product lifetime value in USD.</description>
        <formula>IF (Opportunity.Locked_Exchange_Rate__c &lt;&gt; 0, LT_Value__c / ROUND(Opportunity.Locked_Exchange_Rate__c, 6), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity product lifetime value in USD.</inlineHelpText>
        <label>Prod LT Value (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <formula>PricebookEntry.Product2.MAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MAG</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prod_Lost_Cancelled__c</fullName>
        <label>Prod Lost/Cancelled</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Program</label>
        <referenceTo>OpportunityProgram__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OpportunityLineItemsSelector.cls
public class OpportunityLineItemsSelector extends ApplicationSelector {

	public Schema.SObjectType getSObjectType() {
		return OpportunityLineItem.SObjectType;
	}
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			OpportunityLineItem.Id,
			OpportunityLineItem.OpportunityId,
			OpportunityLineItem.Program__c
		};
	}
	
	public List<OpportunityLineItem> selectById(Set<Id> ids) {
		p('selectById');
		return (List<OpportunityLineItem>)selectSObjectsById(ids);
	}
	
	public List<OpportunityProductValueSummary> selectLifetimeValueByOpptyIdGroupByMag(Set<Id> opptyIds) {
		p('selectLifetimeValueByOpptyIdGroupByMag');
		List<OpportunityProductValueSummary> result = new List<OpportunityProductValueSummary>();
		
		List<AggregateResult> opptyProdMagLtValues = 
			[select PricebookEntry.Product2.MAG__c mag, sum(LT_Value_USD__c) totalMagLtValue
           	   from OpportunityLineItem 
          	  where OpportunityId in :opptyIds 
          	    and Prod_Lost_Cancelled__c = null
         	 group by PricebookEntry.Product2.MAG__c];
         	 
		for (AggregateResult ar : opptyProdMagLtValues) {
			result.add(new OpportunityProductValueSummary(ar));	
		}         	 	
		
		return result;
	}
	
	public List<OpportunityProductValueSummary> selectLifetimeValueByOpptyIdGroupByBl(Set<Id> opptyIds) {
		p('selectLifetimeValueByOpptyIdGroupByBl');
		List<OpportunityProductValueSummary> result = new List<OpportunityProductValueSummary>();
		
		List<AggregateResult> opptyProdBlLtValues = 
			[select PricebookEntry.Product2.BL__c bl, sum(LT_Value_USD__c) totalBlLtValue
           	   from OpportunityLineItem 
          	  where OpportunityId in :opptyIds 
          	    and Prod_Lost_Cancelled__c = null
         	 group by PricebookEntry.Product2.BL__c];
         	 
		for (AggregateResult ar : opptyProdBlLtValues) {
			result.add(new OpportunityProductValueSummary(ar));	
		}         	 	
		
		return result;
	}
	
	public class OpportunityProductValueSummary {
		private AggregateResult result;
		
		private OpportunityProductValueSummary(AggregateResult result) {
			this.result = result;	
		}
		
		public String mag { 
			get { return (String)result.get('mag'); } 
		}
		
		public Double totalMagLtValue { 
			get { return (Double)result.get('totalMagLtValue'); } 
		}
		
		public String bl { 
			get { return (String)result.get('bl'); } 
		}
		
		public Double totalBlLtValue { 
			get { return (Double)result.get('totalBlLtValue'); } 
		}
	}
	
	private static void p(String msg) {
		System.debug('//-s OpportunityLineItemsSelector - ' + msg);
	}
    
}