src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BL__c</fullName>
        <label>BL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Basic_Type__c</fullName>
        <label>Basic Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Legacy Id from FSL</description>
        <externalId>true</externalId>
        <label>Legacy Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MAG__c</fullName>
        <label>MAG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesItem_CSI__c</fullName>
        <description>1602 Release SIR 450</description>
        <inlineHelpText>Sales Item Customer Specific Indicator</inlineHelpText>
        <label>Sales Item CSI</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesItem_OrderablePartNumber__c</fullName>
        <description>1602 Release SIR 450</description>
        <label>Sales Item Orderable Part Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesItem_ProductState__c</fullName>
        <label>Sales Item Product State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Item__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sales Item</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>X9NC__c</fullName>
        <formula>LEFT( Sales_Item__c ,9)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>9NC</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ProductsSelector.cls
public class ProductsSelector extends ApplicationSelector {
	
	public override Schema.SObjectType getSObjectType() {
		return Product2.SObjectType;
	}
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Product2.Id,
			Product2.IsActive,
			Product2.Basic_Type__c,
			Product2.BL__c,
			Product2.BU__c,
			Product2.Legacy_Id__c,
			Product2.MAG__c,
			Product2.Sales_Item__c,
			Product2.SalesItem_CSI__c,
			Product2.SalesItem_ProductState__c,
			Product2.SalesItem_OrderablePartNumber__c,
			Product2.X9NC__c
		};
	}
    
}