src/objects/Survey_Answer__c.object
<CustomObject>
    <description>Object to store community survey answers by user.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Field to store survey answer</description>
        <label>Answer</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master detail to case object.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Master detail to survey question object.</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answer</label>
    <nameField>
        <label>Survey Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <description>Object to store community survey questions.</description>
    <fields>
        <fullName>Question__c</fullName>
        <description>Field to store question title.</description>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/surveyfeedcaseclass.cls
/*****************************************************************************************
@Created By :   Ranganath C N
@Created Date:  31 Aug 2018
@Description:    To display Survey_answres update in case object feed as a part of SFDC-1967.
*******************************************************************************************/
public class surveyfeedcaseclass
{
    public static void casefeed(List<Survey_Answer__c> surveyupdate,map<id,Survey_Answer__c> surveyOld)
    {
         Map<Id,String> surveyquest = new Map<Id,String>();
         set<id> setSurveyCase = new set<id> ();
         
         for(Survey_Answer__c objSurvAnswer :surveyupdate ){
          //   surveymapcase.put(c.Id,c.Case__c);
             setSurveyCase.add(objSurvAnswer.Case__c);
          }
    
        list<FeedItem> lstFeeds = new list<FeedItem>();  
        
        List<Case> lstCases= new List<Case>();
        lstCases = [select Id from case where id=:setSurveyCase];
    
        List<Survey_Question__c> lstSurveyQuestion = new List<Survey_Question__c>();
        lstSurveyQuestion = [select id,Question__c from Survey_Question__c];
    
        for(Survey_Question__c objSurQues: lstSurveyQuestion){
        surveyquest.put(objSurQues.Id,objSurQues.Question__c);
        }
        
        for(Survey_Answer__c objSurAns :surveyupdate ){
            for(Case objCase : lstCases){
                if(objSurAns.Case__c == objCase.id)
                {
                    FeedItem feed = new FeedItem(); 
                    feed.ParentId= objCase.Id;
                   // String aa = Trigger.oldMap.get(sa.Id).Answer__c;
                   String surAns = surveyOld.get(objSurAns.Id).Answer__c;
                    String question = surveyquest.get(objSurAns.Survey_Question__c); 
                    feed.Body = 'changed the value' + ' ' + 'from'  + ' ' + surAns +' '+ 'to' + ' ' +  objSurAns.Answer__c + ' '+'for question' + ' '+ '\'' + + ' ' +question + ' '+ '\'';
                    lstFeeds.add(feed);
                }
          }
     }
     
      insert lstFeeds;
    }
}